ext/php7/ddtrace.c
ext/php7/engine_hooks.c
ext/php7/engine_hooks.h
ext/php7/handlers_internal.c
ext/php7/handlers_internal.h
ext/php8/ddtrace.c
ext/php8/engine_hooks.c
ext/php8/engine_hooks.h
ext/php8/handlers_internal.c
ext/php8/handlers_internal.h

Turns out that the message_handler implementation in Zend is broken since forever (since 2000). zend_llist_apply_with_arguments() does not va_copy() its va_args array and thus serves us a random pointer instead of a valid zend_extension pointer, if there is more than one simultaneous message_handler.
Note that web tests are broken due to not yet merged composer changes (see #1669).

Check for datadog-profiling in startup only instead of inside a message_handler

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Check for datadog-profiling in startup only instead of inside a message_handler #1670. This fixes a possible crash when all of tracer, profiler and appsec are loaded.
- Add opcode shutdown handlers, fix integrations after repeated minit #1669. This fixes a crash when using reload on apache (sending SIGUSR1).
- (PHP 7) Fix curl wrapper use after free #1662. This fixes a possible crash when curl handles are manually released within destructors inside the PHP shutdown sequence.
- Fix -Werror=address-of-packed-member (#1664).
- Skip curl test if curl is not loaded #1668
- Fix crash with SAPI env vars DataDog/dd-prof-php#46
- Avoid .message_handler due to upstream bug DataDog/dd-prof-php#47

Release 0.76.2

---

ext/php7/ip_extraction.c
ext/php8/ip_extraction.c
tests/ext/extract_ip_addr.phpt

According to [Azzure Application Gateway documentation](https://docs.microsoft.com/en-us/azure/application-gateway/how-application-gateway-works#modifications-to-the-request) the IPs on x-forwarded-for header
can contain the port. Our ip extraction code was not expeting ports as part of this header.
This PR fixes DataDog/dd-trace-php#1672

Add support for ports on x-forwarded-for header

---

ext/hook/uhook_legacy.c
tests/ext/sandbox/hook_function/recursion.phpt

Thus, it is now possible to write code like
```php
DDTrace\hook_function('greet', [
'prehook' => function ($args) {
echo "greet prehook: {$args[0]}\n";
},
'posthook' => function ($args) {
echo "greet posthook: {$args[0]}\n";
},
'recurse' => true
]);
```
to have traces also trigger upon recursion
Fixes #1105.

Add "recurse" => true option to hook/trace config array

---

.circleci/config.yml
datadog-setup.php
dockerfiles/compile_extension/Dockerfile_alpine
dockerfiles/compile_extension/alpine.Dockerfile
dockerfiles/compile_extension/build-dd-trace-php
dockerfiles/compile_extension/docker-compose.yml
dockerfiles/compile_extension/install-php
dockerfiles/verify_packages/installer/test_install_uninstall_install_tracer_profiling.sh
dockerfiles/verify_packages/installer/test_profiler_install_enabled.sh
dockerfiles/verify_packages/installer/test_uninstall.sh
dockerfiles/verify_packages/installer/utils.sh
profiling/Cargo.toml
profiling/LICENSE
profiling/LICENSE-3rdparty.csv
profiling/NOTICE
profiling/datadog-profiling-install.sh
profiling/src/bindings/mod.rs
profiling/src/lib.rs
tests/ext/profiling/runtime_id_02.phpt
tooling/bin/generate-final-artifact.sh
zend_abstract_interface/interceptor/php7/interceptor.c

This adds jobs to the `build_packages` workflow in CircleCI that build
the datadog-profiling extension on x86_64-unknown-linux-gnu and
x86_64-alpine-linux-musl. It adjusts the `datadog-setup.php` install
script to use `extension = datadog-profiling.so` instead of
`zend_extension = datadog-profiling.so` and checks for profiling 
dependencies that weren't there before, which depending on your OS
includes `libgcc_s`, `libdl`,  `libpthread`, and `librt`.
This also updated the Alpine images to v3.16, which caused a few things
to break in CI. I fixed one of them already, but there's still an issue
with the warning `return-local-addr`. This was beyond my skill to just
drop in and fix quickly, so I dropped in a
`-Wno-error=return-local-addr` that should be removed once the fix is
in place. In the …

Build and package datadog-profiling in CI

---

profiling/src/profiling.rs

The exact fake frame name may change to align with other profilers,
but currently this information is missing and we can't easily tell if
a customer has hit a stalk walking bug, genuinely has weird stacks, or
if it's been truncated.
Here's a screenshot with an artificial max depth of 4 to illustrate it:

[Profiling] Add fake frame when truncating stacks

---

tests/randomized/config/inis.php

This was still using `zend_extension` instead of `extension` for `datadog-profiling.so`.

Fix profiling config in randomized tests

---

profiling/src/profiling.rs

When a call frame refers to top-level PHP code, the profiler will now
display this as `<?php` mirroring an open PHP tag instead of `<php>`.
This should be more intuitive to new users.

[Profiling] Switch `<php>` to `<?php`

---

profiling/src/profiling.rs

Some customers are seeing truncated stacks. This PR allows going up
to 512 frames deep now but it no longer allocates the max stack depth
when initializing samples buffer. This avoids waste when the stack is
much smaller than the limit, which it very often will be with a higher
limit.

[Profiling] Raise max stack depth to 512

---

.gitlab-ci.yml

Updates the gitlab deployments to use v0.77.0.

Update artifact URL for v0.77.0 gitlab deployments

---

.gitlab-ci.yml

This updates the relenv deployment to use datadog-setup.php instead of
the .deb installer. Note that I deployed it using artifacts from #1688
so that I could grep the logs to make sure that they were wired up
correctly (latest and previous are currently the same due to the recent
release), but since appsec is only installed but not enabled, you
shouldn't see any differences on the current deployment.
This opens the door to run profiling and/or appsec configurations.

Update relenv to use datadog-setup.php

---

.circleci/config.yml
profiling/src/lib.rs
profiling/tests/phpt/disabled_hooks_01.phpt
profiling/tests/phpt/phpinfo_01.phpt

These were ported from the DataDog/dd-prof-php repository. I made some
minor edits to update them.
I updated the names of the CI test jobs to better reflect that they run
more than cargo tests now.

Add phpt tests for profiling

---

ext/php7/ip_extraction.c
ext/php8/ip_extraction.c
tests/ext/extract_ip_addr.phpt

This PR fixes #1692
The ip extraction module was not taking into consideration that the via header can contain pseudonym instead of IPs. When a pseudonym was parsed it was not detected as an IP and the extension was logging out an error. This PR accept pseudonyms as part of the header as specified on [rfc7230](https://httpwg.org/specs/rfc7230.html#header.via)

Accept pseudonym on via header as specified by rfc7230

---

.circleci/config.yml
ext/php7/span.c
ext/php8/span.c

Fixes a memory leak if Z_TYPE_INFO() reaches zero and the hashtable implementation will consider the value inexistent.

Fix span memory leak and packaging 

---

Makefile

Update appsec package URL to the latest release v0.4.0

Update AppSec to v0.4.0

---

datadog-setup.php
dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/installer/test_install_without_scan_dir.sh
dockerfiles/verify_packages/installer/utils.sh
tests/Integration/PHPInstallerTest.php

Fix #1687 datadog-setup.php failing in environments without scan directory

Fix #1687 datadog-setup.php failing in environments without scan directory

---

ext/php7/random.c
ext/php8/random.c

Using the proper php_random_int() function to get a truly random seed.
Fixes #1695.

Use a true random seed by default

---

profiling/Cargo.toml
profiling/src/bindings/mod.rs
profiling/src/config.rs
profiling/src/lib.rs
profiling/src/php_ffi.h
profiling/src/profiling.rs
profiling/tests/phpt/uds_01.phpt
profiling/tests/phpt/uds_02.phpt

If any configuration is set, it prioritizes that over UDS. If the
socket file doesn't exist then it falls back to http://localhost:8126.
There are tests for various units, and I have tested this manually for
end-to-end for both the default and setting `DD_TRACE_AGENT_URL` to
`unix:///var/run/datadog/apm.socket`.
I had to upgrade libdatadog; this PR is blocked on a release.
Various things have been renamed:
- `ddprof::profiles` -> `datadog_profiling::profile`
- `ddprof::exporter` -> `datadog_profiling::exporter`

[profiling] Add Unix Domain Socket (UDS) support

---

profiling/Cargo.toml
profiling/build.rs
profiling/src/bindings/mod.rs
profiling/src/config.rs
profiling/src/lib.rs
profiling/src/php_ffi.c
profiling/src/php_ffi.h

Since opcache overrides the intern function and you still have to
provide refcounting anyway, the previous version of the code would
leak.
At this point, the Rust <-> C globals bridge isn't providing any value
at all. Although in the future we there may be value in bridging these
things, such as to support INI handling, today it's just dragging us
down. So, I removed it, resulting in about twice as many lines deleted
as I added.
Also bump profiling version to v0.9.0.

[profiling] Avoid PHP per-request interning

---

src/Integrations/Integrations/Symfony/SymfonyIntegration.php
tests/Integrations/Symfony/V2_3/RouteNameTest.php
tests/Integrations/Symfony/V2_8/RouteNameTest.php
tests/composer.json

Fixes #1703.
Also fixing tests - phpunit has dropped its direct phpspec/prophesize dependency.

Set root span name only in HttpKernel::boot() to avoid side effects on CLI

---

datadog-setup.php

The installer adds appsec.so without commenting it out, so it's always necessary to run the replacement to comment it out when we are not installing appsec.
This should be picked into the 5 branch also.

Fix #1709 appsec attempting to load erroneously

---

Makefile

The architecture is called arm64 instead of aarch64 on debian.
Fixes #1714

Rename deb to arm64

---

profiling/src/capi.rs
profiling/src/lib.rs
profiling/src/profiling.rs

Extracts the bits for the C API of the profiler into one location.
This API surface will expand with Endpoint Profiling and this is
a cleanup PR in preparation for that.
Also simplify capi::Uuid and add tests.

[profiling] Extract C API module; refactor Uuid

---

src/Integrations/Integrations/Symfony/SymfonyIntegration.php
tests/Integrations/Symfony/V5_2/ConsoleCommandTest.php

Previous fix for #1703 didn't cover the full problem since Kernel::boot is also used in symfony cli commands, instead root span name should be set to symfony.request only when Kernel actually handles a request which is the case when Kernel::handle is called.

Fix symfony service and root span name

---

.circleci/config.yml
profiling/Cargo.toml

I haven't paid proper attention, and actually just ended up compiling an x86_64 build into an aarch64 directory, running on the wrong machine.
Touched Cargo.toml comments to invalidate aarch64 cargo cache...

Actually use arm64 machines for our arm profiler builds

---

src/Integrations/Integrations/Symfony/SymfonyIntegration.php
tests/Common/SpanChecker.php
tests/Integrations/Symfony/V3_0/CommonScenariosTest.php
tests/Integrations/Symfony/V3_0/TraceSearchConfigTest.php
tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
tests/Integrations/Symfony/V3_3/TraceSearchConfigTest.php
tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
tests/Integrations/Symfony/V4_0/TraceSearchConfigTest.php
tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
tests/Integrations/Symfony/V4_2/TraceSearchConfigTest.php
tests/Integrations/Symfony/V5_2/ConsoleCommandTest.php

This adds a span 'symfony.console.command.run' whose resource is the
name of the command (e.g. `$command->getName()`) if it's not null. It
attaches the command's class name as meta-data.
Suggestions are welcome for the name of the span and the metadata.
Here's a screenshot of the span created by the test:

Integrate with Symfony console commands

---

ext/ddtrace.c
zend_abstract_interface/interceptor/php7/interceptor.c
zend_abstract_interface/interceptor/php7/interceptor.h
zend_abstract_interface/interceptor/php8/interceptor.c
zend_abstract_interface/interceptor/php8/interceptor.h
zend_abstract_interface/interceptor/tests/interceptor.cc
zend_abstract_interface/interceptor/tests/resolver.cc

Fixes compatibilty with the blackfire extension.
Fixes #1725.

Initialize hooks and config early to prevent conflicts with code executed in early startup

---

tests/ext/sandbox-regression/method_invoked_via_reflection.phpt
tests/ext/sandbox/hook_method/posthook_scope_01.phpt
tests/ext/sandbox/hook_method/posthook_scope_02.phpt
tests/ext/sandbox/hook_method/posthook_scope_03.phpt
tests/ext/sandbox/hook_method/prehook_error_01.phpt
tests/ext/sandbox/hook_method/prehook_scope_01.phpt
tests/ext/sandbox/hook_method/prehook_scope_02.phpt
tests/ext/sandbox/hook_method/prehook_scope_03.phpt

This doesn't add full PHP 8.2 support; it just avoids some compatibility issues reported in #1738. However, there is a sigsegv in that issue and locally I get many failures; this is just a step.

Avoid deprecated in PHP 8.2 constructs in tests

---

datadog-setup.php
dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/installer/test_install_non_binary.sh
tests/Integration/PHPInstallerTest.php

Avoid installing non-binaries even when matching the pattern by default (i.e. with `--php-bin=all`), because these may handle args differently, have unexpected side-effects or simply hang the installer.

Handle non-binaries in installer

---

ext/serializer.c
profiling/src/lib.rs
profiling/src/sapi.rs
profiling/tests/phpt/service_01.phpt
profiling/tests/phpt/service_cli_01.phpt
profiling/tests/phpt/service_web_01.phpt

If DD_SERVICE is unset or empty, then the tracer defaults the service name to one of these:
- the script name, aka argv[0]
- cli.command
- web.request
The profiler now does the same which should result in fewer services named unnamed-php-service.

[profiling] Match the service names of the tracer when unset or empty

---

.circleci/config.yml
config.m4
ext/handlers_api.c
ext/handlers_api.h
ext/handlers_curl.c
ext/handlers_curl_php7.c
ext/handlers_exception.c
ext/handlers_internal.c
ext/handlers_internal.h
ext/handlers_pcntl.c
profiling/Cargo.toml
profiling/build.rs
profiling/src/bindings/mod.rs
profiling/src/capi.rs
profiling/src/lib.rs
profiling/src/pcntl.rs
profiling/src/php_ffi.c
profiling/src/php_ffi.h
profiling/tests/phpt/fork_01.phpt

The profiler doesn't support forking yet. However, it shouldn't crash.
This PR reduces some crash surface, but there is more to be done.
Since the tracer already has an API for overwriting the internal
function handler of a given function, I moved those bits into their own
file and made a note that the profiler also compiles these files.
I investigated adding full forking support but decided it would be too
much work to do right now. However, I left some comments about what I
learned, and did leave in some refactoring.

[profiling] Avoid crashing when pcntl_fork is called

---

Makefile

Update AppSec to v0.4.2, this fixes some issues which were causing existing applications to have a large delay on requests with a relatively large number of parameters.

Update AppSec to v0.4.2

---

Makefile

Simple non-critical patch, but could prevent further issues combined with the previous patches.

Update AppSec to v0.4.3

---

ext/span.c
tests/ext/sandbox/hook_function/dropping_trace_hook.phpt

Previously return false was ignored in any trace hook, but the first one.
This now properly allows for (as intended) to write code like:
```
DDTrace\trace_method("mysqli", "prepare", function() { return false; });
```
Dropping all spans from trace hooks on mysqli->prepare.

Fix behaviour of return false in trace hooks

---

profiling/Cargo.toml
profiling/src/lib.rs
profiling/src/pcntl.rs
profiling/src/profiling.rs

Deadlocks are prevented by the following technique:
- Prior to the fork, all profiling threads will wait on the same barrier.
- After the fork in the parent process, all threads will wait on the same barrier. They are then free to resume regular operations.
- After the fork in the child process, the barrier will not be joined, the profiler object will be forgotten, and profiling will be disabled.
It should be easy to support profiling the child process from here.

[profiling] Prevent deadlocks when forking

---

config.m4
ext/ddtrace.c
ext/handlers_fiber.c
ext/handlers_fiber.h
ext/span.h
tests/ext/fibers/fiber_observer_bailout.phpt
tests/ext/fibers/fiber_stack_switch.phpt
zend_abstract_interface/interceptor/php8/interceptor.c
zend_abstract_interface/interceptor/php8/interceptor.h

Stacked on top of the #1746 span stacks PR.
Quite lightweight, but adding crash safety on bailout on PHP 8.1.

Implement fibers

---

ext/ddtrace.c
ext/ddtrace.h
ext/handlers_fiber.c
ext/span.c

Fixes the system tests: appsec wants to access spans very late in the request cycle, we need to delay destruction for that.

Fix interaction with appsec

---

profiling/.cargo/config

While trying to compile and link the PHP profiler on an arm64 mac I got some linking issues from `ld` not finding some of the symbols.
Not writing / adding a test for this one, as we are not officially supporting MacOS.

[PROF-6331] fix linking on arm64 mac

---

zend_abstract_interface/config/CMakeLists.txt
zend_abstract_interface/config/config.c
zend_abstract_interface/config/config.h
zend_abstract_interface/config/config_decode.c
zend_abstract_interface/config/config_decode.h
zend_abstract_interface/config/config_ini.c
zend_abstract_interface/config/config_runtime.c
zend_abstract_interface/config/tests/CMakeLists.txt
zend_abstract_interface/config/tests/decode.cc

This PR modifies zai config in a way that multiple extensions can share common settings.
Required for #1764 and https://github.com/DataDog/dd-appsec-php/pull/114.

Reusability of zai config across products

---

ext/handlers_curl.c
tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_003.phpt

Add missing zend_get_gc_buffer_use() in ddtrace_curl_multi_get_gc.

Fix crash in ddtrace_curl_multi_get_gc

---

datadog-setup.php
dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/installer/test_install_no_ldconfig_in_path.sh

The installer depends on a working ldconfig (for glibc install) and assumes it is in PATH.
It is becoming common place for /sbin to be omitted from the PATH of normal users, so we must search outside of PATH in the most common paths for a working ldconfig and use its full path on execution.

improve ldconfig operation in installer

---

profiling/Cargo.toml
profiling/src/lib.rs
profiling/src/profiling.rs

This PR will bump the `libdatadog` version used to `0.9`

Bump `libdatadog` to `0.9`

---

zend_abstract_interface/config/config_decode.c

This was deprecated in PHP 8.2 with the recommendations to use:
1. `ZEND_STRTOL()` for general purpose string to long conversion.
2. A variant of `zend_ini_parse_quantity()` for parsing ini quantities.
For now at least, since this code is ZAI config which deals with .ini settings, I picked the latter.
We should probably re-plumb the function calls at some point to pass the ini setting name to this function so we can use `zend_ini_parse_quantity_warn()` instead.

Avoid deprecated zend_atol on PHP 8.2

---

.circleci/config.yml
CONTRIBUTING.md
tests/randomized/lib/docker-compose.yml

Use [dd-apm-test-agent](https://github.com/DataDog/dd-apm-test-agent) instead of the real agent in CI. 
The test agent is used here only as a mock but we could imagine dumping the snapshots in some cases and verifying them.

[CI] Use the test agent instead of the real agent in tests

---

datadog-setup.php
ext/configuration.h
profiling/Cargo.toml
profiling/build.rs
profiling/src/bindings/ffi.rs
profiling/src/bindings/mod.rs
profiling/src/config.rs
profiling/src/lib.rs
profiling/src/php_ffi.c
profiling/src/php_ffi.h
profiling/src/profiling.rs
profiling/src/sapi.rs
profiling/tests/phpt/phpinfo_ini_01.phpt
profiling/tests/phpt/service_web_01.phpt
tests/ext/read_c_configuration.phpt
tests/randomized/generate-scenarios.php
tests/randomized/lib/PhpIniGenerator.php
tests/randomized/lib/templates/docker-compose.template.yml
zend_abstract_interface/config/config.h
zend_abstract_interface/config/config_ini.c

Implements #1764. This uses the ZAI config component to add support for .ini configuration in profiling. Thank, @bwoebi, for laying the groundwork for this in #1765.
Note that the profiler now defaults to being enabled, but it is not installed by default. This is because it on Alpine it has a dependency on `libgcc` and the tracer does not have this dependency. If a user is only using the tracer and then upgrades, we would emit warnings about undefined symbols and such when it starts up whether they use the profiler or not.
This also moves the default of DD_AGENT_PORT from 8126 to 0. This is easier to work with when working with fallbacks to other connection settings.
There's a good bit of boilerplate to help Rust understand lifetimes for `zai_string_view`. There's also code which tries to …

[profiling] Add .ini support

---

Makefile

Update AppSec to v0.4.5 with support for PHP 8.2.0RC6

Update AppSec to v0.4.5

---

src/Integrations/Integrations/Integration.php

We got a report that sometimes Symfony may emit \Error objects, which then emits another TypeError here.
I'm not sure exactly on how we get there, so, no test attached.

Fix $integration->setError() to also accept \Error instances

---

.circleci/config.yml
Makefile
ext/ddtrace.c
ext/ddtrace.h
ext/handlers_exception.c
zend_abstract_interface/config/config_ini.c

Fixes #1795.
Since 8.1.0 opcache will free our objects before module_shutdown during preloading. Work around it by intercepting the latest possible point in time before objects freeing, then do our normal rshutdown sequence early.
Adding asan for opcache tests.
Looking at asan output, also some small changes had to be done to zai config and hooking.

Fix crash during preloading on 8.1+

---

ext/handlers_exception.c
tests/Integration/ErrorReporting/ErrorReportingTest.php
tests/Integration/ErrorReporting/scripts/dispatcher.php
tests/Integration/ErrorReporting/scripts/index.php

Apparently we have tested everything in detail, but multiple catches on a same try block.
Sometimes it works, sometimes it didn't intercept the exception, and sometimes it just hanged, depending on the surrounding opcodes.
This now properly mirrors the access happening in ZEND_CATCH handler in zend_vm_def.h.

Fix ZEND_CATCH chaining logic

---

profiling/Cargo.toml

This fixes the
```
warning: use of deprecated tuple variant `env_logger::Target::Pipe`: This functionality is [broken](https://github.com/env-logger-rs/env_logger/issues/208) and nobody is working on fixing it
--> src/logging.rs:23:29
|
23 |             .target(Target::Pipe(target))
|                             ^^^^
|
= note: `#[warn(deprecated)]` on by default
```
during `cargo build`
See: https://github.com/rust-cli/env_logger/issues/208

[PROF-6420] bump env_logger to `0.9.3`

---

ext/span.c
tests/ext/sandbox-regression/handle_many_hooks.phpt

Fix misbehaviour with 256+ hooks on a same function

---

.circleci/config.yml

Currently, the "Attaching workspace" step is really slow. I opened a CircleCI ticket and they say the issue is the number of files, there are like 32k files.
So, this PR no longer checks in all the repository sources into the workspace. Before, the "package extension" step would say:
> Total size downloaded: 406 MiB
With this PR:
> Total size downloaded: 250 MiB
However, this only shaved off ~1.5 minute, and the step still takes 6-7+ minutes. There's obviously more work to do.

Speed up "Attaching workspace" step in CI

---

profiling/Cargo.toml
profiling/src/profiling.rs

As https://github.com/DataDog/libdatadog/ was just tagged `v1.0.0` this PR bumps the version in our `Cargo.toml`

Bump `libdatadog` to `v1.0.0`

---

ext/startup_logging.c
tests/ext/priority_sampling/001-default-sampling.phpt
tests/ext/priority_sampling/gh-1828.phpt

Fixes GH-1828. When `DD_TRACE_SAMPLING_RULES` was set explicitly to the empty array, the ZAI/config component would try to increase the reference count on the global, immutable `zend_empty_array` when printing out `phpinfo()`.
If we don't duplicate the array, we get a crash in JSON encoding, so a simple `GC_TRY_ADDREF` is insufficient.

Fix GH-1828: crash when copying an immutable array

---

profiling/src/config.rs
profiling/src/profiling.rs

Being able to save the profiles to disk instead of sending them to Datadog is nicer for certain kinds of tests, including the prof-correctness ones that Erwan and others are working on.

Add configuration to save profiles to disk

---

tests/Integrations/CodeIgniter/V2_2/NoCI_ControllertTest.php

Add missing span kind to CodeIgniter test. This was overlooked by merging two PRs at the same time without first merging master back into the second one.

Add missing span kind to CodeIgniter test

---

datadog-setup.php

When installing a version of the library on top of an existing installation of the same version, in the circumstance in which the appsec helper process is running, the installer fails as it's unable to replace the helper binary. This fixes the issue by forcing  the copy, which results in the removal of the previous binary and the addition of the new (existing) one.

Force the replacement of the appsec helper when reinstalling

---

src/api/Log/InterpolateTrait.php

Otherwise "{name}" may appear and let the user wonder which span is named "{name}".
- [] ~Tests added for this feature/bug.~

Always interpolate error message placeholders to avoid confusion

---

profiling/Cargo.toml

We've made these changes and haven't bumped the version number yet:
- #1819
- #1825
- #1837
So doing that now.
I'm simultaneously seeing if I have my new signing setup working. It appears I do not.

Bump profiling version for release

---

datadog-setup.php

Be less sensitive to the actual filepath; as suggested in #1846.

Improve extension matching in installer

---

ext/span.c

Fixes crash found in internal API stresstest.
It seems to me that the crash occurs, when a stack has been created on top of an existing stack, all its child spans closed and the tracer then reset.
Then new child spans must have been created on top of both stacks, and all of them closed.

Clear the active closed stack head when resetting the tracer

---

Makefile

Upgrade AppSec to 0.6.0

---

zend_abstract_interface/interceptor/php8/resolver.c

Work around broken enum functions run_time_cache on PHP 8.2.0 and 8.2.1

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Use the HttpWorker instead of the Psr7Worker for Roadrunner for more generic usage #1864
- Fix trace_id reset in DDTrace\set_distributed_tracing_context() #1863
- Work around broken enum functions run_time_cache on PHP 8.2.0 and 8.2.1 #1862

Release 0.83.1

---

datadog-setup.php

Reformat `datadog-setup.php` in preparation for further work. Mostly this changed long strings, string concatenation, and multi- line ternary expressions.

style(datadog-setup.php): reformat file

---

ext/integrations/integrations.c

This is a followup on #1864 and #1858
Signed-off-by: Adrien Fillon <adrien.fillon@manomano.com>

Lazy load RoadRunner\Http\HttpWorker instead of Psr7Worker

---

profiling/src/lib.rs
profiling/src/php_ffi.c
profiling/src/php_ffi.h
profiling/tests/phpt/gc_mem_caches_01.phpt

The PHP userland function `gc_mem_caches()` just forwards calls to `zend_mm_gc()` which will do exactly nothing and return `int(0)` in case a custom allocator is installed.
This PR makes sure we intercept userland calls to `gc_mem_caches()` and prepare the heap for such a call.

fix(profiling): prepare heap for `gc_mem_caches()`

---

profiling/Cargo.toml

This will build the `allocation-profiling` feature by default from now on.
An alternative approach would have been to remove all `#[cfg(feature = "allocation_profiling")]` from the source code, but the chosen path allows a quicker (and easier) rollback in case something goes wrong in the time until the beta release.

feat(profiling): compile `allocation-profiling` feature by default

---

profiling/Cargo.toml

this will bump the profiler version from `0.12.0` to `0.13.0` for the upcoming release

Bump profiler version for upcoming release

---

datadog-setup.php

This will add the `datadog.profiling.experimental_allocation_enabled` ini setting to the `datadog-setup.php`

[PROF-6813] add allocation profiling ini setting to `datadog-setup.php`

---

profiling/Cargo.lock

Update the `Cargo.lock` file to reflect the version bump in `Cargo.toml` from #1879 and update third party deps

fix(profiler) bump minor versions in Cargo.lock

---

profiling/src/profiling.rs

This removes left over code that leads to a situation where profiles could be empty, when allocation profiling was disabled as the `sample_values` and `sample_types` would not match anymore.
The code removed is leftover from an earlier refactoring in #1815

Fix empty profiles if sample types and samples values mismatch

---

.circleci/config.yml
.gitlab-ci.yml
ext/serializer.c
profiling/Cargo.toml
profiling/src/profiling.rs
tests/ext/sandbox-regression/nested_dropped_spans.phpt

Concerning a libdatadog bump to 1.0 and a fix for an infinite loop with nested dropped spans.
This reverts commit 152e5dd79c2101125d2410fa5e4ea99e0d4e4f42.

Revert bogus revert commit

---

ext/ddtrace.c
ext/profiling.c
ext/span.c
tests/ext/fibers/enable_tracer_in_fiber.phpt

This fixes a crash with toggling the tracing within fibers.
Additionally add another safety NULL-check to ensure #1880 cannot happen. (Blackfire executes code before ddtrace RINIT.)

Make active_stack infaillible: there always exists a stack

---

datadog-setup.php

These changes were all discovered through warnings in PhpStorm, but this PR does not attempt to clean up all warnings PhpStorm gives.

refactor(datadog-setup.php): cleanup PhpStorm warnings

---

.circleci/config.yml

Add apt update before fetching codecov dependencies

---

src/Integrations/Integrations/PDO/PDOIntegration.php
tests/Integrations/PDO/PDOTest.php

Adds the error message in the error message tag when available. This gives more information on where the issue is. Error messages are contained inside the [errorInfo array](https://www.php.net/manual/en/pdo.errorinfo.php). The specs state it contains 3 elements but [SQLServer seems to set more than that.](https://learn.microsoft.com/en-us/sql/connect/php/pdo-errorinfo?view=sql-server-ver16#additional-odbc-messages)
This extra data shouldn't contain sensitive data as it should be close to what we get on PDOException when there is one.

Show error message when PDO returns an error

---

.circleci/config.yml

Allowing CI to run on external pull requests, otherwise it just fails with `fatal: reference is not a tree`.

Fix running CI in external PRs

---

ddtrace.sym
ext/auto_flush.c
ext/auto_flush.h
ext/ddtrace.c
ext/span.c

Export `ddtrace_flush_tracer` and allow flushing during request startup. Currently appsec blocks the request primarily on RINIT, which results in no traces in the backend, this should allow the ASM extension to flush the traces before blocking.

Export ddtrace_flush_tracer and allow flushing during request startup

---

ddtrace.sym
ext/auto_flush.c
ext/auto_flush.h

- Add and export `ddtrace_close_all_spans_and_flush`
- Unexport `ddtrace_flush_tracer`

Add exported function to close all spans and flush

---

config.m4
ext/hook/uhook.c
ext/hook/uhook_arginfo.h
ext/hook/uhook_attributes.c
ext/hook/uhook_attributes.stub.php
ext/hook/uhook_attributes_arginfo.h
phpcs.xml
tests/ext/traced_attribute.phpt
zend_abstract_interface/hook/hook.c
zend_abstract_interface/hook/hook.h

Adds a DDTrace\Trace Attribute for PHP 8, to trace functions inline with annotations.
It provides the following named args:
```
string $name = "",
string $resource = "",
string $type = "",
string $service = "",
array $tags = [],
bool|array $args = false,
bool $return = false,
bool $recurse = true,
bool $run_if_limited = false
```

Implement #[DDTrace\Trace] attribute

---

ext/configuration.h
ext/ddtrace.c
ext/ddtrace.h
ext/serializer.c
ext/span.c
ext/tracer_tag_propagation/tracer_tag_propagation.c
tests/ext/generate_128_bit_trace_id.phpt
tests/ext/integrations/curl/distributed_tracing_curl_tracestate.phpt

Adds a new `DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED=false` config option.

Add 128-bit trace id generation and propagation via _dd.p.tid

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Add component tag #1834
- Add W3C tracecontext propagation and propagate full 128 bit B3 headers #1856
- Implement #[DDTrace\Trace] attribute #1867
- Add 128-bit trace id generation and propagation via _dd.p.tid #1875
- Allow IP Collection, disabled by default #1895
- Add support for tracing Dispatched Events in Laravel 5.8+ #1897 (Thanks @ralphschindler)
- Show error message when PDO returns an error #1839
- Make active_stack infallible: there always exists a stack #1883
- Fix DDTrace\flush() with DD_AUTOFINISH_SPANS=1 #1892
- Null the parent span of span stacks when resetting the tracer #1899
- style(datadog-setup.php): reformat file #1869
- refactor(datadog-setup.php): cleanup PhpStorm warnings #1870
- Add test Wordpress 6.1 application #1884
- Revert bogus revert commit #1888
- Add …

Release 0.84.0

---

profiling/src/lib.rs
profiling/src/profiling.rs

Simplifies the add/remove interrupt code by using the [Iterator::position](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.position) function.
Also fixes a very minor mistake in a warning log where `index` and `interrupt` were swapped.

refactor(profiling): cleanup add/remove interrupts

---

profiling/Cargo.lock
profiling/src/bindings/mod.rs
profiling/src/php_ffi.c
profiling/src/profiling.rs

- Filename and lineno are both only used for user functions. Merging them into a single function simplifies the code.
- Using as_ref() on pointers cleans up the code in many places as it allows using methods like `filter` and `map`.
- Renames `datadog_php_profiling_zend_string_view` to `ddog_php_prof_zend_string_view` as per our modern naming.
- Adds new `collect_call_frame` function which is called by `collect_stack_sample` on each iteration of the stack-walking.
- Checking for stack truncation is moved from being done every loop, to only when a sample is pushed. For performance this should be slightly better but almost negligible. It's done because it's more maintainable code, the performance is just a nice cherry on top.
I was investigating the stalk walking in preparation to use the …

refactor(profiling): clean up stalk walking

---

profiling/src/lib.rs

Did some benchmarks in relenv and saw that we do not get a better resolution with 50 KB sampling distance compared to 512 KB, but we pay with a higher CPU time overhead.
This PR will lower the sampling distance to 512 KB.
PROF-7186

perf(profiling): increased allocation sampling distance to 512KiB

---

ext/compatibility.h
ext/hook/uhook.c
ext/hook/uhook.stub.php
ext/hook/uhook_arginfo.h
ext/hook/uhook_attributes_arginfo.h
ext/hook/uhook_legacy.c
ext/span.c
tests/ext/sandbox/dd_dumper.inc
tests/ext/sandbox/install_hook/trace_closure.phpt
tests/ext/sandbox/install_hook/trace_closure_from_callable.phpt
tests/ext/sandbox/install_hook/trace_function.phpt
tests/ext/sandbox/install_hook/trace_generator.phpt
zend_abstract_interface/hook/hook.c
zend_abstract_interface/hook/hook.h
zend_abstract_interface/interceptor/php8/interceptor.c

Extracted from my experiments with revolt; the DDTrace\install_hook() API now got proper instrumentation for Closures. Note that hooks applied to closures only apply to the lifetime of the specific hooked closure.
This makes it trivial to check with a WeakMap whether the Closure already has been hooked.
Additionally the DDTrace\HookData API got a span() method which must be called in the begin handler at least once if the hook is to be traced.

Add hooking for Closures

---

profiling/src/profiling.rs

This is never supposed to fail, but better check for it than avoiding it.
Fixes an issue reported in #1880.

Use checked_sub duration ops for handling cpu time

---

dockerfiles/ci/alpine_compile_extension/docker-compose.yml
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/centos/7/base.Dockerfile
dockerfiles/ci/centos/7/docker-compose.yml

These images are already pushed, I just forgot to commit them.
We don't need protoc-c anymore since we use Rust.
Edit: We found the need to downgrade PHP 8.2 to 8.2.1 due to this bug:
https://github.com/php/php-src/commit/95016138a54b3352a0988878cd71c2ebe7cdeca5
So, we're taking the opportunity to rebuild and fix this in a few places.

Upgrade CentOS 7 images to Rust 1.64

---

profiling/src/lib.rs
profiling/src/profiling.rs

These are minor cleanups from the rust upgrade:
1. Fix a clippy warning.
2. Remove one lazy_static! that held a Mutex. Since Rust 1.63, `Mutex::new` is const.

refactor: cleanup after Rust 1.64 upgrade

---

profiling/src/lib.rs
profiling/src/profiling.rs

This mitigation is for issue #1919. It doesn't fix the root cause, which we haven't been able to determine yet.
This also bounds our shutdown timeouts. Before, they _ought_ to have been bounded as a consequence of how the code was written, but this is explicit. It's also a tighter bound than before, 2 seconds instead of 10 seconds.
Also, the new Rust 1.64 formatter apparently formats some things differently, so those are included as well.

Mitigate panic in profiler shutdown, bound timeout

---

ext/ddtrace.c
ext/signals.c
ext/signals.h

This will allow us to debug core dumps without having direct access to the executable.

Set coredump_filter to include private file mapped areas in dumps

---

ext/compatibility.h
ext/ddtrace.c
src/Integrations/Integrations/Curl/CurlIntegration.php
tests/Integrations/Curl/CurlIntegrationTest.php

There's no reason for it not be there...

Add an error.stack to curl_exec() on failure

---

profiling/src/lib.rs
profiling/src/profiling.rs
profiling/src/thread_utils.rs

Extracts a `thread_utils` module for the `spawn` and `join_timeout` routines.
The motivation is that the profiling file is getting a bit too big for my liking, and this was a pretty easy thing to extract.

refactor(profiling): extract thread_utils module

---

ext/compatibility.h
ext/hook/uhook.c
ext/hook/uhook.stub.php
ext/hook/uhook_arginfo.h
tests/ext/sandbox/install_hook/replace_hook_args.phpt

This functionality is required to inject some data on method calls (like adding logging info, mostly trace/span ids).

Add HookData->overrideArguments() method to replace arguments in a pre-hook

---

tests/ext/sandbox-regression/abstract_method_hook.phpt
tests/ext/sandbox/abstract_trait_hook.phpt
tests/ext/sandbox/abstract_trait_hook_inherit.phpt
tests/ext/sandbox/interface_hook.phpt
tests/ext/sandbox/interface_hook_internal.phpt
tests/ext/sandbox/interface_inherit_hook.phpt
tests/ext/sandbox/interface_inherit_hook_explicit_reimplement.phpt
tests/ext/sandbox/interface_inherit_hook_multiple.phpt
zend_abstract_interface/hook/hook.c
zend_abstract_interface/hook/hook.h
zend_abstract_interface/interceptor/php7/interceptor.c
zend_abstract_interface/interceptor/php7/resolver.c
zend_abstract_interface/interceptor/php8/interceptor.c
zend_abstract_interface/symbols/call.c

This PR allows tracing of interface and abstract parent methods.
Abstract trait methods are not supported due to complexity with renaming etc. They may be considered in the future, but not now.

Add hooking for abstract methods

---

profiling/src/lib.rs
profiling/src/profiling/mod.rs
profiling/src/profiling/uploader.rs
profiling/src/sapi.rs

This function is called once per stack walk, so it's on the hot path but not as important to optimize as walking the stack itself.
However, it was showing up more than I would have expected in my profiles when examining it with the native profiler. Unfortunately I didn't have granular feedback on what was slowing it down, so I did some general optimization techniques:
1. Statically store the sample types as an array instead of creating them on-demand.
2. Replace Cow<'static, str> with &'static str in ValueType. All usages were already static strings, and I don't see this changing.
3. Simplify the branching logic into slicing operations.
4. Move tag creation to rinit, and share them with `Arc<Vec<Tag>>` instead of copying them. This makes the work to do on each stack sample be a simple …

perf(profiling): optimize prepare_sample_message

---

ext/hook/uhook.c
profiling/src/lib.rs
profiling/src/profiling/mod.rs
profiling/src/profiling/uploader.rs
zend_abstract_interface/config/config_runtime.c
zend_abstract_interface/hook/hook.c
zend_abstract_interface/hook/hook.h
zend_abstract_interface/interceptor/php7/interceptor.c
zend_abstract_interface/interceptor/php7/resolver.c
zend_abstract_interface/interceptor/php8/interceptor.c
zend_abstract_interface/interceptor/php8/resolver_pre-8_2.c

Use ZEND_TLS/TSRM_TLS macros instead of __thread to only use thread local storage in ZTS builds

---

ext/configuration.h
ext/hook/uhook.c
ext/hook/uhook_legacy.c
tests/ext/sandbox-regression/handle_many_hooks.phpt
tests/ext/sandbox/hook_limit.phpt
zend_abstract_interface/hook/hook.c
zend_abstract_interface/hook/hook.h

The primary motivation is users mistakenly installing hooks in a loop and observing memory leaking / increasing overhead.
Closes #1956.

Add DD_TRACE_HOOK_LIMIT

---

.circleci/config.yml
tests/randomized/analyze-results.php

Also reduce false positives from randomized memory report.
Should reduce errors in CI of type:
```
docker: Error response from daemon: Head "https://ghcr.io/v2/datadog/dd-apm-test-agent/ddapm-test-agent/manifests/latest": Get "https://ghcr.io/token?scope=repository%3Adatadog%2Fdd-apm-test-agent%2Fddapm-test-agent%3Apull&service=ghcr.io": context deadline exceeded (Client.Timeout exceeded while awaiting headers).
```

Reduce flakiness from docker containers not starting properly

---

.circleci/config.yml
.gitignore
Makefile
zend_abstract_interface/interceptor/php8/interceptor.c

Instead recognize libasan in the active php binary. "ASAN=" to disable, "ASAN=1" to enable explicitly.
I noticed that even though I have debug-zts-asan in my container, I usually did not have the extension itself built with asan, which sort of defeated the point mostly, given that I've not been adding `_asan` to my commands all the time.
Also optimizing Makefile to only do a `composer update` on missing lockfile or lockfile for different PHP version being installed when running `make test_*` commands.

Cleanup _asan usages in Makefile

---

ext/hook/uhook_legacy.c

CI failure, which was discovered after merging asan and the hook changes. 

Fix memory leak on hook/trace failure

---

ext/handlers_internal.c
tests/ext/sandbox/internal_hook_jit.phpt
zend_abstract_interface/interceptor/php8/interceptor.c
zend_abstract_interface/interceptor/php8/interceptor.h

On PHP 8.0 and PHP <=8.1.17, zend_execute_internal is not called in JIT. This replaces the handlers by a thin wrapper calling our zend_execute_internal handler directly.
This has been fixed in php-src via https://github.com/php/php-src/commit/c53e8d3e309a3c6154d9875d2a491822ecf78b9d.

Ensure that internal functions we trace in our integrations are always traced under JIT

---

profiling/src/lib.rs
profiling/src/profiling/mod.rs

This builds on #1932 by also doing `send_timeout` instead of a blocking `send`. The waiting on the threads now only occurs if the send is successful, and it also moved to zend extension shutdown, which happens after module shutdown.

fix(profiling): do not block indefinitely in mshutdown

---

ext/serializer.c
ext/span.c
tests/ext/inherit_meta_from_parent.phpt

Fetch things from parent span in order to ensure consistency of global tags, if the root spans metadata is changed after start.
Relates to #1958.

Inherit version, env and _dd.origin from parent span

---

.gitlab-ci.yml

Turns out reliability env deploys were not triggered automatically.
And fix the tracer version.

Fix reliability environment deploys

---

datadog-setup.php
tooling/bin/generate-installers.sh

This makes it easier to install directly from master or a branch, without having to install the .tar.gz manually.

Include the circleci URL for 1.0.0-nightly installers

---

tests/Integrations/PHPRedis/V5/PHPRedisTest.php
tests/ext/sandbox/hook_method/hook_extended_internal_class.phpt
zend_abstract_interface/hook/hook.c

In particular, test for \Redis being able to be extended.
Note: I discovered that we also don't hook anon classes properly (that's why they were commented out in the test). This is to be addressed in a future PR.

Allow for hooking of extended internal classes

---

profiling/src/config.rs
zend_abstract_interface/config/config_ini.c

Also handle the special case of the empty string in the profiling log level parser because of an unquoted "off" in ini becoming an empty string.

Fix system ini handling of invalid values in zai config

---

datadog-setup.php

Changes in this PR:
- Update appsec helper path
- Update appsec rules path
- Comment appsec rules if default (so that remote configuration can be used instead by default)
Updating the rules path and commenting it might seem unintuitive, the former is done just to keep it up to date in case the customer wants to use it, the latter is used so that remote configuration can override the rules (if user-defined rules are provided we can't override them). Commenting the rules is only done if the path corresponds to the default one.

Installer: update appsec helper and rules path

---

.circleci/config.yml
profiling/Cargo.lock
profiling/Cargo.toml
profiling/build.rs
profiling/src/bindings/mod.rs
profiling/src/lib.rs
profiling/src/php_ffi.c
profiling/src/php_ffi.h
profiling/tests/phpt/preload_01.phpt
profiling/tests/phpt/preload_01_preload.php

Fixes #1919. An issue occurred when preloading and a non-root user for php-fpm were combined, and eventually php-fpm would hang when the Profiler's channels were full. The full channel was worked around in a previous commit that landed in dd-trace-php v0.85.0, but this PR addresses the core issue so that profiles will actually get sent. Sampling will no longer occur when preloading is happening.
This adds a `CFG_PRELOAD` define for C and `cfg(php_preload)` for Rust, which match. They are made by the `build.rs` script, and are based on PHP version (PHP 7.4+ has preloading).
Bumps the profiling version to v0.15.0.
In CI, this changes the `cargo build` and `cargo test` type of jobs to use devtoolset-7 if it's present. This was required in a previous version of the PR which used …

fix(profiling): issues when preloading and non-root php-fpm user are used

---

src/Integrations/Integrations/DatabaseIntegrationHelper.php
src/Integrations/Integrations/Mysqli/MysqliIntegration.php
src/Integrations/Integrations/PDO/PDOIntegration.php
tests/Integration/DatabaseMonitoringTest.php

mssql is service-mode only, given it full context propagation messes with the query plan caching.

Restrict backends on DBM propagation

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Add MemcacheIntegration #1981
- Add PSR18 tracing support in any PSR18 ClientInterface #1938 
- Restrict backends on DBM propagation #1983 
- Allow for hooking of extended internal classes #1976
- Include the circleci URL for 1.0.0-nightly installers #1977
- Fix issues when preloading and non-root php-fpm user are used #1975
- perf: speed up stack walking by using function run_time_cache #1949
- Fix system ini handling of invalid values in zai config #1982
- Delete `enabled_on_cli` ini setting DataDog/dd-appsec-php#182
- Add uid and gid to sock and lock files DataDog/dd-appsec-php#183
- Remote configuration client DataDog/dd-appsec-php#115
- Plug remote config service DataDog/dd-appsec-php#163
- Add `config_sync` helper command DataDog/dd-appsec-php#164
- Add ASM_DATA Product Listener …

Release 0.86.0

---

ext/request_hooks.c
tests/ext/request-init-hook/auto_prepend_file_exception.inc
tests/ext/request-init-hook/exception_prepend_file.phpt
tests/ext/request-init-hook/invalid_prepend_file.phpt

Fixes crashes and swallowing of exceptions in auto_prepend_file. 
Guess `zend_execute_scripts` needs a fat warning "do not invoke without EG(current_execute_data) == NULL".

Fix exceptions and errors in auto_prepend_file

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Fix crash by reverting "perf(profiling): speed up stack walking by using function run_time_cache" #1994. Thanks, @zeroxs for reporting.

Release 0.86.1

---

profiling/tests/phpt/fibers_01.phpt

This will add a `.phpt` test to ensure we are not crashing with fibers being used.

test(profiling) add a test to ensure we do not crash with fibers

---

ext/ddtrace.c
ext/ddtrace.stub.php
ext/ddtrace_arginfo.h
tests/ext/distributed_tracing/distributed_trace_consume_array.phpt
tests/ext/distributed_tracing/distributed_trace_consume_func.phpt

This should be much more straightforward when generating headers to later consume them when doing manual injection and extraction.

Allow for consuming an array via DDTrace\consume_distributed_tracing_headers

---

bridge/autoload.php
tests/Composer/ComposerInteroperabilityTest.php
tests/Composer/app/preload.composer.no.ddtrace.php

Fixing an issue with preloading.
The current code assumes a src/ directory exists next to the ddtrace bridge, which is not the case in actually installed environments.

Load API files relative to the ComposerBootstrap.php instead of the ddtrace autoloader

---

ext/hook/uhook.c
ext/hook/uhook.h
ext/hook/uhook_legacy.c
ext/serializer.c
tests/ext/sandbox/hook_function/hook_does_not_leak_error.phpt
zend_abstract_interface/sandbox/php7/sandbox.c
zend_abstract_interface/sandbox/php8/sandbox.c
zend_abstract_interface/sandbox/sandbox.h

In particular this avoids the side effect of setting the response code to 500 for fatal errors in a hook callback if display_errors=0.

Avoid side effects from errors within the sandbox

---

ext/hook/uhook.c
tests/ext/sandbox/install_hook/hook_not_invoked_if_tracer_disabled.phpt

This led to crashes in combination with the database integrations, if database calls happened after the tracer was disabled.

Prevent execution of install_hook() hooks after disabling tracer

---

.circleci/config.yml
.gitlab-ci.yml
ext/version.h
profiling/Cargo.lock
profiling/Cargo.toml
src/DDTrace/Tracer.php
tooling/bin/generate-installers.sh
tooling/bin/pecl-build
tooling/ci/download-binary-php.sh

- The profiling version will now be synchronized with the tracer version.
- The tracer version on master will be the latest feature release instead of `1.0.0-nightly`.
- Non-release builds will append '+' followed by the git sha1 to the version number.
- Bump rust version in the Cargo.toml file. We had previously already bumped the version in other places and just missed this one.

Sync profiling version with tracer; append git sha1 to non-release builds

---

ext/compatibility.h
ext/ddtrace.c
ext/hook/uhook.c
ext/hook/uhook.stub.php
ext/hook/uhook_arginfo.h
tests/ext/sandbox/hook_function/hook_internal_fake_closure.phpt
tests/ext/sandbox/install_hook/hook_internal_fake_closure.phpt
tests/ext/sandbox/install_hook/trace_callable.phpt
tests/ext/sandbox/install_hook/trace_closure.phpt
tests/ext/sandbox/install_hook/trace_closure_from_callable.phpt
tests/ext/sandbox/install_hook/trace_file.phpt
zend_abstract_interface/hook/hook.c
zend_abstract_interface/hook/hook.h
zend_abstract_interface/interceptor/tests/resolver.cc

Also by default, apply closure hooks to the actual closure source; adding a flag DDTrace\HOOK_INSTANCE to only hook the specific Closure instance.
Given that the API is new and everyone I talked to was surprised by the behaviour, I'm changing it.

Allow DDTrace\install_hook to take any callable

---

ext/hook/uhook.c
tests/ext/sandbox/install_hook/install_hook_return_by_ref.phpt
zend_abstract_interface/interceptor/php7/interceptor.c

Two issues:
- IS_VAR passed to ZEND_RETURN(_BY_REF) on PHP 7 may be IS_INDIRECT. When copying these, we must ensure to not copy the IS_INDIRECT itself. It largely was unproblematic, but manipulating $hookData->returned could have unexpected side effects.
- On PHP 8 we need to track type sources as the $returned property is typed mixed and thus, the type source needs to be carried around. Otherwise we run into an assertion failure.
Note that these changes on the PHP 7 side also enable changing the return value (on PHP 8 no extra handling is needed).

Fix install_hook on functions returning by-reference

---

zend_abstract_interface/config/config.h

Increase the value of `ZAI_CONFIG_ENTRIES_COUNT_MAX` from 160 to 200. This will fix the failed assertion that appeared on master after merging the recent integrations (#1996 and #1990).

Increase the number of configuration entries in zai config

---

ext/hook/uhook.c
ext/hook/uhook.stub.php
ext/hook/uhook_arginfo.h
tests/ext/sandbox/install_hook/replace_hook_retval.phpt

Adding HookData->overrideReturnValue.
Needed for Laravel Queues implementation to inject distributed tracing data.

Implement replacing of return values

---

.circleci/config.yml
src/Integrations/Util/Normalizer.php

And adding a CI check for that...

Fix #2012: Remove PHP 7-only types from signatures 

---

ext/ddtrace.c
zend_abstract_interface/hook/hook.c
zend_abstract_interface/hook/hook.h
zend_abstract_interface/hook/tests/internal/request.cc
zend_abstract_interface/hook/tests/internal/static.cc
zend_abstract_interface/interceptor/tests/interceptor.cc
zend_abstract_interface/interceptor/tests/resolver.cc

Static TLS block bytes are scarce, and we've encountered, when including libdatadog on another branch, the infamous "cannot allocate memory in static TLS block" error when dlopen()'ing dd-trace-php.
Reducing potential conflicts with other extensions also making usage of TLS data.

Optimize TLS usage

---

.gitlab-ci.yml

This PR changes reliability environment deploys to happen according to these rules:
- nightly
- on every commit to a release branch
- manually

Schedule reliability env deploys

---

profiling/src/config.rs
profiling/src/lib.rs

This PR will raise the sampling distance for allocation profiling from 512 KB to 2048 KB to prepare for GAing

feat(profiling) raise sampling distance for allocation profiling

---

.circleci/config.yml
profiling/Cargo.toml
profiling/README.md
profiling/build.rs
profiling/src/php_ffi.c
profiling/src/php_ffi.h
profiling/src/profiling/stalk_walking.rs

This PR will add a test for stack walking to the profiler, that can be run without PHP being around. The main reason for this PR is that it provides the foundation of building micro benchmarks for the profiler that run without PHP.
- adds a unit test that validates the resulting stack frames against a fake PHP stack
- adds function to create a fake stack frame
- which is only compiled when enabling the `stack_walking_tests` feature
When reviewing please keep on eye on the following: The `ddog_php_test_*` functions in the `php_ffi.c` should not be compiled when building a release, but only when running tests. Currently this is implemented with a cargo feature `stack_walking_tests`, but maybe in the future we find a more automatic way.

test(profiling) add stack walking test

---

ext/handlers_curl_php7.c
ext/span.c
tests/randomized/config/envs.php

In preparing allocation profiling GA we found some bugs in the profiler -> tracer interaction that this PR fixes.
- possible segfault when instrumenting `curl_setopt()` in PHP7
- possible segfault when fetching active span during priority sampling decision

fix(profiling): crashes when allocation sampling occurs in certain places

---

.circleci/config.yml

It seems that `libonig4` has been removed from the Debian pool servers and the `datadog/docker-library:ddtrace_php_fpm_packaging` which is currently based on Debian Stretch is broken due to this.

fix(ci) switch to static binary for `jq`

---

tests/ext/sandbox-regression/class_resolver_bailout_hook.phpt
zend_abstract_interface/interceptor/php7/interceptor.c
zend_abstract_interface/interceptor/php7/resolver.c
zend_abstract_interface/interceptor/php8/interceptor.c
zend_abstract_interface/interceptor/php8/resolver_pre-8_2.c

We fix this issue by ensuring that the opline is always connected to its proper execute_data and popping newer entries if they aren't matching.
Note for the reviewer: the PHP 7 and PHP 8 changes are identical.

Fix #2030: Segmentation fault with autoloaders bailing out

---

.circleci/config.yml
profiling/Cargo.lock
profiling/Cargo.toml
profiling/src/bindings/mod.rs
profiling/src/config.rs
profiling/src/lib.rs
profiling/src/profiling/mod.rs
zend_abstract_interface/json/json.c
zend_abstract_interface/json/json.h

This makes the profilers dependency on `ext-json` explicit, as well as fixes a bug on MacOS, where `php_json_serializable_ce` was `NULL` in every case (due to the missing `extern`) and the profiler would panic:
```
[2023-05-10T13:25:27.409327Z TRACE datadog_php_profiling] MINIT(1, 36)
thread '<unnamed>' panicked at 'assertion failed: tmp', src/config.rs:513:9
stack backtrace:
0: rust_begin_unwind
at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt
at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
2: core::panicking::panic
at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
3: datadog_php_profiling::config::minit
at ./src/config.rs:513:9
4: …
```

fix(profiling): fix panic by explicitly depending on `ext-json`

---

ext/auto_flush.c
ext/auto_flush.h
ext/configuration.h
ext/ddtrace.c
ext/span.c
ext/span.h

We had an user where it massively impacted their performance: And _practically_ it should rarely make a difference (it only matters with autoflush active and forgetting to close all of a stacks spans and GC running next to never in a long running script. But if it _does_ delay traces from arriving, there's an escape hatch configuration option.

Do not force cycle collection at runtime on flush by default

---

.circleci/config.yml

This will remove the installation of `jq` as it is now backed into the container, see https://github.com/DataDog/docker-library/pull/93

fix(ci) this will update the container used for `package extension`

---

datadog-setup.php

I'm trying to install Datadog APM in a legacy PHP 5 application and it's failing with a syntax error because of the return types on lines [244](https://github.com/DataDog/dd-trace-php/blob/8979b7c3742389208c56bbc0de7b6b16568aa8fe/datadog-setup.php#L244), [742](https://github.com/DataDog/dd-trace-php/blob/8979b7c3742389208c56bbc0de7b6b16568aa8fe/datadog-setup.php#L742) and [801](https://github.com/DataDog/dd-trace-php/blob/8979b7c3742389208c56bbc0de7b6b16568aa8fe/datadog-setup.php#L801). This error was apparently introduced in #1951
This PR removes the return types so it's syntax-compatible with PHP 5 (tested with `php -l` on PHP 5.6.40, which is the version my app uses).
I guess #2021 was merged after #1951, otherwise the "Lint PHP 5" would've caught it.
The installer for dd-trace-php …

fix(datadog-setup.php): remove return types for compatibility with PHP 5

---

tests/composer.json

v2 was released yesterday and it dropped support for PHP <7.2. We don't support promises v2 yet so our tests fail without the pin.
Thanks, @realFlowControl, for investigating why CI was failing suddenly.

build: pin guzzlehttp/promises to ^1.5.3

---

dockerfiles/ci/xfail_tests/8.1.list
dockerfiles/ci/xfail_tests/8.2.list
dockerfiles/ci/xfail_tests/README.md
ext/handlers_fiber.c
ext/span.h

Work around fiber->execute_data only being correct upon yielding

---

tests/Integrations/Guzzle/V6/guzzle_in_distributed_web_request.php
tests/composer.json

Change some methods in the guzzle test suites that were removed with the v2 of guzzle promises:
- [all](https://github.com/guzzle/promises/blob/136a635e2b4a49b9d79e9c8fee267ffb257fdba0/src/functions.php#L177): `Promises\all` --> `Utils::all`
- [is_settled](https://github.com/guzzle/promises/blob/136a635e2b4a49b9d79e9c8fee267ffb257fdba0/src/functions.php#L346): `Promises\is_settled`--> `Is:settled`

Update removed methods used in Guzzle V6 & V7 test suites

---

profiling/src/lib.rs
profiling/src/php_ffi.c
profiling/src/php_ffi.h
profiling/tests/phpt/jit_01.phpt
profiling/tests/phpt/phpinfo_01.phpt
profiling/tests/phpt/phpinfo_02.phpt
profiling/tests/phpt/phpinfo_ini_01.phpt

We did find a crash under the following conditions:
- PHP JIT is enabled
- Allocation profiling is enabled
- a `ZEND_GENERATOR_RETURN` is being executed
- and we collect a stack frame at exactly this time
For the time being we decide to disable allocation profiling as long as JIT is enabled. This should only affect a small subset of users, as JIT is still (PHP 8.2) default disabled. Which means: if you have not manually enabled JIT, it won't be enabled at all.
In the future we will work around this problem and allow you to enable allocation profiling even when JIT is active.
This PR will also state this in the `phpinfo()` output and mark "Allocation Profiling Enabled" as "not available" in case an active JIT is detected:
```sh
php -d extension=datadog-profiling --ri datadog-profiling | …
```

feat(profiling) disable allocation profiling when JIT is active

---

components-rs/common.h
components-rs/ddtrace.h
components-rs/telemetry.rs
ext/telemetry.c
tests/ext/telemetry/config.phpt

Telemetry v2 also expects default configs to be sent.
Buffering sending config data to avoid I/O overhead.

Send telemetry for all configs, including unchanged ones

---

profiling/src/allocation.rs
profiling/src/lib.rs
profiling/src/profiling/mod.rs

This PR extracts the allocation profiling specific parts into their own mod. Main motivations are:
- `lib.rs` is > 1270 lines, ¼ of this is allocation profiling
- there is `#[cfg(feature = "allocation_profiling")]` spread everywhere (and missing in some places, where it should be)
- IIRC the `lib.rs` intention was to bind to the Zend Engine, so I guess it is a good idea to move allocation profiling specific parts away from this file
**Attention**: besides moving code around this PR will also do a change in how we call the orginal / previous allocation function. Prior to this PR in every `malloc()`/`realloc()`/`free()` call we did check if we found custom handlers during `RINIT`, then called those, and otherwise called the original handlers.
Now we initialise a function pointer depending …

refactor(profiling): move allocation profiling to its own module

---

.circleci/continue_config.yml
Makefile
dockerfiles/ci/buster/build-extensions.sh
dockerfiles/ci/buster/build-php.sh
dockerfiles/ci/xfail_tests/8.1.list
dockerfiles/ci/xfail_tests/8.2.list
dockerfiles/ci/xfail_tests/README.md
zend_abstract_interface/interceptor/php8/interceptor.c
zend_abstract_interface/symbols/call.c

This PR mirrors the changes done to https://github.com/php/php-src/commit/709540ccdc5a3fc25fcdfceba322e6ad3aa3ce6f for the 8.1 implementation.
Additionally, given that PHP 8.2 is broken up to now, we default to our own implementation for PHP 8.2, and use the proper php-src API only from PHP 8.3 on.
Fixes #2075.

Ensure no crashes happen with multiple observers installed

---

src/Integrations/Integrations/Laminas/LaminasIntegration.php

While doing some testing for logs correlation, I got an exception in the Laminas Integration. The issue was that `MvcEvent::setError` doesn't return an array (but an `MvcEvent`), yet the offset `0` was tried to be accessed.

(Laminas) Fix incorrect offset access

---

ext/configuration.h
src/Integrations/Integrations/Laravel/LaravelIntegration.php
src/Integrations/Integrations/LaravelQueue/LaravelQueueIntegration.php
src/Integrations/Integrations/Predis/PredisIntegration.php
tests/Integrations/Laravel/V5_8/QueueTest.php
tests/Integrations/Laravel/V8_x/QueueTest.php

Fix #2080.
Two configuration options are added:
- `DD_TRACE_REMOVE_ROOT_SPAN_LARAVEL_QUEUE`: Defaults to `true`. If enabled and a Laravel Queue/Horizon command was used (more specifically, `queue:work` and `horizon:work`), then the environment variables `DD_TRACE_GENERATE_ROOT_SPAN` and `DD_TRACE_AUTO_FLUSH` will be set to `0` and `1`, respectively, during the Laravel integration's initialization phase.
- `DD_TRACE_REMOVE_AUTOINSTRUMENTATION_ORPHANS`: Defaults to `false`. If enabled, the following 'solo-trace-span' will be ignored by the backend
- `laravel.event.handle`
- `laravel.provider.load`
- `Predis.Client.__construct`
- `Predis.Client.executeCommand`
- `Predis.Pipeline.executePipeline`
**Additionally**, it will also remove the hook that was installed on the job method call after it …

Disable root span generation and removes orphans for Laravel Horizon

---

src/Integrations/Integrations/AMQP/AMQPIntegration.php
tests/Integrations/AMQP/AMQPTest.php

Draft PR
This PR changes the behavior of the consuming methods in a distributed context.
Related to `basic_deliver`:
- If the message has distributed headers, a new trace will be started in the prehook and closed in the posthook. 
- The message's distributed context will be extracted onto this newly created trace.
- A bidirectional span link between this newly created `basic_deliver` and the original `basic_deliver` will be created.
Related to `basic_get`:
- The automatic context extraction from the message is **removed**.
- Instead, a span link to the emitting trace will be created using the message's distributed headers and converting the trace identifiers to the required format, if needed.

Use span links in the RabbitMQ Integration

---

Makefile
ddtrace.sym
ext/configuration.h
tests/Integrations/Custom/Autoloaded/InstrumentationTest.php
tests/ext/telemetry/composer.phpt
tests/ext/telemetry/config.phpt
tests/ext/telemetry/integration.phpt
tests/ext/telemetry/simple.phpt

Also fix runtime_id integration with profiler (missing exported symbol).

Disable telemetry by default until further stabilization

---

components-rs/ddtrace.h
components-rs/lib.rs
components-rs/telemetry.rs

Explanation of lints:
- `#[must_use]` doesn't make sense on functions that return `()` aka `void`.
- Rust prefers using `!foo.is_empty()` over `foo.len() > 0`
- Clippy likes unsafe functions to have their safety conditions documented.
- There's no need to explicitly type the unit return type `-> ()`; it's implicit in Rust.
There are more lints, but these ones were trivial to fix.

style: fix clippy lints

---

.circleci/continue_config.yml

The most recent few releases of profiling have a commit hash in their version number. This is expected for non-releases, but shouldn't be there for releases.
This does two things in CI:
- Profiling jobs check that the env var `CIRCLE_BRANCH` exists and is not empty. If it's not set, the job isn't set up right.
- Propagates `CIRCLE_BRANCH` in the `setup_docker` command, which the profiling jobs use.

build: fix commit hashes in profiling release versions

---

Makefile
README.md
config.m4

Add note about cargo in README, make debug symbols included by default for manual compilation

---

Makefile
config.m4

Mistake in the last PR, noticed when downloading the artifacts.

Fix debug symbols stripping for rust

---

.circleci/continue_config.yml
config.m4

Fixes #2113.
Works around the fact that it might be called e.g. php-config8.2 or similar.

Use proper variable for php-config

---

.circleci/continue_config.yml

In the internal API randomized tests the core file (in case a segfault happens) would not be in `/tmp/core`,  because `/proc/sys/kernel/core_pattern` is set to `|/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E` on the host which is inherited by the container. Now inside the container the `apport` binaray does not exists, so core dumps are lost.
We can not change the core pattern from inside the container, as this is not a privileged one, so we do it as an extra step from the outside.
Find the failed job here that did not have a core dump in the artifacts:
https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/11602/workflows/0ac9f7b9-8200-4c94-ae58-7edd648f90fc/jobs/2461257/steps

ci: make sure core file is where it should be

---

ext/compatibility.h
ext/span.c

Just increase rc by a billion instead of 1...

Better GC workaround on PHP 7.3 and below for cycle collected span stacks

---

profiling/src/profiling/mod.rs
profiling/src/profiling/uploader.rs

This adds endpoint counts to the profiles, bring PHP up to feature parity in this regard. The UI can now show "per Minute by Endpoint" or "by Endpoint Call".

feat(profiling): add endpoint counts

---

CONTRIBUTING.md

The following operations are required but were not mentioned in the CONTRIBUTING file.
```
git submodule init
git submodule update
```

Add git submodules operations to the CONTRIBUTING file

---

.github/CODEOWNERS
Cargo.lock
profiling/Cargo.toml

Fortunately, we are not affected by any breaking changes. Also attempts to make `Cargo.lock` approvable by profiling or tracing.

build(profiling): bump indexmap to v2.0.0

---

Cargo.lock
profiling/Cargo.toml
profiling/build.rs
profiling/src/allocation.rs
profiling/src/bindings/mod.rs

Bumps the bindgen dependency to 0.66.1:
- Had to fix some `u64`/`size_t` differences for allocation profiling.
- `rustfmt_bindings` is deprecated now and it's enabled by default.
- Removes unnecessary qualifications like `::libc::c_void`. Also imports things like `libc::c_void` if other `libc::` items were already being imported.
This is stacked on top of another PR; merge it first.

build(profiling): bump bindgen to 0.66.1

---

.gitlab/benchmarks.yml
tests/randomized/config/envs.php

This will make sure the benchmarks are only run on changes in the profiler, as the tracer does not have benchmarks yet. Additionally it will add the timeline feature to the randomized tests.
We do not need the `DD_PROFILING_EXPERIMENTAL_ALLOCATION_ENABLED` env variable anymore, as allocation profiling is enabled by default now.

Run benchmarks only in profiling PRs

---

ext/ddtrace.c

Without this, in SAPIs which fork after MINIT, the runtime id will be shared by multiple processes. This issue was introduced in #2029 in v0.88.0 when the tracer took over runtime generation. Previously the profiler was in charge of generating the runtime id.
This affects cross-product features such as Code Hotspots in the profiler.

fix: generate runtime-id on first request

---

profiling/src/lib.rs
profiling/tests/phpt/phpinfo_02.phpt

This will add more helpful output the the `phpinfo()` output for the profiler.
Example:
```
$ php --ri datadog-profiling
datadog-profiling
Version => 0.89.0
Profiling Enabled => true
Experimental CPU Time Profiling Enabled => true
Allocation Profiling Enabled => Not available due to JIT being active, see https://github.com/DataDog/dd-trace-php/pull/2088 for more information.
Experimental Timeline Enabled => Not available. The profiler was build without timeline support.
Endpoint Collection Enabled => true
Platform's CPU Time API Works => true
Profiling Log Level => trace
Profiling Agent Endpoint => http://localhost:8126/
Application's Environment (DD_ENV) =>  
Application's Service (DD_SERVICE) => Standard input code
Application's Version (DD_VERSION) =>  
...
```

doc(profiling): make `phpinfo()` output more helpful

---

.circleci/continue_config.yml
dockerfiles/ci/xfail_tests/7.0.list
dockerfiles/ci/xfail_tests/README.md

The language tests are sometimes flaky with network related tests. Although we've added many to our xfail lists, new ones get added from time to time when we update PHP versions used in the tests. This seems a bit more robust than explicitly listing all of them in the xfail lists.
Some online tests like `ext/sockets/tests/socket_shutdown.phpt` exist on versions which don't check `SKIP_ONLINE_TESTS`, so they are added to the xfail lists for the relevant versions.

ci: skip online tests due to flakiness

---

ext/configuration.h
ext/ddtrace.c
ext/ddtrace.h
tests/ext/runtime_ini_env_version_change.phpt

Generally, users have been trying to change datadog.version or datadog.env at runtime (because it fits their setup easier) and were disappointed it to not affect the root span.

Reflect changes to datadog.version and datadog.env in existing spans

---

.cargo-registry/.gitignore
components-rs/build.rs
config.m4
docker-compose.yml

- Use a shared cache of dependencies
- Ensure that cargo doesn't always need to recompile when tracer files change
- Fix tracking of rust dependencies in Makefile

Improve cargo build a bit

---

src/DDTrace/ScopeManager.php
tests/Common/BaseTestCase.php
tests/Unit/TracerTest.php

While experimenting with ways to reproduce #2172, I stumbled on an issue that would lead to the tracer crashing with the error message `Attempt to read property "id" on null`. The latter would happen when using `Tracer::getActiveSpan` after `start_root_span()` was called.

(Legacy OpenTracing API) Check if the active span has a parent

---

.gitlab/benchmarks.yml

Fixes the the changes detection on Gitlab, so it starts working for new branches.
Gitlab has a known issue with changes detection, please see documentation for more info:
* https://docs.gitlab.com/ee/ci/jobs/job_control.html#jobs-or-pipelines-run-unexpectedly-when-using-changes
* https://gitlab.com/gitlab-org/gitlab/-/issues/11427
Gitlab ignores `changes` keyword when a new branch is pushed, unless merge request on Gitlab exists (which doesn't, since we use custom gitsync tooling). In order to mitigate the issue, [a keyword `compare_to` was introduced in Gitlab](https://docs.gitlab.com/ee/ci/yaml/#ruleschangescompare_to), so developers can specify a ref for changes detection.
This PR uses `compare_to` to enable automatic benchmark runs for branches that have changes in `/profiling` …

Run profiling benchmarks in Gitlab only when changes are detected

---

profiling/src/profiling/stalk_walking.rs
profiling/src/string_table.rs

This makes the entries in the string table more compact by a small bit. This is not expected to be a significant improvement, just a small one, and mostly oriented around memory consumption rather than CPU.

perf(profiling): use u32 instead of usize for string table indices

---

Cargo.lock
dockerfiles/ci/README.md
dockerfiles/ci/alpine_compile_extension/Dockerfile
dockerfiles/ci/alpine_compile_extension/docker-compose.yml
dockerfiles/ci/buster/Dockerfile
dockerfiles/ci/buster/build-php.sh
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/centos/7/base.Dockerfile
dockerfiles/ci/centos/7/docker-compose.yml
dockerfiles/ci/centos/7/download-src.sh
profiling/rust-toolchain.toml

This PR will upgrade:
- Rust from 1.64 to 1.71
- LLVM from 14 to 16 (to match Rust 1.71)
- Alpine from 3.17 to 3.18
- and add `lld` (the llvm linker)
I am currently building the images locally.

build: Update to Rust 1.71 / Alpine 3.18

---

zend_abstract_interface/config/config.c
zend_abstract_interface/config/config_ini.c
zend_abstract_interface/config/config_ini.h
zend_abstract_interface/zai_string/string.h

Soon I hope to enforce that `zai_string_view`s never hold null pointers. While refactoring, I accidentally hit a case where `.ptr == null` was handled differently from `.ptr = ""`. I added `zai_option_str` to address this case.
This changes the signature of a possibly-public function `zai_config_initialize_ini_value`. The profiler does not use this function directly, but application security may--I haven't checked.

Add `zai_option_str` and use it in config

---

ext/configuration.c
ext/ddtrace.c
ext/hook/uhook.c
ext/integrations/integrations.c
ext/serializer.c
zend_abstract_interface/config/config.c
zend_abstract_interface/config/config_ini.c
zend_abstract_interface/config/config_ini.h
zend_abstract_interface/config/config_runtime.c
zend_abstract_interface/env/env.c
zend_abstract_interface/exceptions/exceptions.h
zend_abstract_interface/exceptions/tests/exceptions.cc
zend_abstract_interface/headers/headers.c
zend_abstract_interface/interceptor/tests/resolver.cc
zend_abstract_interface/symbols/api/call.h
zend_abstract_interface/symbols/api/class.h
zend_abstract_interface/symbols/api/constant.h
zend_abstract_interface/symbols/api/function.h
zend_abstract_interface/symbols/api/property.h
zend_abstract_interface/symbols/lookup.c
zend_abstract_interface/symbols/tests/api/call.cc
zend_abstract_interface/symbols/tests/api/class.cc
zend_abstract_interface/symbols/tests/api/constant.cc
zend_abstract_interface/symbols/tests/api/function.cc
zend_abstract_interface/symbols/tests/api/property.cc
zend_abstract_interface/symbols/tests/call/closure.cc
zend_abstract_interface/zai_string/string.h

This adds new macros and functions for working with zai_string_view. They are prefixed with `zai_str_` or `ZAI_STR_` in preparation for renaming `zai_string_view` to simply `zai_str`. By naming these with the new prefix, it will reduce the size of the review for that PR.
This changes the signatures of many functions taking pairs of pointers and lengths to using zai_string_views instead, and the functions were renamed because they had `literal` in their names which didn't apply anymore. A small number of these already had versions that took views, so the versions with literals were outright removed.

Refactor zai_string_view APIs and use them more

---

ext/configuration.c
zend_abstract_interface/zai_string/string.h

Renames`zai_str_equals_ci_cstr` to `zai_str_eq_ci_cstr` to match `zai_str_eq`.
This is a follow-up from [code review](https://github.com/DataDog/dd-trace-php/pull/2203#pullrequestreview-1580538278) on a previous PR.

refactor: rename zai_str_equals_ci_cstr to zai_str_eq_ci_cstr

---

dockerfiles/ci/xfail_tests/8.1.list
dockerfiles/ci/xfail_tests/8.2.list
dockerfiles/ci/xfail_tests/README.md

There are two tests failing since #2208:
- `ext/standard/tests/network/syslog_null_byte.phpt`
- `ext/standard/tests/network/syslog_new_line.phpt`
Both of them have a additional `PHPT: DIGEST-MD5 common mech free` in the output which is not expected in the test. This line originates from `libdigestmd5.so` which is shipped as part of `libsasl2-modules` in Debian. We are currently running those tests on Debian Buster which is stuck on Version 2.1.27 of that package, while the ["fix" is in 2.1.28 version of the Debian package](https://git.launchpad.net/ubuntu/+source/cyrus-sasl2/tree/debian/patches/0001-plugins-digestmd5-Remove-debug-log-mech-free.patch).
For the time being we'll just allow those tests to fail. We'll have to revisit once we run the tests not on Debian Buster anymore.
More …

Not run syslog tests on outdated libsasl2-2.1.27

---

ext/ddtrace.stub.php
ext/ddtrace_arginfo.h
ext/hook/uhook.stub.php
ext/hook/uhook_arginfo.h

I wanted to use the stubs, and it seems that not all are defined correctly.
Btw. why not to move them to https://github.com/JetBrains/phpstorm-stubs?

chore: readonly not suppose to have default value

---

ext/ddtrace.h
ext/hook/uhook.c
ext/serializer.c

And add a small safeguard in serialization with dropping parents (I'm not sure under which circumstances that happens, but apparently it happens, but CI should be happy I hope).
That should fix the CI issues encountered.

Fix tests: allocate less TLS space by putting uhook HashTables into module globals

---

profiling/build.rs
profiling/src/bindings/ffi.rs
profiling/src/bindings/mod.rs
profiling/src/capi.rs
profiling/src/config.rs
profiling/src/profiling/stalk_walking.rs
profiling/src/timeline.rs
tea/include/common.h
zend_abstract_interface/config/tests/id.cc
zend_abstract_interface/env/tests/error.cc
zend_abstract_interface/headers/tests/headers.cc
zend_abstract_interface/hook/tests/internal/request.cc
zend_abstract_interface/symbols/call.c
zend_abstract_interface/zai_assert/zai_assert.h
zend_abstract_interface/zai_string/CMakeLists.txt
zend_abstract_interface/zai_string/string.h

Requires `zai_str.ptr` to not be null and also moves the `.ptr` to be first. This matches Rust's slice layout, as well as `struct iovec` on most platforms. Reordering also helped find some C++ locations which were using designated initializers, as that feature in C++ requires fields to be initialized in the same order as the source, and were thereby broken by the re-ordering.
This also fixes the profiler's equivalent structs (there were two of them 🤦🏻). It combines them into one struct since they had to be updated anyway.
This also fixes a potential heap-buffer-overflow when zai is used without an observer. I think only the tracer was using the particular set of functions which could have hit this, and the tracer is an observer, so in practice I don't think it could have been triggered by …

Require `zai_str.ptr` to not be null

---

ext/hook/uhook.c
tests/ext/sandbox/install_hook/override_argument_jit.phpt
tests/ext/sandbox/install_hook/replace_hook_args.phpt
tests/ext/sandbox/internal_hook_jit.phpt

Fix #2174: Can't pass less args to an untyped function than originally passed

---

config.m4
profiling/build.rs
profiling/src/bindings/mod.rs
profiling/src/capi.rs
profiling/src/php_ffi.c
profiling/src/profiling/stalk_walking.rs
profiling/src/timeline.rs
zend_abstract_interface/config/CMakeLists.txt
zend_abstract_interface/env/CMakeLists.txt
zend_abstract_interface/env/env.h
zend_abstract_interface/headers/CMakeLists.txt
zend_abstract_interface/symbols/CMakeLists.txt
zend_abstract_interface/symbols/lookup.c
zend_abstract_interface/zai_string/CMakeLists.txt
zend_abstract_interface/zai_string/string.c
zend_abstract_interface/zai_string/string.h
zend_abstract_interface/zai_string/tests/CMakeLists.txt
zend_abstract_interface/zai_string/tests/strings.cc

This adds a `zai_string` struct and associated methods. Part of the `zai_config` code was storing owned pointers inside `zai_str`s, and since it did it more than once, I figured adding a dedicated struct with methods seemed prudent.
A few notes:
- We don't want to allocate for empty strings. There is some effort made to return a canonical empty string `ZAI_STRING_EMPTY` which always uses `ZAI_STRING_EMPTY_PTR` for the pointer value. This pointer is not freed in `zai_string_dtor`.
- There are tests for some `zai_string` and `zai_str` functions now.
This also uses the `zai_str_from_zstr` function in the profiler instead of rolling its own `ddog_php_prof_zend_string_view`. This means that at least for now, `zai_str_from_zstr` cannot be purely `static inline`. So I use the standardized C99 …

Add `zai_string` and use it in `zai_config`

---

Makefile
README.md

And bump the required rust version in the README.

Fix #2232: Add Cargo.lock to pecl

---

src/Integrations/Integrations/Logs/LogsIntegration.php

`str_contains` does not exist in PHP7. The tests missed this because of the tests' polyfill (`symfony/polyfill-php80`). 
This may address the issue mentioned in #2231 (TBD).

fix: PHP7 compatibility in logs correlation

---

datadog-setup.php
package.xml

When the INI file found by `datadog-setup.php` is a symlink, the script wont update the INI file correctly.
We found out by a customer complaint. They where installing the tracer via a Debian Package which creates the `/usr/local/etc/php/conf.d/98-ddtrace.ini` as a symlink to `/opt/datadog-php/etc/ddtrace.ini`. Now `sed` is being used with `-i` to update some parts of the INI file, but `sed -i` destroys the symlink and creates a regular file instead which leads to none of the changes are making it to the INI file.
The workaround in that specific case is to not install the tracer via a Debian package, but only use the `datadog-setup.php`,  but still the INI file being a symlink should be supported.
PROF-8145

fix: `datadog-setup.php` when INI file is a symlink

---

config.m4
ext/ddtrace.c
ext/hook/uhook.c
package.xml
tests/ext/sandbox/install_hook/override_argument_jit.phpt
zend_abstract_interface/jit_utils/jit_blacklist.c
zend_abstract_interface/jit_utils/jit_blacklist.h

This PR forcefully disallows inlining the hooked methods where overrideArguments is used.
I'll look at implementing a mechanism directly in php-src to avoid this issue.

Work around JITting when using HookData->overrideArguments

---

Cargo.lock
package.xml

This is done especially because I saw this https://github.com/advisories/GHSA-8qv2-5vq6-g2g7
```
Updating crates.io index
Updating git repository `https://github.com/DataDog/libdatadog`
Updating aho-corasick v1.0.4 -> v1.0.5
Updating chrono v0.4.26 -> v0.4.29
Updating clap v4.4.1 -> v4.4.2
Updating clap_builder v4.4.1 -> v4.4.2
Adding home v0.5.5
Updating memchr v2.6.0 -> v2.6.3
Updating object v0.32.0 -> v0.32.1
Updating prettyplease v0.2.12 -> v0.2.14
Updating regex v1.9.4 -> v1.9.5
Updating regex-automata v0.3.7 -> v0.3.8
Updating rustix v0.38.10 -> v0.38.11
Updating shlex v1.1.0 -> v1.2.0
Updating syn v2.0.29 -> v2.0.31
Updating thiserror v1.0.47 -> v1.0.48
Updating thiserror-impl v1.0.47 -> v1.0.48
Updating walkdir v2.3.3 -> v2.4.0
Updating webpki v0.22.0 -> v0.22.1
Updating which …
```

dependencies: update webpki and others

---

profiling/build.rs
profiling/src/allocation.rs
profiling/src/bindings/mod.rs
profiling/src/config.rs
profiling/src/lib.rs
profiling/src/php_ffi.c
profiling/src/php_ffi.h
profiling/tests/phpt/jit_02.phpt
profiling/tests/phpt/phpinfo_01.phpt
profiling/tests/phpt/phpinfo_02.phpt
profiling/tests/phpt/phpinfo_03.phpt
profiling/tests/phpt/phpinfo_04.phpt

In #2088 we disabled allocation profiling on PHP Version >= 8.0.0 when an active JIT is detected. This PR will incorporate the fact that PHP 8.1.21 and 8.2.8 have a fix for this bug, so we will now disable allocation profiling only when JIT is active on PHP 8.0, 8.1.0 - 8.1.20 and 8.2.0 - 8.2.7.

feat(profiling): Do not disable allocation profiling on fixed PHP version with active JIT

---

profiling/src/profiling/mod.rs
profiling/src/timeline.rs
profiling/tests/correctness/timeline.json
profiling/tests/correctness/timeline.php

String compilation events (`eval()`) where missing an `end_timestamp_ns` label, so they did not show up in the profiling timeline. This PR adds the missing label
It is currently not testing, that there is a `end_timestamp_ns` label onyl that there is an `eval()` call observed, as I would have to add a value, but that value is unpredictable. This would need a change in https://github.com/DataDog/prof-correctness/

fix(profilier) Add missing `end_timestamp_ns` to string compilation event

---

profiling/src/php_ffi.c

One of our randomized tests surfaced a segfault in allocation profiling, here is how you may reproduce the bug:
- create a PHP file that includes another PHP file (besides that, those files can be emtpy)
- make sure to collect every allocation (set `ALLOCATION_PROFILING_INTERVAL` in `src/allocation.rs` to `1.0`)
- comment out ignoring runtime cache on CLI SAPI in [src/php_ffi.c](https://github.com/DataDog/dd-trace-php/blob/5f38251b568fc028f6d1ef44dcb32f0c67c8dd10/profiling/src/php_ffi.c#L81)
- execute the script with loaded profiler and activated OPcache and see it segfault
What is happening is that after file compilation, the OPcache tries to persist the currently compiled PHP file into the OPcache, creating a fake stack frame and pushing that onto the stack in …

fix(profiling) detect an uninitialized runtime cache

---

tests/Frameworks/Symfony/Version_5_2/composer.json

This PR explicitly sets the version of `doctrine/dbal` to `^2.13`
**Reasons** 👇 
The Symfony 5.2 tests started failing and were characterized by the following exception on the framework side:
```
[critical] Uncaught Error: Undefined constant Doctrine\DBAL\Types\Types::JSON_ARRAY
```
As shown in the screenshot above, the composer started updating the `doctrine/dbal` dependency from major version 2 to major version 3. However, `Doctrine\DBAL\Types\Types::JSON_ARRAY` was [deprecated](https://github.com/doctrine/dbal/blob/c480849ca3ad6706a39c970cdfe6888fa8a058b8/lib/Doctrine/DBAL/Types/Types.php#L38) and [removed](https://github.com/doctrine/dbal/blob/3.0.0/src/Types/Types.php) in version 3.

fix: keep doctrine/dbal to major version 2 in symfony 5.2 tests

---

ext/ddtrace.c
tests/Frameworks/Custom/Version_Not_Autoloaded/per-dir-disabled/.htaccess
tests/Frameworks/Custom/Version_Not_Autoloaded/per-dir-disabled/.user.ini
tests/Frameworks/Custom/Version_Not_Autoloaded/per-dir-disabled/test.php
tests/Integrations/Custom/NotAutoloaded/EarlyDisableTest.php
zend_abstract_interface/config/config_ini.c

And ensure in ZAI config that perdir configuration is handled the same with fpm and apache. Fixes #2266.

Fix toggling datadog.trace.enabled with perdir configuation

---

src/Integrations/Integrations/DatabaseIntegrationHelper.php
tests/Integration/DatabaseMonitoringTest.php

Prioritize `peer.service` as dddbs for SQL comments when available. Reasoning explained [in this task](https://datadoghq.atlassian.net/browse/AIT-8319).

Set peer.service as dddbs when available

---

ext/startup_logging.c

We officially support DD_LOGS_INJECTION (also in docs), so it's confusing if this is marked deprecated.

Do not emit a deprecated diagnostic for DD_LOGS_INJECTION

---

profiling/src/allocation.rs

In case another extension is installing it's own heap into the ZendMM we start calling this instead of the one that we installed our custom handlers.
This PR will store the heap that we installed our custom handlers in and reuse it.

fix(profiling) store customized heap

---

dockerfiles/ci/buster/Dockerfile
dockerfiles/ci/buster/build-extensions.sh
dockerfiles/ci/buster/build-php.sh
dockerfiles/ci/xfail_tests/7.0.list
dockerfiles/ci/xfail_tests/7.1.list
dockerfiles/ci/xfail_tests/7.2.list
dockerfiles/ci/xfail_tests/7.3.list
dockerfiles/ci/xfail_tests/7.4.list

The buster images (7.0->8.2) were rebuilt to add the following extensions to the buster images for the Magento test frameworks to be installable:
- bcmath
- gd
- intl (PHP 7.1+)
- soap
- sodium
- xsl
(non-impactful) Redis 6.0.0 dropped support for PHP 7.1 and below, hence 5.3.7 is explicitly used for these anterior versions.

ci: Add some php extensions to the buster images

---

profiling/src/lib.rs
profiling/tests/phpt/trampolines_02.phpt

A customer reported a crash which lead to the discovery of this use-after-free. Note that this is limited to Closure trampolines, and only when the profiler is enabled. It has been a potential issue for some time, but seems to be more likely to cause a crash since #1998 was merged.

fix(profiling): use-after-free with Closure trampolines

---

Cargo.lock
Cargo.toml
appsec/CMakeLists.txt
components-rs/common.h
ext/version.h
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

Bump version to 0.92.0

---

.gitlab-ci.yml

This PR will fix the reliability environment deployment by making sure that if no `LATEST_LIBRARY_x86_64_LINUX_GNU` is passed to the job, it fetches the latest artifact from CircleCI and not from GitHub.
PROF-8281

ci: fix relenv deployment

---

zend_abstract_interface/config/config_ini.c
zend_abstract_interface/config/tests/ini.cc

It was reported that when using `php_value` on `php-fpm` configuration to set values to datadog inis shared between `ddtrace` and `ddappsec` , the values were not getting picked by `ddappsec`. It was getting defaults or values ono `.ini` files

Fix getting fpm php_values in appsec and profiler

---

ext/hook/uhook.c
ext/request_hooks.c
tests/ext/sandbox/die_in_sandbox.phpt
zend_abstract_interface/exceptions/exceptions.c

Just a small crash with DD_TRACE_DEBUG=1 active, including a safeguard in zai_exception_message.

Handle UnwindExit in sandbox error reporting

---

profiling/src/allocation.rs
profiling/tests/phpt/allocation_jit_01.phpt

When running PHP with `USE_ZEND_ALLOC=0` and allocation profiling being disabled, in `RSHUTDOWN` we were crashing. This is due to `is_zend_mm()` returning false in that case and we wrongly assumed this would also mean allocation profiling is installed.
Technical background: `USE_ZEND_ALLOC=0` installs the system allocator and sets the `AG(heap)->use_custom_heap` to 1 in https://heap.space/xref/PHP-8.2/Zend/zend_alloc.c?r=4553258d#2895-2918
The `ci/circleci: PHP 82 Xdebug tests` failing is due to the container already being upgraded to run xdebug 3.2.2 and not the 3.2.0RC1 anymore. The fix for this is in https://github.com/DataDog/dd-trace-php/pull/2098
PROF-8286

fix(profiling) allocation profiling shutdown with `USE_ZEND_ALLOC=0` crashing

---

zend_abstract_interface/config/config_ini.c
zend_abstract_interface/config/tests/ini.cc

When connecting .htaccess via php-fpm, apache will set true environment variables, a circumstance where the handling explicitly calling ZaiConfigOnUpdateIni was skipped, leading to non-updated configs.

Fix ZAI config handling for .htaccess with php-fpm

---

Makefile

Upgrade appsec which now includes the ZAI config fix for `.htaccess` in fpm (https://github.com/DataDog/dd-trace-php/pull/2298) and another small fix .

Upgrade appsec to v0.14.2

---

profiling/src/allocation.rs
profiling/tests/phpt/gc_mem_caches_02.phpt

In case there is another custom handler installed on the heap that we also hook into, we should not play with the `AG(heap)->use_custome_heap` flag anymore and we need to assume that the "other extension" takes care of this. This comes also into play when running PHP with `USE_ZEND_ALLOC=0` for ASAN which will point the allocation functions to the system allocator but also set the `use_custom_heap` flag.
PROF-8286

fix(profiling) neighboring extension handling in `gc_mem_caches()`

---

profiling/src/lib.rs
profiling/src/pcntl.rs
profiling/tests/phpt/gc_mem_caches_01.phpt

So this PR brings multiple things:
The `tests/phpt/gc_mem_caches_01.phpt` test should not run when `USE_ZEND_ALLOC=0` as the expectation would fail. We might be able to combine this and the `gc_mem_caches_02.phpt`, but I'd rather have both tests to make sure we have a version that explicitly tests the `USE_ZEND_ALLOC=0` case.
Implement a `reset()` function on the `RequestLocals` struct and call this after forking instead of setting values directly. This, and the fact that the `reset()` function resets not only `profiling_enabled` to `false` but all other profiling types as well solves a panic in `allocation_profiling_shutdown()` when PHP was run with `USE_ZEND_ALLOC=0`. What happened was that after forking we call the `allocation_profiling_shutdown()` function and reset the `HEAP` to …

fix(profiling) panic after shutdown of forked child when `USE_ZEND_ALLOC=0`

---

ext/compat_string.c
ext/compatibility.h
ext/serializer.c
tests/ext/sandbox/safe_to_string_metadata.phpt
tests/ext/sandbox/safe_to_string_metadata_drops_invalid_keys.phpt
tests/ext/sandbox/safe_to_string_properties.phpt

This will be required for the display of OpenTelemetry array attributes. Note that this also removes the parenthesis from boolean/null values in order to be consistent with other languages, i.e. system-tests.

Expand arrays and public properties of objects in meta into nested-tag format

---

config.m4
ext/ddtrace.c
ext/ddtrace.h
ext/ddtrace.stub.php
ext/ddtrace_arginfo.h
ext/handlers_exception.c
ext/hook/uhook.c
ext/hook/uhook_attributes.c
ext/hook/uhook_legacy.c
ext/priority_sampling/priority_sampling.c
ext/priority_sampling/priority_sampling.h
ext/random.c
ext/serializer.c
ext/span.c
ext/span.h
ext/tracer_tag_propagation/tracer_tag_propagation.c
tests/ext/active_span.phpt
tests/ext/sandbox/span_clone.phpt

This allows setting specific data on RootSpans.
Further, since properties are always at the end of the zend_object, if RootSpanData has properties, they would conflict with the trailing SpanData members. Hence, they need to be moved in front.
This is preparatory work for adding more properties to RootSpanData.

Subclass SpanData with RootSpanData

---

ext/ddtrace.c
tests/ext/integrations/curl/distributed_tracing_curl_drop_dm.phpt

Beforehand, the tracer would pass _dd.p.dm unfiltered, if it was propagated and sampling priorities not changed. I do think this is the more reasonable behaviour, but complying with system tests here.

Explicitly drop dd.p.dm if provided in propagated tags when the incoming sampling priority is reject

---

ext/ddtrace.c
ext/serializer.c
ext/tracer_tag_propagation/tracer_tag_propagation.c
ext/tracer_tag_propagation/tracer_tag_propagation.h

Also ensure consuming trace headers does apply to an existing root span instead of preset if one exists.
Passes the system-tests.

Strictly validate dd.p.tid

---

profiling/src/allocation.rs
profiling/src/exception.rs

While doing work on the overhead task, I found that we are spending quite some amount of work in actual sampling, and suddenly I saw that we are recreating the poisson distribution thread RNG every time we calc the next sample. Turns out, we do not have to and can just reuse the one already created. This does not bring a huge amount of performance, but every step counts 😉 
PROF-7418

feat(profiling) reuse poisson sampler and thread rng

---

Makefile

This appsec release fixes the sampling priority incompatibility introduced in https://github.com/DataDog/dd-trace-php/pull/2314, through the use of the new exported function `ddtrace_set_priority_sampling_on_root`.

Update appsec to v0.14.3

---

src/Integrations/Integrations/IntegrationsLoader.php

This seems like an oversight - it's only present on PHP 7+.

Fix PHP 5: The Drupal integration is not part of PHP 5

---

profiling/src/exception.rs
profiling/src/lib.rs
profiling/tests/phpt/exceptions_01.phpt

There were two problems in exception profiling that this PR fixes:
1. `checked_sub()` does not change the value, but return the new one, which we have only checked for `is_none()` and ignored the return value otherwise. We did not update the `self.next_sample` value, effectively walking the stack for every exception.
2. When moving the initialisation to the first `RINIT`, we moved to a too early position in `lib.rs` where `REQUEST_LOCALS` where not yet initialised, resulting in sampling distance always defaulting to `100`.
I also added a test to ensure this is not failing again in the future 😉 
PROF-6915

fix(profiling) exception sampling distance

---

.github/workflows/prof_correctness.yml
Cargo.lock
profiling/Cargo.toml
profiling/src/profiling/mod.rs
profiling/src/profiling/uploader.rs

This PR will upgrade our dependencies, but especially upgrade `libdatadog` from v4 to v5, as there are some neat improvements that will especially help with timeline.
I am currently working on a benchmark, this is a scenario where I am sending HTTP Requests for around ~30 seconds to an HTTP endpoint:
|     | v4 | v5 | baseline (no profiling) |
|----|----|---|---|
| Max RSS | 109.527 KB | 64.389 KB | 43.360 KB |
| Max RSS (before serialization) | 60.432 KB | 59.168 KB | - |
PROF-7418

feat(profiling) upgrade to `libdatadog` v5

---

.github/workflows/prof_correctness.yml

There was a typo in the `DD_PROFILING_EXPERIMENTAL_EXCEPTION_SAMPLING_DISTANCE`:
```diff
- SAMLPING
+ SAMPLING
```
Which was why the test was flaky

fix(profiling) flaky exception correctness test

---

ext/serializer.c
ext/tracer_tag_propagation/tracer_tag_propagation.c

Before https://github.com/php/php-src/commit/e14fbc84acef9a14283986d47433ed7de45b4033 (i.e. PHP 8.1) strings provided with a max length were always truncated at 500 chars.
Note: libdatadog submodule updated for commit https://github.com/DataDog/libdatadog/commit/c9a8afc839e23a49a8e9358949587027b64f676c.

Avoid %.*s in places where longer strings are used

---

ext/serializer.c
tests/ext/sandbox/safe_to_string_metrics.phpt

Complements #2302 by applying the nested-tag format on the `metrics` array as well (longs, doubles, or array of longs or doubles).

Expand arrays in metrics into nested-tag format

---

.circleci/continue_config.yml
appsec/CMakeLists.txt
appsec/cmake/Toolchain.aarch64.cmake
appsec/cmake/Toolchain.x86_64.cmake

This PR introduces a new job to build the appsec helper using the libddwaf cross-compilation toolchain (although no cross-compilation is being done here)

Appsec helper build

---

.circleci/continue_config.yml
appsec/CMakeLists.txt
appsec/cmake/Toolchain.aarch64.cmake
appsec/cmake/Toolchain.x86_64.cmake
appsec/cmake/extension.cmake
appsec/cmake/helper.cmake

This is a first step towards building / testing appsec within this repository. This PR  introduces:
- Extension build for all PHP versions, nts and zts for both aarch64 and x86_64, gnu and musl. 
- Helper build on aarch64 and x86_64, statically linked musl & libc++ using the libddwaf toolchain.
Note that helper builds could be massively simplified, however since the helper logic will eventually be migrated to the sidecar, this might not be worth the effort at this stage.
The next steps (in a future PR):
- Build package using the outcome of the new build jobs.
- Extension tests
- Integration tests
Related Jira: [APPSEC-11707] [APPSEC-11708]
[APPSEC-11707]: https://datadoghq.atlassian.net/browse/APPSEC-11707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

Build AppSec extension & helper in CI

---

ext/compatibility.h
ext/hook/uhook.c
src/Integrations/Integrations/PDO/PDOIntegration.php
tests/ext/sandbox/install_hook/replace_hook_args_internal.phpt
zend_abstract_interface/hook/hook.c
zend_abstract_interface/symbols/call.c

This fixes:
- overrideArguments usage when changing a by-ref parameter
- overrideArguments usage when optional arguments to internal functions are being set
- properly handles freeing of garbage in overrideArguments for internal functions on PHP 8 when more arguments are provided than initially set.

Handle extra arguments for internal overrideArgs

---

profiling/src/allocation.rs
profiling/tests/correctness/allocations.json
profiling/tests/correctness/allocations.php

This causes fewer stack walks due to allocation profiling.
A customer recently complained about performance overhead, and in their case, the allocation profile was more than twice as expensive as the wall-time/cpu-time profiles.
I did some testing with the symfony-demo application as well, and also came up with ~2x cost. So... doubling this number brings allocation profiling costs roughly in line with wall-time/cpu-time, at least for a few recent tests (overhead can vary substantially based on the test).
Part of PROF-8596.

perf(profiling): increase allocation sampling distance

---

.circleci/config.yml

Enable appsec unit tests when dependencies change, for now only `zend_abstract_interface` and the tracer extension.

Test appsec on dependency change

---

profiling/tests/correctness/allocations.json

This fixes the absolute numbers in bytes allocated in the prof-correctness runs.
Part of [PROF-8596](https://datadoghq.atlassian.net/browse/PROF-8596).
[PROF-8596]: https://datadoghq.atlassian.net/browse/PROF-8596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(profiling) absolute numbers for allocation correctness 

---

appsec/tests/extension/client_init_record_span_tags.phpt
appsec/tests/extension/ddtrace_basic.phpt
appsec/tests/extension/rinit_record_span_tags.phpt
appsec/tests/extension/rinit_record_span_tags_fail.phpt
appsec/tests/extension/rinit_root_span_add_tag.phpt
appsec/tests/extension/root_span_add_tag.phpt
appsec/tests/extension/root_span_add_tag_with_intermediate_spans.phpt

These tests started failing since 128-bit is now enabled by default. Adds the missing `_dd.p.tid`.
- [] (only for Members) Changelog has been added to the release document.

Update appsec tests (128-bit)

---

Makefile
src/Integrations/Integrations/CakePHP/CakePHPIntegration.php
tests/Frameworks/CakePHP/Version_2_8/app/Config/routes.php
tests/Frameworks/CakePHP/Version_2_8/app/Controller/ParameterizedController.php
tests/Frameworks/TestScenarios.php
tests/Frameworks/Util/CommonScenariosDataProviderTrait.php
tests/Integrations/CakePHP/V2_8/CommonScenariosTest.php

Add `http.route` tag to CakePHP root spans

CakePHP http.route implementation

---

ext/distributed_tracing_headers.c
ext/distributed_tracing_headers.h
tests/Integrations/Curl/CurlIntegrationTest.php

And respect order of configurations.

Retain tracestate from tracecontext if extracted at all

---

ext/configuration.h
ext/integrations/integrations.h
tests/Integrations/Custom/Autoloaded/InstrumentationTest.php
tests/Integrations/Logs/BaseLogsTest.php
tests/Integrations/Logs/LaminasLogV2/LaminasLogV2Test.php
tests/ext/logging_default_value.phpt
tests/ext/telemetry/integration.phpt

Disables the LogsIntegration by default (`DD_TRACE_LOGS_ENABLED` & `DD_LOGS_INJECTION`)

Respect `DD_LOGS_INJECTION` default value

---

profiling/src/lib.rs
profiling/src/profiling/mod.rs
profiling/src/timeline.rs
profiling/tests/correctness/timeline.json

This PR will add idle phases between requests and idle phases due to the `sleep()`-class functions to the timeline view.
In detail this covers:
- idle phase between RSHUTDOWN and RINIT (PHP process not handling a request)
- and PHP process sleeping due to a sleep-class function call, namely
- `sleep()`
- `usleep()`
- `time_nanosleep()`
- and `time_sleep_until()`
Also includes one unrelated change: Moves the call to `exception::exception_profiling_mshutdown();` a few lines up, so that it happens before the config and the profiler is shutdown.
This PR superseeds #2315 and will only contain idle phases as in sleeping or waiting to handle a new request in synchronous PHP (as used in PHP-FPM or Apache mod_php). Everything else (like event loop idle phases) shall go to another PR.
PROF-8370

feat(profiling): add idle phases to timeline

---

ext/hook/uhook.c
ext/hook/uhook.stub.php
ext/hook/uhook_arginfo.h
src/Integrations/Integrations/Logs/LogsIntegration.php
tests/ext/sandbox/install_hook/exclude_inherited_hook.phpt
zend_abstract_interface/hook/hook.c
zend_abstract_interface/hook/hook.h

This is implemented by adding the ability to remove a hook from selected classes directly.

Completely avoid instrumenting the PSR NullLogger

---

ext/compatibility.h
ext/ddtrace.c
ext/ddtrace.h
ext/ddtrace.stub.php
ext/ddtrace_arginfo.h
ext/handlers_curl.c
ext/handlers_curl_php7.c
ext/hook/uhook.c
ext/integrations/integrations.c
src/Integrations/Integrations/Curl/CurlIntegration.php
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
tests/internal-api-stress-test.php
zend_abstract_interface/exceptions/exceptions.c
zend_abstract_interface/exceptions/exceptions.h

Fixes the long-standing issue #1156.
This works by creating a parent curl_multi_exec() span, and then creating a span for every single attached request.
When the second arg of curl_multi_request() (i.e. `$still_running`) returns 0, we assume everything is finished and we add data to the request spans.
Doing this needs some support from internal code (`DDTrace\curl_multi_exec_get_request_spans()`) to grab all the CurlHandle instances as well as an associated span started at the right time.
I think it's not fool-proof (it shouldn't throw or crash ever though, just possibly show too short spans / missing some info), but it should work with common patterns of curl_multi usage.
It should provide the insight of tracking individual requests, however it's not possible (currently) to get a proper …

Add tracing for curl_multi_exec()

---

zend_abstract_interface/hook/hook.c

Doing the due diligence whether I can reuse nNumOfElements in the HashTable, to increase and decrease it, so that all checks for zend_hash_num_elements() == 0  only are true when neither internal duplicates exist, nor actual hooks exist, I missed the tiny detail, that, while all direct usages of nNumOfElements were safe, there was an usage of nNumOfElements in the HT_IS_WITHOUT_HOLES() macro, checking whether nNumOfElements == nNumUsed.
Thus, when there were two hooks, one later removed, and one class inheriting the internal method, nNumOfElements happened to be equal to nNumUsed in shutdown. During hash destruction the smart Zend code would check this and unconditionally iterate over all elements of the array, skipping IS_UNDEF checks.
Eventually leading to a double free.
As a saving …

Fix possible double-free with hooks on internal methods inherited by user classes

---

appsec/cmake/helper.cmake
appsec/src/helper/client.cpp
appsec/src/helper/engine.cpp
appsec/src/helper/std_logging.hpp
appsec/src/helper/subscriber/waf.cpp
appsec/tests/helper/client_test.cpp
appsec/tests/helper/waf_test.cpp
appsec/third_party/CMakeLists.txt

- `TEST(WafTest, Logging)` had to be removed due to build-time conflicts between `spdlog/fmt` and `libddwaf/fmt`.
Related Jira: [APPSEC-12103]
[APPSEC-12103]: https://datadoghq.atlassian.net/browse/APPSEC-12103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ASM] Upgrade libddwaf to v1.15.1

---

dockerfiles/verify_packages/installer/test_install_on_plesk.sh

Change PHP version used on installer verification tests on plesk, as PHP 8.0 seems to have been removed from the image:
```
Status: Downloaded newer image for plesk/plesk:18.0
dockerfiles/verify_packages/installer/test_install_on_plesk.sh: 12: /opt/plesk/php/8.0/bin/php: not found
```

Fix installer verification on plesk

---

dockerfiles/ci/alpine_compile_extension/docker-compose.yml
dockerfiles/ci/buster/build-extensions.sh
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/centos/7/docker-compose.yml
dockerfiles/ci/xfail_tests/8.3.list
dockerfiles/ci/xfail_tests/README.md
tests/Integrations/MongoDB/MongoDBTest.php
tests/ext/force_flush_traces.phpt

This PR updates CI images:
- PHP 8.3.0rc3 upgraded to PHP 8.3.0rc6.
- mongodb is pinned to 1.16.2 for PHP 7.2-7.3 as 1.17.0 was released last week and dropped support for these versions.
This is a prerequisite for PROF-8286.

Update CI images to use PHP 8.3.0rc6, pin mongodb for PHP 7.2-7.3

---

datadog-setup.php

It really means that the build is not available on the version, build type tuple, not generally for that build type.
Has been on my todo for a while :-)

Fix #2312: More precise installer error message

---

.circleci/config.yml
.circleci/continue_config.yml

Enable appsec extension unit tests on PHP 8.0 with debug-zts-asan, this test was failing but was recently fixed in https://github.com/DataDog/dd-trace-php/pull/2383 and https://github.com/DataDog/dd-trace-php/pull/2353

Enable appsec tests on PHP 8.0 with debug-zts-asan 

---

tests/ext/priority_sampling/invalid-json-rule.phpt
zend_abstract_interface/json/json.c

The json parse is going to helpfully call zval_ptr_dtor_nogc, which eventually calls zend_array_destroy upon encountering a json parse error.
zend_array_destroy really dislikes persistent arrays. Cheat it by creating a RC=2 array and allow insertion into these (CoW violation bypass).
Effectively fixes invalid. sampling rules.

Fix handling of invalid persistent JSON

---

src/Integrations/Integrations/Curl/CurlIntegration.php

Fixes #2390.
The artifact was tested and appears to have solved the corresponding issue.

Use http_code instead of connect_time to detect curl errors

---

.github/workflows/prof_correctness.yml
profiling/src/timeline.rs

A customer contacted us that with upgrading to `0.94.0` they see profiles being send to Datadog, although the profiler is disabled for them and therefore should not send profiles.
The bug is that the new idle phases added in https://github.com/DataDog/dd-trace-php/pull/2343 where not checking if the timeline is enabled.
This PR will add this missing check, as well as a test to ensure that in all prof-correctness cases the profiler does not emit pprof files when profiling is disabled.
[SCP-378](https://datadoghq.atlassian.net/browse/SCP-378)
[SCP-378]: https://datadoghq.atlassian.net/browse/SCP-378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(profiler) do not emit profiles when profiler is disabled

---

.github/PULL_REQUEST_TEMPLATE.md
.github/labeller.yml
.github/workflows/auto_add_pr_to_miletone.yml
.gitignore
github-actions-helpers/Build.Github.cs
github-actions-helpers/Build.cs

All PRs merged to master will be in the next minor release. Adding to the milestone can be done automatically.
The action does nothing if there's already a milestone on the PR.
We will use in a next PR, the milestone content to generate the release notes
Additionally, fixes a missing gitignore and some regexes for the labeller

[Automation] Adds automatically merged PRs to next milestone

---

.github/workflows/auto_add_pr_to_miletone.yml

Fixes the path used by the action. This was harder to test as it's an action trigger on merge only.
The Nuke target action had been tested locally though

[Automation] Fix script path in the milestone action

---

.circleci/continue_config.yml
dockerfiles/ci/xfail_tests/8.1.list
dockerfiles/ci/xfail_tests/8.2.list

This will fix the failing xdebug tests with the new containers and also add
- `sapi/cli/tests/bug80092.phpt` and
- `Zend/tests/gh12073.phpt`
to the xfail list.  `bug80092.phpt` is already blacklisted for PHP 8.3 and might be unlisted with 8.3.1. `gh12073` sets the memory limit to 2MB which is not possible anymore when the `dd_wrap_autoloader.php' is included.
`gh12073` fails with:
```
========DIFF========
001+ Warning: Failed to set memory limit to 2097152 bytes (Current memory usage is 8388608 bytes) in /usr/local/src/php/Zend/tests/gh12073.php on line 10
001- Fatal error: Allowed memory size of %d bytes exhausted%s(tried to allocate %d bytes) in %s on line %d
```

fix(ci) fix xdebug

---

Cargo.lock
profiling/Cargo.toml
profiling/src/allocation.rs
profiling/src/exception.rs
profiling/src/profiling/uploader.rs

Alongside the pprof file we can upload an `event.json` which this PR will add and deliver the absolute numbers for:
- allocations count
- allocations len
- exceptions count
To see them you'd need to enable the `profiling_custom_data_display` feature flag, so this would most likely help us in debugging.

feat(profiling) add allocation and exception count to `event.json`

---

ext/handlers_http.h
ext/tracer_tag_propagation/tracer_tag_propagation.c
tests/OpenTelemetry/Integration/API/TracerTest.php
tests/OpenTelemetry/Integration/InteroperabilityTest.php
tests/OpenTelemetry/Integration/SDK/TracerTest.php
tests/ext/distributed_tracestate_consumption.phpt
tests/ext/integrations/curl/distributed_tracing_curl_drop_dm.phpt
tests/ext/integrations/curl/distributed_tracing_curl_invalid_tags.phpt
tests/ext/integrations/curl/distributed_tracing_curl_tracestate.phpt

As per our specification, otherwise other tracers may complain about a malformed tid.

Zero pad the tid and exclude it from OTel tracestate

---

src/Integrations/Integrations/CodeIgniter/V2/CodeIgniterIntegration.php
tests/Frameworks/CodeIgniter/Version_2_2/application/config/routes.php
tests/Frameworks/CodeIgniter/Version_2_2/application/controllers/parameterized.php
tests/Integrations/CodeIgniter/V2_2/CommonScenariosTest.php
tests/Integrations/CodeIgniter/V2_2/ExitTest.php
tests/Integrations/CodeIgniter/V2_2/NoCI_ControllertTest.php

Add `http.route` tag to CodeIgniter spans

Add http.route to CodeIgniter

---

dockerfiles/verify_packages/alpine/install.sh

A [new Alpine image](https://hub.docker.com/_/alpine/tags) was released four days ago, which uses PHP 8.2 instead of 8.1, which would make the verify alpine:latest tests fail on the CI.

CI: Handle latest Alpine 3.19 image

---

src/Integrations/Integrations/WordPress/V2/WordPressIntegrationLoader.php
tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_callbacks_test.test_scenario_get_return_string.json
tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_callbacks_test.test_scenario_get_with_exception.json
tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_callbacks_test.test_scenario_get_with_view.json
tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_test.test_scenario_get_return_string.json
tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_test.test_scenario_get_with_exception.json
tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_test.test_scenario_get_with_view.json
tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_callbacks_test.test_scenario_get_return_string.json
tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_callbacks_test.test_scenario_get_to_missing_route.json
tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_callbacks_test.test_scenario_get_with_exception.json
tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_callbacks_test.test_scenario_get_with_view.json
tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_test.test_scenario_get_return_string.json
tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_test.test_scenario_get_to_missing_route.json
tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_test.test_scenario_get_with_exception.json
tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_test.test_scenario_get_with_view.json
tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_callbacks_test.test_scenario_get_return_string.json
tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_callbacks_test.test_scenario_get_to_missing_route.json
tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_callbacks_test.test_scenario_get_with_exception.json
tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_callbacks_test.test_scenario_get_with_view.json
tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_test.test_scenario_get_return_string.json
tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_test.test_scenario_get_to_missing_route.json
tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_test.test_scenario_get_with_exception.json
tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_test.test_scenario_get_with_view.json
tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_callbacks_test.test_scenario_get_return_string.json
tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_callbacks_test.test_scenario_get_with_exception.json
tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_callbacks_test.test_scenario_get_with_view.json
tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_test.test_scenario_get_return_string.json
tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_test.test_scenario_get_with_exception.json
tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_test.test_scenario_get_with_view.json

Fixes #2423 
See the issue for a comprehensive description of the issue.
> If a user is not authenticated, usr.id should not be set
Currently, If a user is not authenticated, the user ID would be set to 0, hence conflicting with ASM.

[WordPress] Avoid Setting User ID When Unauthenticated

---

.github/workflows/prof_correctness.yml
profiling/src/config.rs
profiling/src/lib.rs
profiling/src/profiling/mod.rs
profiling/tests/phpt/phpinfo_06.phpt
profiling/tests/phpt/phpinfo_07.phpt

This will add the `datadog.profiling.experimental_features_enabled` INI setting (and corresponding ENV var `DD_PROFILING_EXPERIMENTAL_FEATURES_ENABLED`) which allows to enable all experimental features in the profiler with this one setting.
This will overrule all INI/ENV settings that configure experimental features.
[PROF-8393](https://datadoghq.atlassian.net/browse/PROF-8393)
[PROF-8393]: https://datadoghq.atlassian.net/browse/PROF-8393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(profiling): allow to enable all experimental features

---

.github/workflows/prof_correctness.yml

This PR adds a nightly run for the prof-correctness job. The goal is to run the nightly jobs for `master` in the `dd-trace-php` repo and not in the `prof-correctness` repo to not need to keep the tests and expectations in sync.
PROF-8786

ci(profiling): run prof-correctness nightly

---

ext/serializer.c
tests/OpenTelemetry/Integration/API/TracerTest.php

A system-test testing the behavior of `analytics.event` tag override was added with Datadog/system-tests#1818. The current implementation would fail :)
This PR simply explicitly checks for 'true' (not case sensitive) to return `1.0`, and _anything else_ would yield `0.0`
I set it as  `do-not-merge` as I need the pipeline to finish to test it properly, but the local tests otherwise pass.

Fix analytics.event override

---

Cargo.lock
appsec/CMakeLists.txt
ext/version.h
github-actions-helpers/Build.cs
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

This bumps versions and updates the `package.xml` in preparation for the `0.96.0` release

Bump versions for `0.96.0` release

---

appsec/src/helper/compression.cpp

This change fixed the encoding used on schema extraction and therefore will fix the sytem tests checks
APPSEC-18493

Change schema extraction zip compression to PHP_ZLIB_ENCODING_GZIP

---

.gitattributes

Update `.gitattributes` file to reduce the number of files and folder that are packaged when using composer.
Fixes #2181

Reduce noise in composer package download

---

tests/ext/sandbox/install_hook/exclude_inherited_hook_after_binding.phpt
tests/ext/sandbox/install_hook/remove_hook_null_logger.phpt
zend_abstract_interface/hook/hook.c

Taking the tests from #2422, but actually remove the hooks inside DDTrace\remove_hook instead.
And for some reason I was left-shifting ce_addresses, causing more collisions, instead of less. Fixed to right-shift.

Fix removal of the directly accessed hook after binding in DDTrace\remove_hook

---

tests/ext/traced_attribute.phpt
tests/ext/traced_attribute_delayed.phpt
zend_abstract_interface/interceptor/php8/resolver_pre-8_2.c

This only may pose problems with DDTrace\Trace attributes. In theory having the hook installed twice should not pose problems, but adding a hook to an unresolved class is at the very least not a supported scenario. Checking for the classes being actually linked.
This only affects PHP 8.0 and PHP 8.1 (classes only).

Avoid resolving unresolved functions and classes

---

src/Integrations/Integrations/Exec/ExecIntegration.php

Stumbled onto this error while running the microbenchmarks with the debug logs.
```
Error thrown in ddtrace's closure defined at /app/candidate/src/Integrations/Integrations/Exec/ExecIntegration.php:197 for proc_close(): Typed property DDTrace\HookData::$data must not be accessed before initialization
```

fix: Uninitialized access in ExecIntegration

---

.gitlab/benchmarks.yml

Run the macrobenchmarks without the sidecar on PHP 8.
[Sample Results](https://ddstaging.datadoghq.com/dashboard/ipf-dbi-7ub?refresh_mode=paused&tpl_var_bp_branch%5B0%5D=alex%2Fbench%2Fno-sidecar&tpl_var_bp_commit_sha%5B0%5D=1d5c31af&tpl_var_ci_pipeline_id%5B0%5D=26212920&view=spans&from_ts=1704890404619&to_ts=1704891211000&live=false)
Works hand-in-hand with this [commit](https://github.com/DataDog/benchmarking-platform/commit/3626ef5f2fe67ea8c33d8caeac352be643f89a53) made to the benchmarking platform.

feat: Add `no-sidecar` benchmark configuration

---

.gitlab/benchmarks.yml
tests/Benchmarks/API/ContextPropagationBench.php
tests/Benchmarks/Integrations/PDOBench.php
tests/Benchmarks/Integrations/PHPRedisBench.php

Three benchmarks appear to be flaky:
```
PHPRedisBench/benchRedisBaseline
ContextPropagationBench/benchExtractHeaders128Bit
PHPRedisBench/benchRedisOverhead
```
Following @ddyurchenko's recommendations, increase the iteration count of these subjects to 15.

Increase iterations of flaky benchmarks

---

.github/workflows/prof_correctness.yml
profiling/src/lib.rs
profiling/src/php_ffi.c
profiling/src/php_ffi.h
profiling/src/sapi.rs

**Note:** This does not make the profiler ZTS compatible, it only ensures that it is compiling against a ZTS version of PHP
This PR will additionally add ZTS PHP version to the `prof_correctness` tests. Even though this seems awesome, please note that this test currently only runs one thread, so it is expected to not fail 😉 
PROF-8904

feat(profiler) make the profiler compile in ZTS PHP

---

ext/handlers_fiber.c

Missing indirection. Sadly PHP < 8.1.3, hence no tests.
Fixes #2471.

Fix fibers on PHP 8.1.2

---

tests/Benchmarks/API/ContextPropagationBench.php

These benchmarks are flaky, particularly because of their short execution time, which is too short for `microtime`'s precision. Increasing revolutions may address this issue.

Increase revolutions of context propagation benchmarks

---

profiling/src/profiling/mod.rs

This will make sure that empty profiles that we might send to the `ddprof_time` thread will be ignored. This should not happen anyway, but it happened in the past.
PROF-8749

fix(profiler) prevent emitting empty profiles

---

ext/engine_hooks.c
profiling/src/capi.rs
profiling/src/lib.rs
profiling/src/wall_time.rs

PROF-8912
Does two things:
1. Extracts bits from `lib.rs` and `capi.rs` and puts them in a new `wall_time.rs` file.
2. Uses `ddog_php_prof_` instead of `datadog_profiling_` for functions in `wall_time.rs`.  This function is used by the tracer so it updates `ext/engine_hooks.c` too.

refactor(profiling): extract wall_time.rs file

---

tests/ext/sandbox/install_hook/remove_executing_hook.phpt
zend_abstract_interface/hook/hook.c
zend_abstract_interface/hook/hook.h
zend_abstract_interface/interceptor/php8/interceptor.c

Fixes https://bugs.xdebug.org/view.php?id=2232.
We need to keep track of the observer which we just replaced if we removed it in an end observer, and call it manually.
The underlying reason is that call_end_observers() in php-src merely iterates through the pointers. When removing an observer, all trailing observers will be memmove()d by one slot back, so that handler is the next observer and handler+1 in call_end_observers is now the observer after, leading to the next observer being skipped.

Fix removing an end observer with other observers active

---

ext/ddtrace.c

Fixes possible crashes on old versions by ensuring that attribute constructor dummy functions are always on the VM stack.
(essentially works around https://bugs.php.net/bug.php?id=81430, which happens to crash more often for users now, given that Symfony started using PHP attributes.)

Move the dummy function of call_attribute_constructor onto the VM stack

---

.circleci/config.yml
tests/tea/profiling/profiling.cc
tests/tea/profiling/profiling.h

Fixes the failing zai test in `master` that came after merging #2467. Also enabled running the zai tests on profiler changes so that we do not fall for this again.

fix(profiler) zai tests

---

profiling/src/timeline.rs

Fixes a clippy lint in the timeline feature of the profiler.

style(profiling): fix clippy::single-match

---

datadog-setup.php
profiling/src/config.rs
profiling/src/lib.rs
profiling/src/profiling/mod.rs
profiling/src/timeline.rs
profiling/tests/phpt/phpinfo_06.phpt
profiling/tests/phpt/phpinfo_07.phpt

This PR will default enable timeline for the PHP profiler

feat(profiling): enable timeline by default

---

.gitlab/benchmarks.yml

Reduce flakiness of macrobenchmark.
Improves spread of p50 latency from 9.7ms to 0.02ms (by ~40x).
Downside is that all variants are run now sequentially on the same machine (which currently takes still under 30 minutes).
If we need to scale horizontally to reduce execution time, there should be done more investigation into flakiness on reruns (in particular, I would use same seed for [random data generation](https://github.com/PROFeNoM/laravel-realworld-example-app/blob/main/database/seeders/DummyDataSeeder.php#L29-L81) that happens on benchmark reruns, but totally possible that something more might be done there).

Reduce macrobenchmark flakiness

---

.gitlab/benchmarks.yml

Run macrobenchmarks nightly (master). 
More specifically, the PR introduces a `NIGHTLY_BENCHMARKS` to specifically allow the benchmarks to be run with the added corresponding [scheduled pipeline](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-php/-/pipeline_schedules).

ci: Run Macrobenchmarks nightly

---

.github/workflows/prof_correctness.yml

With https://github.com/DataDog/prof-correctness/pull/21 the `prof-correctness` tests in this repo started failing, as the regex looking for `pprof` files does not match anymore. Luckily the referenced PR also brings lz4 support to prof-correctness, so we can just remove the `lz4 -d` step and let `prof-correctness` read directly from that lz4 file 🎉

ci(profiling) prof correctness supports lz4 now

---

appsec/src/extension/logging.c
appsec/src/extension/request_abort.c

Ensure logs are committed to disk upon shutdown

---

.circleci/continue_config.yml
.github/workflows/prof_asan.yml
profiling/src/allocation.rs
profiling/src/bindings/mod.rs
profiling/src/capi.rs
profiling/src/config.rs
profiling/src/exception.rs
profiling/src/lib.rs
profiling/src/pcntl.rs
profiling/src/php_ffi.c
profiling/src/profiling/mod.rs
profiling/src/profiling/uploader.rs
profiling/src/timeline.rs
profiling/src/wall_time.rs
profiling/tests/phpt/jit_01.phpt
profiling/tests/phpt/phpinfo_01.phpt
profiling/tests/phpt/phpinfo_ini_01.phpt

PROF-8912
The recently introduced `SystemSettings` had its data duplicated in `RequestLocals` because there were multiple ways to handle that issue. This PR is one way to resolve this.
There's now one `SystemSettings` in memory, and it's defined in `src/config.rs`. The `RequestLocals` and `Profiler` objects hold a non-null pointer to it. The system settings are fetched from the zai config's memoized entries, rather than the thread-locals, and this is done on first rinit. These changes caused a fair bit of churn in the codebase.
There are a few side effects as well:
- The agent endpoint is no longer part of the profile index key, since that's part of system configuration. Less things to hash and compare, so this is a tiny perf reduction on each sample collected.
- The allocation profiler …

refactor(profiling): use SystemSettings in locals

---

src/Integrations/Integrations/Symfony/SymfonyIntegration.php

Fixes #2427
This PR should have been included with #2436
TL;DR of the issue:
```
Could not add hook to MyCommand::run with more than datadog.trace.hook_limit = 100 installed hooks in /opt/datadog-php/dd-trace-sources/bridge/_generated_integrations.php on line 4014; This message is only displayed once. Specify DD_TRACE_ONCE_LOGS=0 to show all messages.
```
The current implementation of the command hooks adds a hook to a `<scope>::run` if it wasn't already added. This could, theoretically, lead to multiple hooks added when considering numerous inheritors.
About the fix: Considering that in the previous version the hook was made on `Symfony\Component\Console\Command\Command::__construct`, it means that `$scope` fundamentally represents a `Symfony\Component\Console\Command\Command` instance. …

Remove Symfony Command Hook After Execution

---

appsec/src/extension/commands/request_exec.c
appsec/src/extension/commands/request_init.c
appsec/src/extension/commands/request_shutdown.c
appsec/src/extension/commands_ctx.h
appsec/src/extension/commands_helpers.c
appsec/src/extension/commands_helpers.h
appsec/src/extension/php_compat.h
appsec/src/extension/request_abort.c
appsec/tests/integration/src/docker/apache2-fpm/entrypoint.sh
appsec/tests/integration/src/docker/apache2-mod/entrypoint.sh
appsec/tests/integration/src/docker/nginx-fpm/entrypoint.sh
appsec/tests/integration/src/test/www/roadrunner/run.sh

Fix blocking on PHP 7.0-7.1 ZTS

---

src/Integrations/Integrations/Curl/CurlIntegration.php
tests/snapshots/tests.integrations.guzzle.v6.guzzle_integration_test.test_multi_exec.json
tests/snapshots/tests.integrations.guzzle.v7.guzzle_integration_test.test_multi_exec.json

Gives the same experience for any curl_exec operation independently of whether it's behind curl_multi_exec or not.
Fixes #2504.

Include generated curl_exec spans of curl_multi_exec() in metrics

---

ext/ddtrace.c

Avoids propagation of OOM errors to the cleanup phase causing the next request to fail.
No tests as reproducing OOMs is quite finnicky, with different versions and continuous development of the tracer.

Add zend_try around closing and flushing spans

---

ext/configuration.h
tests/ext/integrations/curl/distributed_tracing_curl_drop_dm.phpt

W3C Phase 2: Convert default propagation headers from tracecontext,datadog to datadog,tracecontext

propagation: convert default style to datadog,tracecontext

---

appsec/src/extension/configuration.c
ext/configuration.c
profiling/src/lib.rs
zend_abstract_interface/config/config.c
zend_abstract_interface/config/config.h
zend_abstract_interface/config/tests/ext_zai_config.cc
zend_abstract_interface/config/tests/ini.cc
zend_abstract_interface/json/json.c

Multiple threads manipulating the refcount at once is a possible source of race conditions (especially with many small requests increasing the likeness).
Properly mark the strings as interned / arrays as immutable to avoid this.

Mark config as immutable and interned to avoid refcounting race conditions

---

profiling/tests/phpt/exceptions_01.phpt
profiling/tests/phpt/gc_collect_cycles_01.phpt

Two tests have been skipped due to an "Experimental" check for features that are not experimental anymore.

test(profiling): fix accidentally skipped tests

---

profiling/build.rs
profiling/src/config.rs
profiling/src/exception.rs
profiling/src/php_ffi.c
profiling/src/php_ffi.h
profiling/src/profiling/mod.rs
zend_abstract_interface/symbols/lookup.c

This will add the exception message to the sample that is taken. You'd need to opt-in to the collection of exception messages by setting the environment variable `DD_PROFILING_EXCEPTION_MESSAGE_ENABLED` or the INI setting `datadog.profiling.exception_message_enabled` to `true`/`1`/`on`.
Additionally I moved reading the exception class name (and the message) to after the sampling decision which lowers the overhead of exception profiling.
PROF-8838

feat(profiler) add exception message to exception sample

---

ext/ddshared.c
ext/priority_sampling/priority_sampling.c
tests/ext/priority_sampling/021-rule-name-as-glob-with-question-mark.phpt

Also making glob patterns case insensitive.

Evaluate numbers and bools in tags and metrics for sampling rules

---

src/Integrations/Integrations/Integration.php
src/Integrations/Integrations/PDO/PDOIntegration.php
tests/Integrations/PDO/PDOTest.php

Split by should take priority in PDO integration over service name flattening
Fixes #2519.

Make PDO split-by coherent with other DB split-by with service name flattening

---

Cargo.lock
appsec/CMakeLists.txt
ext/version.h
github-actions-helpers/Build.cs
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

The one point zero will come soon :-)

Bump version to 0.98.0

---

ext/logging.c

We should probably ensure the sidecar doesn't fail spawning if the permissions of the log file don't match.

Ensure the permissions of the log file are actually really 0666

---

tests/ext/background-sender/default_unix_domain_socket_agent.phpt

This test is just too flaky. Retries don't seem effective, and the issue still persists. This issue may arise because of a connection issue with the request replayer. 
It is okay for us to mark this test as XFAIL, considering that we know it will sometimes fail for **external** reasons, and we seemingly have no actionable steps to take when this test is failing.
This time, it succeeded eight times in a row... This time will be the right one.

Skip the flaky unix socket test on CI environments

---

tests/Benchmarks/API/ContextPropagationBench.php
tests/Benchmarks/API/HookBench.php
tests/Benchmarks/API/MessagePackSerializationBench.php
tests/Benchmarks/API/SamplingRuleMatchingBench.php
tests/Benchmarks/API/SpanBench.php
tests/Benchmarks/API/TraceAnnotationsBench.php
tests/Benchmarks/API/TraceSerializationBench.php
tests/Benchmarks/Integrations/EmptyFileBench.php
tests/Benchmarks/Integrations/LaravelBench.php
tests/Benchmarks/Integrations/LogsInjectionBench.php
tests/Benchmarks/Integrations/PDOBench.php
tests/Benchmarks/Integrations/SymfonyBench.php
tests/Benchmarks/Integrations/WordPressBench.php

Native profiles when:
- [Running benchSymfonyOverhead (i.e., with tracer) and opcache](https://app.datadoghq.eu/profiling/search?query=service%3Abenchsymfonyoverhead-opcache-1708611588%20&fromUser=true&op_filter=function%3A%22opcache_compile_file%20%28ZendAccelerator.c%29%22&viz=flame_graph&start=1708608216377&end=1708611816377&paused=true). We can indeed see some opcache_compile_file calls
- [Running benchSymfonyOverhead (i.e., with tracer) without opcache](https://app.datadoghq.eu/profiling/search?query=service%3Abenchsymfonyoverhead-base-1708611812%20&fromUser=false&op_filter=opcache&viz=flame_graph&start=1708608473149&end=1708612073149&paused=false). We cannot see any opcache_compile_file calls
These profiles assess that opcache is indeed used in web requests. What's more, the warmups …

benchmarks: Use 1 Warmup Interation and ensure opcache is used

---

tests/Common/WebFrameworkTestCase.php
tests/phpbench-opcache.json

I somehow messed up something while rebasing/force-pushing in #2531... This PR adds the "and ensure opcache is used" part.

fix(benchmarks): Ensure OPCache is used in cgi-fcgi web servers

---

ext/compatibility.h
ext/ddtrace.c
ext/ddtrace.h

Simple bugfix, found with frankenphp zts.

Make ddtrace_disable a true global to avoid crashes in ZTS with unsupported SAPI/extensions

---

ext/configuration.h
tests/ext/priority_sampling/005-rule-name.phpt
tests/ext/priority_sampling/007-rule-service.phpt
tests/ext/priority_sampling/009-rule-name-service.phpt
tests/ext/priority_sampling/014-rule-resource.phpt
tests/ext/priority_sampling/021-rule-name-as-glob-with-question-mark.phpt
tests/ext/priority_sampling/022-rule-name-as-glob-with-multiple-criterias.phpt
tests/ext/priority_sampling/invalid-regex-rule.phpt

Change DD_TRACE_SAMPLING_RULES_FORMAT default from regex to glob.

Change DD_TRACE_SAMPLING_RULES_FORMAT default from regex to glob

---

ext/auto_flush.c
ext/serializer.c

Fix faulty logic reusing a freed shm handle when sending fails.
Not sure how to test that as the precondition never should fail ... in theory.

Avoid remapping freed memory in trace sender fallback

---

.circleci/continue_config.yml
ext/ddtrace.c
tests/ext/sandbox/deferred_load_attempt_loading_once.phpt
tests/ext/sandbox/deferred_load_using_function.phpt
tests/ext/telemetry/integration.phpt
zend_abstract_interface/hook/hook.c

Fixes #2547.
Null-checks can be sometimes important.

Fix possible crash in dd_patched_zend_call_known_function

---

Cargo.lock
tests/Integrations/Custom/Autoloaded/InstrumentationTest.php
tests/ext/telemetry/integration.phpt

Should bring a considerable speedup by not using json, which is comparatively slower.

Use faster bincode for ipc

---

src/DDTrace/OpenTelemetry/Context.php
src/DDTrace/OpenTelemetry/SpanBuilder.php
tests/OpenTelemetry/Integration/InteroperabilityTest.php

This PR removes redundant resource info from being set on _all_ OTel (native or remapped) spans. It fundamentally is a breaking change (since we are removing data from some spans), so if we want to do it, now is the time.
**What is Resource Info?**
From [OTel Doc](https://opentelemetry.io/docs/languages/php/resources/):
- environment
- host information
- host operating system
- current process
- runtime
**Why should we remove it?**
- First, a customer would ingest "many" irrelevant bytes.
Here is a sample payload without resources (9 tags)
```json
{
"trace_id": "65ddafdb0000000007b244ca5366620e",
"span_id": "805384663926885947",
"parent_id": "9429929380169505464",
"start": 1709027293.039369,
"end": 1709027293.039381,
"duration": 1.2125e-05,
"type": "web",
"service": …
```

[OTel] Only set resource info on root spans

---

.circleci/continue_config.yml
datadog-setup.php
dockerfiles/verify_packages/verify_windows.ps1

Fixes src/ dir copy and avoids the `.dll` suffix at all costs for windows.

Handle relative ext/ paths and test the windows installer

---

config.m4
ext/integrations/exec_integration.c
ext/integrations/exec_integration.stub.php
ext/integrations/exec_integration_arginfo.h

ZEND_RAW_FENTRY is changed on PHP 8.4 and thus the build breaks. Use the generated arginfo instead.
(The change in config.m4 is a mistake in a recent commit I revert here.)

Fix exec integration build on PHP 8.4

---

profiling/src/lib.rs

PROF-9204 / #2070 
This PR will add the PHP build (`ZTS` vs `NTS`) as a tag (`runtime_engine`) to the profiles. In more detail: we will start reporting ZTS as `zend-zts-ndebug` and NTS as `zend-nts-ndebug`(because there is no `debug` build support so far). In case we would support `debug` builds, we'd also add a `zend-nts-debug` and `zend-zts-debug` value.

feat(profiling) report PHP build (`NTS` vs `ZTS`)

---

components-rs/common.h
components-rs/telemetry.h
ext/auto_flush.c
ext/logging.c
ext/sidecar.c
ext/telemetry.c

**What does this PR do?**
This PR updated dd-trace-php to use the helpers that were changed/ introduced in https://github.com/DataDog/libdatadog/pull/347 .
TL;DR: `DDOG_CHARSLICE_C` includes the cast to `(ddog_CharSlice)` to all uses of `(ddog_CharSlice) DDOG_CHARSLICE_C` in the codebase were converted to not have the cast; and `DDOG_CHARSLICE_C_BARE` does not have the cast, so all uses of `DDOG_CHARSLICE_C` without the cast in the codebase were converted to this one.
**Motivation:**
Update to match the latest libdatadog changes.
**Additional Notes:**
This is my first dd-trace-php contribution I think?
**How to test the change?**
I'm guessing CI should be able to validate this (?), not very familiar with our testing setup.

Update to use `DDOG_CHARSLICE_C` and new `DDOG_CHARSLICE_C_BARE` helpers

---

datadog-setup.php

Amend bug which was setting `datadog.appsec.enabled` either `On` or `Off` on the `.ini` file.
When `enable-appsec` flag is not present , `datadog.appsec.enabled` should be commented out on the `.ini` file. This way, remote config will be able to enable appsec.

Enable appsec by ini only when enable-appsec present

---

.circleci/continue_config.yml
.github/workflows/prof_correctness.yml
.gitlab/ci-images.yml
dockerfiles/ci/bookworm/build-extensions.sh
dockerfiles/ci/buster/build-extensions.sh
dockerfiles/ci/centos/7/php.Dockerfile
profiling/src/exception.rs
profiling/tests/correctness/exceptions_zts.json
profiling/tests/correctness/exceptions_zts.php
profiling/tests/phpt/exceptions_01.phpt
profiling/tests/phpt/exceptions_zts_01.phpt
profiling/tests/phpt/zts_01.phpt

This PR will add some tests for exception profiling in ZTS PHP builds:
- prof correctness test
- PHPT tests
- rebuild Buster and CentOS images to have `ext-parallel`
PROF-8923 / #2070

ci(profiling) add tests for exception profiling in ZTS builds

---

profiling/src/config.rs

I wasn't able to find any bad effects when testing this. It's been this way for about 2 months when #2487 was merged.. I think we got lucky because the only not disabled profile type is time, and the time thread will not automatically spawn in the fork.

fix(profiling): fully disable on fork

---

tests/Common/IntegrationTestCase.php

Update CI reporting naming for extensions, to make it consistent with the naming reported by telemetry https://github.com/DataDog/dd-trace-php/blob/4c0dcf6ae38d439434b721dbd11ba8884113e982/ext/telemetry.c#L36

Make CI version naming consistent with telemetry

---

ext/ddtrace.c
tests/ext/fibers/fiber_switch_tracer_disabled.phpt

Fibers were crashing when using ddtrace.disable=1.

Fix fibers with tracer disabled

---

Makefile
benchmark/run_with_native_profiler.sh
docker-compose.yml
tests/Benchmarks/README.md

This PR introduces a script to ease our life (🤞) when running the native profiler on the newly added microbenchmarks. This is nothing more than a shell script.
[Sample profile](https://support-admin.eu1.prod.dog/admin/switch_handle_get/org_id/1000105026?next_url=%2Fprofiling%2Fsearch%3Fquery%3Dservice%253Atest-base-benchtelemetryparsing%2520%26op_filter%3Dddtrace%2520datadog%2520libdatadog%26viz%3Dflame_graph%26zoom%3D1656706656%26start%3D1704288854033%26end%3D1704893654033%26paused%3Dfalse) from the execution of `./run_with_native_profiler.sh --scenario benchTelemetryParsing --style base -n 5 -w`
I think (and hope) the added [README.md](https://github.com/DataDog/dd-trace-php/pull/2454/files#diff-cbd79286e6d4bb77e8f734014e745dac2f0ead6c83de8d03263cfba7d1c2a3e5) can act as this PR's …

Ease local MicroBenchmarks runs with the Native Profiler

---

profiling/README.md
profiling/src/allocation.rs
profiling/src/lib.rs
profiling/src/pcntl.rs
profiling/tests/phpt/jit_01.phpt
profiling/tests/phpt/jit_02.phpt
profiling/tests/phpt/phpinfo_02.phpt

PROF-8922 / #2070 
This PR will bring allocation profiling to ZTS versions of PHP. In the "there is another custom handler installed" code path we are using an `UnsafeCell` for a thread local which is the cheapest way (evaluated at compile time and not runtime), as this is in the hot path (every allocation and free would borrow check at runtime).
We could argue that the case of another extension that has custom handlers installed is nearly non existing, so we could also be better safe then sorry, but OTOH I could not get it to crash.

feat(profiling) allocation profiling for PHP ZTS

---

profiling/src/config.rs
profiling/src/lib.rs
profiling/src/profiling/mod.rs

Adds a setting for disabling the automatic collection of wall-time samples. This only disables the automatic collection, not the entire profile type.
This allows us to remove a source of non-determinism for tests. This is NOT meant for users. Note that if you set this to false, you probably want to disable CPU time.

test(profiling): setting for wall-time enabled/disabled

---

ext/ddtrace.stub.php
ext/ddtrace_arginfo.h

Fixes #2585
Changes update_span_duration return type from null to false|null

fix: Update update_span_duration return type

---

ext/logging.c

We now only change log permissions on log creation.
Not sure how to do a phpt test for that. The file must already exist before the test runs, so a bit of a catch 22.

Fix #2563: ddtrace overrides php error log permissions

---

tests/ext/sandbox/install_hook/hook_internal_inherited_constructor.phpt
zend_abstract_interface/hook/hook.c

Internal constructors are edge cases and need to be handled explicitly.

Allow hooking an inherited internal constructor

---

src/DDTrace/Integrations/PHPRedis/PHPRedisIntegration.php

Broken by https://github.com/DataDog/dd-trace-php/commit/700085c2407d64c2bbe1322012ed9512adfd50a6#diff-2222cf9adbccf7c0c2da75d4b0544f0a03b32c5ee63b7daeb69616f68257a2edR46

Fix PHPRedisIntegration::init method signature (ddtrace-1.0.0)

---

datadog-setup.php

Ensure the installer emits a proper error when trying to be installed on 32 bit architectures.

Distinguish architectures on windows

---

src/Integrations/Integrations/Exec/ExecIntegration.php

For some reason this was still core. It should be exec.

Fix the ExecIntegration name

---

Makefile
tests/Common/IntegrationTestCase.php

Make changes in how supported versions are reported from CI
* Include all composer installed packages instead of only direct dependencies (Composer scenario dependencies are not considered direct dependencies)
* Append to files instead of overriding. The versions are written from within ddSetUpBeforeClass, so there were cases where they might have been overriden and information lost.
* Run composer show in the actual tests dir that it is used from.

Version reporting improvements

---

compile_rust.sh

Fix compilation of the rust crate on macOS when using the `php_shared_build` config option.
Error was:
```
= note: Undefined symbols for architecture arm64:
"_DDTRACE_MOCK_PHP", referenced from:
_ddog_sidecar_connect_php in ddtrace_php.ddtrace_php.5b56db22beb5c715-cgu.0.rcgu.o
"_DDTRACE_MOCK_PHP_SIZE", referenced from:
_ddog_sidecar_connect_php in ddtrace_php.ddtrace_php.5b56db22beb5c715-cgu.0.rcgu.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Fix compilation on macOS

---

src/Integrations/Integrations/ElasticSearch/V8/ElasticSearchIntegration.php

As mentioned in this [GH comment](https://github.com/DataDog/dd-trace-php/issues/2427#issuecomment-2039673277) from #2427, an elasticsearch hook wasn't removed
> [ddtrace] [error] Could not add hook to Elastic\Elasticsearch\Endpoints\Indices::__construct with more than datadog.trace.hook_limit = 100 installed hooks in /opt/datadog-php/dd-trace-sources/bridge/_generated_integrations.php on line 5437; This message is only displayed once. Specify DD_TRACE_ONCE_LOGS=0 to show all messages.
`dd_untrace` was called on the Trait while it should have been called on the hooked class. With this PR, the installed hook is removed on the correct class.

fix(elasticsearch): Hook not being removed

---

dockerfiles/ci/buster/0001-Delete-timers-on-fork.patch
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/buster/php-8.2/Dockerfile
dockerfiles/ci/xfail_tests/8.2.list

Works around https://github.com/php/php-src/issues/12298 and the related memory leaks. This is necessary with the relatively old version of glibc we are building against.
The patch with free() is also specific to the glibc the buster container uses.

Fix asan leak on fork in PHP 8.2 buster container

---

appsec/src/extension/ddappsec.c

When installing via `php datadog-setup.php` appsec will also be installed but crash FrankenPHP after few HTTP requests with the following stack trace:
```
Thread 21 "thpool-7" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xffff68f9f020 (LWP 835)]
dd_entity_body_rinit () at /home/circleci/datadog/appsec/src/extension/entity_body.c:112
112	/home/circleci/datadog/appsec/src/extension/entity_body.c: No such file or directory.
(gdb) bt
#0  dd_entity_body_rinit () at /home/circleci/datadog/appsec/src/extension/entity_body.c:112
#1  0x0000ffff80ccbf68 in zm_activate_ddappsec (type=<optimized out>, module_number=<optimized out>) at /home/circleci/datadog/appsec/src/extension/ddappsec.c:266
#2  0x0000fffff72130e4 in zend_activate_modules () at …
```

disable Appsec when FrankenPHP SAPI is detected

---

benchmark/runall.sh
profiling/benches/exceptions.json
profiling/benches/exceptions.php

This PR will add benchmarks for exceptions, this is also done in preparation for adding exception events to the timeline, so we already gather benchmark data.
Merge together with https://github.com/DataDog/benchmarking-platform/pull/46

ci(profiling): add exceptions benchmark

---

Cargo.lock
Makefile
components-rs/php_sidecar_mockgen/Cargo.toml
components-rs/php_sidecar_mockgen/src/bin/php_sidecar_mockgen.rs

Make `make install` works out of the box on MacOS, like on Linux.

Make the root Makefile macOS compatible

---

src/DDTrace/ScopeManager.php
src/DDTrace/Tracer.php
tests/Unit/GlobalTracerTest.php

May address #2592 
Using the reproducer added as a test, the host scopes would keep on growing, hence slowly but surely increasing memory usage

fix: Host Scopes not being removed

---

datadog-setup.php
dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/installer/test_install_custom_ext_dir_and_ini.sh
dockerfiles/verify_packages/installer/test_install_custom_extension_directory.sh
dockerfiles/verify_packages/installer/test_install_custom_ini_file.sh
dockerfiles/verify_packages/installer/utils.sh

[FRAPMS-4418](https://datadoghq.atlassian.net/browse/FRAPMS-4418)
The setup script now has two new installation options: `--ini` and `--extension-dir`. This should allow customers more flexibility regarding which INI file should be used and where the `.so` files will be copied.
[FRAPMS-4418]: https://datadoghq.atlassian.net/browse/FRAPMS-4418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add `--ini` and `--extension-dir` installation option

---

dockerfiles/verify_packages/installer/test_install_custom_ext_dir_and_ini.sh
dockerfiles/verify_packages/installer/test_install_custom_extension_directory.sh
dockerfiles/verify_packages/installer/test_install_custom_ini_file.sh

fix: Installer tests version lock

---

.github/CODEOWNERS

Add libdatadog-apm team as co-codeowners of libdatdog's related code.

Add libdatadog-apm as codeowners.

---

profiling/src/allocation.rs
profiling/src/logging.rs
profiling/src/profiling/mod.rs

This PR fixes some easy clippy complaints that showed up when running `cargo +stable clippy`

style(profiling): fix some easy clippy lints

---

ext/profiling.c

get_DD_TRACE_ENABLED() must not be accessed outside of requests, given that it accesses a request local array of configs.
DDTRACE_G(active_stack) is supposed to be always properly reset between requests, so we can just put this first and then the calls to get_DD_TRACE_ENABLED() are always correct.
Fixes a crash in datadog_profiling::timeline::timeline_mshutdown doing collect_idle() and ultimately accessing the profiling_context here.
Not sure how to test this; it was reported with the pretty obvious backtrace by an user.

Do not check get_DD_TRACE_ENABLED() outside of a request

---

.circleci/continue_config.yml
profiling/benches/stack_walking.rs
profiling/build.rs
profiling/src/allocation.rs
profiling/src/bindings/mod.rs
profiling/src/lib.rs
profiling/src/pcntl.rs
profiling/src/php_ffi.c
profiling/src/profiling/mod.rs
profiling/src/profiling/stalk_walking.rs
profiling/src/profiling/uploader.rs
profiling/src/timeline.rs

Fixes a few clippy and compiler lints in profiling. Just trying to polish up a bit at the end of our profiling meetup.
Note that it only runs for `x86_64-unknown-linux-gnu` because there was a problem building some packages with clippy on ARM, and the alpine images don't have `clippy`. It also is only running for NTS builds of PHP.

ci(profiling): run clippy, fix lints

---

profiling/src/config.rs
profiling/src/lib.rs

This changes the fields `env`, `service`, and `version` in `RequestLocals` from `Option<Cow<'static, str>>` to `Option<String>`. In practice they were rarely a borrowed string. Doing this shrinks the size of the request locals and is simpler to work with.

refactor(profiling): shrink env/service/version and simplify

---

src/DDTrace/Integrations/LaravelQueue/LaravelQueueIntegration.php
tests/snapshots/tests.integrations.laravel.v8_x.queue_test.test_broadcast.json

Fixes laravel queue integration issue with service naming described in #2637

Use app name as service for laravel queue

---

Makefile

Looking at the debug logs, it appeared that the integrations weren't loaded, hence explaining why the baseline and overhead benchmarks were similar
```
[30-Apr-2024 13:20:46 UTC] [ddtrace] [warning] Error loading deferred integration DDTrace\Integrations\PDO\PDOIntegration: Class not loaded and not autoloadable
```
It seems like using CLI INIs doesn't make it through; using env var allows to properly pass the variable to the phpbench process and beyond.
[See Results](https://benchmarking.us1.prod.dog/benchmarks?benchmarkGroupPipelineId=33250223&benchmarkGroupSha=3cf562aaad06544c4daa351516c328263f4060f9&page=1&ciJobDateStart=1711894338881&ciJobDateEnd=1714486338881&benchmarkId=3441474) 🩸

fix(bench): Pass sources path as an env var to the PHP process

---

.github/CODEOWNERS

[AIDM-68](https://datadoghq.atlassian.net/browse/AIDM-68)
The IDM team wants to limit notifications and narrow the scope of code ownership for Datadog tracing libraries, which is a part of that initiative.
I set the ownership for the IDM team to `/src/`, but it could theoretically be narrowed down even further (e.g., /src/Integrations, /src/OpenTelemetry/), but I think that's OK as is.
However, I see the following error and have no idea where it should be fixed. Maybe in the settings 🤔 
```
Unknown owner on line 15: make sure the team @DataDog/apm-idm-php exists, is publicly visible, and has write access to the repository
```
[Datadog/apm-idm-php team](https://github.com/orgs/DataDog/teams/apm-idm-php)
[AIDM-68]: https://datadoghq.atlassian.net/browse/AIDM-68?atlOrigin=eyJpIjoiNWRkNTljNzYx …

chore: add `apm-idm-php` to CODEOWNERS

---

ext/priority_sampling/priority_sampling.c
tests/ext/priority_sampling/023-manual.keep-distributed_overwrite.phpt

This particular issue only applied when the distributed headers were extracted onto an existing root span. Thus it worked as expected for normal http root spans, but just posed issues with messaging (e.g. laravelqueue).

Fix rejected distributed sampling decision overwrite

---

.github/workflows/prof_correctness.yml

This will notify the `#prof-correctness` channel if the correctness test fails in `master`

ci(profiling) notify if correctness job fails on master

---

CONTRIBUTING.md
Makefile

Update `CONTRIBUTING.md` + fix the `cbindgen` Makefile target not working without installing `cbindgen` manually.

Minor improvements

---

src/DDTrace/Integrations/Laravel/LaravelIntegration.php
src/DDTrace/Integrations/Swoole/SwooleIntegration.php
tests/Integrations/Laravel/Octane/CommonScenariosTest.php

As surfaced in #2636
Currently, the root span from Laravel octane requests' will be `web.request`.
However, this can cause confusion on the Datadog UI, as the backend will most likely choose `laravel.request` as the primary operation, as seen from the screen below:
Therefore, this PR changes the operation name of Laravel octane requests (Swoole, Roadrunner, and beyond) from `web.request` to `laravel.request`, so that it is consistent with the default Laravel behavior.
This is a breaking change, but the next release is 1.0, right? 😉 
Additionally, with this change, if `DD_SERVICE` isn't set, then the request will use Laravel's APP_NAME instead of 'swoole', which is a better experience
---
Technically, I'm hooking `Laravel\Octane\Worker::handle` as it is guaranteed to happen for all …

Mark Laravel Octane requests as `laravel.request`

---

profiling/src/allocation.rs
profiling/src/bindings/mod.rs
profiling/src/lib.rs
profiling/src/php_ffi.c

Refactors the code to get the `PHP_VERSION` info at run-time. Also renames `PHP_VERSION` to `RUNTIME_PHP_VERSION` and `PHP_VERSION_ID` to `RUNTIME_PHP_VERSION_ID` to be a little more specific.
This uses the `php_version` function I added in PHP 8.3 to grab the version of PHP at run-time when it's available. This still uses the `Reflection` module version as a fallback for older versions.
If we fail to get the version at run-time, then we just fall back to the compile-time version and emit a warning.

refactor(profiling): use `php_version` when available

---

src/DDTrace/Integrations/AMQP/AMQPIntegration.php
tests/Integrations/AMQP/AMQPTest.php

This fixes #2644 by configuring the extension to trace the necessary methods.

Instrument AMQP batched publishing

---

ext/compat_string.c
ext/compatibility.h
ext/configuration.h
ext/ddtrace.c
ext/ddtrace.h
ext/ddtrace.stub.php
ext/ddtrace_arginfo.h
ext/priority_sampling/priority_sampling.c
ext/serializer.c
ext/serializer.h
ext/span.c
ext/span.h
src/DDTrace/Integrations/DatabaseIntegrationHelper.php
src/DDTrace/Span.php
tests/Integration/DatabaseMonitoringTest.php
tests/Integration/ErrorReporting/ErrorReportingTest.php
tests/Integration/TracerTest.php
tests/OpenTracer1Unit/TracerTest.php
tests/OpenTracerUnit/TracerTest.php
tests/ext/active_span.phpt
tests/ext/background-sender/agent_sampling.phpt
tests/ext/inherit_meta_from_parent.phpt
tests/ext/runtime_ini_env_version_change.phpt
tests/ext/sandbox/span_clone.phpt

As a fallback, direct assignments to $span->meta["env"] (or version) do still take precedence over the new properties. This was deprecated, and will be eventually removed.
Side note: There were tests for DD_TAGS vs DD_ENV and DD_VERSION. These tests started failing. I elected to remove the tests instead of adding special handling in ddtrace_set_global_span_properties() (if key equals env and property_env non-empty, then ignore). These tests came from a 4 year old migration, at which time these tags had to be set via DD_TAGS, thus prioritizing DD_ENV and DD_VERSION explicitly made sense. By now it would just be a waste of CPU cycles to check that.
This change is important for being able to track changes to service/env/version in the future context of remote configuration.

Move env and version from meta to span properties

---

src/DDTrace/Integrations/DatabaseIntegrationHelper.php
tests/Integration/DatabaseMonitoringTest.php

Please take a look at [AIT-10031](https://datadoghq.atlassian.net/browse/AIT-10031) for the full details (contains the short RFC).
**Changed**
- `dddbs`: It should NOT be overridden by peer.service. There is some fake service thingy in the RFC, but I don't believe it applies there? Or there is something that I'm unaware of
**Added**
- `ddh`: The hostname of the database server
- `dddb`: The schema/database/namespace
- `ddprs`: Value of peer.service if and only if the customer explicitly sets this
[AIT-10031]: https://datadoghq.atlassian.net/browse/AIT-10031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Peer Service Precursors for DBM

---

dockerfiles/verify_packages/installer/test_install_on_plesk.sh

The installer test job has been failing for quite some days now (e.g., [here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/15754/workflows/b221448e-4c47-4c12-9606-b3de7c2b0d60/jobs/4296357?invite=true#step-105-1214)). It seems like a new `plesk/plesk` image was pushed which doesn't include `php`. 
This PR installs PHP in the relevant test environment _(the plesk way)._

fix(ci): Install `php` during plesk installer test

---

.circleci/continue_config.yml
Cargo.lock
Makefile
components-rs/common.h
components-rs/ddtrace.h
components-rs/sidecar.h
ext/coms.c
ext/ddtrace.c
ext/ddtrace.h
ext/sidecar.c
ext/telemetry.c
ext/telemetry.h
tests/Common/WebFrameworkTestCase.php
tests/Integrations/Custom/Autoloaded/InstrumentationTest.php
tests/OpenTelemetry/Integration/InternalTelemetryTest.php
tests/OpenTracing/InternalTelemetryTest.php
tests/ext/appsec/sca_test.inc

Collect trace_api.{requests,responses,errors} metrics in the background trace sender

---

compile_rust.sh
package.xml

Ensures that telemetry from the sidecar points to a proper version.

Compile tracer version into sidecar

---

ext/handlers_api.c
ext/handlers_api.h
package.xml
profiling/src/bindings/mod.rs
profiling/src/exception.rs
profiling/src/php_ffi.h
profiling/tests/phpt/exceptions_generator_throw.phpt

The prev_execute_frame of fake frame of the generator is not fixed up when throwing. Only when executing afterwards.
[SCP-456](https://datadoghq.atlassian.net/browse/SCP-456)
[SCP-456]: https://datadoghq.atlassian.net/browse/SCP-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix exception profiling in Generator->throw()

---

Cargo.lock
components-rs/sidecar.h
ext/auto_flush.c
ext/sidecar.c
package.xml
tests/ext/background-sender/agent_headers.phpt
tests/ext/background-sender/agent_headers_container_id.phpt
tests/ext/background-sender/agent_headers_container_id_empty.phpt
tests/ext/background-sender/agent_headers_container_id_fargate.phpt
tests/ext/background-sender/agent_headers_ignore_userland.phpt
tests/ext/background-sender/agent_headers_unix_domain_socket.phpt
tests/ext/background-sender/agent_sampling.phpt
tests/ext/dd_trace_send_traces_via_thread_001.phpt
tests/ext/dd_trace_span_link_with_exception.phpt
tests/ext/dogstatsd/metrics_over_udp.phpt
tests/ext/dogstatsd/metrics_over_uds.phpt
tests/ext/includes/request_replayer.inc
tests/ext/telemetry/config.phpt

Also, initial stack size is a low number. Also the wrong number, generally. Instead, we'll flush the traces in the sidecar when a significant percentage of the max payload size is reached.

Send a correct size hint to the sidecar trace flusher

---

components-rs/sidecar.h
ext/auto_flush.c
ext/configuration.c
ext/configuration.h
ext/ddtrace.c
ext/ddtrace.stub.php
ext/ddtrace_arginfo.h
ext/hook/uhook_legacy.c
ext/sidecar.c
package.xml

- Synchronous flushing for testing.
- Reduced flush interval for sidecar.
- Reduced flush limit to avoid the sidecar ballooning up memory wise.
- Respect DD_TRACE_AGENT_FLUSH_AFTER_N_REQUESTS with the sidecar active.

Allow synchronous sidecar flushes and reduce flush limit

---

ext/auto_flush.c

Small improvement as I stumbled upon it. Default log level is `error` so no need to evaluate the agent_url in most cases

Switch 2 logs to logev to avoid useless work

---

ext/serializer.c
tests/ext/otel_http_response_status_code_remapping.phpt
tests/ext/otel_http_response_status_code_remapping_precedence.phpt

[GDoc](https://docs.google.com/document/d/19OAW3sfN_HLai91agdZTNjyMuej_1DszJeSZ4WFD7U0/edit)
Remap http.response.status_code to http.status_code, the former taking precedence.
Also, OTel's status code is also an **int**, meaning that when we setAttribute on it in our Span.php shim, it will be redirected to the metrics array.

feat: Remap OTel to DD status code

---

Cargo.toml

This is an attempt to shrink artifacts, but unlike #2601,  this does not do `panic=abort`. For `panic=abort` to be really effective, you also need to rebuild std from source. That means rebuilding images and also installing Rust from rustup (because the packages we are using do not include std sources). We had issues with CI last time we tried it. We played whack-a-mole for a while, but since the issues just kept going and we wanted to release 1.0.0beta1, we decide to revert back.
But this PR without `panic=abort` will still shrink the size a fair bit, so it's worth splitting out. I wouldn't go so far as saying that it will fix the size issue reported in PR #2599, but it helps.

build: shrink size of Rust artifacts

---

components-rs/ddtrace.h
components-rs/telemetry.rs
config.m4
config.w32
ext/configuration.h
ext/ddtrace.c
ext/ddtrace.h
ext/otel_config.c
ext/otel_config.h
ext/sidecar.c
ext/telemetry.c
ext/telemetry.h
profiling/src/bindings/mod.rs
profiling/src/config.rs
tests/ext/background-sender/agent_headers_container_id.phpt
tests/ext/background-sender/agent_headers_container_id_fargate.phpt
tests/ext/otel_config_remapping.phpt
zend_abstract_interface/config/config.c
zend_abstract_interface/config/config.h
zend_abstract_interface/config/config_ini.c
zend_abstract_interface/config/config_ini.h

As per [GDoc](https://docs.google.com/document/d/1gtdjhsMSIvuTnM9E4EreI7oZ-bAUoAxkhXX0-fBvdDY/edit).

Implement OTel config remapping

---

Cargo.lock
profiling/Cargo.toml
profiling/src/lib.rs

PROF-9125
This shrinks our memory footprint. It also reduces our CPU (but just a smidge, not a big change).

perf(profiling): upgrade libdatadog to v10

---

components-rs/ddtrace.h
components-rs/lib.rs
ext/serializer.c

Ensure no utf8 is contained in msgpack strings.
The agent would properly sanitize this away, but the sidecar is not. All traces containing a single invalid utf-8 sequence were dropped.

Ensure the msgpack contents include only valid utf8

---

ext/ddtrace.c

I have zero idea _how_ this happened, given that I'm unable to reproduce it, but a core dump indicated that the memory it pointed to was from the previous request. While this is not a very proper fix (as this should not be possible in the first place), it mitigates the effects.
So, better a mitigation than a crash... :-)

Ensure DDTRACE_G(active_stack) is always NULL when the root span is being pushed

---

profiling/src/bindings/mod.rs
profiling/src/profiling/mod.rs
profiling/src/profiling/stack_walking.rs
profiling/tests/correctness/allocations.json
profiling/tests/correctness/exceptions.json
profiling/tests/correctness/exceptions_zts.json
profiling/tests/correctness/strange_frames.json
profiling/tests/correctness/time.json
profiling/tests/phpt/exceptions_01.phpt
profiling/tests/phpt/exceptions_fibers_throw.phpt
profiling/tests/phpt/exceptions_zts_01.phpt

Turns out the profiling-backend assumes that all pprof based profiles emit a `thread id` and `thread name` label with every sample, so this PR aims to do this. Edit: profiling-backend was updated to not require the thread name, but we should add at least `thread id` anyway. Since thread names are uncommon (we don't know of a single PHP program/library which names threads), we omit `thread name` for now.
Took this as an opportunity to clean up a few things:
- `message_labels` was renamed to `common_labels` and now sets the "fiber" tag (was in `prepare_message` before). It also accepts a parameter for how much extra space to allocate in the `Vec`, so callers can avoid reallocations.
- Avoided `lazy_static` labels, and removed un-necessary `vec!` usages to reduce allocations.
- We always …

feat(profiling): `thread id` label on every sample

---

profiling/tests/correctness/allocations.json
profiling/tests/correctness/exceptions.json
profiling/tests/correctness/exceptions_zts.json
profiling/tests/correctness/strange_frames.json
profiling/tests/correctness/time.json
profiling/tests/correctness/timeline.json

This PR adds a check for the timeline feature for missing labels (mostly `end_timestamp_ns`) and also cleans up the JSON files using `jq`.

ci(profiling): cleanup correctness tests

---

profiling/Cargo.toml
profiling/src/config.rs

Fixes lints from new Rust release. Note that our MSRV has been 1.71 for a while, and we apparently missed it in this place.

style(profiling): fix lints from Rust 1.79 release

---

ext/serializer.c
tests/ext/otel_http_status_code_remapping.phpt

[AIDM-162](https://datadoghq.atlassian.net/browse/AIDM-162)
The following [system test](https://github.com/DataDog/system-tests/blob/6c78b4029f1c6474115c561783f6ce2c2624958c/tests/parametric/test_otel_span_methods.py#L105-L119) was failing. This is because from OTel pov, doing `setAttribute` sets the status code in the metrics array. 
This PR simply maps (and therefore overrides, if set) the deprecated `http.status_code` metric to the meta array. 
This tag is set in [Otel HTTP semantic versions inferior or equal](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.20.0/specification/trace/semantic_conventions/http.md#common-attributes) than [1.21.0](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/trace/semantic_conventions/http.md# …

fix: Handle OTel HTTP semantic conventions < 1.21.0

---

ext/configuration.h
src/DDTrace/Integrations/Memcache/MemcacheIntegration.php
src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
tests/Integrations/Memcache/MemcacheTest.php
tests/Integrations/Memcached/MemcachedTest.php

Add config to disable obfuscation in memcached queries. Keeps old behavior by default. Added on both memcache and memcached. Tests for memached cover only one path, but I didn't want to duplicate the number of integration tests.

Add config to disable obfuscation in memcached queries

---

Makefile
tests/ext/background-sender/agent_sampling_sidecar.phpt
tests/ext/valgrind/suppressions.txt
tests/ext/valgrind/valgrind

Redirect valgrind executions to our custom valgrind-invoking script, to apply suppressions.

Use valgrind suppressions instead of disabling valgrind

---

Cargo.lock
profiling/Cargo.toml
profiling/build.rs
profiling/src/bindings/mod.rs
profiling/src/profiling/stack_walking.rs

Adds `_zend_function.is_internal()` and uses it in a few places.  Also bumps bindgen version and fixes a deprecated warning.

refactor(profiling): extract func is_internal()

---

.circleci/continue_config.yml

See https://github.com/oerdnj/deb.sury.org/issues/2098 for context.
This PR does not change the OS version used to compile the extension. It's just about testing.

Stop testing on debian:buster as sury packages are gone for it

---

profiling/src/allocation.rs
profiling/src/lib.rs
profiling/src/profiling/mod.rs

This reduces unsafe:
1. `RUNTIME_PHP_VERSION_ID` is atomic. The reads and writes are `Relaxed` because the only write happens in module init where no other threads exist.
2. Use `AtomicPtr` for `Profiler.system_settings`, which removes the need for manually derived unsafe `Sync` and `Send`.
I have been reviewing past work to remove the `Mutex` in the `PROFILER` global. The increased scrutiny lead me to change these things.

refactor(profiling): less unsafe code

---

ext/serializer.c
ext/serializer.h
ext/sidecar.c
tests/ext/dogstatsd/metrics_over_udp.phpt

I just noticed that while testing live-debugger metrics - the actual service still ought to be reported.
It's just php-dogstatsd which isn't aware of ddtrace state.

Respect the active service/env/version for metric tags

---

zend_abstract_interface/interceptor/php8/interceptor.c

When optimized, all is fine; however, in unoptimized builds the compiler will write stacktarget back to the stack and read it later from there, even though the stack address has moved. (i.e. only affects development builds.)
Adding register keyword to avoid this.

Fix post bailout hook execution in 8.3 unoptimized builds

---

.circleci/continue_config.yml
.gitlab/ci-images.yml
Makefile
components-rs/lib.rs
components-rs/sidecar.rs
config.m4
dockerfiles/ci/alpine_compile_extension/Dockerfile
dockerfiles/ci/alpine_compile_extension/base.Dockerfile
dockerfiles/ci/alpine_compile_extension/docker-compose.yml
loader/dd_library_loader.c
loader/php_dd_library_loader.h
tooling/bin/verify-dd-trace-php.sh

This also allows using the `.so` shared libraries to be used individually, to reduce size.

Compile sidecar and extension separately, to link them together later

---

.circleci/continue_config.yml
Makefile
components-rs/sidecar.rs
loader/config.m4
loader/dd_library_loader.c
tooling/bin/generate-ssi-package.sh

Package structure is like
```
/
version
trace/
src/
linux-gnu/
loader/
libddtrace_php.so
dd_library_loader.ini  <-- zend_extension=${DD_LOADER_PACKAGE_PATH}/linux-gnu/loader/dd_library_loader.so
dd_library_loader.so
trace/
ext/
...
linux-musl/
loader
libddtrace_php.so
dd_library_loader.ini  <-- zend_extension=${DD_LOADER_PACKAGE_PATH}/linux-musl/loader/dd_library_loader.so
dd_library_loader.so
trace/
ext/
...
```

New SSI package merging glibc/musl

---

profiling/src/pcntl.rs

This refactors the fork handling of profiler. This is roughly an extraction of work that was done in #2714 but not yet merged. That PR has conflicts to fix anyway, so may as well pull out the unrelated refactoring.

refactor(profiling): fork handling

---

.circleci/continue_config.yml

System tests now use a python 3.12.

Switch system-tests to python 3.12

---

profiling/tests/phpt/zts_01.phpt

In PHP 8.4 the `PHP_ZTS` constant got changed to type bool in https://github.com/php/php-src/pull/13079

ci(profiling) fix `PHP_ZTS` test for PHP 8.4

---

loader/dd_library_loader.c

Avoid trying to load an incompatible lib if we know it will fail.
Check code taken from https://github.com/DataDog/auto_inject/pull/266/files#diff-612d425717135d74863f5b8ef8a0c02d214976ad4a5d8b1690ee4bf2297459f0R47-R60

[loader] Add a libc check at runtime

---

src/DDTrace/Integrations/PDO/PDOIntegration.php

feat: Add PDO spans to orphans removal

---

config.m4

Currently a make clean would remove intermediate archives in rust target/ directory, like "./target/debug/build/aws-lc-sys-ca1986c45891d6ab/out/libaws_lc_0_19_0_crypto.a" These intermediate files would not be recreated on their own after a make clean, letting the build fail after a make clean (until one manually removed more files).
This will keep these intermediate rust files, relying on cargo to detect changes, but make distclean will remove the whole target/ directory.

Properly handle make clean

---

.gitlab-ci.yml
.gitlab/benchmarks.yml
.gitlab/download-circleci_artifact.sh
.gitlab/prepare-oci-package.sh
tooling/bin/generate-ssi-package.sh

~~Based on https://github.com/DataDog/dd-trace-php/pull/2684~~ ~~Based on https://github.com/DataDog/dd-trace-php/pull/2744~~
Include the pipeline in charge of creating and pushing an OCI package for SSI
~~This pipeline has no support for Alpine/musl yet, but we can implement this later.~~

Init OCI packaging for SSI

---

src/DDTrace/OpenTelemetry/Context.php
tests/OpenTelemetry/Integration/InteroperabilityTest.php

fix: Crash in OpenTelemetry Span::getCurrent() when accessing span link

---

ext/otel_config.c

The [RFC](https://docs.google.com/document/d/1gtdjhsMSIvuTnM9E4EreI7oZ-bAUoAxkhXX0-fBvdDY/edit?usp=sharing) has been revised since #2691
The expected telemetry tags when reporting OTel env-var mapping issues now use snake-case:
```
config.datadog       -> config_datadog
config.opentelemetry -> config_opentelemetry
```
The expected tag values should also be lower-case.

Update the expected telemetry tags for OTel env-var mapping

---

src/DDTrace/Integrations/Swoole/SwooleIntegration.php
tests/Frameworks/Swoole/index.php
tests/Sapi/SwooleServer/SwooleServer.php

A [swoole_fork](https://github.com/swoole/swoole-src/blob/f4299e7d02dec030fd7b26c3d060cbeec41e3304/src/server/process.cc#L106) always happens during Factory::spawn_Event_worker, regardless of the server's mode. Therefore, when multiple workers are used, we have to handle forking.
This wasn't caught before because, considering that we use 1 core in all of our tests, we were, therefore, using 1 worker by default.
Removed the fork handling at worker stop/exit/error, since they aren't necessary.
On my app (Laravel Octane w/ Swoole), I generated some load and it's working as well ([sandbox](https://app.datadoghq.eu/apm/traces?query=%40_trace_root%3A1%20env%3Aprod&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_c …

fix(swoole): Multiple Workers in SWOOLE_BASE mode

---

.circleci/continue_config.yml
Makefile
compile_rust.sh
config.m4
dockerfiles/packaging/fpm_packaging/Dockerfile
dockerfiles/packaging/fpm_packaging/README.md
dockerfiles/packaging/fpm_packaging/fpm_apk_pax_header.patch
tests/ext/background-sender/agent_sampling_sidecar.phpt
tests/randomized/Makefile
tooling/bin/generate-final-artifact.sh
tooling/bin/generate-ssi-package.sh

This is not the final incantation (i.e. more to come in future PRs), but containing all changes affecting multiple types of jobs at once:
- package extension is parallelized, now taking only 10 min; also uses `ln` instead of `cp` to save time copying things around.
- There also was a redundant tar -> untar cycle in profiling, where the profiler artifacts were first tar-ed together, then untared at the expected location for the packaging script. This was a historic relic from the past and has now been unified.
- This needs tar 1.35 to avoid tar exiting with exit code 1 if any inode link count changes in parallel... I'm also using that occasion to move the fpm packaging docker image to datadog/dd-trace-ci (instead of datadog/docker-library)
- all jobs depending on package extension fetch …

Optimize circleci build times

---

.circleci/continue_config.yml

This ensures we can compare capabilities against e.g. system tests, distinguishing old and new release, otherwise everything would be the same version for them.

Bump the version of the CI builds

---

datadog-setup.php

When using the `--extension-dir` argument, the installer would not find a pre-existing `extension = /path/to/ddtrace.so` line, because it just matched against the default value which is without path.
Fixes #2788

fix ini creation when `--extension-dir` is used

---

.circleci/continue_config.yml
Cargo.lock
components-rs/common.h

Updates the Cargo.lock because it's not current on master, and pins cbindgen to 0.26 in CircleCi. The new cbindgen release requires Rust 1.74, we're on 1.71. This is causing a CircleCI job to fail. Been broken since #2773, I think.

Update Cargo.lock, pin cbindgen in CircleCI, and rerun cbindgen

---

appsec/src/extension/ddtrace.c

This seemed to happen in appsec preload shutdown.
I'm not sure _why_ meta was uninit in the first place, (yes a call to ddtrace_span_data_free_storage will make it undef, but why was that called - it's not a refcounting issue at least?!, I mean it wasn't an use after free?!).

Fix fatal error when reading uninit $meta on a span

---

profiling/src/profiling/mod.rs

This will add a timestamp to the exception sample in order to show it in the timeline view, see also:
- https://github.com/DataDog/profiling-backend/pull/5730
- https://github.com/DataDog/web-ui/pull/152074
PROF-10122

feat(profiling) add timestamp to exception sample

---

datadog-setup.php

`extension_dir = c:/php/ext` is also valid on Windows.
Fixes #2786.

Handle absolute paths in extension_dir containing forward slashes

---

tests/ext/autoload-php-files/dd_init_open_basedir.phpt

Other logs, like
`[ddtrace] [datadog_sidecar::service::blocking] The sidecar transport is closed. Reconnecting...` can be mixed in the output
e.g. https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/17137/workflows/a83b3763-d86e-4723-a2d7-3520f7c61aa0/jobs/4978669

Fix flaky test

---

tests/xdebug/3.0.0/line-breakpoint.inc
tests/xdebug/3.0.0/line-breakpoint.phpt
tests/xdebug/DDTrace/Integrations/Logs/LogsIntegration.php
tests/xdebug/dbgpclient.php
zend_abstract_interface/hook/hook.c

Fixing #2774, just copy pasting the necessary logic from normal entry removal.

Fix #2774: shared hooks removal caused xdebug end handler to be skipped

---

ext/integrations/integrations.c

It was the wrong way round.
And it will mostly fail due to unsupported versions triggering the hook. Explicitly say that.

Fix error message for not loaded/not available

---

appsec/src/extension/backtrace.c

PHP 8.4 changed the string version of a closure. This PR filters out ddtrace closures on 8.4.

Fix backtraces 8.4

---

ext/signals.c

Our signal handlers probably conflicts with golang, causing memory issues on our reliability environments.

Disable SIGSEGV signal handler and crashtracker when sapi is FrankenPHP

---

ext/autoload_php_files.c
package.xml
tests/ext/autoload-php-files/default_spl_autoloader.phpt
tests/ext/autoload-php-files/legacy_autoloader.phpt
tests/ext/autoload-php-files/skip_default_autoloader.phpt
tests/ext/autoload-php-files/splautoload.inc

This could lead to accidental inclusion of files, breaking __autoload() and possibly including the wrong file.

Do not implicitly fall back to spl_autoload() if no autoloader is registered on PHP 7

---

package.xml
zend_abstract_interface/hook/hook.c

This seems to be possible to happen when fatal errors occur beforehand.
This specific fatal error occurred due to a timeout, hence it's not trivially reproducible.

Prevent crash in shutdown if hook was not stored

---

.circleci/continue_config.yml
Cargo.lock

And include a CI check for it in future.
Fixes #2825.

Avoid using non-bundled rust git dependencies

---

ext/configuration.h
tests/ext/autoload-php-files/dd_init_open_basedir.phpt

This mode is supposed to bring some performance improvements, but it turns out it was always disabled, due to the type confusion.

Fix DD_AUTOLOAD_NO_COMPILE

---

ext/signals.c

~~Alternative to https://github.com/DataDog/system-tests/pull/2968~~
Does not fix the system-test, but anyway it may help customer using containers

Wait for the crashtracker receiver response when in a container

---

tests/ext/sandbox/install_hook/trace_generator_jit.phpt

Because JIT is not stable enough on PHP 8.0.
Could be related to [this fix](https://github.com/php/php-src/pull/10153) which seems to have been applied only to PHP 8.1.15 and 8.2.2, but not to PHP 8.0.

Disable trace_generator_jit.phpt test on PHP 8.0

---

ext/distributed_tracing_headers.c
tests/ext/distributed_tracing/distributed_trace_conflicting_span_ids_tracecontext.phpt

Access of span_parent_key would be NULL on second 'p'.

Fix crash with double parent key in tracestate

---

.github/workflows/auto_add_pr_to_miletone.yml
.github/workflows/auto_check_snapshots.yml
.github/workflows/auto_label_prs.yml

As inspired by Datadog/dd-trace-dotnet#5728.
We recently turned off broad permissions, but that caused these workflows to fail / not work.

Fix github actions permissions

---

ext/configuration.h
ext/signals.c

Crashtracker: fix a use-after-free error

---

.github/workflows/prof_correctness.yml

This will add PHP 8.0 to profiling correctness tests

ci(profiling): Add PHP 8.0 to correctness tests

---

.gitlab-ci.yml
tests/Common/SpanChecker.php
tests/Common/TracerTestTrait.php
tests/Integrations/CLI/Symfony/V4_4/CommonScenariosTest.php
tests/Integrations/CLI/Symfony/V5_2/CommonScenariosTest.php
tests/Integrations/CLI/Symfony/V6_2/CommonScenariosTest.php
tests/Integrations/Custom/Autoloaded/InstrumentationTest.php
tests/Integrations/PCNTL/PCNTLTest.php
tests/Integrations/PCNTL/scripts/long-running-autoflush.php
tests/OpenTelemetry/Integration/InternalTelemetryTest.php
tests/OpenTracing/InternalTelemetryTest.php

It look more stable :finger_crossed:; it passed three times in a row.
There were several kinds of errors that could have occurred:
- The order of requests is not guaranteed.
- The number of requests (traces may have been grouped into a single request).
- A timeout could have occurred before the background sender finished sending traces.

Improve pcntl tests stability

---

Makefile
tests/Integrations/DeferredLoading/composer.json
tests/Integrations/DeferredLoading/index.php

Both scenarios DeferredLoading and Predis were running `composer install` in the same directory.
It seems it could break the installation
i.e. https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/17446/workflows/0a933327-d943-4704-b7c9-4f9f560cb329/jobs/5142824

Fix integration tests using Predis

---

appsec/cmake/cond_flag.cmake
appsec/cmake/extension.cmake
appsec/cmake/helper.cmake
appsec/src/extension/ddappsec.version
appsec/src/helper/helper.version

Both the extension and the helper need version scripts to prevent symbols from being exported. -fvisibility=hidden is not sufficient because it's not being applied to some of the static libraries they link against.
On the extensions side: the path to the version script was wrong, as this error was ultimately ignored because invalid ld options were being ingored. This resulted in some extra zai_* functions being exported.
On the helper side: symbols from libunwind, libc++ and possibly others were being exported.

Fix improper symbol exports in appsec ext/helper

---

appsec/src/extension/helper_process.c
appsec/tests/extension/inc/mock_helper.php

Now that we're inside sidecar, we need to have the same uniqueness characteristics of sidecar; in particular, there's one instance of sidecar per uid, but not per (uid,gid) as was the case with the helper before.

Remove gid from socket/lock path of helper

---

CONTRIBUTING.md

This piece of doc hasn't been updated since 2018 😛 
It's just a super small PR to remove the pre-beta mention. Maybe we should revise some aspect of the doc at one point, but let's see that later. In the meanwhile, stating we are in pre-beta is not great advertising. +1:

docs: Remove pre-beta state

---

tests/Integrations/PHPRedis/V3/PHPRedisClusterTest.php
tests/Integrations/PHPRedis/V4/PHPRedisClusterTest.php
tests/Integrations/PHPRedis/V5/PHPRedisClusterTest.php

Fix [this error](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/17484/workflows/db4d6f24-1dbb-491e-a5d7-a03750fd1d9c/jobs/5160204/steps)
```
1) DDTrace\Tests\Integrations\PHPRedis\V4\PHPRedisClusterTest::testMethodsOnlySpan with data set "bgRewriteAOF" ('bgRewriteAOF', null)
RedisClusterException: Unable to send command at a specific node
```
Some Redis commands can fail, so we must account for this in the assertion.
So far, I've only encountered the issue with the `PHPRedisClusterTest`. Let's wait and see if we also need it for the regular `Redis` client.

Fix Redis tests flakiness

---

ext/configuration.h
ext/signals.c
tests/ext/crashtracker_and_backtrace_are_mutually_exclusive.phpt
tests/ext/crashtracker_segfault_disabled.phpt
tests/ext/includes/request_replayer.inc

Corresponding env var `DD_CRASHTRACKING_ENABLED` is handled at least by dd-trace-dotnet and dd-trace-py, and is required by a system-test.
Additionally, I reduced the wait time in the request replayer. 
Previously, the default was 5 seconds per iteration with a maximum of 100 iterations. 
Now, it’s 0.5 seconds per iteration, with a maximum of 200 iterations (500 on Windows).

Add new ini config `datadog.crashtracking_enabled`

---

appsec/src/helper/main.cpp
appsec/src/helper/network/acceptor.cpp
appsec/src/helper/runner.cpp
appsec/src/helper/runner.hpp
appsec/tests/integration/src/test/groovy/com/datadog/appsec/php/integration/Apache2FpmTests.groovy

The sent SIGUSR1 was just terminating the process.

Fix orderly helper appsec shutdown

---

ext/configuration.h
ext/excluded_modules.c
tests/xdebug/2.7.2/self_disable_php_7.0.phpt
tests/xdebug/2.9.2/force_inject.phpt
tests/xdebug/2.9.2/startup_logging_diagnostics.phpt

Add ionCube to the list of incompatible extensions + add INI setting to ignore incompatible extensions

---

ext/git.c

It can crash because `property_commit` or `property_repository` can be NULL.
But the calls to `zend_string_addref` are not needed as `add_git_info` will do a copy.

Fix crash with git metadata injection

---

.gitlab-ci.yml

This PR disables kubernetes injection tests. Tests are already disable in one-pipeline but that will soon be changing with https://github.com/DataDog/libdatadog-build/pull/36 . The variants come from [this pr](https://github.com/DataDog/system-tests/pull/3126) , however, that PR is not ready to be merged yet

Disable kubernetes injection tests

---

.circleci/continue_config.yml
loader/compat_php.c
loader/compat_php.h
loader/dd_library_loader.c
loader/php_dd_library_loader.h
loader/tests/functional/fixtures/opcache_jit.php
loader/tests/functional/includes/autoload.php
loader/tests/functional/test_incompatibility_jit.php
loader/tests/functional/test_incompatibility_xdebug.php
loader/valgrind.supp
zend_abstract_interface/hook/hook.c

Loader: disable the tracer in case of a potential incompatibility (extension/jit)

---

.circleci/continue_config.yml

add necessary auth for new aws system tests and add IDM scenarios of interest

add aws credentials to circleci system tests

---

.circleci/continue_config.yml

Root cause of #2865 - using a large instead of a medium circleci instance.
And changing the build step so that it will properly fail now if any command fails.

Allocate more memory for link_extension step 

---

tests/Frameworks/Custom/OpenTelemetry/index.php
tests/Frameworks/Custom/OpenTracing/index.php
tests/OpenTracing/InternalTelemetryTest.php

Fix OpenTracing test flakiness

---

.gitlab-ci.yml
loader/packaging/allow_tests.json
loader/packaging/block_tests.json
loader/packaging/requirements.json
tooling/bin/generate-ssi-package.sh

~~**Draft, as the RFC might still change.**~~
Implementation of the [RFC](https://docs.google.com/document/d/1TezwaDF_-TXQFHfVTySpd7FvSPRwSTQmSBG2ot129PE/edit?pli=1)
~~Tested manually on `allow_tests.json`/`block_tests.json` using the validator introduced [in this PR](https://github.com/DataDog/auto_inject/pull/380).~~
~~This PR does not add a CI job to check the file [as one will be added to the shared-pipeline](https://github.com/DataDog/dd-trace-dotnet/pull/5928/files#r1738550008)~~

Add SSI requirements.json file

---

src/DDTrace/Integrations/MongoDB/MongoDBIntegration.php

We want to use the new methods when they both exist (and hence, use deprecated methods when either of them _doesn't_ exist). 
I made a typo and forgot a `!`. My bad.
That said, we should look in another PR why our tests didn't catch this.

fix: MongoDBIntegration condition typo

---

ext/span.c

gc_collect_cycles may be intercepted by profiler and when happening precisely within ddtrace_switch_span_stack, the DDTRACE_G(active_span) points to just freed memory.

Fix crash in profiler when span stack switch causes GC run

---

.circleci/continue_config.yml
dockerfiles/ci/alpine_compile_extension/env-init

Make switch-php accept the same inputs than on centos build so that `build_profiler` works correctly on both targets.
Apparently `build_profiler` was trying to use `switch-php` before, and if it didn't exist ... just built NTS and pretended it was the ZTS target on alpine. That obviously does not work.

Fix profiler ZTS build on alpine

---

appsec/src/extension/commands/client_init.c
appsec/src/extension/commands/config_sync.c
appsec/src/extension/ddappsec.c
appsec/src/extension/request_lifecycle.c
appsec/src/helper/client.cpp
appsec/src/helper/remote_config/listeners/asm_features_listener.hpp
appsec/src/helper/service_config.hpp
appsec/src/helper/subscriber/waf.cpp
appsec/tests/integration/src/main/groovy/com/datadog/appsec/php/mock_agent/TracesV04Handler.groovy
appsec/tests/integration/src/test/groovy/com/datadog/appsec/php/integration/RemoteConfigTests.groovy
appsec/tests/integration/src/test/www/base/public/change_env.php

AppSec: improve behavior with empty DD_SERVICE/DD_ENV

---

Cargo.lock
README.md
appsec/src/extension/commands/client_init.c
appsec/src/extension/commands/config_sync.c
appsec/src/extension/ddappsec.c
appsec/src/extension/request_lifecycle.c
appsec/src/helper/client.cpp
appsec/src/helper/remote_config/listeners/asm_features_listener.hpp
appsec/src/helper/service_config.hpp
appsec/src/helper/subscriber/waf.cpp
appsec/tests/integration/src/main/groovy/com/datadog/appsec/php/mock_agent/TracesV04Handler.groovy
appsec/tests/integration/src/test/groovy/com/datadog/appsec/php/integration/RemoteConfigTests.groovy
appsec/tests/integration/src/test/www/base/public/change_env.php
components-rs/Cargo.toml
components-rs/common.h
components-rs/ddtrace.h
components-rs/remote_config.rs
components-rs/sidecar.h
ext/ddtrace.c
ext/git.c
ext/sidecar.c
ext/sidecar.h
tests/ext/integrations/source_code/001/git_metadata_injection_from_valid_files.phpt
tests/ext/integrations/source_code/002/git_metadata_injection_from_invalid_files.phpt

See https://github.com/DataDog/system-tests/pull/3212 - we need to submit these.

Send git tags via remote config

---

Makefile
ext/ddtrace.c
ext/sidecar.c

And set LSAN_OPTIONS=fast_unwind_on_malloc=0 for more complete traces.

Fix memory leak with sidecar trace sender

---

ext/serializer.c

Visible when running stress-test with debug mode active.

Fix crash with missing name in span in debug mode

---

appsec/src/extension/configuration.h

The ASM event obfuscation regex was updated some time ago to cover an extra set of known keys highlighted by the pentesting exercise. This PR just updates the regexes to their new versions.

[ASM] Update event obfuscation regex

---

src/DDTrace/Integrations/LaravelQueue/LaravelQueueIntegration.php

A customer reported hitting the hook limit from `laravel.queue.action` hook installs.
While their issue disappears when removing [these three lines](https://github.com/DataDog/dd-trace-php/blob/ed256f3fc2ee784b98995a593d172862b10f3eca/src/DDTrace/Integrations/LaravelQueue/LaravelQueueIntegration.php#L160-L162) (CallQueueHandler::call being called before the job handler), this is by no means a fix. For legacy, doing `method_exists` on the hooked [$class::$method](https://github.com/DataDog/dd-trace-php/blob/ed256f3fc2ee784b98995a593d172862b10f3eca/src/DDTrace/Integrations/LaravelQueue/LaravelQueueIntegration.php#L166) was returning `true` for them, and we have had confirmation that this method was indeed being called; yet, the hook wasn't invoked.
This PR acts as a mitigation by preventing …

fix: Prevent Laravel Queue hooks from stacking up

---

appsec/src/helper/main.cpp
appsec/src/helper/runner.cpp
appsec/src/helper/runner.hpp

runner was living too long (until shared library unload) due to a static shared pointer used for RC notifications. Plus, the destructor would have a call to shared_for_this(), which would try to revive the shared pointer being destroyed, which raise an exception due to there being no shared pointer anymore. We would catch this and abort().
Instead, destroy the runner earlier (when its own thread finishes). Reset the static shared pointer just before that.

Fix abort() call on appsec helper unload

---

ext/configuration.c

Disable sidecar sending on lambda

---

.github/workflows/prof_asan.yml
.github/workflows/prof_correctness.yml

I stumbled over the cache not being used in GitHub Actions due to a spelling error ...
So I also bumped the versions and fixed the checkout (`depth: 1` is sufficient).
This reduces CI times a bit

ci(profiling) fix actions cache

---

Cargo.lock
components-rs/sidecar.rs

Flushing sometimes takes longer than 1 second, so we would emit WouldBlock and CI would fail.

Increase read timeout of sidecar for synchronous flushes

---

ext/compatibility.h
ext/live_debugger.c
tests/ext/live-debugger/debugger_log_probe.phpt

Capturing $this on PHP 7.0 segfaulted.

Fix bad hasThis() check on PHP 7.0

---

ext/ddtrace.c
tests/ext/dd_trace_multiple_write.phpt

If there's a cache_slot set, it will bypass the write handler, which very much is not what we want. NULL it to prevent assignment.
(And the assignment of an integer parentId did memory leak...)

Fix RootSpanData writer interception on consecutive calls

---

appsec/src/helper/client.cpp
appsec/src/helper/engine_settings.hpp
appsec/src/helper/json_helper.cpp
appsec/src/helper/remote_config/config.hpp
appsec/src/helper/remote_config/product.hpp
appsec/src/helper/remote_config/settings.hpp
appsec/src/helper/service_config.hpp
appsec/src/helper/subscriber/waf.cpp
appsec/third_party/CMakeLists.txt

https://github.com/gabime/spdlog/commit/287a00d364990edbb621fe5e392aeb550135fb96

Update spdlog so it works with recent musls

---

appsec/src/extension/ddtrace.c

Fix heap corruption after apache reloads (appsec)

---

.github/workflows/prof_asan.yml
docker-compose.yml
dockerfiles/ci/bookworm/Dockerfile
dockerfiles/ci/bookworm/build-extensions.sh
dockerfiles/ci/bookworm/build-php.sh

This PR bumps Rust Nightly to `2024-11-04` to be able to run ASAN tests again. Additionally in order to get the bookworm containers compile in our CI, it bumps LLVM there to 17 (like we did for the buster containers already) and adds a PHP 8.4 ASAN run.
[PROF-10137](https://datadoghq.atlassian.net/browse/PROF-10137)
[PROF-10137]: https://datadoghq.atlassian.net/browse/PROF-10137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci(profiling) fix profiling ASAN tests

---

ext/hook/uhook.c
tests/ext/sandbox-regression/trampoline_install_fake_closure_hook.phpt

It may not be perfect, but we cannot trivially check for zend_closure_call_magic being the internal method due to that one being static. I assume it to be good enough unless proven otherwise.

Handle hooks on trampoline fake closures

---

config.m4

It's clang, but a different clang.
It's better to do actual checks for the functionailty than checking for a specific compiler.

Fix macos build where ld will break with -Wl,--undefined-version

---

src/DDTrace/Integrations/Mysqli/MysqliIntegration.php

Otherwise the error stems from "Mysqli/MysqliIntegration.php:379" which may be confusing and seemingly hint at a problem in our integrations.

Avoid the hook frame in mysqli connection error tracking

---

.gitlab/ci-images.yml
dockerfiles/ci/alpine_compile_extension/docker-compose.yml
dockerfiles/ci/bookworm/docker-compose.yml
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/centos/7/docker-compose.yml
dockerfiles/ci/windows/docker-compose.yml

PHP 8.4 RC4 got released, this updates docker images to the latest rc
[PROF-10137](https://datadoghq.atlassian.net/browse/PROF-10137)
[PROF-10137]: https://datadoghq.atlassian.net/browse/PROF-10137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: update PHP 8.4 to rc4

---

loader/compat_php.c
loader/compat_php.h
loader/dd_library_loader.c

Previous build could be loaded with php:5.6 docker image and I believe on centos 7 also. But on Ubuntu 22.04, there were issues like `undefined symbol: __zend_malloc`.
This PR fixes this.
https://datadoghq.atlassian.net/browse/INPLAT-180

[loader] Fix compatilibity with PHP 5

---

ext/exception_serialize.c
ext/span.c

Depending on where the exception originates, a span may have been part of it and be freed during serialization. Immediately send to avoid dangling pointers.

Fix use-after-free in exception replay

---

profiling/src/timeline.rs

add the missing timeline active runtime check for #2820
[PROF-10117](https://datadoghq.atlassian.net/browse/PROF-10117)
[PROF-10118](https://datadoghq.atlassian.net/browse/PROF-10118)
[PROF-10119](https://datadoghq.atlassian.net/browse/PROF-10119)
[PROF-10117]: https://datadoghq.atlassian.net/browse/PROF-10117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PROF-10118]: https://datadoghq.atlassian.net/browse/PROF-10118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PROF-10119]: https://datadoghq.atlassian.net/browse/PROF-10119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(profiling) add timeline active check for fatals

---

profiling/src/lib.rs
profiling/src/timeline.rs

This will wrap functions that are used to wait on blocking I/O, like `stream_select()` and others. It also moves the `frankenphp_handle_request()` to the `idle` visualisation because technically it is waiting on I/O, but it is used to wait for the next request, just like `RSHUTDOWN` -> `RINIT` so it should share the same vis.
In async PHP (using ReactPHP, AMPHP or others), spending time in a `stream_select()`-type function call means the event-loop is idle.
PPROF-10884
AMPHP event loop:
`ext-parallel`'s `\parallel\Events::poll()` method:

feat(profiling) add `stream_select()`-type functions to timeline

---

loader/dd_library_loader.c
loader/tests/functional/test_load_loader_multiple_times.php

[loader] Fix crash when the loader is loaded multiple times

---

appsec/src/extension/configuration.c
ext/configuration.c

It doesn't work properly there, so just disable it until we fix it.
This effectively disabled appsec remote config too, but it's what we got, and lambda is currently rather best-effort support.

Fully disable the sidecar on lambda by setting all related configs to false

---

zend_abstract_interface/jit_utils/jit_blacklist.c

Maybe I don't understand the code well enough, but I don't think it should happen. We had crashes there though, so that should probably should mitigate them.

There may or may not be a readable ZEND_TRACE_OP_INFO()

---

Cargo.lock
appsec/src/extension/configuration.c
components-rs/ddtrace.h
components-rs/remote_config.rs
components-rs/sidecar.h
config.m4
ext/handlers_internal.c
ext/handlers_signal.c
ext/remote_config.c
ext/remote_config.h

These are sensitive to EINTR, so block the signal during their execution.
Fixes #2952.

Block remote config signals during ftp functions

---

src/DDTrace/Integrations/SymfonyMessenger/DDTraceStamp.php

While we no longer make use of it, immediately removing it may break existing applications. Let's keep it for a few versions and drop it later.
See: https://github.com/DataDog/dd-trace-php/pull/2956#pullrequestreview-2442766665

Keep DDTraceStamp

---

.circleci/continue_config.yml
tooling/bin/generate-ssi-package.sh

With the release of the version `1.5.0` (and the addition of PHP `8.4`), we exceed the limitation of 120MB we set for the Kubernetes injection image.
Let's remove the `debug` versions that should not be used except in a local dev environment.

Remove the 'debug' versions from the SSI package to reduce its size

---

loader/dd_library_loader.c

Testing PHP 8.4 with [Ondrej PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php), tracer was disabled because `opcache.jit` is an empty string

[loader] Fix detection of JIT enabled

---

ext/compatibility.h
ext/ddtrace.c
ext/ddtrace_arginfo.h
ext/hook/uhook_arginfo.h
ext/hook/uhook_attributes.c
ext/hook/uhook_attributes_arginfo.h

Make sure things still work :-)

Compatibility with newest arginfo gen_stub from PHP 8.4

---

zend_abstract_interface/jit_utils/jit_blacklist.c

The use of pipe() creates an extra file descriptor which makes the helper unable to find the correct pipe file descriptor. While this could perhaps be improved by telling the helper explicitly the id of the correct file descriptor, it's probably better to swap write() calls of reading invalid addresses with mincore().
See https://github.com/DataDog/dd-trace-php/pull/2942 , which broke the tests

Fix appsec tests in 8.1-8.3

---

dockerfiles/ci/alpine_compile_extension/Dockerfile
dockerfiles/ci/alpine_compile_extension/docker-compose.yml
dockerfiles/ci/bookworm/build-extensions.sh
dockerfiles/ci/buster/build-extensions.sh
zend_abstract_interface/jit_utils/jit_blacklist.c

This updates Xdebug and swoole to the latest PHP 8.4 compatible versions

ci: update xdebug/swoole

---

.github/workflows/auto_add_pr_to_miletone.yml
.github/workflows/auto_check_snapshots.yml
.github/workflows/auto_label_prs.yml
.github/workflows/prof_asan.yml
.github/workflows/prof_correctness.yml

GitHub [announced](https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/?#ubuntu-latest-upcoming-breaking-changes) to migrated `ubuntu-latest` to version 24.04 starting December 5th, so this is just to make sure this will work as expected.

ci(all): Pin Ubuntu version

---

.circleci/continue_config.yml
appsec/src/extension/configuration.c
appsec/src/helper/subscriber/waf.cpp
appsec/tests/helper/client_test.cpp

Appsec pipeline was broken. This PR fixes all errors:
- Update appsec ubuntu docker images to 24:04
- Amend helper tests generating segmentation fault on fuzzer
- Fix linting issues

Fix appsec pipeline

---

loader/dd_library_loader.c
loader/php_dd_library_loader.h
loader/tests/functional/test_telemetry_error.php

[loader] Assign an appropriate tag to each type of error

---

.circleci/continue_config.yml
docker-compose.yml

This adds the missing verify checks for PHP 8.4.
Relates to #2984

ci: add verfy php 8.4

---

Cargo.lock
profiling/src/timeline.rs

Happens in timeline filename for zend_error_observer.
I found this mismatch while doing something else. I asked Florian about it and he prepared a different way to fix it in #2988. I thought I'd push mine up too so we can compare.

fix(profiling): mismatch in utf8 handling

---

appsec/src/extension/network.c

Restart usleep() on EINTR

---

appsec/tests/extension/client_init_record_span_tags.phpt
appsec/tests/extension/rinit_record_span_tags.phpt
ext/asm_event.c
tests/ext/integrations/curl/distributed_tracing_curl_propagate_asm_event.phpt

Let standard limiters to work when standalone not enabled

---

appsec/tests/helper/client_test.cpp
appsec/tests/helper/waf_test.cpp
appsec/tests/integration/src/test/groovy/com/datadog/appsec/php/integration/CommonTests.groovy
appsec/tests/integration/src/test/waf/recommended.json

This PR upgrades libddwaf to v1.22.0 and fixes a few tests:
- Failures due to the fact that the WAF will evaluate some rules even with a timeout of 0 (denylists).
- Failures due to rule order expectations in the integration tests.
Related Jiras: [APPSEC-56195]
[APPSEC-56195]: https://datadoghq.atlassian.net/browse/APPSEC-56195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade libddwaf to v1.22.0

---

datadog-setup.php

This fixes an issue that already happened for PHP 8.3: https://github.com/DataDog/dd-trace-php/pull/2417
Also, I'm removing support for PHP 5.

Supported php84

---

datadog-setup.php

It's not always obvious to the user how to work around a permission denied error here.

Leave a hint at what to do if the temp dir is not writable in installer

---

ext/handlers_signal.c

Follow-up of https://github.com/DataDog/dd-trace-php/pull/2957
At least 2 customers reported random issues with database connections that seems to be fixed when remote config is disabled.
For one of the reports, the error was `EINPROGRESS` (`Operation now in progress`), which could seems unrelated, but actually [a bug in PHP](https://github.com/php/php-src/pull/13252#issuecomment-2438917586) (likely fixed by https://github.com/php/php-src/pull/16606) could return this error while the real one is `EINTR`

Block signals for more functions

---

appsec/src/extension/commands_helpers.c
appsec/src/extension/network.c
appsec/src/extension/network.h

appsec: fix recv/writev calls in the face of interrupting signals

---

tests/Integration/PHPInstallerTest.php

Integration tests are failing ([Sample Failure](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/18757/workflows/0b6e006c-4183-4100-becb-a10acc391675/jobs/5839611?invite=true#step-119-7553_22)):
```
There were 2 failures:
1) DDTrace\Tests\Integration\PHPInstallerTest::testBuildCommandNamesMatrix
Failed asserting that an array contains 'php54'.
/home/circleci/datadog/tests/Integration/PHPInstallerTest.php:80
2) DDTrace\Tests\Integration\PHPInstallerTest::testSearchPhpBinaries
Failed asserting that an array has the key '/tmp/dd-php-setup-tests/opt/remi/php74/root/usr/sbin/php56-fpm'.
```

fix: PHP Installer Tests

---

src/DDTrace/Integrations/AMQP/AMQPIntegration.php
src/DDTrace/Integrations/CodeIgniter/V2/CodeIgniterIntegration.php
src/DDTrace/Integrations/Logs/LogsIntegration.php
src/DDTrace/Integrations/WordPress/WordPressIntegrationLoader.php
src/DDTrace/OpenTelemetry/Span.php
src/DDTrace/OpenTelemetry/SpanBuilder.php
src/DDTrace/OpenTracer/Tracer.php
src/DDTrace/OpenTracer1/Tracer.php
src/DDTrace/ScopeManager.php
src/DDTrace/Tracer.php
src/ddtrace_php_api.stubs.php

This PR removes implicitly nullable parameters because these result in deprecation warnings for PHP 8.4.
https://www.php.net/manual/en/migration84.deprecated.php#migration84.deprecated.core.implicitly-nullable-parameter

Fix PHP 8.4 deprecations

---

src/DDTrace/Integrations/Slim/SlimIntegration.php
tests/Integrations/Slim/V4/CommonScenariosTest.php

I couldn't find a reason for the root span name to differ in Slim 3 compared to Slim 4. Furthermore, setting it to `slim.request` is consistent with all other integrations.
This behavior was identified in the linked escalation.

fix: root span name in Slim V4

---

Cargo.toml
profiling/src/php_ffi.c

Fixes #3012. The profiler can crash on PHP 8.4 when walking the stack for any kind of sample type. The internals upgrading guide says:
```
* zend_get_internal_function_extension_handle[s]() must now be used over
zend_get_op_array_extension_handle[s]() when registering run_time_cache slots
for internal functions. If you need a cache slot for both internal and user
functions, you may obtain a slot for each through the corresponding function.
```
So we call this now as well and use that handle instead of the user handle for internal functions.
~Note that there is a piece in this PR which shouldn't ship: an increase to the debug level. I did this so I can inspect variables and such with the artifacts from CI. This should be reverted before merging.~ Reverted. PR is ready for review.

fix(prof): crash on PHP 8.4

---

appsec/src/extension/commands_helpers.c
appsec/src/extension/network.c

Fix appsec lint

---

zend_abstract_interface/hook/hook.c

Internal functions, when inherited, may (on PHP 8.1 with opcache at least) have pointers which are into heap memory which is local to a given process (e.g. attributes), not present on the target process. Thus accessing the attributes of a duplicated internal functions will crash there.
And on top of that, we anyway don't want to process these twice.

Avoid repeated processing of internal functions

---

ext/ddtrace.c
tests/ext/distributed_tracing/distributed_trace_span_link_from_headers_invalid_tags.phpt

Fix SpanLink::fromHeaders() crash with no or invalid propagated tags

---

appsec/CMakeLists.txt

Fix to prevent the need for https://github.com/DataDog/dd-trace-php/pull/3024

[ASM] Strip new line from version on CMake

---

src/api/Type.php

Fix https://github.com/DataDog/dd-trace-php/issues/3029

Restore MESSAGE_* types

---

.circleci/continue_config.yml
config.w32
docker-compose.yml
profiling/src/allocation.rs
profiling/src/bindings/mod.rs
profiling/src/exception.rs
profiling/src/profiling/stack_walking.rs
profiling/src/sapi.rs
profiling/src/thin_str.rs
tests/randomized/lib/docker-compose.yml

I think there are some `static mut` uses and other things clippy should be complaining about in CI, but it's not. While investigating why we aren't getting more clippy errors, I figured I'd run `cargo +1.84 clippy fix` while I was at it.
We also fix some other small things with the build so that tests pass. Thanks Bob and Florian for contributing those.

style: cargo clippy --fix and fmt on Rust v1.84

---

profiling/build.rs
profiling/src/allocation/allocation_ge84.rs
profiling/src/allocation/allocation_le83.rs
profiling/src/allocation/mod.rs
profiling/src/bindings/mod.rs
profiling/src/config.rs
profiling/src/lib.rs

This PR changes the way we hook into the ZendMM starting from PHP 8.4 thanks to the new ZendMM API that got introduced in https://github.com/php/php-src/pull/13432
PROF-10116

feat(profiling) support new ZendMM api

---

profiling/src/profiling/stack_walking.rs

The profiler may crash when:
1. The profiler is enabled,
2. Allocation profiling is enabled (on by default),
3. The application is on PHP 8.4,
4. and Opcache is enabled and used (strongly recommended for production).
If allocation profiling triggers at a precise spot in the optimizer, then it will dereference a null pointer. The reason is that the optimizer puts a fake frame with a zeroed opline in `accel_preload`, and the profiler does not check for null at this location.
There are other access in the profiler to the opline such as `extract_file_and_line`, but they already guard against a null pointer. This specific bit of code that did not guard was added for PHP 8.4 to handle frameless functions, a new optimization in PHP 8.4.

fix(prof): PHP 8.4 crash with opcache optimizer

---

src/DDTrace/Integrations/Laravel/LaravelIntegration.php

As per #3034 this fixes the scenario in which a Laravel 11+ application does not have the config/app.php file and when in this file is not specified the "name" key (using the default from vendor/laravel/framework/config/app.php).
I was trying to cover my code with test but I cannot execute the test suite, it cannot execute some build using make due to lack of permissions :man_shrugging: .
The new behaviour from Laravel config loader is here: https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L189
This is the default config:
https://github.com/laravel/framework/blob/11.x/config/app.php#L19
Fixes #3034

improve the Application::bootstrapWith hook to find Laravel's application name

---

components-rs/crashtracker.h
components-rs/sidecar.rs

This mitigates issues with logging being to special devices / pipes.

Fall back to stderr if the log path contains colons

---

components-rs/remote_config.rs

Since `VERSION` file was created. Appsec remote config tests where failing. This PR fixes this issue

fix(Appsec Tests) Trim CRLF chars on version file on Remote Config

---

profiling/build.rs
profiling/src/lib.rs

This fixes a bug on `master` where the profiler would not upload profiles anymore:
```
[WARN  datadog_php_profiling::profiling::uploader] Failed to upload profile: failed to parse header value
```
This error could happen when the `VERSION` file had a trailing CRLF sign. This got removed on `master` but profiling still relied on this not existing.

fix(profiler) guard `VERSION` against CRLF characters

---

.github/workflows/prof_correctness.yml
Cargo.lock
profiling/Cargo.toml
profiling/src/profiling/uploader.rs

We have not updated `libdatadog` for profiling in a while, so here is a bump to version 15.
Additionally, this fixes the `prof-correctness` test which was not running due to:
```
[Error](https://github.com/DataDog/dd-trace-php/actions/runs/12865013613/workflow)
shivammathur/setup-php@v2 is not allowed to be used in DataDog/dd-trace-php. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, or matching the following: shivammathur/setup-php@2.32.0, peter-evans/create-pull-request@v7, php-actions/composer@v6.
```
See https://github.com/DataDog/dd-trace-php/actions/runs/12868354364

build(prof): bump `libdatadog` to version `15`

---

Cargo.lock

This PR is the result of running these commands from the `profiling` subdirectory:
```sh
cargo update
cargo update home@0.5.11 --precise 0.5.9
cargo update cc --precise 1.1.31 
cargo update lazy_static --precise 1.4.0
```
These crates were kept back:
- `home`: the new version of home requires too new of an MSRV.
- `cc`: starts complaining about unrecognized targets, such as `x86_64-alpine-linux-musl` (it doesn't know `*-alpine-*`).
- `lazy_static`: triggers an ASAN violation, we'll need to make a bug report.

build(prof): update dependencies

---

Cargo.lock
components-rs/Cargo.toml
components-rs/ddtrace.h
components-rs/lib.rs
ext/sidecar.c
ext/signals.c
tests/ext/background-sender/sidecar_handles_invalid_agent_url.phpt

This avoids panics in the sidecar and crashes in crashtracker initialization.

Validate DD_TRACE_AGENT_URL

---

Cargo.lock
profiling/Cargo.toml
profiling/src/lib.rs
profiling/src/php_ffi.c
profiling/src/profiling/mod.rs
profiling/src/profiling/thread_utils.rs

Null out the extension's handle if the ddprof_upload or ddprof_time threads timeout instead of joining. If the PHP engine dlclose's the handle and the shared object is unloaded while another thread is running, we've hit undefined behavior. This also probably results in a crash (on platforms that unload instead of no-op).
This may be the source of a crash when php-fpm does a log rotate. When doing the rotate, php-fpm shuts down all workers. If a worker is slow to process an upload and the timeout is hit, then we could hit this issue.

fix(prof): avoid dlclose if threads did not join

---

tests/PackageUpdater.php

In #3062, `IntegrationTestCase` was updated to declare `getAppIndexScript` and `getConsoleScript`. Since these methods now exist on any test suite extending `IntegrationTestCase,` we had this type of failures:
```
- Error processing /home/circleci/app/tests/Integrations/AMQP/Latest/AMQPTest.php: dirname(): Argument #1 ($path) must be of type string, null given
#0 /home/circleci/app/tests/PackageUpdater.php(94): dirname(NULL)
#1 /home/circleci/app/tests/PackageUpdater.php(66): PackageUpdater->findComposerFile('DDTrace\\Tests\\I...', '/home/circleci/...')
#2 /home/circleci/app/tests/PackageUpdater.php(21): PackageUpdater->processFile('/home/circleci/...')
#3 /home/circleci/app/tests/PackageUpdater.php(185): PackageUpdater->run()
#4 {main}
```
This fix just proposes to check whether it's …

fix: PackageUpdater failure

---

profiling/src/profiling/mod.rs

I used the wrong combinator before, need to use `Result::and`. From [Result::and documentation](https://doc.rust-lang.org/std/result/enum.Result.html#method.and):
```rs
let x: Result<u32, &str> = Ok(2);
let y: Result<&str, &str> = Err("late error");
assert_eq!(x.and(y), Err("late error"));
let x: Result<u32, &str> = Err("early error");
let y: Result<&str, &str> = Ok("foo");
assert_eq!(x.and(y), Err("early error"));
let x: Result<u32, &str> = Err("not a 2");
let y: Result<&str, &str> = Err("late error");
assert_eq!(x.and(y), Err("not a 2"));
let x: Result<u32, &str> = Ok(2);
let y: Result<&str, &str> = Ok("different result type");
assert_eq!(x.and(y), Ok("different result type"));
```
This is a follow-up to #3075.

fix(prof): combine thread timeout errors properly

---

ext/serializer.c

Add track_error: false on ignored caught exceptions

---

components/atomic_win32_polyfill.h
ext/logging.c

This leaked the log file descriptors due to compare_exchange being a 64 bit operation, on 32 bit ints.

Fix log fd opening on windows

---

.github/workflows/add-asset-to-gh-release.yml

This adds a manual workflow that we can use to add assets to a release. This is not magically finding the current draft release, nor is it magically downloading the correct assets from the latest CircleCI `ddtrace-$VERSION` workflow run, but it removes the need to download and re-upload assets.

ci(all) use workflow to add assets to release

---

.github/workflows/add-asset-to-gh-release.yml

Update to use a 8core machine, should have 32 GB memory and 300 GB disk

fix runner size

---

Makefile
ext/ddtrace.c
ext/live_debugger.c
zend_abstract_interface/interceptor/php8/interceptor.c
zend_abstract_interface/interceptor/php8/interceptor.h

See also https://github.com/php/php-src/issues/17715.
Relatively simple fix: just initialize the cache slots on every request. Has a slight per request-overhead, but avoids crashes when SomePreloadedEnum::cases().
Not adding a test, it's covered by `preload_enum_observed.phpt` from php-src.

Work around preloaded enums being broken on early PHP 8.4 versions with observers

---

Makefile
config.m4
config.w32
ext/ddtrace.c
ext/hook/uhook.c
ext/hook/uhook_otel.c
ext/telemetry.c
ext/telemetry.h
src/DDTrace/OpenTelemetry/CachedInstrumentation.php
src/bridge/_files_opentelemetry.php
tests/Frameworks/Custom/OpenTelemetry/composer.json
tests/OpenTelemetry/Integration/SpanProvenanceTest.php
tests/OpenTelemetry/composer-beta-pre-8.1.json
tests/OpenTelemetry/composer-pre-8.1.json
tests/OpenTelemetry/composer.json
tests/phpunit.xml
zend_abstract_interface/hook/hook.c

- Fires app-integration-changed events whenever a CachedInstrumentation object is constructed. (this generally happens once in constructors of well-behaving OTel integrations.
- Adds a component tag to spans created from a tracer created by the CachedInstrumentation object.

Add OTel Integration tracking

---

profiling/src/allocation/allocation_ge84.rs
profiling/src/allocation/allocation_le83.rs

In case a `fork()` happens before the allocation profiler got initialised, the atfork handler in the child will try and shutdown the allocation profiler in the child and crash.

fix(prof): `fork()` call handling before rinit

---

appsec/src/extension/backtrace.c
appsec/src/extension/commands_helpers.c
appsec/src/extension/dddefs.c
appsec/src/extension/ddtrace.c
appsec/src/extension/request_lifecycle.c
appsec/src/helper/client.cpp
appsec/tests/helper/client_test.cpp
appsec/tests/helper/main.cpp
appsec/tests/helper/service_manager_test.cpp
appsec/tests/integration/src/test/groovy/com/datadog/appsec/php/integration/CommonTests.groovy
appsec/tests/integration/src/test/waf/recommended.json

Add more logging around stack generation

---

Cargo.lock
profiling/src/config.rs
profiling/src/lib.rs

"Fun" fact: the profiler once had `DD_TAGS` support, and this is why
there are tag parsing functions in libdatadog. I think it was lost when
the profiler adopted ZAI config, which was quite a long time ago.
Another "fun" fact: the profiler also had an INI entry for
`datadog.tags`, it just didn't use it anywhere.

feat(prof): add DD_TAGS support

---

ext/compatibility.h
ext/ddtrace.c
ext/ddtrace.stub.php
ext/ddtrace_arginfo.h
ext/handlers_curl.c
ext/hook/uhook.c
ext/hook/uhook_attributes.c
ext/live_debugger.c
ext/span.c
ext/span.h
tests/ext/active_span.phpt
tests/ext/sandbox/span_clone.phpt
tests/ext/span_create_observer.phpt
tests/ext/span_on_close.phpt

The span creation handler is, in particular, needed to attach data dynamically to spans created within a context. E.g. attaching span links from a promises completion span to the promise awaiting span.
It is also beneficial for compression of spans; e.g. an eloquent integration may now opt to no longer create its own span, but manipulate the span created by the mysql integration instead - by first attaching a spanCreationObserver and then in that one attaching an onClose handler, gaining access to the final contents and able to manipulate it.
Span creation handlers are inherited via create_stack(). This can be essentially considered a form of context propagation without having a context with arbitrary metadata. These handlers can be globally removed by returning false (it resets the …

Add span creation and close handlers

---

src/DDTrace/Integrations/SQLSRV/SQLSRVIntegration.php
src/api/Tag.php
src/ddtrace_php_api.stubs.php
tests/Integrations/SQLSRV/SQLSRVTest.php
tests/api/Unit/UserAvailableConstantsTest.php

db.statement is not normalized while sql.query is. Also sending sql.query in SQLSRVIntegration is redundant.

Avoid using db.statement in favor of sql.query

---

Makefile
ext/configuration.h
ext/ddtrace.stub.php
ext/distributed_tracing_headers.c
ext/integrations/integrations.c
ext/integrations/integrations.h
ext/priority_sampling/priority_sampling.c
ext/startup_logging.c
ext/telemetry.c
ext/tracer_tag_propagation/tracer_tag_propagation.c
src/DDTrace/Integrations/Ratchet/RatchetIntegration.php
src/DDTrace/Integrations/Swoole/SwooleIntegration.php
src/api/Type.php
src/ddtrace_php_api.stubs.php
tests/Common/SpanChecker.php
tests/Integrations/Ratchet/V0_4/RatchetTest.php
tests/Integrations/Ratchet/V0_4/composer.json
tests/api/Unit/UserAvailableConstantsTest.php
tests/bootstrap_common.php
tests/ext/integrations/curl/distributed_tracing_curl_propagate_asm_event.phpt
zend_abstract_interface/config/config.c
zend_abstract_interface/config/config.h
zend_abstract_interface/config/config_ini.c
zend_abstract_interface/config/config_runtime.c
zend_abstract_interface/hook/hook.c

Implements server (cboden/ratchet) and clients (ratchet/pawl) of ratchet.
This is going to be the basis of further integrations in conjunction with event loops.

Add a ratchet integration

---

ext/ddtrace.c
ext/handlers_http.h

Fixes segfault from system tests.
And properly supports numeric keys in serialization.

Initialize baggage in RINIT

---

profiling/src/profiling/mod.rs

Runs `cargo +nightly fmt`; running `fmt` was missed in a previously merged PR.

style(prof): cargo +nightly fmt

---

tests/internal-api-stress-test.php

Print date/time in asan test_internal_api_randomized. This way I can see if all tests are slow or if it just gets "stuck." Locally they are all quite fast.

test: print date/time in asan test_internal_api_randomized

---

tests/Frameworks/Symfony/Latest/composer.json

We currently have the following issue since https://github.com/DataDog/dd-trace-php/pull/2956:
```
In ConstExprParser.php line 32:
PHPStan\PhpDocParser\Parser\ConstExprParser::__construct(): Argument #1 ($u
nescapeStrings) must be of type bool, PHPStan\PhpDocParser\ParserConfig giv
en, called in /home/circleci/datadog/tests/Frameworks/Symfony/Latest/vendor
/symfony/property-info/Extractor/PhpStanExtractor.php on line 87
```
There is some weird interaction only when using xdebug.
Upgrading to v2 seems to address the issue.

chore: Update phpstan/phpdoc-parser to v2

---

profiling/src/lib.rs
profiling/src/profiling/mod.rs
profiling/src/profiling/stack_walking.rs
profiling/src/vec_ext.rs

Some customer crash reports indicate that we can hit a Rust OOM panic when stack walking and try to allocate a filename. Based on a quick reading of the code, this can fail if the length exceeds `isize::MAX` or some other fringe conditions. Usually it's not because the system returned `NULL` as this generally doesn't happen on Linux, due to memory overcommit. However, some customers may disable overcommit.
This PR has some steps to be cautious around large strings, notably ones that are longer than `u16::MAX`, or 65,535. It also is a bit more cautious around some Vec operations. However, this is not a full implementation to handle allocation failures--it's just a step in the right direction.

fix(prof)!: avoid some OOM panics and avoid long strings

---

ext/profiling.c

The collection of the active span was missing a `NULL` check

fix(prof): add active span null check

---

ext/ddtrace.c
ext/ddtrace.stub.php
ext/ddtrace_arginfo.h
ext/handlers_http.h
ext/span.c
ext/span.h
src/DDTrace/Integrations/Symfony/SymfonyIntegration.php
tests/Common/TracerTestTrait.php
tests/Frameworks/Symfony/Latest/src/Command/SttyCommand.php
tests/Frameworks/Symfony/Version_4_4/src/Command/SttyCommand.php
tests/Frameworks/Symfony/Version_5_2/src/Command/SttyCommand.php
tests/Frameworks/Symfony/Version_6_2/src/Command/SttyCommand.php
tests/Integrations/CLI/Symfony/V4_4/CommonScenariosTest.php
tests/Integrations/CLI/Symfony/V5_2/CommonScenariosTest.php
tests/Integrations/CLI/Symfony/V6_2/CommonScenariosTest.php
tests/ext/try_drop_span.phpt
tests/snapshots/tests.integrations.cli.symfony.latest.common_scenarios_test.test_silenced_spans_are_dropped.json
tests/snapshots/tests.integrations.cli.symfony.v4_4.common_scenarios_test.test_silenced_spans_are_dropped.json
tests/snapshots/tests.integrations.cli.symfony.v5_2.common_scenarios_test.test_silenced_spans_are_dropped.json
tests/snapshots/tests.integrations.cli.symfony.v6_2.common_scenarios_test.test_silenced_spans_are_dropped.json

Allow dropping top-of-stack (i.e. active) spans in a safe manner.

Add DDTrace\try_drop_span() API

---

profiling/src/lib.rs
profiling/src/timeline.rs

This PR fixes FrankenPHP idle phase detection in worker mode. Turns out, that `frankenphp_handle_request()` does also execute the closure given to it, so the current way of measuring the idle phase in worker mode is incorrect. So what I am doing now instead of hooking `frankenphp_handle_request()` is hooking into `sapi_module.activate`/ `sapi_module.deactivate` in case the detected SAPI is FrankenPHP. If one of those functions is being called while `frankenphp_handle_request()` is the current execute frame, we are indeed in the idle phase.
Why does this work?
FrankenPHP in `frankenphp_worker_request_shutdown()` calls into [`sapi_deactivate()`](https://github.com/dunglas/frankenphp/blob/d3589f97706eac585cdafddbc059cdd53711faf9/frankenphp.c#L141) and in `frankenphp_worker_request_startup()` …

fix(prof) FrankenPHP idle phase

---

ext/asm_event.c
ext/auto_flush.c
ext/ddtrace.c
ext/serializer.c
ext/span.c
ext/span.h
ext/trace_source.c
ext/trace_source.h
package.xml
tests/Integrations/PCNTL/PCNTLTest.php
tests/Integrations/PCNTL/scripts/long-running-manual-flush.php
tests/ext/force_flush_traces.phpt

Working around the agent complaining about "foreign_span". With the agent each array of spans must have the same trace id.
This is already naturally separated with the closed_stack logic, but it was never actually split into different arrays.
This needs to also move the asm logic as now there's definitely no longer one single trace returned from ddtrace_serialize_closed_spans.
The asm logic for event emitted is instead stored on the root span where the event happens (or inherited from global scope if there was no root span at emission time). And the priority sampling / rate limiting applied when the root span is closed. Moving it to the root span close also simplifies the logic and allows possibly straightforwardly dropping the whole trace in future. This also fixes the asm event …

Handle flushing of multiple traces at once

---

profiling/src/bindings/mod.rs
profiling/src/config.rs
profiling/src/php_ffi.c
profiling/tests/phpt/phpinfo_08.phpt
profiling/tests/phpt/phpinfo_ini_02.phpt
zend_abstract_interface/config/config.c
zend_abstract_interface/config/config.h
zend_abstract_interface/config/config_decode.c
zend_abstract_interface/config/config_decode.h
zend_abstract_interface/config/config_ini.c

In the context of Single Step Instrumentation, all profilers must accept the value `auto` in the `DD_PROFILING_ENABLED` environment variable.
Treating it as `true` is adequate for the initial version.
This PR adds a new "displayer" function pointer to the zai entry structs, as it is needed to display "On" if the value is `auto` when the config is printed.

[Profiling] Accept `auto` as valid value for DD_PROFILING_ENABLED

---

.circleci/continue_config.yml
ext/configuration.c
ext/configuration.h
tests/Unit/ConfigurationTest.php

Addresses edge cases missing from: https://github.com/DataDog/dd-trace-php/pull/3162. 
Failing tests: https://github.com/DataDog/system-tests/actions/runs/14201484499/job/39789366220?pr=4439 
- The new parser is currently not used. We need to load `DD_TAGS` using `CUSTOM(MAP)`
- Ensure the first `:` colon in a tag is used to split key-value pairs. 
- If there are no colons in tag then the full tag becomes the key. 
- If there are more than one colons in a tag then the remaining colons must be included in the value.

chore(ddtags): capture key before first colon

---

appsec/src/extension/request_lifecycle.c

There was a bug on IP collection. Whenever a process could not get an IP for valid reasons, like IP not provided, that process would get stuck on an state that IP collection would never happen again. The reason was that the `_client_ip` was not set to null

Amend bug on ip collection not happening

---

ext/serializer.c
tests/ext/ust.phpt
tests/ext/ust_precedence_over_ddtags.phpt
tests/ext/ust_via_ddtags.phpt

Ensure that configurations set in `DD_SERVICE`, `DD_ENV`, and `DD_VERSION` take precedence over values set in DD_TAGS.

fix(dd_tags): Update precedence of UST Configurations

---

appsec/tests/integration/build.gradle
appsec/tests/integration/src/main/groovy/com/datadog/appsec/php/docker/InspectContainerHelper.groovy
appsec/tests/integration/src/main/groovy/com/datadog/appsec/php/model/Span.groovy
appsec/tests/integration/src/test/groovy/com/datadog/appsec/php/integration/RaspSqliTests.groovy
appsec/tests/integration/src/test/resources/init.sql
appsec/tests/integration/src/test/waf/recommended.json
appsec/tests/integration/src/test/www/base/public/rasp_sqli_mysqli.php
appsec/tests/integration/src/test/www/base/public/rasp_sqli_pdo.php
src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
src/DDTrace/Integrations/PDO/PDOIntegration.php

Pass SQL queries to the libddwaf, allowing actions for SQL injections
[APPSEC-51313]
[APPSEC-51313]: https://datadoghq.atlassian.net/browse/APPSEC-51313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Detection/blocking of SQL injections through libddwaf

---

dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/buster/php-8.0/0001-Fix-memory-leak-in-zend_wrong_callback_error.patch
dockerfiles/ci/buster/php-8.0/Dockerfile
dockerfiles/ci/xfail_tests/8.0.list
dockerfiles/ci/xfail_tests/8.1.list
dockerfiles/ci/xfail_tests/8.2.list
ext/ddtrace.stub.php
ext/ddtrace_arginfo.h
tests/ext/request-replayer/dd_trace_agent_env.phpt
tests/internal-api-stress-test.php

A bit, so that it doesn't frequently time out.
This test was effectively always red due to the timeout.

Reduce work done by stress test

---

Cargo.lock
profiling/Cargo.toml
profiling/src/profiling/mod.rs
profiling/src/profiling/uploader.rs

This PR aims to update the `libdatadog` dependency to latest version 17. It does _not_ aim to use any of the new features, like the managed string storage introduced in https://github.com/DataDog/libdatadog/pull/725
Also this PR ran:
```sh
$ cargo update target-triple --precise 0.1.4
```
A `cargo update` does not work because otherwise the tracer `.so` file that we compile for Alpine fails on Alpine 3.7 on loading in PHP with `getrandom: symbol not found`.

chore(prof): update `libdatadog` to v17

---

profiling/src/allocation/allocation_ge84.rs
profiling/src/allocation/mod.rs
profiling/src/config.rs
profiling/src/lib.rs
profiling/tests/phpt/jit_01.phpt
profiling/tests/phpt/jit_02.phpt
profiling/tests/phpt/jit_03.phpt
profiling/tests/phpt/phpinfo_04.phpt

A customer reached out in #3197 with a crash while collecting a stack frame for an allocation that is done while hot function is compiled. This code seems to be there since the new JIT in PHP 8.4. So for now we are disabling allocation profiling when an active JIT is detected in PHP 8.4.

fix(prof): disable allocation profiling when JIT is enabled on PHP 8.4

---

appsec/CMakeLists.txt
appsec/cmake/ddtrace.cmake
appsec/cmake/ext_asan.cmake
appsec/cmake/extension.cmake
appsec/cmake/run_tests.cmake
appsec/src/extension/commands_helpers.c
appsec/tests/extension/helper_bad_response_01.phpt
appsec/tests/extension/push_params_ok_04.phpt
appsec/tests/extension/push_params_ok_06.phpt
appsec/tests/extension/push_params_ok_08.phpt
appsec/tests/extension/push_params_ok_09.phpt
appsec/tests/mock_helper/CMakeLists.txt
ext/configuration.h
tests/Common/WebFrameworkTestCase.php
tests/Integrations/Custom/Autoloaded/InstrumentationTest.php
tests/ext/telemetry/integration.phpt
tests/ext/telemetry/integration_filesystem_01.phpt
tests/ext/telemetry/integration_filesystem_02.phpt
tests/ext/telemetry/integration_filesystem_03.phpt
tests/ext/telemetry/integration_filesystem_04.phpt

RASP configuration needs to be also default on the tracer

Enable RASP by default also in the tracer

---

profiling/benches/fakeapp/bench.sh
profiling/benches/fakeapp/driver.sh
profiling/benches/fakeapp/php.ini
profiling/benches/fakeapp/public/index.php
profiling/benches/fakeapp/src/HttpApp.php
profiling/benches/fakeapp/src/autoload.php
profiling/benches/fakeapp/src/functions.php
profiling/benches/fakeapp/vendor/FakeApp/FakeRoute/autoload.php
profiling/benches/fakeapp/vendor/FakeApp/FakeRoute/src/Config.php
profiling/benches/fakeapp/vendor/FakeApp/FakeRoute/src/ConfigRoute.php
profiling/benches/fakeapp/vendor/FakeApp/FakeRoute/src/Dispatcher.php
profiling/benches/fakeapp/vendor/FakeApp/FakeRoute/src/Found.php
profiling/benches/fakeapp/vendor/FakeApp/FakeRoute/src/MatchedRoute.php
profiling/benches/fakeapp/vendor/FakeApp/FakeRoute/src/MethodNotAllowed.php
profiling/benches/fakeapp/vendor/FakeApp/FakeRoute/src/NotFound.php
profiling/benches/fakeapp/vendor/FakeApp/Http/autoload.php
profiling/benches/fakeapp/vendor/FakeApp/Http/src/Headers.php
profiling/benches/fakeapp/vendor/FakeApp/Http/src/Response.php
profiling/benches/fakeapp/vendor/FakeApp/Http/src/Status.php
profiling/benches/fakeapp/vendor/autoload.php

This adds an app for benchmarking purposes which is somewhat similar to real world things, but gathers stack samples at deterministic points.
The benchmarking script are here but not being run in CI. You'd roughly do:
```sh
cd 'profiling/benches/fakeapp'
bash +x driver.sh "$(git rev-parse --abbrev-ref HEAD)" "master"
```
The driver still needs to compare the output from `$TMPDIR/trigger-*.txt` to the ones in `./trigger-*.txt`.

Add FakeApp for profiling benchmarking

---

ext/span.c
tests/ext/try_drop_span_root.phpt

Recursion in ddtrace_close_span is not that great.

Fix #3191: crash due to double close of span

---

Cargo.lock
components-rs/common.h
components-rs/crashtracker.h
components-rs/library-config.h
components-rs/telemetry.h
loader/dd_library_loader.c
tests/Integrations/Custom/Autoloaded/InstrumentationTest.php
tests/ext/appsec/sca_flag_is_sent_01.phpt
tests/ext/appsec/sca_flag_is_sent_02.phpt
tests/ext/appsec/sca_flag_is_sent_03.phpt
tests/ext/appsec/sca_flag_is_sent_04.phpt
tests/ext/appsec/sca_flag_is_sent_05.phpt
tests/ext/telemetry/config.phpt

Looks like `the ionCube PHP Loader + ionCube24` is also a thing.
And update libdatadog to fix the windows PECL build.

Checks for more ioncube extension names in SSI loader

---

appsec/tests/integration/src/test/groovy/com/datadog/appsec/php/integration/RemoteConfigTests.groovy
components-rs/remote_config.rs

Adds a missing remote config capability for sqli.

Add RASP_SQLI remote config capability

---

tooling/tested_versions/create_or_update_supported_versions_pr.sh

The script was failing when trying to checkout an existing remote branch because it wasn't being fetched first. This change ensures we fetch the specific target branch before attempting to checkout.
[Current failure on master](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/20575/workflows/ae13dac5-bbc9-445f-8a71-19353329186e/jobs/6771995?invite=true#step-106-0_25):
```
++ git status --porcelain
+ [[ -z  M aggregated_tested_versions.json
M integration_versions.md ]]
+ git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
+ git config --global user.name 'github-actions[bot]'
+ CURRENT_BRANCH=master
+ TARGET_BRANCH=update-supported-versions
+ git remote remove origin
+ git remote add origin …
```

fix: fetch target branch before checkout in version update script

---

src/ddtrace_php_api.stubs.php
tooling/stubs/CustomPrinter.php

```
- Upgrading nikic/php-parser (v4.19.4 => v5.4.0)
```
I believe that this change in the composer dependencies from the [0.8.5 php stub generator release](https://github.com/php-stubs/generator/releases/tag/v0.8.5) is responsible for the Fatal Error shown below that can be reproduced by running `make generate_stubs`:
```
Fatal error: Declaration of CustomPrinter::pStmt_Namespace(PhpParser\Node\Stmt\Namespace_ $node) must be compatible with PhpParser\PrettyPrinter\Standard::pStmt_Namespace(PhpParser\Node\Stmt\Namespace_ $node): string in /home/circleci/app/tooling/stubs/CustomPrinter.php on line 8
```
Re-running the aforementioned command after the fix adds many whitespaces :-) 
Thanks @iamluc for the report 🚀

fix: fatal error when generating stubs

---

ext/ip_extraction.c

Otherwise client header IP extraction may crash.

Check server first before accessing in ddtrace_ip_extraction_find

---

zend_abstract_interface/config/config.c

Additionally we always intern the zai config value zval on PHP 7.3+. Not interning these zvals leads to unncessary string value duplication.
This was discovered when running the test_web_custom testsuite PHP 7.3 under apache. (It's enabled on the coming gitlab testsuite.)

Fix assumptions around interned strings on PHP 7.3

---

components-rs/ddtrace.h
components-rs/remote_config.rs
ext/ddtrace.c
ext/remote_config.c
ext/sidecar.h
tests/ext/live-debugger/debugger_span_probe_class.phpt

This also prevents an use-after-free given that only ddtrace_rinit_remote_config will initialize `DDTRACE_G(active_rc_hooks)`.
This use-after-free only manifests sometimes on consecutive requests where both requests end up using live-debugger resources.

Fix initial double remote config reading

---

profiling/src/profiling/uploader.rs

The `Uploader::create_internal_metadata()` would always return `None`...
PROF-11749

fix(profiling) empty internal metadata

---

Cargo.lock
profiling/Cargo.toml
profiling/build.rs
profiling/src/allocation/allocation_ge84.rs
profiling/src/allocation/allocation_le83.rs
profiling/src/bindings/mod.rs
profiling/src/config.rs
profiling/src/lib.rs
profiling/src/profiling/mod.rs
profiling/src/profiling/stack_walking.rs
profiling/src/wall_time.rs

Many clippy lints have accumulated. This fixes all of the lints on PHP 8.3/8.4 and on Rust 1.78. It also fixes many lints from Rust 1.86 and nightly. Here are some of the things fixed:
- Using Rust's CStr literal syntax `c""` and converting some engine members from `*const u8` to `*const c_char`.
- Using `core::ptr::eq` for certain pointer comparisons.
- Adjust use of mutable statics to use pointers, see [Disallow references to static mut](https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html#disallow-references-to-static-mut).
And some non-clippy items:
- Converts `/*` style comments to `//`, which is by far more popular.
- Converts `Safety:` comments to `SAFETY:`, which is mostly what we use everywhere else.
- Updates some of the historical comments to be …

style(prof): fix tons of clippy lints

---

.editorconfig

AFAIK there is only a small number of files where we do want to have no final newline at the end of the file, so far I know it is the `VERSION` file, but all other files should have a final newline character.

fix trailing whitespace

---

ext/sidecar.c
package.xml

This regressed in #3225. Fixing before the 1.9.0 release.

Fix remote config applying with consecutive requests to the same resource

---

ext/ddtrace.c

Try to fix this kind of crash:
```json
{
"symbol_address": "0x64207d58657f",
"function": "zend_hash_find",
"ip": "0x64207d5865d5",
"sp": "0x7fff1479f4d0"
},
{
"symbol_address": "0x75096545b970",
"function": "ddtrace_ip_extraction_find",
"ip": "0x75096545b9ed",
"sp": "0x7fff1479f550"
},
{
"symbol_address": "0x750961814ff0",
"file": "/home/circleci/datadog/appsec/src/extension/request_lifecycle.c",
"line": 436,
"function": "_extract_ip_from_autoglobal",
"ip": "0x750961815035",
"sp": "0x7fff1479f5c0"
}
```
pointing to an NULL zend_string* passed to zend_hash_find.

Try to fix crash with uninitialized priority_header_map

---

profiling/src/profiling/stack_walking.rs

This affects PHP 8.0+ and web SAPIs. The string arena was borrowed to check how much space the arena uses, and then it gets replaced. Unfortunately, the first borrow was not released, probably because of a lifetime extension.
It's hard to make a test case that triggers this edge, because you have to accumulate over 2 MiB in the string cache. This is also why few customers have hit it. In web SAPIs, the worker will often be rotated out for various before this happens. I verified it manually locally with a lower threshold to make sure it's fine now.

fix(prof): borrow error in request shutdown

---

profiling/src/allocation/allocation_ge84.rs
profiling/src/allocation/allocation_le83.rs
profiling/src/allocation/mod.rs
profiling/src/config.rs
profiling/src/exception.rs
profiling/src/io.rs
profiling/src/lib.rs
profiling/src/profiling/mod.rs
profiling/src/profiling/stack_walking.rs
profiling/src/timeline.rs

Rust added these in v1.73. Cleans up our code a bit. I didn't want mingle them in with a bug fix.

style(prof): use local_key_cell_methods

---

loader/dd_library_loader.c

Ensure that injected ddappsec is init after a manually installed version

Add missing dep to injected ddappsec

---

profiling/src/php_ffi.c

[PROF-11814](https://datadoghq.atlassian.net/browse/PROF-11814)
A PHP application _may_ crash happen if:
- Using PHP 7.4+
- The allocation profiler is enabled
- And the ZEND_INIT_ARRAY opcode is executed
The engine currently does not save the opline in ZEND_INIT_ARRAY. Usually if it's out-dated and the line-number is a bit stale, it's not a big deal. But in some cases the opline will be dangling, and in those cases we read invalid memory. This is a bug in the PHP VM that needs to also be fixed upstream: php/php-src#18578. Since PHP 8.1 and 8.2 are in security fixes only, this will go into PHP 8.3 and 8.4, and we'll have to mitigate it on <8.3.
The fix works because by having a user opcode handler the engine will save the opline before it calls the user opcode handler. This has a small …

fix(prof): crash in ZEND_INIT_ARRAY

---

ext/coms.c

In `ddtrace_coms_minit`, `ddtrace_coms_globals.tmp_stack` is never initialized. As a result, when `tmp_stack` differs from `current_stack` in `_dd_unsafe_cleanup_dirty_stack_area`, it may be freed—potentially causing a memory leak.
https://github.com/DataDog/dd-trace-php/blob/master/ext/coms.c#L207-L236
This is related to https://github.com/DataDog/dd-trace-php/issues/3208.

Init ddtrace_coms_globals.tmp_stack

---

datadog-setup.php

Also guard against realpath from failing to resolve the realpath. (This can happen with execute-only permissions.)

Filter SSI paths from installer ini paths

---

profiling/src/allocation/allocation_ge84.rs
profiling/tests/phpt/jit_03.phpt

With #3199 we've disable allocation profiling when an active JIT was detected on PHP 8.4. The [upstream fix](https://github.com/php/php-src/pull/18289) landed in PHP 8.4.7 and was confirmed to fix the issue, so we can allow allocation profiling even when an active JIT is detected on PHP >= 8.4.7

feat(profiling) re-enable allocation profiling with JIT for PHP 8.4.7

---

ext/otel_config.c

Turns out `tracers.` is only the namespace and not part of the name.

Fixup the otel.env.invalid metric name

---

appsec/src/extension/commands_helpers.c
appsec/src/helper/metrics.hpp
appsec/src/helper/subscriber/waf.cpp
appsec/src/helper/subscriber/waf.hpp
appsec/tests/helper/waf_test.cpp

Update SLO metrics:
- Adding rasp.error
- Updating waf_error
- Adding required tags
[[APPSEC-57288]]
[APPSEC-57288]: https://datadoghq.atlassian.net/browse/APPSEC-57288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update SLO metrics

---

.github/workflows/prof_correctness.yml

https://github.com/shivammathur/setup-php is using PECL to install extensions. Currently PECL seems to be slower than usualy and `setup-php` is not able to fetch `ext-parallel`. This PR makes the following:
- update actions
- make sure to fail if an extension can not be installed
- install `ext-parallel` from GitHub to decouple from PECL

fix(ci): failing `prof_correctness` tests

---

profiling/src/allocation/allocation_ge84.rs
profiling/src/bindings/mod.rs
profiling/src/php_ffi.c
profiling/src/profiling/stack_walking.rs
profiling/tests/phpt/allocation_generator_01.phpt

When collecting the stack trace outside of a vm interrupt, the `execute_data.opline` might be a dangling pointer. So far we had some mitigations in place for known cases, but there are some cases where this may still happen. Granted this is extremely rare, but annoying.
The root cause is that the `execute_data.opline` pointer has a different lifetime than the `execute_data.func.op_array` it points into.
This PR:
- adds an out-of-bounds check for accessing the `opline`
- removes all our mitigations
- runs the `allocation_generator_01.phpt` test only if PHP > 8.0.10 is used, as otherwise it crashes in PHP

fix(profiling): validate `opline` before access

---

profiling/src/allocation/allocation_ge84.rs
profiling/src/allocation/allocation_le83.rs
profiling/src/allocation/mod.rs
profiling/src/capi.rs
profiling/src/exception.rs
profiling/src/io.rs
profiling/src/lib.rs
profiling/src/profiling/mod.rs
profiling/src/profiling/stack_walking.rs
profiling/src/timeline.rs
profiling/src/wall_time.rs

We found a `panic_already_borrowed` in our RelEnv with I/O profiling. The following is happening:
- the profiler takes a sample
- during this, a signal arrives (PHP timed out)
- the timeout handler want’s to write it’s usual “Fatal error: Maximum execution time ..” error
- this calls into the I/O profiling write hook which decides to take a sample :boom:
So far we've assumed that we do not sample while we sample, turns out the signal handler for timeout can bypass our assumptions and we may actually sample while we sample 😬
There is no reason to hold onto the mutable borrow for those `RefCell`'s while we collect the stack trace, so this PR aims to only hold onto the mutable borrow for those `RefCell`'s while we change the stats data and make the sampling decision. After that we release …

fix(prof): fewer borrows, less panics on borrows

---

.github/CODEOWNERS
.github/chainguard/gitlab-ci-aggregate-versions.sts.yaml
.gitlab/generate-common.php
.gitlab/generate-tracer.php
tooling/tested_versions/create_or_update_supported_versions_pr.sh

This PR fixes failing GitLab CI integration tests and restores automated tracking of supported library versions that was lost during the CircleCI → GitLab migration.
**Error**: `RdKafka\Exception: Connect to ipv4#127.0.0.1:9092 failed: Connection refused`
**Root Cause Analysis**:
1. **Missing Kafka Service**: Service mapping was `$services["kafk"] = "zookeeper"` - this only added Zookeeper service, but tests connect to `kafka-integration:9092`
2. **Startup Timing**: Zookeeper takes time to start in CI, but Kafka was timing out waiting for Zookeeper
3. **Port Conflicts**: Default Zookeeper admin server conflicted with other services
**Solutions Applied**:
- **Array Service Handling**: Modified service mapping logic to handle arrays: `$services["kafk"] = ["kafka", "zookeeper"]` 
- …

fix(ci): Resolve Kafka/Elasticsearch test failures and add automated supported versions tracking

---

ext/ip_extraction.c
tests/ext/extract_ip_addr_precedence.phpt
tests/ext/extract_ip_private_01.phpt

Add `forwarded` header as source of ip and also add a new range of private ips
[APPSEC-58242]
[APPSEC-58082]
[APPSEC-58242]: https://datadoghq.atlassian.net/browse/APPSEC-58242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPSEC-58082]: https://datadoghq.atlassian.net/browse/APPSEC-58082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add forwarded header and private IP

---

Cargo.lock
profiling/Cargo.toml

Indexmap is no longer used, so it's removed. Some dependencies are upgrade (patch versions only, no minors or majors).

build(prof): bump patch versions, drop indexmap

---

profiling/src/php_ffi.c

There is a [use-after-free crash](https://github.com/php/php-src/pull/19212) which we need to work around.
I've already prepared for the upstream fix to be merged and added some version checks that are all commented out at this point in time and should have the comment removed and version number fixed once the upstream PR has landed.
PROF-12148

fix(prof): Do not call `zend_jit_status()` on affected versions

---

appsec/src/extension/configuration.h

Align the default value of `DD_APPSEC_RASP_ENABLED` on appsec with the tracer

Set DD_APPSEC_RASP_ENABLED default to true as on the tracer

---

appsec/.clang-tidy
appsec/src/helper/main.cpp
appsec/src/helper/service_manager.cpp

musl doesn't support sending a `pthread_kill` to a detached thread that has finished (crashes). So, instead, make the appsec runner thread joinable, and attempt a non-blocking join during shutdown. C++11 thread doesn't have a non-blocking or time-limited join, so revert to using pthreads.

Fix musl appsec helper shutdown crash

---

tooling/tested_versions/create_or_update_supported_versions_pr.sh

Picked up from https://github.com/DataDog/dd-trace-php/pull/3368
**Reason**: Proper GitHub token authentication format to resolve fatal: could not read Password errors during git push

fix: update git remote URL format to use x-access-token for authentication

---

ext/integrations/exec_integration.c

Fix possible crash with freed proc resource
