composer.json
phpunit.xml

Enhancement: Add configuration for phpunit

---

README.md

README example code doesn't work without also using OpenTracing\GlobalTracer

---

.circleci/config.yml
src/DDTrace/Propagator.php
src/DDTrace/Span.php
src/DDTrace/Transport/Stream.php

This PR
💁‍♂️ For reference, see https://github.com/phpstan/phpstan.

Enhancement: Run phpstan on CircleCI

---

.circleci/config.yml

Downgrade composer to get around https://github.com/composer/xdebug-handler/pull/69 (adds --ansi to commands that don't support it, causing failures).

Chuck.hagenbuch/composer selfupdate

---

.circleci/config.yml

This PR
💁‍♂️ Not sure if you prefer, I find the current usage a bit confusing.

Fix: Improve use of anchors and references

---

.circleci/config.yml

This PR
💁‍♂️ For reference, see http://github.com/phpstan/phpstan/compare/0.10.2...0.10.3.

Fix: Update phpstan/phpstan

---

src/DDTrace/Tags.php
src/DDTrace/Tracer.php
tests/Unit/TracerTest.php

Small step towards parity with other tracers

Send system.pid with the root span to match python tracer

---

src/DDTrace/Integrations/LaravelProvider.php
src/DDTrace/Integrations/PDO.php

This PR fixes problems encountered while testing Laravel integration. 
It also includes a fix for PDO.

[ laravel ] #get method wrapper fix

---

src/DDTrace/Integrations/LaravelProvider.php

One small call signature slipped through

[laravel] Fix method signature

---

.phpcs.xml
composer.json

Add check to verify if syntax is compatible with oldest supported PHP5.6 version

PHPCS check PHP5.6 compatibility

---

src/ext/debug.h
src/ext/dispatch_compat_php5.c
tests/ext/case_insensitive_method_hook.phpt

Accidentally we were doing case sensitive lookup in the hash

Fix case sensitive lookup bug

---

.circleci/config.yml
.editorconfig
dockerfiles/debug_php-5.6/Dockerfile
dockerfiles/debug_php-7.2/Dockerfile
src/DDTrace/Integrations/LaravelProvider.php
src/DDTrace/Integrations/PDO.php
src/ext/ddtrace.c
src/ext/dispatch.c
tests/ext/method_returning_array.phpt

Fix  Laravel errors found when running sample "realworld" app
+ keep 5.6 improvements
+ store debug Dockerfiles

Various fixes

---

src/DDTrace/Integrations/Memcached.php

A few minor fixes for memcached integration tags. Tests in different branch `test/memcached`.

Fix metadata in tags generation

---

src/DDTrace/Integrations/SymfonyBundle.php

Small tweaks to Symfony integration.

Symfony add service type and resource name to root span

---

.circleci/config.yml
.gitignore
docker-compose.yml
src/DDTrace/Integrations/PDO.php
src/DDTrace/Span.php
tests/Integration/Common/IntegrationTestCase.php
tests/Integration/Integrations/MemcachedTest.php
tests/Integration/Integrations/PDOTest.php
tests/Integration/Integrations/PredisTest.php

PDO integration tests

---

.circleci/config.yml
src/DDTrace/Integrations/Predis.php
src/DDTrace/Types.php
tests/Integration/Common/SpanChecker.php
tests/Integration/Integrations/PredisTest.php

Extend Predis integration tests coverage

---

docker-compose.yml
dockerfiles/debug_php-5.4/Dockerfile

In preparation for PHP 5.4 support

Dockerfile and compose configuration for php 5.4

---

.circleci/config.yml
docker-compose.yml
dockerfiles/verify_packages/Makefile
src/ext/dispatch.c

Add php 5.6 to prebuilt packages

Native packages with PHP 5.6

---

docker-compose.yml
dockerfiles/ubuntu-16.04-php-7.1/Dockerfile
src/ext/debug.h
src/ext/dispatch.c
src/ext/dispatch_setup.c

This PR addresses underlying problem found in #113

Support tracing calling internal functions

---

CHANGELOG.md
src/DDTrace/Version.php

bump version 0.5.1

---

CHANGELOG.md
src/DDTrace/Integrations/Curl/CurlIntegration.php
src/DDTrace/Integrations/Integration.php
src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php

Guzzle and Curl enabling for Laravel integrations

---

CHANGELOG.md
src/DDTrace/Version.php

bump version 0.6.0

---

CHANGELOG.md
src/DDTrace/Version.php
src/ext/version.h

Bump version 0.7.0

---

README.md

I just realized the docs didn't link to the package release downloads. I also added a section that explains how to install the extension manually from source. :)

Add better instructions for installing the extension

---

src/ext/ddtrace.c
src/ext/dispatch_setup.c

Fix ZTS compilation

---

src/ext/ddtrace.c

Fixes segfault happening on 5.6 ZTS build

Add missing TSMRC suffix

---

CHANGELOG.md
src/DDTrace/Version.php

Release version 0.7.1

---

src/ext/ddtrace.c

Just a quick fix to unregister the INI settings to prevent any leakiness. :)

Unregister the INI settings

---

CHANGELOG.md
src/DDTrace/Version.php
src/ext/version.h

bump version 0.8.0

---

dockerfiles/verify_packages/debian_jessie/Dockerfile

Fix issues found while building packages on circle ci

add --force-yes to package installation when building packages

---

docs/getting_started.md

Add correct info to the Symfony section of the docs.

Update symfony 3/4 docs

---

README.md

[docs] Fix usage example in readme

---

CHANGELOG.md
src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
src/DDTrace/Util/TryCatchFinally.php
tests/Unit/Util/TryCatchFinallyTest.php

add TryCatchFinally::executeAnyMethod to avoid not being able to call protected methods

---

.circleci/config.yml
CHANGELOG.md
src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
src/DDTrace/Util/TryCatchFinally.php
src/ext/ddtrace.c
src/ext/ddtrace.h
src/ext/dispatch.c
src/ext/dispatch.h
src/ext/dispatch_setup.c
tests/Unit/Util/TryCatchFinallyTest.php
tests/ext/enable_throw_exception_if_overridable_doesnt_exist.phpt
tests/ext/reset_configured_overrides.phpt
tests/ext/silently_check_if_overridable_exists.phpt

Merge latest master into dev

---

CHANGELOG.md
package.xml
src/DDTrace/Version.php
src/ext/version.h

Bump version 0.9.1

---

tests/request_replayer/index.php

Improve request replayer returning traces

---

tests/Common/TracerTestTrait.php
tests/Frameworks/Util/CommonScenariosDataProviderTrait.php

This is a patch to handle error edge cases in the testing env when things don't go right. :)

Fix test error cases

---

.circleci/config.yml

Fix packaging compilation + use dd blessed images 

---

.circleci/config.yml
CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Version bump 0.10.0

---

CHANGELOG.md
package.xml

Just a quick patch to update the release notes for PECL. :)

Update release notes for PECL and fix type-os in CHANGELOG

---

.circleci/config.yml
CHANGELOG.md
Makefile
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Update version to 0.11.0  + add verification steps to ensure consistency

0.11.0 version bump

---

local-build.sh

This PR enable building extension for php 5.4 locally.

Build php extension for 5.4 locally

---

CHANGELOG.md
composer.json
src/DDTrace/Bootstrap.php
src/DDTrace/Configuration.php
src/DDTrace/Configuration/AbstractConfiguration.php
src/DDTrace/Configuration/EnvVariableRegistry.php
src/DDTrace/Configuration/Registry.php
src/DDTrace/Http/Request.php
src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php
src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
src/DDTrace/Integrations/ZendFramework/V1/Ddtrace.php
src/DDTrace/Type.php
tests/Frameworks/Custom/Version_Autoloaded/.gitignore
tests/Frameworks/Custom/Version_Autoloaded/README.md
tests/Frameworks/Custom/Version_Autoloaded/composer.json
tests/Frameworks/Custom/Version_Autoloaded/public/index.php
tests/Frameworks/Custom/Version_Autoloaded/src/ErrorController.php
tests/Frameworks/Custom/Version_Autoloaded/src/SimpleController.php
tests/Frameworks/Custom/Version_Autoloaded/src/SimpleViewController.php
tests/Frameworks/Custom/Version_Autoloaded/src/routes.php
tests/Frameworks/README.md
tests/Integrations/Custom/Autoloaded/CommonScenariosTest.php
tests/Unit/Configuration/EnvVariableRegistryTest.php
tests/Unit/ConfigurationTest.php
tests/Unit/Http/RequestTest.php
tests/WebServer.php

This PR ensures that unsupported and custom frameworks still get traced out of the box.

Unsupported & custom framework traces

---

CHANGELOG.md
RELEASING.md
package.xml

Version bump for 0.11.0

---

.circleci/config.yml
CHANGELOG.md
dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/alpine/Dockerfile.template
dockerfiles/verify_packages/docker-compose.yml
dockerfiles/verify_packages/verify_apk.sh

After inclusion of file paths longer than 100 character - a bug in fpm got triggered which

Fix Packaged extension compatiblity with Centos 6 and Alpine linux 

---

CHANGELOG.md
RELEASING.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Version bump for release 0.12.1

Bump version 0.12.1

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Version bump 0.13.0

---

CHANGELOG.md
composer.json
src/DDTrace/Integrations/Curl/CurlIntegration.php
src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
src/DDTrace/Integrations/Predis/PredisIntegration.php
src/ext/ddtrace.h
src/ext/dispatch.c
src/ext/dispatch_setup.c
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php

Fix 5.4 internal functions being called twice

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version 0.13.1

---

src/ext/ddtrace.c
src/ext/dispatch.h
src/ext/dispatch_setup.c

Fix ZTS compilation in php 5.6

---

.circleci/config.yml
CHANGELOG.md
dockerfiles/verify_packages/Makefile

Add debug builds to the package

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Version bump 0.13.2

---

src/ext/backtrace.c
src/ext/backtrace.h
src/ext/ddtrace.c
src/ext/env_config.c
src/ext/logging.c
src/ext/logging.h

support ZTS build for backtrace and logging functions

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Version bump 0.13.4

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Version bump 0.14.0

---

src/ext/ddtrace.c
src/ext/dispatch.c
src/ext/dispatch.h

Just fixing the build in thread-safe mode for PHP 5.6. :)

Fix 5.6-zts build

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Version bump 0.14.1

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Version bump for version 0.14.2

Version bump 0.14.2

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Version bump 0.15.0

---

CHANGELOG.md
RELEASING.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version 0.15.1

---

CHANGELOG.md
src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php

Fixes the remaining issue in #346 where access to the user ID was generating errors when the user model was null.

Fix user ID access in Laravel integration

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version to 0.16.0

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version to 0.16.1

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Release 0.17.0

---

.circleci/config.yml

fixes missing -debug .so files

Fix debug builds in CI

---

dockerfiles/verify_packages/Makefile

Don't verify installation of non existing 7.3 binaries

---

CHANGELOG.md
src/ext/request_hooks.c
tests/ext/run_file_before_request_handling.phpt

This PR ensures no partial matches are possible
Closes: https://github.com/DataDog/dd-trace-php/issues/371

Make request hook do exact match on black list 

---

src/ext/request_hooks.c

Fix compilation errors on master

---

.circleci/config.yml
docker-compose.yml
src/ext/serializer.c

~~- [ ] [Changelog entry](docs/changelog.md) added, if necessary~~

Fix master build

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

~~- [ ] [Changelog entry](docs/changelog.md) added, if necessary~~

Bump version to 0.18.0

---

package.xml

fix #393 add mpack to pecl archive

---

.circleci/config.yml

increase composer memory limit to infinite

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version to 0.19.0

---

CHANGELOG.md

Looks like I forgot to update the header in the CHANGELOG. I also fixed the first tag entry. :)

Fix CHANGELOG headings

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Release version 0.19.1

---

CHANGELOG.md
src/DDTrace/Contracts/Tracer.php
src/DDTrace/NoopTracer.php
src/DDTrace/Span.php
src/DDTrace/Tag.php
src/DDTrace/Tracer.php
tests/Unit/SpanTest.php

Force tracing of whole trace via special Span tags (manual.keep and manual.drop)

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

- Bump version and update changelog and package.xml

Release 0.20.0

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version to 0.21.0

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version to 0.22.0

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version to 0.23.0

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Release version 0.24.0

---

tests/Frameworks/README.md
tests/Frameworks/Slim/Version_3_12/.gitignore
tests/Frameworks/Slim/Version_3_12/CONTRIBUTING.md
tests/Frameworks/Slim/Version_3_12/README.md
tests/Frameworks/Slim/Version_3_12/composer.json
tests/Frameworks/Slim/Version_3_12/docker-compose.yml
tests/Frameworks/Slim/Version_3_12/logs/README.md
tests/Frameworks/Slim/Version_3_12/phpunit.xml
tests/Frameworks/Slim/Version_3_12/public/.htaccess
tests/Frameworks/Slim/Version_3_12/public/index.php
tests/Frameworks/Slim/Version_3_12/src/dependencies.php
tests/Frameworks/Slim/Version_3_12/src/middleware.php
tests/Frameworks/Slim/Version_3_12/src/routes.php
tests/Frameworks/Slim/Version_3_12/src/settings.php
tests/Frameworks/Slim/Version_3_12/templates/index.phtml
tests/Frameworks/Slim/Version_3_12/tests/Functional/BaseTestCase.php
tests/Frameworks/Slim/Version_3_12/tests/Functional/HomepageTest.php

This is a clean install of the [Slim PHP Framework v3.12](http://www.slimframework.com/) to be used in our test suite. I didn't make any modifications to it yet. :)

Add clean install of Slim PHP v3.12

---

CHANGELOG.md
bridge/dd_optional_deps_autoloader.php
bridge/dd_require_all.php
composer.json
phpunit.xml
src/DDTrace/Integrations/IntegrationsLoader.php
src/DDTrace/Integrations/Slim/SlimIntegration.php
src/DDTrace/Integrations/Slim/V3/SlimIntegrationLoader.php
tests/Frameworks/README.md
tests/Frameworks/Slim/Version_3_12/app/SimpleViewController.php
tests/Frameworks/Slim/Version_3_12/composer.json
tests/Frameworks/Slim/Version_3_12/src/dependencies.php
tests/Frameworks/Slim/Version_3_12/src/routes.php
tests/Frameworks/Slim/Version_3_12/templates/simple_view.phtml
tests/Integrations/Slim/V3_12/CommonScenariosTest.php
tests/WebServer.php

This PR adds support for [Slim v3](http://www.slimframework.com/). :)

 Add Slim v3 integration

---

Makefile

This PR validate **package.xml** in CI checks to avoid issues like #447. :)

Validate package.xml in CI checks

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version to 0.26.0

---

src/ext/coms_curl.c
src/ext/ddtrace.c

Fix Small miss-configuration in how current connection is set up in C client.

Fix maximum connection duration not properly set for C client

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Release 0.27.0

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Release 0.27.1

---

.circleci/config.yml
.circleci/valgrind/7_3_musl_valgrind.rc
.circleci/valgrind/musl_valgrind.rc
CHANGELOG.md
package.xml
src/ext/compatibility.h
src/ext/coms.c
src/ext/coms.h
src/ext/coms_curl.c
src/ext/coms_debug.c
src/ext/ddtrace.c
tests/ext/dd_trace_coms_empty_stacks_correctly_recycled.phpt

Ensure C extension is memory leak tested

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

- Valgrind configuration to perform more thorough memory consistency verification #472
- Memory leak detected in tests #472

Release 0.27.2

---

src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php

Remove leftover echo statement

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version to 0.28.0

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version to 0.28.1

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump version to 0.29.0

---

src/ext/ddtrace.c
src/ext/dispatch.c

These are minor issues that I noticed while familiarizing myself with the extension. I left every change as an individual commit in case we need to back single changes out during review.

Cleanup for July 2019

---

.circleci/config.yml

Fix CI cache composer for integration tests

---

LICENSE
LICENSE-3rdparty.csv

Add 3rdparty licenses for vendored files

---

src/ext/coms.c
src/ext/coms.h
src/ext/ddtrace.c

So far, this fixes leak 1 of 4 reported by address sanitizer.

Fix memory leaks August 2019

---

CHANGELOG.md
src/DDTrace/Contracts/Tracer.php
src/DDTrace/NoopTracer.php
src/DDTrace/Tracer.php
src/DDTrace/Transport/Http.php
tests/Integration/Transport/HttpTest.php

Add trace count header only to PHP (subset of #522)

---

.circleci/config.yml

Always build packages on release branches

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Release version 0.30.0

---

CHANGELOG.md

Update changelog to reflect 0.30.0 release

---

.github/PULL_REQUEST_TEMPLATE.md

Add labels and milestone PR checklist for reviewer

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/compatibility.h
src/ext/ddtrace.c
src/ext/dispatch.c
src/ext/dispatch_compat.h
src/ext/version.h
tests/ext/desctructor_called_when_this_gets_out_of_scope.phpt

Release 0.30.1

---

dockerfiles/frameworks/src/Dockerfile
dockerfiles/frameworks/src/laravel/patch.patch
src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php
src/DDTrace/Integrations/PDO/PDOIntegration.php

Align all Laravel framework tests with tracing

---

tests/Integrations/PDO/PDOTest.php

Test PDO active query exception is not happening when variable is unset

---

src/DDTrace/Integrations/Curl/CurlIntegration.php
tests/Integrations/Curl/CurlIntegrationTest.php

If a curl handle is copied, we need to duplicate the HTTP headers onto the new handle. Fixes issue #502.

Fix #502: Curl headers are overwritten when using `curl_copy_handle` function

---

src/DDTrace/Tracer.php
tests/Unit/TracerTest.php

This PR fixes a bug in the sandbox API where internal spans were being sent as a separate trace to the Agent and therefore showing up like a distributed trace in the UI. This would also make a separate trace with only userland spans in the UI.

[Sandbox] Fix merging of internal and userland spans

---

tests/ext/sandbox-regression/disable_tracing_disables_tracing.phpt

This test was already added to package.xml, but the sources were not committed.

Add missing sandbox-regression test

---

src/ext/version.h

This file was missed in the initial version bump.

Bump version to 0.31.0

---

src/DDTrace/Integrations/CodeIgniter/V2/CodeIgniterSandboxedIntegration.php

- Adds a check on CI_VERSION so CodeIgniter v3 doesn't get traced
(since it hasn't been tested at all, and sometimes mismatched
versions cause issues).
- Add URL normalization for root resource name.

Add CodeIgniter Version check and URL normalization

---

src/DDTrace/Integrations/ZendFramework/ZendFrameworkIntegration.php

This tiny PR just fixes the ZF1 integration response after the integration is loaded. :)

Fix ZF1 integration response after loading

---

src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
tests/Integrations/Mysqli/MysqliTest.php

This PR add support for `real_connect` approach when using mysqli.

Support mysqli usage when using real_connect approach

---

bridge/functions.php
src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
src/DDTrace/Integrations/ZendFramework/ZendFrameworkIntegration.php
tests/Integrations/Mysqli/MysqliTest.php

This pulls in recent commits to master. Since we wanted all of them in the release, I merged master instead of cherry-picking.
If all goes as expected, we'll release 0.32.1 tomorrow.

Prepare for 0.32.1 release

---

composer.json
package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump version to 0.33.0

---

src/DDTrace/Bootstrap.php
src/DDTrace/Time.php

The [latest release of phpcs](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.5.1) breaks our build. This PR fixes. :)
- ~[ ] Changelog has been added to the appropriate release draft. For community contributors the reviewer is in charge of this task.~

Update linting for phpcs release

---

src/DDTrace/Integrations/Yii/V2/YiiIntegrationLoader.php

Use the first controller that matches the Application->requestedRoute as the app.endpoint. Before, it was using the first controller whose post-hook executed first.

Update Yii 2 controller matching

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Update versions for release 0.34.0

Update versions for release 0.34.0

---

src/DDTrace/Bootstrap.php

This PR fixes a notice that can be raised when running the request init hook outside of the sandbox on non-web SAPI's that don't set a `$_SERVER['REQUEST_METHOD']` or `$_SERVER['REQUEST_URI']`. I also tried to refactor the root-span initialization a bit, but it certainly could do with some more TLC.

Fix notice and refactor root span init

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump version to 0.34.1

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump 0.35.0 versions

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Version bump 0.35.0

---

src/ext/circuit_breaker.c

Print circuit breaker errors only if DD_TRACE_DEBUG is enabled. Also fix misspelling in function name. Fixes #643.

Print circuit breaker errors only if DD_TRACE_DEBUG is enabled

---

dockerfiles/frameworks/src/Dockerfile

This PR fixes the Composer download in the framework tests build.
- ~~[ ] Changelog has been added to the appropriate release draft. For community contributors the reviewer is in charge of this task.~~

Fix Composer download

---

src/ext/ddtrace.c

This PR adds another incompatible extension to the blacklist.
- ~~[ ] Changelog has been added to the appropriate release draft. For community contributors the reviewer is in charge of this task.~~

Disable ddtrace when incompatible extension is detected

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump version to 0.36.0

---

.circleci/config.yml
composer.json
src/DDTrace/StartSpanOptions.php
tests/OpenTracerUnit/TracerTest.php

Support OpenTracing contexts as parent contexts

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump version for bugfix release.

Bump version to 0.36.1

---

package/post-install.sh

Tiny PR to fix the [package verification](https://app.circleci.com/jobs/github/DataDog/dd-trace-php/100217) after the latest merge.

Replace "which" with "command -v" for better compatibility

---

package.xml
src/DDTrace/Integrations/Curl/CurlIntegration.php
src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
src/DDTrace/Util/CodeTracer.php
src/ext/ddtrace.c
src/ext/dispatch.h
src/ext/dispatch_setup.c
src/ext/logging.c
src/ext/logging.h
src/ext/php5/engine_hooks.c
src/ext/php7/engine_hooks.c
src/ext/span.c
tests/Unit/TraceOverrideMethodTest.php
tests/Unit/TracerTest.php
tests/ext/dd_trace_api_error.phpt
tests/ext/keep_spans_in_limited_tracing_internal_functions.phpt
tests/ext/keep_spans_in_limited_tracing_internal_methods.phpt
tests/ext/keep_spans_in_limited_tracing_userland_functions.phpt
tests/ext/keep_spans_in_limited_tracing_userland_methods.phpt
tests/ext/sandbox-regression/dd_trace_tracer_is_limited_hard.phpt
tests/ext/sandbox/dd_trace_api_error.phpt
tests/ext/sandbox/keep_spans_in_limited_tracing_internal_functions.phpt
tests/ext/sandbox/keep_spans_in_limited_tracing_internal_methods.phpt
tests/ext/sandbox/keep_spans_in_limited_tracing_userland_functions.phpt
tests/ext/sandbox/keep_spans_in_limited_tracing_userland_methods.phpt

This PR removes the need to detect limited-tracing mode using `dd_trace_tracer_is_limited()` calls in tracing closures. This allows the tracer to stop tracing much earlier in the execution when the tracer is in limited mode; this in turn provides a much more optimized experience in limited mode.
Currently, to ensure `foo()` will not be instrumented in limited mode, an integration would make a call to `dd_trace_tracer_is_limited()` at the top of the tracing closure: 
```php
dd_trace_function('foo', function (\DDTrace\SpanData $span) {
if (dd_trace_tracer_is_limited()) {
return false;
}
// ...
});
```
With this PR, when limited mode is active, no calls will be instrumented unless `instrument_when_limited` is set to `1` from a new declarative API. To ensure a function or method is still …

Fix limited tracing

---

src/ext/logging.c
src/ext/logging.h

Remove unnecessary macro and header include

---

tests/ext/sandbox/memory_limit_graceful_bailout.phpt

Just a tiny tweak the make the memory-limit-graceful-bailout test hits the memory limit during span serialization and not before. It also ensures that the tracer doesn't go into limited mode and allow the script to run in an infinite loop.

Make memory-limit test less flaky

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump version to 0.37.0

---

README.md

Caused by https://github.com/DataDog/dd-trace-php/pull/497
This is the fix to update the README.md

RELEASING.md was removed

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Release 0.38.0

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump version to 0.38.1

---

composer.json
package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump version and release 0.39.0

---

src/ext/php7/engine_hooks.c

- Prefix static functions with `_dd_`
- Change BOOL_T to bool

Small refactorings on php7/engine_hooks

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Release 0.39.1

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Release 0.39.2

---

src/ext/php5/engine_hooks.c
src/ext/php7/engine_hooks.c

This PR addresses part one of a two-part refactor of the opcode handlers. The primary changes in this PR are:
1. Any neighboring extension's custom opcode handlers are run before ddtrace instruments a call. This ensures that instrumented calls play nicely with a neighboring extension that shares the same hook.
2. If a neighboring extension alters the VM state in any way by returning anything other than `ZEND_USER_OPCODE_DISPATCH` from the opcode handler, ddtrace will not instrument the call. This ensures that ddtrace will play it safe when a neighboring extension changes the VM state at runtime.
This was tested on the nice-neighbor test framework with the following results.
This fake extension hooks all function call opcodes and emits the message `OPCODE (<opcode> -> <function>)`. Before …

Run neighboring extension's opcode handlers before instrumenting

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump version to 0.40.0

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump version to 0.41.0

---

src/DDTrace/Integrations/Symfony/SymfonySandboxedIntegration.php

Use prehook on `EventDispatcher::dispatch()` on PHP 7 to access the arguments before mutation. This unblocks the failing Symfony tests on #762.

Refactor Symfony integration

---

package/post-install.sh

Scenario:
- User installs a very large .ini file (e.g. for browsercap) of ~20MB.
- At the same time it sets in php.ini memory_limit=${PHP_INI_MEMORY_LIMIT} and in the Dockerfile ENV PHP_INI_MEMORY_LIMIT=128M.
- When `apk add` runs the post-install hook that we use to do some operations at installation time, it does not pass the entire set of exported environment var.
Instead, it only pass an artificially created PATH, that's it. Any value that is exported before installing the script is not visible from inside the post-install script.
(From [apk source code](https://git.alpinelinux.org/apk-tools/tree/src/database.c#n1918) function 'apk_db_run_script' which is the one responsible for invoking the post install).
- As a consequence PHP_INI_MEMORY_LIMIT=128M is not visible and the above is …

Set a sane memory limit when running php from inside post-install hook

---

.circleci/config.yml
src/DDTrace/Integrations/Curl/CurlSandboxedIntegration.php
src/DDTrace/Tracer.php
src/ext/php7/handlers_curl.c

This fixes issues from the recent PRs service mapping (#801)  and curl (#814) that were discovered when merged together.

Fix curl issues and implement service mapping in one place

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump version to 0.44.0

---

tests/overhead/hyperfine_tests/Makefile
tests/overhead/hyperfine_tests/function_calls.php
tests/overhead/hyperfine_tests/method_calls.php

Hyperfine measure function and method tracing overhead

---

src/DDTrace/Bootstrap.php

Sandbox `header` and `http_response_code`.

Sandbox header and http_response_code

---

src/dd-doctor.php

Adding opcache info to dd-doctor.php

add opcache info to dd-doctor

---

package.xml
src/DDTrace/Integrations/Curl/CurlSandboxedIntegration.php
src/DDTrace/Integrations/Guzzle/GuzzleSandboxedIntegration.php
src/DDTrace/Integrations/PDO/PDOIntegration.php
src/DDTrace/Integrations/PDO/PDOSandboxedIntegration.php
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/php7/auto_flush.c
src/ext/version.h
tests/Common/SpanChecker.php
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Integrations/Curl/curl_in_web_request.php
tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V5/guzzle_in_web_request.php
tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V6/guzzle_in_web_request.php
tests/Integrations/PDO/PDOSandboxedTest.php
tests/Integrations/PDO/PDOTest.php
tests/ext/sandbox/auto_flush.phpt
tests/ext/sandbox/auto_flush_attach_exception.phpt
tests/ext/sandbox/auto_flush_disables_tracing.phpt
tests/ext/sandbox/auto_flush_sandbox_exception.phpt
tests/ext/sandbox/auto_flush_userland_root_span.phpt
tests/ext/sandbox/fake_global_tracer.inc
tests/ext/sandbox/fake_tracer.inc
tests/ext/sandbox/fake_tracer_exception.inc

Bump version to 0.45.1.
This patch release contains the following PRs: #882, #885, #886.

Bump version to 0.45.1

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Release 0.45.2

---

package.xml

This file was previously renamed.

Update package.xml for recent changes to tracer for PHP 5.4

---

phpstan.ddtrace.neon

PHPStan made two recent releases; need to update the config accordingly.

Fix issues from recent PHPStan updates

---

src/dd-doctor.php

~- [ ] Tests added for this feature/bug.~ Manually tested

More info to fix open_basedir issue in dd-doctor.php

---

examples/apache-mod_php/Dockerfile
examples/apache-mod_php/README.md
examples/apache-mod_php/docker-compose.yml
examples/apache-mod_php/public/index.php
examples/apache-mod_php/virtual-host.conf

Add Apache + mode_php example app for docs

---

.circleci/config.yml

Update PHP 7.3 compilation image to newer gcc version

---

src/DDTrace/Tracer.php
tests/Integration/TracerTest.php

The values from `DD_ENV` and `DD_VERSION` take precedence over the same vales from `DD_TAGS` (i.e. `DD_TAGS=version:foo,env:foo`). The precedence was honored for userland children spans, but not for internal spans. This PR fixes this issue.
The precedence order is:
1. Spans with explicit conflicting tags (set via `Span::setTag()` or `SpanData::$meta[]`) will not be overwritten by `DD_ENV` and `DD_VERSION`, or `DD_TAGS`.
2. If no explicit tag exists, the value from `DD_ENV` and `DD_VERSION` will be used.
3. If `DD_ENV` and `DD_VERSION` are not set, the values from `DD_TAGS` will be used.
This was the existing behavior, but this PR addresses an issue setting `DD_TAGS` along with `DD_ENV`/`DD_VERSION`. With this fix, `env` and `version` values from `DD_TAGS` will always be overwritten by …

Consistent env vars: Fix propagation of DD_ENV and DD_VERSION to children spans

---

src/ext/php7/engine_hooks.c

This PR splits several opcode handlers on PHP 7 so that one conditional is removed: the check whether a previous opcode handler was registered. Additionally we mark them as ZEND_HOT which may have additional performance gains.
Aside from these changes, we clean up a few bits of the engine_hooks from prior work.
I don't expect these gains to be large; they may not even surpass regular jitter. We'll see what the rel-env has to say, but in any case the code gets cleaned up.

Split PHP 7's opcode handlers for previous case

---

src/ext/php5/engine_hooks.c
src/ext/php5_4/engine_hooks.c

This finishes a todo item from #988 by updating the url to the live docs.

Update URL for PHP 5 stack overflow docs

---

bridge/_files.php
package.xml
src/DDTrace/Integrations/ElasticSearch/V1/loader.php
src/DDTrace/Integrations/Integration.php
src/DDTrace/Integrations/IntegrationsLoader.php
src/DDTrace/Integrations/SandboxedIntegration.php
src/ext/dispatch.h
src/ext/engine_hooks.h
src/ext/integrations/elasticsearch.h
src/ext/integrations/integrations.c
src/ext/integrations/integrations.h
src/ext/integrations/test_integration.h
src/ext/php5/engine_hooks.c
src/ext/php5_4/engine_hooks.c
src/ext/php7/engine_api.c
src/ext/php7/engine_api.h
src/ext/php7/engine_hooks.c
src/ext/php7/handlers_curl.c
src/ext/php7/handlers_phpredis.c
tests/Unit/Integrations/IntegrationsLoaderTest.php
tests/ext/sandbox/deferred_load_attempt_loading_once.phpt
tests/ext/sandbox/deferred_load_using_function.phpt
tests/ext/sandbox/deferred_loading_helper.php

This refactors the deferred loading mechanism and loads PHPRedis this way as well.

Refactor deferred loading and defer load PHPRedis

---

package.xml

Adds Levi and Luca as leads so they can upload packages to pecl.php.net.

Add Levi and Luca as lead developers to package.xml

---

package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Bump version to 0.50.0

---

.circleci/config.yml
cmake/asan.cmake
ext/DatadogArena/arena.c
ext/DatadogArena/datadog/arena.h
ext/DatadogArena/test/arena.cc

This fixes some arena bugs I found while using it in the profiler. It also adds address sanitizer checks.

Fix arena bugs, add ASAN to build

---

Makefile
package.xml
src/DDTrace/Integrations/WordPress/WordPressIntegration.php

This PR cherry-picks #1081 into the `0.50.0` release.

Include #1081 into 0.50.0

---

.circleci/config.yml
Makefile
tests/Frameworks/Symfony/Version_2_3/composer.json
tests/Frameworks/Symfony/Version_4_0/composer.json
tests/Frameworks/Symfony/Version_4_0/composer.lock

Upgrade to composer 2

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

Bump release 0.51.0

---

.circleci/config.yml

This PR adds an asan run of the PHP 8 phpt tests as requested after the review of #1099.

Add PHP 8 asan tests

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

Bump version to 0.52.0

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

Bump version 0.53.0

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

Release 0.54.0

---

Makefile
include/native/dictionary.h
include/native/pprof.h
include/native/string_table.h
src/native/dictionary.c
src/native/pprof.c
src/native/string_table.c

* pprof uses const chars for copied items
* add small amount of documentation to sources
* Improve rehashing speed in string_table

[pprof] various fixes for shared library

---

CMakeLists.txt
include/native/pprof.h
src/native/pprof.c

- Fix equality for Location, Sample
- Add naive Sample aggregation
- Fix CMake build

[Profiler] Fix equality for Location and Sample; add Sample aggregation

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

Release version 0.55.0

---

README.md

Updating links in our `README.md` as they were pointing to obsolete urls.

update links in README.md to configuration and OT docs

---

examples/long-running/long-running-script.php

Show which method to use for manual tracing in case of class + method when handling long running processes.

Comment to long running example for method instead of function as the repetitive hook

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

bump version 0.56.0

---

CMakeLists.txt
src/dd_send.c
src/http.c

This fixes some build issues and fixes an ownership bug in DDR_init.

[Profiler] Fix CMake build for dd_send

---

components/container_id/container_id.c

This is shorter code. It's based on the observation that there were
many uses related to length, which is easier tracked in a variable.
It also re-orders length checks to happen first, which is generally
safer (though in this case maybe it was fine).
This targets an open PR and not master, so skip the checklist.

Use index based approach for finding container ids

---

CONTRIBUTING.md
Makefile

Updated contributing and fixed typo on Makefile::test_all

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

Release 0.60.0

---

ext/php7/ddtrace.c
ext/php8/ddtrace.c

Remove TSRMLS_C from \DDTrace\current_context

---

Makefile
ext/php8/configuration.c
ext/php8/configuration.h
ext/php8/configuration_php_iface.c
ext/php8/configuration_render.h
ext/php8/env_config.c
ext/php8/env_config.h
ext/php8/startup_logging.c
package.xml
tests/Integrations/Custom/Autoloaded/StartupLoggingTest.php
tests/ext/startup_logging-legacy.phpt
tests/ext/startup_logging.inc
tests/ext/startup_logging_config-legacy.phpt
tests/ext/startup_logging_json-legacy.phpt
tests/ext/startup_logging_json.phpt
tests/ext/startup_logging_json_config-legacy.phpt

Required for the internal spans, as they'll need to access these.
Split out from #1251.

Move mapping-settings to be deserialized as a zend_array *

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

Relese 0.61.0

---

tests/Frameworks/Symfony/Version_4_2/composer.json
tests/Frameworks/Symfony/Version_4_4/composer.json

See https://github.com/symfony/symfony/issues/41742 for details.

Fix tests: Pin Symfony 4 tests to laminas/laminas-code < 4.4

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

Version bump 0.62.0

---

Makefile
config.m4
dockerfiles/ci/centos/6/Dockerfile
ext/php5/coms.c
ext/php7/coms.c
ext/php8/coms.c
ext/version.h
package.xml
src/DDTrace/Tracer.php
tests/ext/background-sender/background_sender_restores_capabilities.phpt

Patch release for broken artifacts of 0.62.0.

Release 0.62.1

---

package.xml

Then I don't vanish from package maintainers on release anymore...

Add myself to package.xml as lead

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

Release 0.63.0

---

.circleci/config.yml
ext/php8/serializer.c

Also checks for leaks in CI now.

Fix memory leak of already defined global tags

---

ext/version.h
package.xml
src/DDTrace/Tracer.php
tests/Common/SpanAssertion.php
tests/Common/SpanChecker.php
tests/Common/TracerTestTrait.php

Release 0.64.1

---

ext/php7/auto_flush.c
ext/php8/auto_flush.c
ext/version.h
package.xml
src/DDTrace/Tracer.php
tests/Integrations/Custom/Autoloaded/NonExecutingEndpointsTracingTest.php
tests/Nginx/nginx-default.conf
tests/Sapi/PhpFpm/www.conf

Release 0.65.1

---

src/DDTrace/Util/ObjectKVStore.php
tests/Unit/Util/ObjectKVStoreTest.php

Migrate ObjectKVStore to WeakMap internally

---

config.m4
zend_abstract_interface/json/json.h
zend_abstract_interface/json/tests/json.cc

We need to name these to avoid clashes/relocations (which crash alpine).

ZAI: json - fix php5 build

---

zend_abstract_interface/config/config.c
zend_abstract_interface/config/config.h
zend_abstract_interface/config/config_decode.c
zend_abstract_interface/config/config_decode.h
zend_abstract_interface/config/tests/CMakeLists.txt
zend_abstract_interface/config/tests/config_decode.cc
zend_abstract_interface/zai_compat.h

ZAI: config/json

---

Makefile

Fix coverage in master, wrong -D

fix coverage in master

---

src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
tests/Integrations/Custom/Autoloaded/FatalErrorTest.php
tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
tests/Integrations/Symfony/V4_2/TraceSearchConfigTest.php
tests/Integrations/Symfony/V4_4/CommonScenariosTest.php
tests/Integrations/Symfony/V5_0/CommonScenariosTest.php
tests/Integrations/Symfony/V5_1/CommonScenariosTest.php
tests/Integrations/Symfony/V5_2/CommonScenariosTest.php
tests/Unit/Http/UrlsTest.php

Fix linting

---

.circleci/config.yml
Makefile

Quick fix for makefile/CI to reduce noise

Introduce selective output for run-tests

---

zend_abstract_interface/json/tests/json.cc

Fixes CI for shared exts, follow up to #1432

fix fake_json_ext load

---

.github/ISSUE_TEMPLATE/bug_report.md

Add tracer version to template for bug issues

---

.gitlab-ci.yml
Makefile
ext/php5/ddshared.c
ext/php5/startup_logging.c
ext/php7/ddtrace.c
ext/php7/ddtrace.h
ext/php7/priority_sampling/priority_sampling.c
ext/php7/serializer.c
ext/php7/span.c
ext/php7/startup_logging.c
ext/php8/ddtrace.c
ext/php8/ddtrace.h
ext/php8/priority_sampling/priority_sampling.c
ext/php8/serializer.c
ext/php8/span.c
ext/php8/startup_logging.c
ext/version.h
package.xml
src/DDTrace/Tracer.php
tooling/bin/generate-final-artifact.sh

Bump version to 0.68.2. Includes cherry picks of patches.

Release 0.68.2

---

zend_abstract_interface/CMakeLists.txt
zend_abstract_interface/value/CMakeLists.txt
zend_abstract_interface/value/tests/CMakeLists.txt
zend_abstract_interface/value/tests/value.cc
zend_abstract_interface/value/value.h

ZAI code (including tests) will be much clearer if we provide a basic interface over values.

ZAI Value Interface

---

zai_sapi/CMakeLists.txt
zai_sapi/php5/zai_sapi.c
zai_sapi/php7/zai_sapi.c
zai_sapi/php8/zai_sapi.c
zai_sapi/testing/catch2.hpp
zai_sapi/tests/zai_sapi.cc
zai_sapi/tests/zai_sapi_functions.cc
zai_sapi/tests/zai_sapi_ini.cc
zai_sapi/tests/zai_sapi_io.cc
zai_sapi/zai_sapi_test.hpp

Test harness for ZAI SAPI and consumers.

ZAI SAPI Test Harness

---

Makefile
zai_sapi/CMakeLists.txt

ZAI SAPI ASAN rules were missing from makefile

ZAI SAPI asan

---

src/DDTrace/Tracer.php
tests/Common/TracerTestTrait.php
tests/Integration/CurrentContextAccess/CurrentContextAccessTest.php
tests/Integrations/PCNTL/PCNTLTest.php
tests/Integrations/PCNTL/scripts/access-tracer-after-fork.php

Always emit NoopSpans if the tracer extension is disabled

---

zend_abstract_interface/sandbox/php5/sandbox.c
zend_abstract_interface/sandbox/php7/sandbox.c
zend_abstract_interface/sandbox/php8/sandbox.c
zend_abstract_interface/sandbox/sandbox.h
zend_abstract_interface/sandbox/tests/error.cc
zend_abstract_interface/sandbox/tests/sandbox.cc

As part of gracefully handling bailouts in ZAI/Symbols, the need has emerged for some API in ZAI/Sandbox.

ZAI Sandbox Bailout

---

src/DDTrace/Span.php
src/api/Contracts/Span.php

Fix Span::setError docblock

---

datadog-setup.php
dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/installer/test_first_install_php_debug.sh
dockerfiles/verify_packages/installer/test_first_install_php_debugzts.sh
dockerfiles/verify_packages/installer/test_first_install_php_zts.sh
dockerfiles/verify_packages/installer/test_profiler_install_unsupported.sh
dockerfiles/verify_packages/installer/test_profiler_install_unsupported_debug.sh
dockerfiles/verify_packages/installer/utils.sh

This improves the user experience. Before this change, the user would
not get an error nor a warning, but profiling wouldn't get installed.

Setup: Error if profiling is given but unavailable

---

Makefile
dockerfiles/ci/alpine/docker-compose.yml
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/buster/php-8.1/Dockerfile
tests/composer.json

Also update PHP 8.0 alpine, closing #1242.

Update PHP 8.1 dependencies in CI, include laravel testing

---

Makefile

This updates profiling to v0.4.0. Highlights of the release:
- Add configuration diagnostics to phpinfo(): ![configuration_diagnostics.png](https://user-images.githubusercontent.com/253316/151485800-6e51fe0a-e518-4268-98e5-febb4b8669b8.png)
- Adds container ID to profiles so the agent can perform container tagging.

Update profiling to v0.4.0

---

.gitlab-ci.yml
Makefile
ext/version.h
package.xml
src/DDTrace/Tracer.php

Release 0.70.0

---

tests/Unit/Util/Normalizer/UriTest.php

Add a test for sub path and wildcards normalization

---

ext/php5/coms.h
ext/php7/coms.h
ext/php8/coms.h

Followup to https://github.com/DataDog/dd-trace-php/pull/1504 as the change was lost during a rebase. See the other PR for an explanation.

Increase sending backlog size by 20%

---

ext/php5/ddtrace.c
ext/php7/ddtrace.c
ext/php8/ddtrace.c
tests/ext/show_actual_active_span_in_hook.phpt

Hide the dummy span during trace hooks away

---

.circleci/config.yml
Makefile
docker-compose.yml
ext/php8/integrations/integrations.c
src/Integrations/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
tests/Integrations/Elasticsearch/V1/ElasticSearchIntegrationTest.php
tests/composer.json

Testing against the current elasticsearch repository, which is supported from 7.3 to current.

Added ES integration support for newer PHP and ES versions

---

tests/Common/WebFrameworkTestCase.php

Just a super tiny enhancement while debugging web tests

Show curl response status code in tests

---

tea/include/extension.h
tea/private/extension.h
tea/src/extension.c
tea/src/sapi.c
tea/tests/extension.cc

This is the ZE support taken from #1503 
I'll push this to master, then rebase hooks, then merge in some stuff to hooks ... this is starting place ...

Tea ZE Suppport

---

tea/CMakeLists.txt

I'm cleaning up a bit in preparation for some work on the TEA SAPI for
Code Hotspots.

Run cmake-format on TEA's CMakeLists.txt

---

ext/php5/tracer_tag_propagation/tracer_tag_propagation.c
ext/php7/tracer_tag_propagation/tracer_tag_propagation.c
ext/php8/tracer_tag_propagation/tracer_tag_propagation.c
tests/ext/integrations/curl/distributed_tracing_curl_copy_handle.phpt
tests/ext/integrations/curl/distributed_tracing_curl_propagate_tags.phpt

Disable x-datadog-tags header propagation

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

Release 0.70.1

---

tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php

Service name for guzzle requests used to be reported as `host-` if (1) `DD_TRACE_HTTP_CLIENT_SPLIT_BY_DOMAIN=true` and (2) the url missed the schema, e.g. `example.com` instead of `https://example.com`.
The fix was actually done in 0.68.0 as part of https://github.com/DataDog/dd-trace-php/pull/1396, but this PR just add a test to Guzzle to make sure it is fixed in stone.

Add a test case for guzzle url no schema + split by domain

---

zend_abstract_interface/symbols/lookup.c

From PHP 7.3 onwards, zend_fetch_function is supposed to be used for function initialization.
Not using it was particularly problematic on PHP 7.3 due to opcache *relying* on the immutable function handling happening in zend_fetch_function.
Failing to do so, leads to runtime not using their own op_array copy, but instead the source function from shared memory.
This fixes the randomized tests failures under PHP 7.3.

Fix ZAI symbols on PHP 7.3+ (randomized tests failures)

---

dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/xfail_tests/8.1.list
dockerfiles/ci/xfail_tests/README.md

Use 8.1.4 in development buster images

---

dockerfiles/ci/buster/docker-compose.yml

Use latest 8.0.17 in buster images

---

tooling/bin/generate-final-artifact.sh

Fix ownership of files within release artifact tars

---

zend_abstract_interface/config/config.c
zend_abstract_interface/config/config_ini.h
zend_abstract_interface/config/php5/config_ini.c
zend_abstract_interface/config/php7-8/config_ini.c
zend_abstract_interface/config/tests/env.cc
zend_abstract_interface/config/tests/ini.cc

Supersedes #1589 with a working implementation.

Fix handling of INI and ENV changes post minit, pre runtime

---

src/Integrations/Integrations/PHPRedis/PHPRedisIntegration.php
tests/Integrations/PHPRedis/V3/PHPRedisClusterTest.php
tests/Integrations/PHPRedis/V4/PHPRedisClusterTest.php
tests/Integrations/PHPRedis/V5/PHPRedisClusterTest.php

Add RedisCluster split by host

---

README.md

Add link to compatibility requirements in README.md

---

ext/php7/configuration.h
ext/php7/ddtrace.c
ext/php7/handlers_curl.c
ext/php7/random.c
ext/php7/random.h
ext/php8/configuration.h
ext/php8/ddtrace.c
ext/php8/handlers_curl.c
ext/php8/random.c
ext/php8/random.h
tests/ext/distributed_tracing/distributed_trace_inherit_b3-single-span.phpt
tests/ext/distributed_tracing/distributed_trace_inherit_b3-single-span_no_sampling.phpt
tests/ext/distributed_tracing/distributed_trace_inherit_b3.phpt
tests/ext/integrations/curl/distributed_tracing_curl.phpt

Add B3 headers injection and extraction

---

composer.json

Add one more allow-plugins in root composer.json

---

.gitlab-ci.yml

Update link to latest released version for the reliability environment

---

.circleci/config.yml

Also %d resource ids out in language tests

---

Makefile

This fixes a serious crash that occurs if environment variables are set
in the Server API configuration (as opposed to the OS).

Update profiling to v0.7.1

---

Makefile

This works around the same PHP bug as #1670.

Update profiling to v0.7.2

---

.gitlab-ci.yml

gitlab 0.76.2

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

Release v0.77.0. See package.xml for release notes.

Release 0.77.0

---

.circleci/config.yml
Makefile
datadog-setup.php
docker-compose.yml
dockerfiles/frameworks/Makefile
dockerfiles/verify_packages/alpine/install.sh
dockerfiles/verify_packages/centos/install.sh
dockerfiles/verify_packages/debian/install.sh
dockerfiles/verify_packages/verify_tar_gz_root.sh
examples/long-running/docker-compose.yml
ext/php7/coms.c
ext/php8/coms.c
tests/ext/background-sender/background_sender_restores_capabilities.phpt
tests/ext/background-sender/background_sender_survives_setuid.phpt
tests/ext/circuit_breaker_retry_time.phpt
tests/randomized/Makefile
tests/randomized/docker/prepare.sh
tests/randomized/lib/docker-compose.yml
tests/randomized/lib/run-base-docker-compose.sh
tests/randomized/lib/templates/Makefile.scenario.template
tests/randomized/lib/templates/docker-compose.template.yml
tooling/bin/generate-final-artifact.sh
zend_abstract_interface/interceptor/php8/interceptor.c

Actual support for building arm on our CI.
Fixes #1145.
Fixes #1252.
Fixes #1659.

Build arm images in CI

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

prepare 0.78.0

---

ext/php7/ip_extraction.c
ext/php8/ip_extraction.c

memrchr has an always available equivalent under the name of zend_memrchr.

Fix compilation on MacOS

---

tea/src/sapi.c
zend_abstract_interface/hook/hook.c
zend_abstract_interface/hook/hook.h
zend_abstract_interface/hook/tests/internal/request.cc

Fix hook dynamic data zeroing when new hooks are added during hook execution

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

Prepare 0.79.0

---

ext/auto_flush.c
ext/comms_php.h
ext/coms.c
ext/coms.h
ext/configuration.h
ext/ddtrace.c
src/DDTrace/Transport/Http.php

Fix #1750 configurable max payload size

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

Release 0.80.0

---

.gitlab-ci.yml

update relenv after release

---

datadog-setup.php

When uninstalling datadog, the messaging was suggesting it was an installation instead.

Amend wording when uninstalling datadog

---

src/Integrations/Integrations/Guzzle/GuzzleIntegration.php

Fix #1762 guzzle integration not loading

Fix #1762 drop check for root span in Guzzle Integration

---

php_ddtrace.h

Seems to have been missed during cleanup of ext/phpX dirs.

Fix in-tree compilation

---

config.m4
ext/configuration.h
ext/ddtrace.c
ext/limiter/limiter.c
ext/limiter/limiter.h
ext/priority_sampling/priority_sampling.c
tests/ext/limiter/001-limiter-disabled.phpt
tests/ext/limiter/002-limiter-reached.phpt

Implement rate limiter

---

package.xml

So that they can do PECL releases in future

Add Pierre and Anil to package.xml

---

.gitlab-ci.yml

Update relenv to use 0.81.0

---

.circleci/config.yml
ext/span.c
tests/ext/sandbox-regression/dd_trace_tracer_limiter_reset_flush.phpt

Regression introduced by fb88a3444f6f8401dfd7940a46ffef42062ea19d.

Fix span limiter not being reset in long running processes

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

-  Fix span limiter not being reset in long running processes #1785

Release 0.81.1

---

profiling/README.md

This PR will add a troubleshooting section and a test section to the `README.md`

Add troubleshooting to `README`

---

tests/ext/limiter/002-limiter-reached.phpt

Fix test to make text_c_disabled pass again

---

src/DDTrace/Propagators/TextMap.php
tests/Unit/Propagators/TextMapTest.php

Extract priority sampling whenever is string or int

---

.circleci/config.yml

Retry docker images not starting in CI

---

README.md

Just add the bit php logo to the readme. 
A relicate from my hackathon

Adds php bits to the readme

---

.gitignore
Makefile
bridge/_files_integrations.php
ext/compatibility.h
ext/ddtrace.c
ext/handlers_exception.c
ext/handlers_exception.h
ext/integrations/integrations.c
ext/integrations/integrations.h
src/Integrations/Integrations/Roadrunner/RoadrunnerIntegration.php
tests/Common/WebFrameworkTestCase.php
tests/Frameworks/Roadrunner/Version_2/composer.json
tests/Frameworks/Roadrunner/Version_2/worker.php
tests/Integrations/Roadrunner/V2/CommonScenariosTest.php
tests/Integrations/Roadrunner/V2/DistributedTracingTest.php
tests/Sapi/Roadrunner/.rr.yaml
tests/Sapi/Roadrunner/RoadrunnerServer.php
tests/Unit/Integrations/IntegrationsLoaderTest.php
tests/WebServer.php

Adds a small integration for handling Roadrunner PSR7 requests and responses.

Add a Roadrunner integration

---

Makefile
bridge/_files_integrations.php
ext/integrations/integrations.c
src/Integrations/Integrations/ElasticSearch/V8/ElasticSearchIntegration.php
tests/Integrations/Elasticsearch/V8/ElasticSearchIntegrationTest.php
tests/composer.json

Instrumentation for elasticsearch 8: some namespace and classes have changed.

Add Elasticsearch 8 support

---

ext/serializer.c
tests/ext/sandbox-regression/nested_dropped_spans.phpt

Fix dropped spans causing an infinite loop

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

Release 0.82.0

---

.gitlab-ci.yml

Update the path to the latest package.

Update reliability environment with latest binary

---

profiling/README.md

This documents the time profiler a bit.

Document Wall- and CPU-time

---

src/Integrations/Integrations/Roadrunner/RoadrunnerIntegration.php

Use the HttpWorker instead of the Psr7Worker for Roadrunner for more generic usage

---

ext/ddtrace.c
tests/Common/TracerTestTrait.php
tests/ext/distributed_tracing/distributed_trace_overwrite_active_span.phpt

Fix trace_id reset in DDTrace\set_distributed_tracing_context()

---

profiling/src/profiling.rs

This PR will please clippy!
The `Profiler::prepare_sample_message` method has too many arguments so in this PR I will group all the sample information together in one struct, this also makes the API nicer IMHO.

refactor(profiling): fix clippy::too_many_arguments

---

.circleci/config.yml

Remove a temporary addition to run more system tests. 
The PR has been merged yesterday so this isn't useful anymore

Remove checkout of experimental branch in the build

---

ext/ddtrace.c
ext/span.c
ext/span.h
tests/ext/flush-autofinish.phpt
tests/internal-api-stress-test.php

Fix DDTrace\flush() with DD_AUTOFINISH_SPANS=1

---

CONTRIBUTING.md

Tiny updates following some back and forth today. 
Also removed the php 5 examples as we don't support it anymore

Small changes to the CONTRIBUTING readme

---

.gitlab-ci.yml

This updates the `LATEST_LIBRARY` version used for deployments in relenv

update latest version used for relenv

---

dockerfiles/ci/buster/build-php.sh
tests/ext/limiter/002-limiter-reached.phpt

Also mark 002-limiter-reached.phpt as timing sensitive, excluding it from valgrind

Fix 7.4 shared json buster image

---

.gitlab-ci.yml

* Change image path: from system-tests to dd-trace-java
* Remove manual trigger in order to avoid not ending checks in pull request.
* Change to a schedule job

Fix docker base image gitlab job

---

.gitlab-ci.yml
tooling/ci/download-binary-php.sh

GitLab pìpeline only launch job "tracer-base-image" on scheduled job

fix gitlab scheduled jobs

---

.gitlab-ci.yml

Why automate it when you also can do it manually :-)

Fetch the latest release from github API instead of manually updating it

---

profiling/src/profiling/mod.rs
profiling/src/profiling/stalk_walking.rs

This extracts the stalk walking code into a new module.

refactor(profiling): extract stalk walking code

---

zend_abstract_interface/interceptor/php8/interceptor.c

Turns out that many users seem to use the 8.1.2 version, it being the Ubuntu default. And Symfony seems to have embraced attributes by now, leading to numerous crashes.
Let's fix it forever now.
Fixes #1933.

Fix observing the attribute constructor on old PHP 8.0 and 8.1 versions

---

ext/hook/uhook.stub.php
ext/hook/uhook_arginfo.h

Document $begin and $end params in install_hook

---

Makefile

Point to appsec 0.7.1

---

Makefile

Update ASM to 0.7.2

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

Release v0.86.3

---

ext/ip_extraction.c
tests/ext/extract_ip_addr.phpt
tests/ext/extract_ip_addr_precedence.phpt
tests/ext/root_span_http_client_ip_duplicate_ip_headers.phpt

Update ip extraction algorithm with new headers and also removing the duplicate tags.

Update ip extraction algorithm

---

Makefile

Upgrade to the latest ASM version.

Upgrade ASM to v0.8.0

---

.circleci/config.yml

large are half the cost of xlarge, and based on the CircleCI insights, we should be very comfortably be able to downgrade.

build: downsize resource class for profiling jobs

---

Makefile

Upgrade appsec to v0.8.1

---

.gitlab/benchmarks.yml

run benches right away

---

Makefile

Upgrade ASM to v0.9.0 which includes some fixes, ruleset upgrade and WAF upgrade

Upgrade ASM to v0.9.0

---

tests/randomized/README.md

This will add a section about ASAN and how to recompile PHP with it in case you need to debug memory issues.

docs(tests): add ASAN section to randomised tests `README.md`

---

ext/version.h
package.xml
profiling/Cargo.lock
profiling/Cargo.toml
src/DDTrace/Tracer.php

Time to ship one more release :-)

Bump version to 0.88.0

---

profiling/Cargo.toml
profiling/src/lib.rs

This PR will add the `timeline` feature to the default features and compile it.

feat(profiling) compile timeline feature by default

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Add hint to remove sensitive information

Add hint to remove sensitive information

---

.circleci/continue_config.yml
docker-compose.yml
tests/randomized/lib/docker-compose.yml

pin test agent version

---

ext/configuration.h
src/Integrations/Integrations/CakePHP/CakePHPIntegration.php
src/Integrations/Integrations/CodeIgniter/V2/CodeIgniterIntegration.PHP5.php
src/Integrations/Integrations/CodeIgniter/V2/CodeIgniterIntegration.php
src/Integrations/Integrations/Laminas/LaminasIntegration.php
src/Integrations/Integrations/Laravel/LaravelIntegration.php
src/Integrations/Integrations/Lumen/LumenIntegration.php
src/Integrations/Integrations/Slim/SlimIntegration.php
src/Integrations/Integrations/Symfony/SymfonyIntegration.php
src/Integrations/Integrations/WordPress/V4/WordPressIntegrationLoader.php
src/Integrations/Integrations/Yii/YiiIntegration.PHP5.php
src/Integrations/Integrations/Yii/YiiIntegration.php
src/Integrations/Integrations/ZendFramework/V1/TraceRequest.php
src/Integrations/Integrations/ZendFramework/ZendFrameworkIntegration.php
tests/Integrations/Laravel/V8_x/HttpHideRouteTest.php

Add DD_HTTP_SERVER_ROUTE_BASED_NAMING config to enforce <method> <path> resources

---

.gitlab/benchmarks.yml

ci: do not run benchmarks in not profiling related PRs

---

Cargo.lock
ext/version.h
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

Bump version to 0.89.0

---

profiling/src/allocation.rs
profiling/src/bindings/mod.rs
profiling/src/capi.rs
profiling/src/config.rs
profiling/src/lib.rs
profiling/src/profiling/mod.rs
profiling/src/profiling/stalk_walking.rs
profiling/src/timeline.rs

This PR applies automatic suggestions from `cargo +nightly clippy --fix` as well as some manual changes that clippy could not fix magically.

refactor(profiling): apply clippy suggestions

---

ext/priority_sampling/priority_sampling.c
tests/ext/priority_sampling/invalid-regex-rule.phpt
zend_abstract_interface/uri_normalization/CMakeLists.txt
zend_abstract_interface/uri_normalization/uri_normalization.c

~Error logging pending on #2158.~ Let's defer that to later.

Add invalid regex handling for sampling rules

---

ext/priority_sampling/priority_sampling.c
tests/ext/priority_sampling/013-rule-service-mapped.phpt

This has led to confusion for users in the past.

Evaluate the service name after the service mapping for a sampling decision

---

Cargo.lock
ext/version.h
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

Preliminary: #2150 and #2157 are not merged yet.

Bump version to 0.90.0

---

Cargo.lock
profiling/src/bindings/mod.rs
profiling/src/profiling/stalk_walking.rs
profiling/src/timeline.rs

This pattern was used by multiple callers. Note that it isn't `impl ToString` because of the unsafe.

refactor(profiling): extract ZaiStringView::to_string

---

Cargo.lock

I'm not sure when exactly it happened, but our `Cargo.lock` isn't quite up-to-date.

build: update Cargo.lock

---

Makefile

Point to Appsec 0.11.0 version

Point to Appsec 0.11.0 version

---

zend_abstract_interface/config/config_ini.c
zend_abstract_interface/config/tests/decode.cc
zend_abstract_interface/interceptor/tests/interceptor.cc
zend_abstract_interface/symbols/tests/call/internal.cc
zend_abstract_interface/symbols/tests/lookup/class.cc

I found these while reviewing #2206.

Use zai_str APIs a bit more

---

profiling/src/lib.rs
profiling/src/profiling/mod.rs
profiling/src/profiling/stalk_walking.rs

Fixes many clippy lints. It's not clean quite yet, but is getting close.

fix(profiling): clippy lints

---

profiling/src/allocation.rs
profiling/src/timeline.rs

Finally we can use the [let-else](https://doc.rust-lang.org/rust-by-example/flow_control/let_else.html) syntax 😄

style(profiler): use let-else syntax

---

.circleci/continue_config.yml

Uses the new system-tests parametric scenario

update CI parametric tests

---

Cargo.lock
Cargo.toml
profiling/Cargo.toml
profiling/src/profiling/mod.rs

This upgrades libdatadog and some other dependencies, and does a small amount of fixing due to those changes.

build(profiling): bump dependencies including libdatadog v4.0.0

---

Cargo.lock
ext/version.h
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

Shipping time for the next release

Bump to version 0.91.0

---

Makefile
package.xml

Update appsec with a small patch fixing the `DD_SERVICE_NAME` configuration alias.
`package.xml` has also been updated.

Update appsec to v0.13.1

---

dockerfiles/ci/alpine_compile_extension/Dockerfile
dockerfiles/ci/buster/Dockerfile
dockerfiles/ci/centos/7/base.Dockerfile

Document why llvm is in the build images.

docs: explain minimum and nice-to-have from LLVM

---

src/Integrations/Integrations/Laravel/LaravelIntegration.php

Well, it wasn't setting anything at all. Now it will.

fix: enable auto flush for artisan commands

---

datadog-setup.php

This will add the missing INI settings to `datadog-setup.php`

feat(profiling): add exception profiling INI settings

---

datadog-setup.php

Well, the profiler is not beta anymore since quite some time already ;-)

fix(profiler) the profiler is not beta anymore

---

Makefile

Update to the latest ASM release

Update ASM to v0.14.0

---

Makefile

Point to Appsec 0.14.1

---

profiling/src/lib.rs

This was done in the early days of the move from C to Rust. The goal at the time was to avoid unsafe code, and that was one way of working around specific requirements. This is a different way, still mostly safe code, but will not leak.
Note that this wasn't a leak that mattered to anything except tooling. The goal is to soon run an NTS+ASAN build for the profiler, and this would trigger the leak sanitizer (implied by address sanitizer on Linux). This is for PROF-8286.

fix(profiling): do not leak module entry on purpose

---

Cargo.lock
appsec/CMakeLists.txt
ext/version.h
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

A small hotfix with a couple fixes.

Add release notes for 0.92.1

---

Cargo.lock
appsec/CMakeLists.txt
ext/version.h
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

ZAI config and ASM config hotfixes.

Add release notes and update versions for 0.92.2

---

components-rs/ddtrace.h
components-rs/telemetry.rs
ext/telemetry.c
tests/Integrations/Custom/Autoloaded/InstrumentationTest.php
tests/ext/telemetry/composer.phpt
tests/ext/telemetry/integration.phpt

Instead of just composer dependencies.

Report extensions used in telemetry

---

src/Integrations/Integrations/Laravel/LaravelIntegration.php
src/Integrations/Integrations/PHPRedis/PHPRedisIntegration.php
src/Integrations/Integrations/Predis/PredisIntegration.php

- Remove redis spans coming from both `PHPRedis` and `PRedis`
- Apply the auto instrumentation orphans removal to all priority sampling types of keep

Redis Span Removal and Priority Sampling Orphans Cleanup

---

src/Integrations/Integrations/DatabaseIntegrationHelper.php
tests/Integration/DatabaseMonitoringTest.php

Respect service mapping when propagating for DBM

---

src/Integrations/Integrations/PDO/PDOIntegration.php

This particular driver seems allergic to our comment-injection, and it's not monitored by DBM at all, so we'll just turn it off.

Specify the odbc driver in db.system and exclude the Ingres driver from DBM

---

Cargo.lock
ext/version.h
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

Add release notes for 0.93.0

---

Cargo.lock
appsec/CMakeLists.txt
ext/version.h
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

Release version and notes update for 0.93.1

Release notes for 0.93.1

---

src/Integrations/Integrations/IntegrationsLoader.php

Fix PHP5: The Magento Integration is not part of PHP5

---

dockerfiles/ci/xfail_tests/8.3.list
dockerfiles/ci/xfail_tests/README.md

Add xfail for Zend/tests/stack_limit/stack_limit_013.phpt on PHP 8.3

---

.github/CODEOWNERS

Otherwise release PRs need three approvals from every team, even though it's just version change.

Allow everyone to modify release files without waiting for approval from all teams

---

Cargo.lock
appsec/CMakeLists.txt
ext/version.h
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

Add release notes for 0.94.0

---

.circleci/continue_config.yml
appsec/cmake/helper.cmake
appsec/tests/fuzzer/CMakeLists.txt
appsec/tests/fuzzer/corpus_generator.cpp
appsec/tests/fuzzer/helpers.hpp
appsec/tests/fuzzer/main.cpp
appsec/tests/fuzzer/mutators.cpp
appsec/tests/fuzzer/mutators.hpp
appsec/tests/fuzzer/network.hpp

Migrate helper fuzzer tests and add CI job.
Related Jiras: [APPSEC-12167]
[APPSEC-12167]: https://datadoghq.atlassian.net/browse/APPSEC-12167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ASM] Helper fuzzer

---

appsec/cmake/helper.cmake
appsec/src/helper/client.cpp
appsec/src/helper/compression.cpp
appsec/src/helper/compression.hpp
appsec/src/helper/engine_settings.hpp
appsec/src/helper/json_helper.cpp
appsec/src/helper/network/msgpack_helpers.cpp
appsec/src/helper/parameter.cpp
appsec/src/helper/parameter.hpp
appsec/src/helper/parameter_base.hpp
appsec/src/helper/sampler.hpp
appsec/src/helper/service.cpp
appsec/src/helper/service.hpp
appsec/tests/fuzzer/CMakeLists.txt
appsec/tests/helper/compression_test.cpp
appsec/tests/helper/json_helper_test.cpp
appsec/tests/helper/parameter_test.cpp
appsec/tests/helper/sampler_test.cpp
appsec/tests/helper/service_test.cpp
appsec/third_party/CMakeLists.txt

Merge back changes

---

.circleci/continue_config.yml
appsec/recommended.json
appsec/third_party/CMakeLists.txt

Move back to having the `recommended.json` file on the repo

Fix recommended json file

---

src/Integrations/Integrations/DatabaseIntegrationHelper.php
src/Integrations/Integrations/Integration.php
tests/Integration/DatabaseMonitoringTest.php

SDBM-729
Service mapping wasn't applied to the `dddbs` tag while it should.

Fix dddbs service mapping

---

src/Integrations/Integrations/Yii/YiiIntegration.php
tests/Frameworks/Yii/Version_2_0/config/web.php
tests/Frameworks/Yii/Version_2_0/controllers/SimpleController.php
tests/Integrations/Yii/V2_0/CommonScenariosTest.php
tests/Integrations/Yii/V2_0/ModuleTest.php
tests/Integrations/Yii/V2_0/ParameterizedRouteTest.php
tests/Integrations/Yii/V2_0/YiiDetailsTest.php

Add http.route to Yii integration

Implement http.route for Yii

---

ext/integrations/exec_integration.c

Fix preproc condition in exec_integration

---

Cargo.lock
appsec/CMakeLists.txt
ext/version.h
github-actions-helpers/Build.cs
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

Bump to 0.97.0

---

Cargo.lock
profiling/Cargo.toml

This updates the cargo dependencies

build(profiler): update dependencies and pin ahash

---

Cargo.lock
profiling/Cargo.toml
profiling/src/profiling/uploader.rs

This will update to libdatadog 6.0.0

feat(profiling) update to libdatadog 6

---

appsec/recommended.json
appsec/tests/fuzzer/CMakeLists.txt
appsec/tests/helper/client_test.cpp
appsec/tests/helper/waf_test.cpp

Simple WAF and ruleset version upgrade to v1.16.0 and v1.10 respectively.

[appsec] Upgrade libddwaf and ruleset

---

ext/ddtrace.c
ext/hook/uhook_legacy.c
tests/ext/set_distributed_tracing_context_wrong_param.phpt
tests/ext/wrong-parameter-errors/DDTrace_hook_function.phpt
tests/ext/wrong-parameter-errors/DDTrace_hook_method.phpt
tests/ext/wrong-parameter-errors/DDTrace_trace_function.phpt
tests/ext/wrong-parameter-errors/DDTrace_trace_id.phpt
tests/ext/wrong-parameter-errors/DDTrace_trace_method.phpt
tests/ext/wrong-parameter-errors/dd_trace_send_traces_via_thread.phpt
tests/ext/wrong-parameter-errors/set_distributed_tracing_context.phpt

Raise API errors instead of debug logs when wrong arguments are passed

---

Cargo.lock
appsec/CMakeLists.txt
ext/version.h
github-actions-helpers/Build.cs
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

Bump to 0.98.1

---

.gitlab/benchmarks.yml
Cargo.lock
components-rs/Cargo.toml
components-rs/common.h
components-rs/ddtrace.h
components-rs/lib.rs
components-rs/sidecar.h
components-rs/sidecar.rs
components-rs/telemetry.h
components-rs/telemetry.rs
ext/telemetry.c

~Speeeed?~ Speeeed!
---
Moving dependency parsing to the sidecar including caching there.

Speed composer dependency parsing up

---

profiling/src/bindings/mod.rs

I was making some unrelated changes in this file and wanted to also adjust these things. I decided to make a separate PR so it's easier to review.

style(profiling): clean up some imports

---

.circleci/continue_config.yml
dockerfiles/ci/alpine_compile_extension/Dockerfile
dockerfiles/ci/alpine_compile_extension/build-dd-trace-php
dockerfiles/ci/alpine_compile_extension/docker-compose.yml
dockerfiles/ci/alpine_compile_extension/env-init
dockerfiles/ci/alpine_compile_extension/install-php
tooling/bin/generate-final-artifact.sh

Adds tracer and appsec zts builds for alpine.

Add zts support for alpine

---

.github/workflows/prof_asan.yml

This should fix the ASAN test, see https://github.com/actions/runner-images/issues/9491#issuecomment-1989718917

ci(profiling) fix asan test

---

tests/ext/fibers/fiber_switch_tracer_disabled.phpt

Only run Fiber test in PHP8.1+

---

Makefile

fix: micro-benchmarks job

---

src/DDTrace/Integrations/Curl/CurlIntegration.php
src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
src/DDTrace/Integrations/Integration.php
src/DDTrace/Integrations/Laminas/LaminasIntegration.php
src/DDTrace/Integrations/Laravel/LaravelIntegration.php
src/DDTrace/Integrations/LaravelQueue/LaravelQueueIntegration.php
src/DDTrace/Integrations/Memcache/MemcacheIntegration.php
src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
src/DDTrace/Integrations/MongoDB/MongoDBIntegration.php
src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
src/DDTrace/Integrations/PDO/PDOIntegration.php
src/DDTrace/Integrations/PHPRedis/PHPRedisIntegration.php
src/DDTrace/Integrations/SQLSRV/SQLSRVIntegration.php
src/DDTrace/Integrations/Slim/SlimIntegration.php
src/DDTrace/Integrations/ZendFramework/V1/TraceRequest.php
src/DDTrace/Integrations/ZendFramework/ZendFrameworkIntegration.php
tests/Integration/CurrentContextAccess/CurrentContextAccessTest.php
tests/Integration/LongRunning/LongRunningScriptTest.php
tests/Integrations/CLI/Custom/Autoloaded/NoRootSpanTest.php
tests/Integrations/Lumen/V5_2/CommonScenariosTest.php
tests/Integrations/Memcached/MemcachedTest.php
tests/Integrations/MongoDB/MongoDBTest.php
tests/Integrations/Slim/V3_12/CommonScenariosTest.php
tests/Integrations/Symfony/V3_0/TraceSearchConfigTest.php

No more PHP 5 checks in our PHP code.

Clean PHP 5 checks

---

src/DDTrace/OpenTelemetry/Context.php
src/DDTrace/OpenTelemetry/Span.php
src/DDTrace/OpenTelemetry/SpanBuilder.php
src/DDTrace/OpenTelemetry/SpanContext.php
tests/OpenTelemetry/Integration/InteroperabilityTest.php

- Don't build an attributes builder instance since we don't apply attributes limit anyway
- Don't build a new tracestate instance if the tracestate didn't change
- More efficient condition checks

Slightly Improve OTel Performances

---

Cargo.lock
appsec/CMakeLists.txt
ext/version.h
github-actions-helpers/Build.cs
package.xml
profiling/Cargo.toml
src/DDTrace/Tracer.php

0.99 soon will overflow to 1.0 :-)

Release 0.99.0

---

ext/ddtrace.stub.php

Be explicit about its limitations.

Add note about update_span_duration semantics

---

components-rs/common.h
components-rs/sidecar.rs
components-rs/telemetry.h
components-rs/telemetry.rs
ext/auto_flush.c
ext/sidecar.h

And include DataDog/libdatadog#397.

Update to match MaybeError changes in libdatadog

---

appsec/src/extension/tags.c
appsec/tests/extension/ancillary_tags.phpt

Update the list of collected headers on ASM.
APPSEC-52618

Update asm collected headers

---

appsec/src/extension/tags.c
appsec/tests/extension/headers_collection_01.phpt
appsec/tests/extension/headers_collection_02.phpt
appsec/tests/extension/headers_collection_03.phpt
appsec/tests/extension/headers_collection_04.phpt
appsec/tests/extension/headers_collection_05.phpt
appsec/tests/extension/headers_collection_06.phpt
appsec/tests/extension/headers_collection_07.phpt
appsec/tests/extension/headers_collection_08.phpt
appsec/tests/extension/headers_collection_09.phpt
appsec/tests/extension/headers_collection_10.phpt
appsec/tests/extension/headers_collection_11.phpt
appsec/tests/extension/headers_collection_12.phpt
appsec/tests/extension/headers_collection_13.phpt

Collect all ASM headers when a user event is triggered
APPSEC-52902

Add all asm headers on user events

---

tests/randomized/README.md
tests/randomized/app/src/RandomizedTests/RandomExecutionPath.php

Update randomized tests `README.md`.
Add a new section to debug a CI failing job

Update randomized tests `README.md`

---

CONTRIBUTING.md
LIBDATADOG.md

Provide documentation to integrate new features from libdatadog.

Add guide to add new libdatadog features.

---

components-rs/common.h
components-rs/ddtrace.h
components-rs/sidecar.h
components-rs/sidecar.rs
components-rs/telemetry.rs
ext/telemetry.c

Rename in sidecar from interface to service.

Update to maintain compatibility with libdatadog

---

package.xml

Derick activated my PECL account, so adding myself to the `package.xml` to make sure it does not get removed. https://news-web.php.net/php.pecl.dev/17585

Add myself as a lead for pecl

---

dockerfiles/verify_packages/alpine/install.sh

Fix alpine:latest verify job

---

profiling/src/exception.rs

docs(profiling): document `ddog_php_prof_generator_throw`

---

package/post-install.sh

Should fix https://github.com/DataDog/dd-trace-php/issues/2704

Fix PHP binary detection in package post-install script

---

docker-compose.linux.override.yml
dockerfiles/dev/linux_entrypoint.sh

Our Docker dev setup is mainly designed for macOS.
This PR should help Linux users (as I am now), and change nothing for macOS users.

Improve Linux dev setup

---

profiling/tests/correctness/allocations.json
profiling/tests/correctness/exceptions.json
profiling/tests/correctness/exceptions_zts.json
profiling/tests/correctness/strange_frames.json
profiling/tests/correctness/time.json
profiling/tests/correctness/timeline.json

This PR ensures compatibility with https://github.com/DataDog/prof-correctness/pull/43

ci(profiling) compatibility with upcoming prof correctness

---

.circleci/continue_config.yml
dockerfiles/ci/centos/7/base.Dockerfile
dockerfiles/ci/centos/7/download-src.sh
dockerfiles/ci/centos/7/php-7.0/configure.sh
dockerfiles/ci/centos/7/php-7.1/configure.sh
dockerfiles/ci/centos/7/php-7.2/configure.sh
dockerfiles/ci/centos/7/php-7.3/configure.sh
dockerfiles/ci/centos/7/php-7.4/configure.sh
dockerfiles/ci/centos/7/php-8.0/configure.sh
dockerfiles/ci/centos/7/php-8.1/configure.sh
dockerfiles/ci/centos/7/php-8.2/configure.sh
dockerfiles/ci/centos/7/php-8.3/configure.sh

centos 7 is EOL and mirrorlist.centos.org does not resolve anymore

Fix centos 7 Dockerfile

---

ext/sidecar.c

Fix env&version tags leaking in metrics

---

appsec/src/helper/subscriber/waf.cpp

Add more logs around schema extraction

---

.circleci/continue_config.yml
loader/bin/check_glibc_version.sh
loader/bin/test.sh

[SSI] Add a check on the max glibc version

---

loader/dd_library_loader.c
loader/tests/functional/test_telemetry_php5.php

Reference: https://docs.google.com/document/d/1kH8wnGDBWJcGw7s5J9dl2McG9H7-pvl0gA6NL0IJ3BQ/edit

[loader] Improve SSI telemetry compatibility

---

ext/hook/uhook.c
tests/ext/sandbox/install_hook/replace_generator.phpt
zend_abstract_interface/interceptor/php8/interceptor.c

Required for the PHP 8.1+ OpenAI integration.

Make generators replaceable

---

.gitlab-ci.yml

Add new system-tests/onboarding on gitlab pipeline.
We are going to tests single step instrumentation using the OCI images and the datadog installer

Add system-tests/onboarding tests

---

.gitlab-ci.yml

Switch to SSI stable pipeline

---

dockerfiles/ci/buster/php-8.3/suppr.txt

Add more LSAN suppressions for use_tls=0

---

package.xml

Add myself as PECL package maintainer

---

tests/Common/SnapshotTestTrait.php

e.g. https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/17131/workflows/6cee4414-3220-49a7-80c4-1e99f51f4ff9/jobs/4974800

Fix OpenAI flaky tests

---

datadog-setup.php

e.g. C:\Program Files\php\php.exe

Fix setup with spaces in path to php binary

---

.circleci/continue_config.yml
dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/centos/install.sh
dockerfiles/verify_packages/installer/test_install_on_plesk.sh

Fix verify_centos CI jobs + remove unused job verify_centos_6 + fix plesk install test

---

datadog-setup.php

only warn on missing `json` extension

---

datadog-setup.php

installer: remove appsec.helper_launch; fix descs

---

Makefile
tests/Benchmarks/Integrations/WordPressBench.php
tests/Benchmarks/composer.json
tests/bootstrap_phpbench.php
tests/composer.json
tests/phpbench-opcache.json
tests/phpbench.json

This PR fixes the microbenchmarks (`benchmarks-tracer` GitLab job); or at least, the [candidate](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-php/-/jobs/618346397#L4070) run is OK as I'm writing this PR description.

fix: MicroBenchmarks Failures

---

dockerfiles/ci/buster/php-8.3/suppr.txt
tests/randomized/analyze-results.php
tests/randomized/docker/buster.Dockerfile
tests/randomized/docker/centos.Dockerfile
tests/randomized/docker/prepare.sh
tests/randomized/docker/run.sh

Make randomized tests green again!
There may still be some I/O related issues in prepare step, but this should cover most of them.
Also collect strace in non-asan tests to have a bit of an insight what goes wrong, when things go wrong.

Improve on randomized tests flakiness

---

.gitlab/download-circleci_artifact.sh

Make the GitLab CI workflow work when triggered by tags

---

ext/sidecar.c
tests/Common/SnapshotTestTrait.php
tests/Common/TracerTestTrait.php
tests/Integrations/OpenAI/OpenAITest.php
tests/ext/crashtracker_segfault.phpt
tests/ext/includes/request_replayer.inc
tests/ext/request-replayer/dd_trace_exception_span_event.phpt

Improve tests stability

---

.circleci/continue_config.yml
loader/php_dd_library_loader.h

Loader: Use the same version number as for other extensions

---

benchmark/runall.sh

Fix tea file not being found on the artefacts of the benchmarks runs

Fix benchmarks

---

.circleci/continue_config.yml

Prefix system tests env vars to not conflict with local dev env vars.

chore: prefix system tests env vars

---

src/DDTrace/Integrations/MongoDB/MongoDBIntegration.php

Fix #2869
Fix #2873
- (Courtesy of @bwoebi)

fix(mongodb): Deprecated exception in v1.20+

---

.circleci/continue_config.yml
appsec/src/extension/helper_process.c
appsec/src/extension/helper_process.h
appsec/tests/extension/report_backtrace_01.phpt
appsec/tests/extension/report_backtrace_05.phpt
appsec/tests/extension/root_span_add_tag.phpt

Fix failing appsec tests on pipeline

---

dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/installer/test_alpine_zts_no_zend_signals.sh
ext/threads.c

I seem to have taken care about the globals, but missed zend_signal_handler_unblock.
Also adding a test for that scenario.

Support build with disabled zend signals

---

zend_abstract_interface/interceptor/php8/interceptor.c

I.e. destroyed without clean finish.

Fix crash when yielding from generators are destroyed

---

README.md

[README.md] Fix minimal PHP version badge

---

.circleci/continue_config.yml
Makefile
docker-compose.yml
ext/integrations/integrations.c
ext/integrations/integrations.h
src/DDTrace/Integrations/GoogleSpanner/GoogleSpannerIntegration.php
tests/Integrations/GoogleSpanner/GoogleSpannerIntegrationTest.php
tests/Integrations/GoogleSpanner/composer.json
tests/Integrations/GoogleSpanner/dummy_credentials.json
tests/Integrations/GoogleSpanner/setup-gcloud.sh
tests/Integrations/GoogleSpanner/setup-spanner-emulator.sh
tests/snapshots/tests.integrations.google_spanner.google_spanner_integration_test.test_database.json
tests/snapshots/tests.integrations.google_spanner.google_spanner_integration_test.test_instance.json
tests/snapshots/tests.integrations.google_spanner.google_spanner_integration_test.test_query.json
tests/snapshots/tests.integrations.google_spanner.google_spanner_integration_test.test_transaction.json

Related to #2916
---
I tried making this PR in copilot workspace, but I haven't been able to test it.
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/DataDog/dd-trace-php/issues/2916?shareId=80a1a2c5-4b22-4f75-9c86-3e41c60e279b).

Add Google Spanner integration

---

Makefile
dockerfiles/ci/buster/build-extensions.sh

Add the grpc extension for the google spanner integration

---

src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
tests/Integrations/Mysqli/MysqliTest.php

Add `mysqli_real_query` function  to MysqliIntegration.
Related to https://github.com/DataDog/dd-trace-php/issues/2963

Add mysqli_real_query to MysqliIntegration

---

dockerfiles/ci/buster/Dockerfile
dockerfiles/ci/buster/build-extensions.sh

Adds the AMQP extension and its dependency in preparation of some future, upcoming work related to #2324

chore: Add the amqp extension to the buster images

---

profiling/src/timeline.rs

cleanup(profiling) apply cargo fmt

---

profiling/README.md

Update `README.md` in regards to ZTS support

---

tests/ext/telemetry/integration_filesystem_01.phpt
tests/ext/telemetry/integration_filesystem_02.phpt
tests/ext/telemetry/integration_filesystem_03.phpt
tests/ext/telemetry/integration_filesystem_04.phpt

Fix flaky appsec tests

---

loader/dd_library_loader.c
loader/php_dd_library_loader.h
loader/tests/functional/includes/assert.php
loader/tests/functional/includes/autoload.php
loader/tests/functional/test_ddtrace_already_loaded.php
loader/tests/functional/test_telemetry_complete.php
loader/tests/functional/test_telemetry_error.php
loader/tests/functional/test_telemetry_php5.php

https://datadoghq.atlassian.net/browse/INPLAT-272

[loader] Add 'library_entrypoint.start' metric

---

ext/handlers_signal.c

Block signals for sqlsrv_connect function

---

tests/api/Unit/UserAvailableConstantsTest.php

This will fix `test_api_unit` failures currently happening on `master`.

fix: `UserAvailableConstantsTest::testAllTypesAreTested`

---

tests/api/Unit/UserAvailableConstantsTest.php

Update types used in `testAllTypesAreTested`

---

appsec/src/helper/helper.version

Fix build of appsec helper with llvm's linker

---

src/DDTrace/Integrations/Predis/PredisIntegration.php
tests/Integrations/Predis/Latest/PredisTest.php

Fixes https://github.com/DataDog/dd-trace-php/issues/3097
I think Predis was simply forgotten at the time of the implementation, so here is a proposition.

fix: Missing Predis Service Override

---

profiling/src/allocation/allocation_ge84.rs
profiling/src/allocation/allocation_le83.rs
profiling/src/io.rs

style(prof): `cargo +nightly fmt` and some minor docs fixes

---

ext/compatibility.h
ext/ddtrace.c
ext/ddtrace_arginfo.h

With the newest gen_stub.php on master ZSTR_PARENT is a thing, and we have to support it.

Support ZSTR_PARENT known_string

---

.github/workflows/add-asset-to-gh-release.yml

This fixes the runner tag as documented and should use GitHub large runners for that job.

fix(ci): fix runner tag

---

appsec/src/extension/configuration.c
ext/configuration.c

Enable the sidecar sender by default on AWS lambda

---

src/DDTrace/OpenTelemetry/Context.php

fix: OTel 7.4 Compatibility

---

src/DDTrace/Integrations/Ratchet/RatchetIntegration.php

This aligns with the serverless definition.

Fixup span pointer direction of RatchetIntegration

---

ext/hook/uhook.c
ext/integrations/integrations.c
ext/serializer.c
tests/ext/sandbox-prehook/exception_error_log.phpt
tests/ext/sandbox-prehook/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
tests/ext/sandbox/die_in_sandbox.phpt
tests/ext/sandbox/exception_error_log.phpt
tests/ext/sandbox/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
tests/ext/sandbox/fatal_errors_ignored_in_tracing_closure.phpt
tests/ext/sandbox/hook_function/posthook_exceptions_04.phpt
tests/ext/sandbox/hook_function/prehook_exceptions_02.phpt
tests/ext/sandbox/hook_function/prehook_exceptions_04.phpt
tests/ext/sandbox/hook_method/prehook_exceptions_02.phpt
tests/ext/sandbox/install_hook/install_hook_return_by_ref.phpt
tests/ext/telemetry/integration_runtime_error.phpt

And reduce profiler notify to debug level.

Show actual file and line for occurrence of exceptions as well

---

appsec/src/extension/configuration.h
package.xml

Reverts DataDog/dd-trace-php#3082

Revert "Enable RASP by default"

---

loader/tests/functional/fixtures/stable_config/default.yaml
loader/tests/functional/test_profiling_and_appsec_can_be_enabled.php

One more stable config test with the 3 extensions loaded

SSI: test that stable config is applied with tracer, profiling and AppSec extensions loaded

---

dockerfiles/ci/xfail_tests/8.1.list
dockerfiles/ci/xfail_tests/8.2.list
dockerfiles/ci/xfail_tests/8.3.list
dockerfiles/ci/xfail_tests/8.4.list
tests/Appsec/Mock.php

Fix RASP related test failures

---

tooling/tested_versions/create_or_update_supported_versions_pr.sh

Handle existing branch for supported versions PR

---

.gitlab/prepare-oci-package.sh
tooling/bin/generate-ssi-package.sh

Store debug symbols in the SSI archive

---

appsec/src/extension/ddtrace.c

This fixes symbol conflicts with SSI and manual extension installation.

Use the ddtrace handle instead of dlopen(NULL)

---

.gitlab/append-build-id.sh

Fix pipelines for gitlab tags

---

ext/exception_serialize.c

The arena is otherwise not destroyed/nulled and will leak across requests.

Fix exception serialize arena cleanup

---

loader/compat_php.c
loader/config.m4
loader/dd_library_loader.c
loader/dd_library_loader_module.c
loader/php_dd_library_loader.h
loader/tests/functional/fixtures/opcache_jit.php
loader/tests/functional/test_incompatibility_jit.php
loader/tests/functional/test_phpinfo.php

[loader] Add injection information to phpinfo output for the SSI loader

---

profiling/Cargo.toml
profiling/rust-toolchain.toml

fix(profiler): bump Rust version

---

ext/ddtrace.h
ext/handlers_http.h
ext/telemetry.c
tests/ext/startup_logging.phpt
tests/ext/startup_logging_json.phpt
tests/ext/telemetry/config.phpt

Fixes #3322.
Also fix some CI issues.

Fix trailing ; in tracestate
