composer.json

This PR
💁‍♂️ For reference, see https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands:
>**Note**: Before executing scripts, Composer's bin-dir is temporarily pushed on top of the PATH environment variable so that binaries of dependencies are easily accessible. In this example no matter if the `phpunit` binary is actually in `vendor/bin/phpunit` or `bin/phpunit` it will be found and executed.

Fix: Composer resolves binaries itself

---

src/DDTrace/Transport/Http.php
tests/Integration/Transport/HttpTest.php

When flushing traces, if everything work as expected, a "OK" can be present in the response; even in a `terminate` method for Laravel. In case of an API this will prevent the client to correctly parse the output.

Prevent curl to print the response in STDOUT

---

composer.json

https://github.com/symfony/polyfill notes that "When using Composer to manage
your dependencies, you should not require the symfony/polyfill package, but the
standalone ones"; also see https://github.com/DataDog/dd-trace-php/issues/19

Remove symfony/polyfill from composer.json

---

tests/Integration/Transport/HttpTest.php
tests/Unit/Encoders/JsonTest.php
tests/Unit/Propagators/TextMapTest.php
tests/Unit/ScopeManagerTest.php
tests/Unit/ScopeTest.php
tests/Unit/SpanContextTest.php
tests/Unit/SpanTest.php
tests/Unit/TimeTest.php
tests/Unit/TracerTest.php
tests/Unit/Transport/HttpTest.php

This PR
💁‍♂️ This will make upgrading to newer versions of `phpunit/phpunit` (perhaps if support for PHP 5.6 is dropped) easier.

Enhancement: Use forward compatibility layer of phpunit/phpunit

---

composer.json

This PR
💁‍♂️ For reference, see https://getcomposer.org/doc/articles/versions.md.

Fix: Use caret operator where applicable

---

composer.json

This PR
💁‍♂️ For reference, see https://getcomposer.org/doc/04-schema.md#prefer-stable.

Fix: Prefer stable dependencies

---

src/DDTrace/ScopeManager.php
tests/Unit/ScopeManagerTest.php

In its state the scope manager cannot manage more than one scope because `unset` will preserve the keys. I replaced `unset` by `array_splice` which does the same thing but recompute the array keys.
ping @vlad-mh @palazzem

Fix ScopeManager fail to manage multiple scopes

---

README.md

Fix: Apply further fixes to examples

---

src/DDTrace/Encoders/Json.php
tests/Unit/Encoders/JsonTest.php

If for some reason the `json_encode` step fails, the encoder will build an invalid JSON output. As a fix I ignored all invalid spans from the JSON output.
It is something we want to log to inform the developer I think. It happened to me when I tried to send as tags all my SQL bindings. It turns out that my primary keys are binary encoded GUID.
ping @vlad-mh @palazzem

Fix JSON encoding for malformed strings

---

src/DDTrace/Propagators/TextMap.php

Fix: Remove unnecessary continue statement

---

composer.json
src/DDTrace/Transport.php
src/DDTrace/Transport/Noop.php

Fix: Remove dependency on guzzlehttp/psr7

---

src/DDTrace/Encoders/Json.php
src/DDTrace/Encoders/Noop.php
src/DDTrace/Transport/Http.php
tests/Unit/Encoders/JsonTest.php

Follow-up to #17 - pass the $logger to the Encoder, and if there's an error encoding JSON, log it at a debug level. If others like the LoggerAwareTrait pattern we could switch the Transport to use it as well. I'm not 100% happy with this since if you call Encoder methods yourself you aren't guaranteed to have a Logger, though. But passing $logger directly to the encodeTraces() method, while expedient, is almost certainly wrong.

Set $logger for the Encoder class, and log errors encoding JSON

---

.phpcs.xml
composer.json
src/DDTrace/Tracer.php
tests/Integration/Transport/HttpTest.php
tests/Unit/ScopeManagerTest.php
tests/Unit/TracerTest.php
tests/Unit/Transport/HttpTest.php

`phpcs` was used with both `Zend` and `PSR2` however only PSR2 was effectively used.
This PR instead uses PSR12 (a newer PSR2 with changes that are still compatible with our codebase).
In addition it adds my personal Favorites of disallowing `Todo` and `Fixme` comments.
With `.phpcs.xml` linting now also correctly works with VS Code extension PHP linter.

Fix tiny misconfiguration of phpcs, and add defaults in .phpcs.xml file

---

.circleci/config.yml
.editorconfig
.phpcs.xml
README.md

CircleCI is able to process JUnit reports to aggregate time spent on each test case as well as improve the presentation of errors in tests and lints 
This PR:
- moves linting as a separate step. As there is no need to duplicate it for different PHP versions or stop testing because small linting problem happened
- adds EditorConfig linting to make sure all files are properly indented
- Uses JUnit formatter for tests, and both EC and PHP lints.
- cleans up circleci configuration to reduce duplication and introduce caching

Report Tests and Linting using JUnit reporter so that CircleCI can better help pinpointing failed tests/lints

---

src/DDTrace/ScopeManager.php

Enhancement: Improve legibility of ScopeManager

---

tests/Integration/Transport/HttpTest.php
tests/Unit/Encoders/JsonTest.php

Fix: Use more appropriate assertions

---

.circleci/config.yml

Fix: Actually make use of anchor

---

composer.json

Trying to fix problems installing without having to override minimum-stability.

Update opentracing provides version, and specify that the dep is beta

---

src/DDTrace/Span.php
src/DDTrace/Tracer.php
tests/Unit/SpanTest.php
tests/Unit/TracerTest.php

This PR
💁‍♂️ I ran
```
$ composer global require friendsofphp/php-cs-fixer
```
and then
```
$ php-cs-fixer fix src --rules=ordered_imports
$ php-cs-fixer fix tests --rules=ordered_imports
```

Fix: Keep imports sorted

---

README.md

In the Transport\Http it is using 'endpoint' while in readme it is still 'endpoint_url'

Fixed inconsistency in README.md

---

src/DDTrace/SpanContext.php

The OpenSSL CSPRNG is [not fork safe](https://wiki.openssl.org/index.php/Random_fork-safety) and was the [reason behind the duplicate-UUID's issue](https://benramsey.com/blog/2016/04/ramsey-uuid/#when-uuids-collide) in [`ramsey/uuid`](https://github.com/ramsey/uuid). This PR replaces the OpenSSL CSPRNG's with the [fork-safe CSPRNG in PHP 7](http://php.net/csprng). This is also backwards compatible with PHP 5.6 since this lib includes the `paragonie/random_compat` CSPRNG polyfill via `symfony/polyfill-php70`. :)

Fix: Replace the OpenSSL CSPRNG with a fork-safe CSPRNG

---

src/DDTrace/Span.php

The `OpenTracing\SpanContext` is not referenced in this file. :)

Remove unused namespace import

---

tests/Unit/TraceOverrideMethodTest.php

This PR primarily adds skip logic to the unit tests that require `ext/ddtrace`.  I also made a few other tweaks:
1. Removed an unused namespace
2. Renamed the class to match the file name (which conforms to the other tests)
3. Tweaked the wording of the comment
I've got a couple more PR's coming your way if that's cool. :)

Fix: Skip ddtrace unit tests if the ddtrace extension is not loaded

---

.gitattributes

When you install `dd-trace-php` with composer, all the files in the repo (including the tests and c files) are copied into the `vendor/` directory.
This PR introduces a `.gitattributes` file to "blacklist" files that should not be downloaded when installing `dd-trace-php` with composer. This makes for a much lighter download.
One caveat that we'd need to discuss is that this change also impacts `git archive`:
```bash
git archive --format zip --output ../export.zip [branch-name]
```
In this example, `export.zip` would also not contain any of the blacklisted files. This also applies to downloading a zip of the repo from GitHub. So the only way to get the `ddtrace` extension that was just added in #55, would be to do a `git clone` which I'm not sure is the desired outcome.
For this reason, …

Add lighter downloads when installing from composer

---

src/ext/dispatch_compat_php5.h

Due to missing `static` keyword, the symbols from `.h` inlineable functions were created in every object file compiled from source that included that `.h` file.
Issue was surfaced by compiling the extension on Debian stretch with GCC 4.9.2

Fix compilation in older GCC versions

---

src/DDTrace/Integrations/LaravelProvider.php

Updated default Laravel App Name from `symfony` to `laravel` in the service provider

Updated default Laravel App Name

---

tests/ext/overriding_construct.phpt

(it does. just needed to verify on 5.6 and figured it's a good thing to include)

Tiny test to verify that tracing __construct works

---

src/ext/ddtrace.c
src/ext/dispatch.c
src/ext/dispatch_setup.c

Current import paths, caused the extension not to compile successfully on Alpine3.4 and Ubuntu16.04
This PR fixes that problem.

Standardize import paths

---

.circleci/config.yml
composer.json

Makes using code instrumented with DD library a bit nicer to work on workstations where this extension is not installed.

Remove dd extension from required extensions in composer.

---

.circleci/config.yml
tests/Integration/Common/IntegrationTestCase.php
tests/Integration/Integrations/MemcachedTest.php
tests/Integration/Integrations/PredisTest.php

**Blocked by #102**
This PR just rename the integration tests base method `withTracer` to `isolateTracer` to make naming more expressive. At the same time, after rebasing on master, we also adapted a few lines of code to be compatible with php 5.4.

Rename withTracer test method to isolateTracer

---

src/DDTrace/Integrations/LaravelProvider.php

After a lot of head scratching and not reading the logs... (I know)
I noticed that when you leave the `config('app.name')` value empty in your app no traces are being sent since it needs to have a non-empty value. So I made sure the app name does return a non-empty value so traces won't be stopped by that :)

Laravel: Prevent traces not sent when app name is empty

---

src/DDTrace/Integrations/LaravelProvider.php

Thanks to @Sh4d1 for the clean explanation in #115 and for providing part of the solution in #116. Really appreciated.

Improve laravel pipeline tracing

---

DDMakefile
docker-compose.yml
dockerfiles/debug_php-5.6/Dockerfile
src/ext/debug.h
src/ext/dispatch.c
src/ext/dispatch_compat_php5.c
tests/Integration/Integrations/MemcachedTest.php
tests/Integration/Integrations/PDOTest.php
tests/Integration/Integrations/PredisTest.php

Fix 5.6 instrumentation dispatch bugs. 
+ reenable tests disabled for php 5.6
+ add dockerfiles that build debug version of PHP - extremely useful for tracing

Bugfixes for PHP 5.6

---

src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php

Fix import of secondary integrations in Laravel and move appropriate tracing logic from register to boot method

---

src/ext/dispatch_compat_php7.c

The closures in PHP 7 aren't being freed. When running the following snippet of PHP:
```php
dd_trace('strlen', function (...$args) {
// Do stuff
});
```
In debug mode, PHP generates the following warning:
```
[Tue Nov 20 08:34:45 2018]  Script:  '%s/foo.php'
%s/Zend/zend_closures.c(451) :  Freeing 0x%d (%d bytes), script=%s/foo.php
=== Total 1 memory leaks detected ===
```
This PR fixes this particular memory leak. This also might be tangentially related to issue #119, but that's just a guess. :)

[Fix] Memory leak with closures in PHP 7

---

src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
src/DDTrace/Obfuscation.php
tests/Integration/Integrations/Memcached/MemcachedTest.php
tests/Unit/ObfuscationTest.php

Since Memcached keys can contain secrets and the keys aren't obfuscated by the dd-agent, this will obfuscate the keys before hitting the dd-agent. :)

Add key obfuscation to Memcached integration

---

src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php

The response in the event is not guaranteed to be an instance of `Illuminate\Http\Response` so it shouldn't use the status method. If using any of the Symfony responses this generates an error.
```
Symfony\Component\HttpFoundation\BinaryFileResponse
Symfony\Component\HttpFoundation\JsonResponse
Symfony\Component\HttpFoundation\RedirectResponse
Symfony\Component\HttpFoundation\StreamedResponse
```

Use the HttpFoundation method to get the status code

---

.circleci/config.yml
docs/getting_started.md
src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
src/DDTrace/Integrations/PDO/PDOIntegration.php
src/DDTrace/Integrations/Predis/PredisIntegration.php
src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
src/DDTrace/Span.php

The problem is that in specific conditions we may not have a `DDTrace\Span` and in place of it we get an `OpentTracing\NoopSpan` which just implement the interface `OpenTracing\Span` => exception.

[core] Remove Span::setResource() which is not part of OpenTracing\Span interface

---

src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php

It is common on servers to not populate $_ENV, so `getenv()` is a more
reliable way to check an env var.
See: https://stackoverflow.com/questions/3780866/why-is-my-env-empty/27077452#27077452

SymfonyBundle: Use getenv() to get env variable

---

.circleci/config.yml
README.md
composer.json

Part of the build checks include static analysis but there's no way to run the analyzer locally before pushing up a PR without manually installing PHPStan globally and running it with the settings from CircleCI.
This PR includes PHPStan in the dev dependencies and adds a custom Composer command to run it with the same settings as CircleCI:
$ composer static-analyze
As a side note - it might be worth revamping the CONTRIBUTING.md docs as bit. We could move all the testing/linting/container setup docs from the main README so that the README is less cluttered and easier for non-contributors to get dd-trace-php installed in their project. Does that sound reasonable? :)

Make PHPStan available to contributors

---

src/ext/ddtrace.c
src/ext/ddtrace.h

This PR changes the existing `phpinfo()` output from the default...
...to a branded version with links to start a free trail:
This also affects the display of `php -i`:
Gotta get that branding on! :D I just wanted to confirm that this display conforms to the [logo style guide](https://www.datadoghq.com/about/press/resources/) or if we need to use the white logo instead in this context.
Also - I don't know why the default behavior from the template extension uses `php_info_print_table_header()` to display the extension-enabled status, but other extensions use `php_info_print_table_row()`. So this PR also changes that display to conform to the same style as other extensions. :)

[ext/ddtrace] Add branding on PHP info output

---

src/ext/ddtrace.c

This should fix the ZTS builds in 5.6. We don't need any `#if`'s for PHP 7 since all the `TSRMLS_*` macros exist in PHP 7 for BC. :)

Fix PHP 5.6 ZTS builds

---

CHANGELOG.md
src/DDTrace/NoopSpan.php
src/DDTrace/Span.php
src/DDTrace/SpanInterface.php
src/DDTrace/Tracer.php
tests/Unit/TracerTest.php

*Problem*
`DDTrace\Span` implements `OpenTracing\Span` interface and adds methods which are not part of the interface, e.g. `setError()`, `setRawError()` and until a few days ago `setResource()` (which has been recently removed). Such methods are used in our integrations.
`DDTrace\Tracer` when should return a `NoopSpan` returned the one from `OpenTracing` which misses such methods, causing ddtrace code to crash in integrations where such additional methods are used.
*Solution*
While the final solution will involve a refactor of the way we support `OpenTracing` and how we access our tracer, for now we just make sure that when the `DDTracer\Tracer` is not enabled it will return a `DDTrace\NoopSpan` (which exposes the all the required methods) in place of a `OpenTracing\NoopSpan`.

Tracer returning DDTrace\NoopSpan when in noop mode

---

.composer/.gitignore
CHANGELOG.md
docker-compose.yml
src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
tests/Integration/Frameworks/Laravel/Version_5_7/tests/Integration/PipeTracingTest.php
tests/Integration/Frameworks/Laravel/Version_5_7/tests/Integration/PipelineTracingTest.php

Refer to #157 for an explanation of the issue.

Laravel pipelines tracer supporting configurable handler method.

---

.github/PULL_REQUEST_TEMPLATE.md

The markdown url used incorrect format

Fix GitHub PR template link

---

CHANGELOG.md
src/DDTrace/Configuration.php
src/DDTrace/Configuration/AbstractConfiguration.php
src/DDTrace/Configuration/EnvVariableRegistry.php
src/DDTrace/Configuration/Registry.php
src/DDTrace/StartSpanOptionsFactory.php
tests/Unit/BaseTestCase.php
tests/Unit/Configuration/EnvVariableRegistryTest.php
tests/Unit/StartSpanOptionsFactoryTest.php

This PR adds the possibility to enable and disable distributed tracing and priority sampling

Possibility to enable/disable distributed tracing and priority sampling

---

CHANGELOG.md
phpunit.xml
src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
tests/bootstrap.php

Quite embarrassingly I [pushed up a feature](https://github.com/DataDog/dd-trace-php/pull/161/files#diff-309a34982b1553d403e515fb7c6fc696R35) that generated errors in `E_STRICT` mode. The tests passed because `E_STRICT` errors were ignored by default. This PR ensures all errors are reported so future PR's don't introduce these types of bugs.
Also, this PR fixes all the `Undefined offset: 0` errors that were being generated by the `ElasticSearch` integration. :)

Report all errors for unit tests

---

CHANGELOG.md
docs/getting_started.md
src/DDTrace/Configuration.php
src/DDTrace/Configuration/AbstractConfiguration.php
src/DDTrace/Configuration/EnvVariableRegistry.php
src/DDTrace/Configuration/Registry.php
src/DDTrace/Integrations/Curl/CurlIntegration.php
src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
src/DDTrace/Integrations/Guzzle/V5/GuzzleIntegration.php
src/DDTrace/Integrations/Integration.php
src/DDTrace/Integrations/IntegrationsLoader.php
src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
src/DDTrace/Integrations/PDO/PDOIntegration.php
src/DDTrace/Integrations/Predis/PredisIntegration.php
src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
src/DDTrace/StartSpanOptionsFactory.php
tests/Integration/Integrations/Curl/CurlIntegrationTest.php
tests/Integration/Integrations/Elasticsearch/V1/ElasticSearchIntegrationTest.php
tests/Integration/Integrations/Guzzle/v5/GuzzleIntegrationTest.php
tests/Integration/Integrations/Memcached/MemcachedTest.php
tests/Integration/Integrations/Mysqli/MysqliTest.php
tests/Integration/Integrations/PDO/PDOTest.php
tests/Integration/Integrations/Predis/PredisTest.php
tests/Unit/Configuration/EnvVariableRegistryTest.php
tests/Unit/ConfigurationTest.php
tests/Unit/Integrations/IntegrationsLoaderTest.php

This PR adds the possibility to have a unique and safe way to load all the libraries (not frameworks) integrations and to disable specific ones by means of env variable.

Let autoload all integrations and disable specific ones

---

CHANGELOG.md
docs/getting_started.md
src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php

This PR adds loose support for [Lumen](https://lumen.laravel.com/) via the Laravel service provider. It also updates the docs with Lumen integration instructions and updates the Laravel docs to point to the correct service provider locations.
It should be noted that this doesn't offer "official" support for Lumen (with integration tests for Lumen as well as Lumen-scoped tags, etc) but this small change will at least make the Laravel service provider compatible with Lumen. :)

Add loose support for Lumen

---

CHANGELOG.md
src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php

We add a duplicate registration of the shutdown hook where we flush the traces. On the second call the the tracer finds the curl span from the previous curl request to the agent a flushes it.
As a immediate remedy we remove the duplicate shutdown hook registration.
In the long term we may prefer to isolate the registration of the shutdown hook function to a separate function, so that it will be easier to mock such call in test and make sure that it is only executed once.

Agent calls traced when using Symfony 3 integration

---

README.md

After a chat with Matt, he suggested breaking up the installation/instrumentation instructions and making them a bit clearer in the getting-started guide. :)

Add "Instrumentation" section to the getting-started docs

---

CHANGELOG.md
src/DDTrace/Encoders/Json.php
src/DDTrace/SpanContext.php
tests/Unit/Encoders/JsonTest.php
tests/Unit/Propagators/CurlHeadersMapTest.php
tests/Unit/Propagators/TextMapTest.php

In order to play well with other APM integrations in distributed tracing contexts, the trace and span ID's need to be unsigned-63-bit ints.
At first glance, it looks like the PHP tracer uses 64-bit hex string ID's for traces & spans; and [it does](https://github.com/DataDog/dd-trace-php/blob/87d21a7d25d4a95b8d8ea5bcdb91451636b1e461/src/DDTrace/SpanContext.php#L160), but these [get encoded as 63-bit base-10 ints](https://github.com/DataDog/dd-trace-php/blob/87d21a7d25d4a95b8d8ea5bcdb91451636b1e461/src/DDTrace/Encoders/Json.php#L69-L71) before sending traces to the agent.
The bug manifests itself in the context of distributed traces which [serialize on the wire as hex string ID's](https://github.com/DataDog/dd-trace-php/blob/87d21a7d25d4a95b8d8ea5bcdb91451636b1e461/src/DDTrace/Propagators/Te …

Replace hex string ID's with unsigned-63-bit ints

---

CHANGELOG.md
composer.json
src/DDTrace/Util/TryCatchFinally.php
tests/Unit/SpanTest.php
tests/Unit/TracerTest.php
tests/Unit/Util/TryCatchFinallyTest.php

PHPUnit 5.x requires php 5.6+. In order to support the soon-to-land php 5.4 we had to downgrade to PHPUnit 4.*
The following checks were performed to make sure that we do not see false positives:
- Mockery expectations on method calls are asserted
- Native PHPUnit assertions still work
- Exceptions have been moved to docblock-based exceptions expectations

Downgrade of phpunit to 4.* in order to prepare for php 5.4

---

CHANGELOG.md
tests/Integrations/Predis/PredisTest.php

Fix linting error merged to master.

Linting check fails on master due to missing space after comma

---

CHANGELOG.md
docs/getting_started.md
src/DDTrace/Configuration.php
src/DDTrace/Tracer.php
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
tests/Unit/TracerTest.php

We had users reporting that in some cases they have manual end-points that `echo` some content and then just `exit(0)` at the end of action's method. While the shutdown hook that flushes traces would still be called, many spans would be unfinished and thus discarded. With this option enabled spans are automatically finished (if not finished yet) when the tracer is flushed.

Configurable autofinishing of unfinished spans on tracer flush

---

src/ext/dispatch_compat_php7.c

In PHP 7.3 there was a [small BC](https://github.com/php/php-src/blob/1c850bfcca97e0456a716a1889b5cf6c5e477cd8/UPGRADING.INTERNALS#L77-L78) that affected ddtrace which was pointed out in #212. This PR doesn't officially offer PHP 7.3 support (we still need to add the proper Docker containers, etc), but ddtrace will at least compile for 7.3 now. I didn't want to make too many changes that would cause more work for @pawelchcki's open work. :)

Fix compile-time error on PHP 7.3

---

dockerfiles/verify_packages/Makefile

This PR disables parts of package build verifcation steps because of no longer supported package sources used in those  steps.

Disable centos 7.0 verification build, and disable cache to ensure other steps are correctly performed

---

README.md
docs/getting_started.md
package.xml
package2.xml

This PR adds the necessary metadata to build a package for [datadog_trace on PECL](https://pecl.php.net/package/datadog_trace).
To build, make sure any new files are added to the `package.xml` and validate the XML and then package it:
```bash
$ pear package-validate package.xml && pear package
```
Since ddtrace is still in beta, you can install it from PECL with the following:
```bash
$ sudo pecl install datadog_trace-beta
```
Once GA hits, you'll be able to just do:
```bash
$ sudo pecl install datadog_trace
```

Add PECL config

---

CHANGELOG.md
src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
tests/Frameworks/Laravel/Version_5_7/config/app.php

This should fix the issue brought up in #216. I also updated the config in the test app for Laravel 5 to keep the deprecated messages from showing up when running the tests. :)

Fix noop tracer issues with Laravel integration

---

CHANGELOG.md
package.xml
src/DDTrace/Version.php
src/ext/version.h

Version bump for `0.9.0` release.

Bump version to 0.9.0

---

.circleci/config.yml
CHANGELOG.md
src/ext/ddtrace.c
src/ext/ddtrace.h
src/ext/dispatch.c
src/ext/dispatch.h
src/ext/dispatch_setup.c
tests/ext/enable_throw_exception_if_overridable_doesnt_exist.phpt
tests/ext/reset_configured_overrides.phpt
tests/ext/silently_check_if_overridable_exists.phpt

- `dd_trace_reset` simply resets the lookup hashes to initial state, allowing removing of existing overrides - mostly usable for tests
- Exception throwing behavior is controlled by `ddtrace.ignore_missing_overridables` ini setting that defaults to `true`

Add `dd_trace_reset` function, and stop throwing exceptions when overriding missing methods 

---

CHANGELOG.md
src/DDTrace/Contracts/Tracer.php
src/DDTrace/NoopTracer.php
src/DDTrace/Tracer.php
tests/Unit/TracerTest.php

This PR adds a way to track the root span so that it can be modified later in the script execution. This is important for integrations that don't have a way of hooking into the request/routing/etc early on in the script execution when the tracer is inited.
It works just like `Tracer::startActiveSpan()`, but it saves the `Scope` instance on the tracer to be accessed later by `Tracer::getRootScope()`.
```php
$tracer->startRootSpan('my_root_span');
// ...do lots of stuff...
$scope = $tracer->getRootScope();
// ..add tags and whatnot
```

Add root span/scope tracking

---

CHANGELOG.md
src/ext/ddtrace.c

The INI settings aren't showing up when you run `$ php -i` or dump info with `phpinfo()`, so this PR adds them. :)

Add INI settings to the info page

---

CHANGELOG.md
package.xml

This fixes #249 by adding the missing files needed to build & test the extension in PECL.

Add missing files to PECL releases

---

CHANGELOG.md
bridge/dd_wrap_autoloader.php

Before we we using a class name as trigger to stop hooking into `spl_autoload_register` calls. The problem is that in some cases we receive directly objects in place of classes, so we needed to handle that case.

Trigger of autoloader un-tracing did not respect object

---

.circleci/config.yml
dockerfiles/verify_packages/docker-compose.yml

Make package verification use Machine type in order do correctly use newer docker-compose based verification.
Before running docker-compose on remote docker, caused problems with mounting volumes. 
By using machine type - we're able to use docker-machine volumes to allow faster verification of built packages.

Make package verification use Machine type in order do correctly use newer docker-compose based verification

---

README.md
docs/getting_started.md

Just a quick type-o fix in the docs. :)

Fix type-o in command to install .deb packages

---

CHANGELOG.md
src/DDTrace/Configuration.php
src/DDTrace/Integrations/IntegrationsLoader.php
src/DDTrace/Integrations/PDO/PDOIntegration.php
src/DDTrace/Log/ErrorLogLogger.php
src/DDTrace/Log/InterpolateTrait.php
src/DDTrace/Log/Logger.php
src/DDTrace/Log/LoggerInterface.php
src/DDTrace/Log/LoggingTrait.php
src/DDTrace/Log/NullLogger.php
src/DDTrace/Log/PsrLogger.php
src/DDTrace/Tracer.php
src/DDTrace/Transport/Http.php
tests/Common/TracerTestTrait.php
tests/DebugLogger.php
tests/Integration/Transport/HttpTest.php
tests/Unit/BaseTestCase.php
tests/Unit/ConfigurationTest.php
tests/Unit/Integrations/IntegrationsLoaderTest.php
tests/Unit/ScopeManagerTest.php
tests/Unit/TracerTest.php
tests/Unit/Transport/HttpTest.php

This PR add a new setting `DD_TRACE_DEBUG` which defaults to `false` and when it is turned on it dumps a number of useful info to the logger. For now we do not implement logging levels as it will come later on.

Debug mode for logging

---

CHANGELOG.md
src/ext/ddtrace.c
src/ext/dispatch.c
src/ext/dispatch_compat.h
src/ext/dispatch_compat_php7.c
tests/ext/enable_throw_exception_if_overridable_doesnt_exist.phpt

Handle all reported memory leaks in 5.6 and 7.x

---

CHANGELOG.md
src/DDTrace/Configuration.php
src/DDTrace/Configuration/AbstractConfiguration.php
src/DDTrace/Configuration/EnvVariableRegistry.php
src/DDTrace/Configuration/Registry.php
src/DDTrace/Tracer.php
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
tests/Integrations/Laravel/V4/CommonScenariosTest.php
tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
tests/Unit/Configuration/EnvVariableRegistryTest.php
tests/Unit/TracerTest.php

This PR adds support for global tags that will be set in each span. They can be defined through the env `DD_TRACE_GLOBAL_TAGS=key1:valu1,key2:value2`

Support for global tags

---

CHANGELOG.md
src/DDTrace/Integrations/ZendFramework/ZendFrameworkIntegration.php
src/DDTrace/Util/Runtime.php

This PR adds a fix to make Zend integration compatible with framework such as Yii. Changes have been tested locally, integration tests will be added immediately after.

Zend integration incompatibility with Yii

---

RELEASING.md

This PR improves packagist update step in releasing instructions. Specifically explains what are the steps to do if packagist does not immediately update with the latest release.

Improvement of packagist update step in releasing instructions

---

CHANGELOG.md
src/DDTrace/Contracts/Span.php
src/DDTrace/NoopSpan.php
src/DDTrace/Span.php
tests/Unit/SpanTest.php

We had deprecated `Span::setResource` back when we were implementing our tracer based on OpenTracing. The problem is that `setResource` method did exist in our `DDTrace\Span` class but not in our `DDTrace\NoopSpan` class.
This PR:
1. adds the method declaration in the `DDTrace\Contracts\Span` interface
1. removes the `@deprectated` annotation from `DDtrace\Span`
1. adds the method to `DDTrace\NoopSpan`

Span::setResource as a legit method

---

CHANGELOG.md
phpstan.neon
src/DDTrace/Bootstrap.php
tests/Integrations/Custom/Autoloaded/CommonScenariosTest.php

Previously we did not set an http status code for generic web requests. This PR introduces such functionality.

Tracing of http status code in generic web requests

---

CHANGELOG.md
src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
src/DDTrace/Util/TryCatchFinally.php
tests/Frameworks/Symfony/Version_3_4/src/AppBundle/Controller/HomeController.php
tests/Integrations/Symfony/V3_4/AutofinishedTracesSymfony34Test.php

When users have an endpoint which `echo` some content and then `exit()` some info such as the route name was not properly traced. This PR correct the way route is set adding an hook when this can be done and that handles this case.

Route not set in symfony 3.4 when user calls exit()

---

src/ext/dispatch_setup.c

This is just a little tweak for destroying the hash tables in PHP 7. Thanks @krakjoe for noticing this one! <3

Fix hash table dtor for PHP 7

---

.gitignore
CHANGELOG.md
src/DDTrace/Encoders/Json.php
src/DDTrace/Log/AbstractLogger.php
src/DDTrace/Log/ErrorLogLogger.php
src/DDTrace/Log/LogLevel.php
src/DDTrace/Log/Logger.php
src/DDTrace/Log/LoggerInterface.php
src/DDTrace/Log/LoggingTrait.php
src/DDTrace/Log/NullLogger.php
src/DDTrace/Log/PsrLogger.php
src/DDTrace/Tracer.php
tests/DebugLogger.php
tests/Integrations/Laravel/V4/CommonScenariosTest.php

We had one single error report from a customer that span encoding went out of memory. In order to answer the following questions we need to add a few info to our logs (only in debug mode).
1) is out of memory caused by too many spans?
2) is out of memory caused by a very large method’s argument added to a manually created span?
3) is out of memory caused by a very large method’s argument added to an automatically created span?
4) is memory leak/recursion problem in our encoder?
At the same time calculating some of the info above may be computationally expansive. For this reason this PR also partially refactor the logging engine to provide the log level information as a boolean.

Logging more span's info when in debug mode

---

src/ext/ddtrace.c

Just removed a function that wasn't being invoked from anywhere. :)

Remove unused function that was moved to dispatch_table_dtor()

---

.circleci/config.yml

Very often php 5.4 tests were failing with [this same error](https://stackoverflow.com/questions/47527455/getting-an-error-peer-fingerprint-did-not-match-after-running-composer-update). Apparently the reason is PHP 5.4 having some issues with tls verification (https://github.com/composer/composer/blob/master/src/Composer/Util/RemoteFilesystem.php#L354). The solution proposed here is to disable tls only when downloading libraries using composer for php 5.4. This has no security implications as this is only done for tests execution and not during package build.

[ci] In CI disable tls check for 5.4 only to avoid Peer fingerprint mismatch

---

tests/AutoInstrumentation/AutoInstrumentationTest.php

Disable tls when updating dependencies for auto-instrumentation tests.

Misfunctioning tls in php 5.4 auto-instrumentation tests

---

.circleci/config.yml
CHANGELOG.md
Makefile
src/ext/dispatch.c

Fixes misconfiguration of CircleCI that allowed failing tests to pass. 
Fixes lifecycle management for `$this` pointer in the C extension

Stop prematurely freeing `this` pointer

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Version bump 0.13.3

---

CHANGELOG.md
src/ext/dispatch.c
src/ext/dispatch.h
src/ext/dispatch_compat.h
src/ext/dispatch_compat_php5.c
src/ext/dispatch_compat_php7.c
src/ext/dispatch_setup.c
tests/ext/used_dispatch_shouldn_t_be_freed.phpt

In rare cases where instrumented code have actually removed/changed existing instrumentation of its own execution a freed pointer was accessed when removing recursion guard.

Fix accessing freed memory when instrumentation code un/instrumented itself 

---

CHANGELOG.md
src/ext/dispatch.c

`This` object handled in the wrapping function needs to be safely released eg when it was created in a closure. 
Before this change we tried to guess those situatios, but while this did work in all cases hapenning in our tests it didn't correctly address all cases, thus in php-fpm in a few instances the This object was freed prematurely, causing memory access problems further down object processing line.
This PR reuses mechanism used e.g. in processing of zend_closure, which checks if the this objects needs to be freed in call info data, which should be correctly set if the This objects needs to be released.

Fix invalid memory access

---

src/ext/ddtrace.c

Just a tiny update to the php info data that points to the official docs and update the copyright year. :)

Update link to docs and copyright year in php info

---

tests/AutoInstrumentation/AutoInstrumentationTest.php
tests/AutoInstrumentation/scenarios/autoloader_die_on_not_found/index.php

Some of our users rely on autoloaders that `die()` or `exit()` when tey do not found a class. Previously we were not compatible with this behavior. Version 0.14.0 added compatibility with such class loaders. This PR simply add a test to make sure that we keep this compatibility alive.

Replicate in tests autoloader that die() on class not found

---

CHANGELOG.md
src/ext/dispatch_setup.c

Ensure function name is copied and zval is recreated in php 7.x

---

CHANGELOG.md
composer.json
src/DDTrace/Contracts/Tracer.php
src/DDTrace/Integrations/Symfony/SymfonyIntegration.php
src/DDTrace/NoopTracer.php
src/DDTrace/Tracer.php
tests/Frameworks/Symfony/Version_2_8/.gitattributes
tests/Frameworks/Symfony/Version_2_8/src/AppBundle/Controller/DefaultController.php
tests/Integrations/Symfony/V2_8/RouteNameTest.php

Properly set resource names on Symfony 2.x controllers.

Resource name on Symfony 2.x requests served through controllers

---

CHANGELOG.md
src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
src/DDTrace/Span.php
tests/Unit/SpanTest.php

This PR move urls sanitization to the span when a tag is recorded with name
http.url. Previously we did it manually in every place and forgot to do it in quite
a few of them
In order to sanitize we use the already available Urls::sanitize() method.

Sanitize url in web spans

---

CHANGELOG.md
composer.json
tests/Frameworks/Symfony/Version_2_3/.gitattributes
tests/Frameworks/Symfony/Version_2_3/src/AppBundle/Controller/DefaultController.php
tests/Integrations/Symfony/V2_3/RouteNameTest.php

Add Symfony 2.3 web tests for resource name setting

Symfony 2.3 web tests for resource name

---

tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
tests/Integrations/Symfony/V4_2/CommonScenariosTest.php

The web tests for Symfony 3.3, 3.4 & 4.2 are failing due to a recent security patch where [the `render()` method now bypasses the `HttpKernel::handle()` method](https://github.com/symfony/symfony/commit/7f912bbb78377c2ea331b3da28363435fbd91337#diff-5740ef31c231cd679c9401de5515e9edR80). So this PR fixes the failing tests. :)

Fix failing Symfony tests

---

CHANGELOG.md
src/DDTrace/Integrations/Symfony/SymfonyIntegration.php
src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
tests/Common/WebFrameworkTestCase.php
tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
tests/Integrations/Symfony/V4_2/CommonScenariosTest.php

Symfony changed the way it auto-loads the twig template engine passing from `Twig_Environment` to psr4 `Twig\Environment`.
This PR adds the support for the latest to support both users that have and have not the latest releases.

Fix Symfony template rendering spans

---

.circleci/config.yml
CHANGELOG.md
docker-compose.yml
dockerfiles/verify_packages/verify_deb.sh
src/ext/backtrace.c
src/ext/ddtrace.c
src/ext/ddtrace.h
src/ext/logging.c
src/ext/logging.h
src/ext/request_hooks.c
src/ext/request_hooks.h
tests/ext/request_init_hook_check_blacklisted_modules.phpt

Some extensions have known incompatibilities with our extension, this PR adds option to disable functions which can cause unexpected errors with specified extensions

Disable request_hook_init if blacklisted module has beed detected 

---

src/ext/backtrace.c

Discovered while working a a build warning
```
/dev/shm/BUILD/php-pecl-datadog-trace-0.15.1/NTS/src/ext/backtrace.c:54:6: warning: type of 'TSRMLS_D' defaults to 'int' [-Wimplicit-int]
void ddtrace_install_backtrace_handler(TSRMLS_D) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Tracking this issue, the bas code is selected as __GLIBC__ is tested before all include, where it is defined.

ensure __GLIBC__ properly defined before using it

---

.circleci/config.yml
docker-compose.yml
src/ext/dispatch.c
src/ext/dispatch_compat.h
src/ext/dispatch_compat_php5.c
src/ext/dispatch_compat_php5.h
src/ext/dispatch_setup.c

Tests still fail for 5.5
this PR makes the code compile on 5.5 and makes CI able to compile any custom compilation combination:
```
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   39
---------------------------------------------------------------------
Number of tests :   39                34
Tests skipped   :    5 ( 12.8%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    6 ( 15.4%) ( 17.6%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   28 ( 71.8%) ( 82.4%)
------------------------------------------
```

PHP 5.5 Compilation support

---

CHANGELOG.md
src/DDTrace/Span.php
tests/Integrations/Custom/Autoloaded/CommonScenariosTest.php
tests/Integrations/Laravel/V4/CommonScenariosTest.php
tests/Integrations/Laravel/V5_7/CommonScenariosTest.php
tests/Integrations/Laravel/V5_8/CommonScenariosTest.php
tests/Integrations/ZendFramework/V1/CommonScenariosTest.php

When an HTTP response status is >= ~~400~~ 500, it  isn't always marked as an error. This PR ensures that all non-success HTTP status codes get marked as an error in the APM UI.

Mark non-success HTTP statuses as errors

---

.circleci/config.yml
CHANGELOG.md
bridge/dd_wrap_autoloader.php
src/DDTrace/Bootstrap.php
src/ext/ddtrace.c
src/ext/ddtrace.h
src/ext/dispatch.c
src/ext/dispatch.h
src/ext/dispatch_compat.h
src/ext/dispatch_compat_php7.c
tests/ext/disable_tracing_disables_tracing.phpt
tests/ext/protected_method_hook.phpt

This PR changes the implementation slightly to honor PHP 7.x cached hash calculations. 
In addition a new function has been implemented `dd_trace_disable_in_request` which is used to disable tracing when its no longer needed in order to  avoid spending CPU time unnecesarily

Use cached hash function results in PHP 7.x  + disable all internals of tracing when its not needed 

---

src/ext/ddtrace.c
src/ext/ddtrace.h
src/ext/request_hooks.c
tests/ext/request_init_hook_check_blacklisted_modules.phpt

Before module blacklist was implement using pcre regexp which caused problems in some installations which differ in installed library versions which changed load order which caused the problem to surface.
This change avoids using php's pcre regexps.

Reimplement blacklist as simple list to avoid problems with missing symbols between modules

---

CHANGELOG.md
src/DDTrace/Span.php
tests/Common/SpanAssertion.php
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Integrations/Laravel/V4/CommonScenariosTest.php
tests/Integrations/PDO/PDOTest.php
tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
tests/Integrations/Symfony/V4_2/CommonScenariosTest.php

Error traces do not appear under the "Total Errors" panel in the APM UI unless `error.type` is set. This PR ensures that `error.type` is set with 500-level HTTP responses.

Fix issue where error traces don't appear in "Total Errors" panel

---

.circleci/config.yml

Disable PHP 7.3 being packaged to avoid shipping binaries for unsupported  (yet) PHP versions

---

.circleci/config.yml

This change will make CI build package artifacts when the branch name contains the word "build". So this one should be built.
~~- [ ] [Changelog entry](docs/changelog.md) added, if necessary~~

Build packages for "build" branch names

---

CHANGELOG.md
src/DDTrace/Transport/Http.php
tests/Common/TestLogger.php
tests/Unit/Transport/HttpTest.php

The Agent has a [10MB payload cap](https://github.com/DataDog/datadog-agent/blob/355a34d610bd1554572d7733454ac4af3acd89cd/pkg/trace/api/api.go#L31) which isn't an issue for us right now, but when/if we start buffering traces sent to the Agent, this will be an issue to account for. The main reason is that the Agent will return a successful 200 response for payloads over the 10MB limit and will drop all the traces quietly.

Add cap to payloads sent to the Agent

---

config.m4

See #395 
I also ass -Wall, which seems to be a best practice

fix #395 build with -std=c99 option

---

tests/ext/dd_trace_serialize_msgpack.phpt
tests/ext/dd_trace_serialize_msgpack_error.phpt
tests/ext/dd_trace_serialize_msgpack_error_strict.phpt

This PR fixes most of the failing tests in #394 by making the `dd_trace_serialize_msgpack()` tests more predictable on more platforms.
~~- [ ] [Changelog entry](docs/changelog.md) added, if necessary~~

Make dd_trace_serialize_msgpack() tests more cross-platform friendly

---

src/ext/dispatch_setup.c

This PR fixes #365 where the original cURL headers set with `curl_setopt_array()` were overwritten by the tracer. Thanks so much to @labbati for [finding the repro](https://github.com/DataDog/dd-trace-php/tree/curl/missing-headers/tests/ManualTesting/CurlMissingHttpHeaders)! :)
I'll include more details on Monday. :)

Fix original curl headers overwritten

---

src/DDTrace/Configuration/EnvVariableRegistry.php

about 4 to 5 percentage points are wasted because this is not cached.

Cache a 'non-existing' bool  and string config lookup to speedup execution

---

tests/ext/dd_trace_serialize_msgpack_error.phpt
tests/ext/dd_trace_serialize_msgpack_error_strict.phpt

As @remicollet pointed out in #394, the error-condition tests for `dd_trace_serialize_msgpack()` fail in PHP 5.4 due to the test's reliance on `json_encode()` which has different error-condition behavior depending on the PHP version. This PR refactors the tests so that they don't rely on `json_encode()`.

Make tests less brittle

---

tests/ext/segfault_backtrace_enabled.phpt
tests/ext/segfault_backtrace_enabled_via_env.phpt
tests/ext/segfault_backtrace_enabled_via_env_disabled_in_ini.phpt

Test suite is failing with 7.3, because regex used is invalid:
```
TEST 29/41 [tests/ext/segfault_backtrace_enabled.phpt]
Warning: preg_match(): Compilation failed: escape sequence is invalid in character class at offset 215 in /builddir/build/BUILD/php-pecl-datadog-trace-0.20.0/NTS/run-tests.php on l
ine 2100
Warning: preg_match(): Compilation failed: escape sequence is invalid in character class at offset 9 in /builddir/build/BUILD/php-pecl-datadog-trace-0.20.0/NTS/run-tests.php on lin
e 2245
========DIFF========
006+ /lib64/libc.so.6(+0x37f40) [0x7f9380d54f40]
006- [\S\W\D\R]*
007+ /lib64/libc.so.6(kill+0xb) [0x7f9380d551bb]
008+ /usr/lib64/php/modules/posix.so(+0x41c7) [0x7f9380c671c7]
009+ /usr/bin/php(+0xfdf85) [0x55602c28cf85]
010+ /usr/bin/php(execute_ex+0x3329) [0x55602c4b55e9] …
```

simplify regex which fails with 7.3

---

.circleci/config.yml
.circleci/valgrind/musl_valgrind.rc
.circleci/valgrind/valgrind_musl_suppressions.lib

###
Stores artifacts in the CI and configures valgrind from PHP repo

Store unit test results and artifacts + use valgrind suppressions and config from PHP repo

---

CHANGELOG.md

With the last rebase I accidentally put the changes under the wrong heading. This fixes that. :)

Put changes under correct heading in CHANGELOG

---

.circleci/config.yml
composer.json

Since the Mongo tests have stopped working and are blocking all the PR's, this PR disables the mongo tests until we can fix the flaky mongo image on the CircleCI side. Once we fix the image, we can simply revert this commit to bring them back.
```bash
$ git revert 4a2692e
```

Temporarily remove Mongo tests from CI pipeline

---

CHANGELOG.md
src/DDTrace/Contracts/Span.php
src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
src/DDTrace/Span.php
tests/Unit/SpanTest.php

In cases where a subclass changes the return value of a known method, the `$value` sent to `Span::setTag()` can be an object that has no `__toString` magic method. This causes an error when trying to cast the value to a string. This is the root cause of #332.
The following repro illustrates what can happen within a traced integration:
```php
class FakePDO
{
public function exec()
{
return 42;
}
}
class MyPDO extends FakePDO
{
public function exec()
{
$obj = new \stdClass;
$obj->rows = parent::exec();
return $obj;
}
}
dd_trace('FakePDO', 'exec', function() {
var_dump($this->exec()); // Assumes return value is an int
});
(new MyPDO())->exec();
```

Ignore objects sent to Span::setTag()

---

CHANGELOG.md
src/DDTrace/Configuration.php
src/DDTrace/Contracts/Tracer.php
src/DDTrace/Integrations/Curl/CurlIntegration.php
src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
src/DDTrace/Integrations/Integration.php
src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php
src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
src/DDTrace/Integrations/PDO/PDOIntegration.php
src/DDTrace/Integrations/Predis/PredisIntegration.php
src/DDTrace/NoopTracer.php
src/DDTrace/Tracer.php
src/DDTrace/Util/CodeTracer.php
tests/Common/TracerTestTrait.php
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Integrations/Elasticsearch/V1/ElasticSearchIntegrationTest.php
tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
tests/Integrations/Memcached/MemcachedTest.php
tests/Integrations/Mongo/MongoTest.php
tests/Integrations/Mysqli/MysqliTest.php
tests/Integrations/PDO/PDOTest.php
tests/Integrations/Predis/PredisTest.php
tests/Unit/TracerTest.php

Tracer will enter `limited()` state after creating 1000 (configurable number) spans. In limited state most integrations should stop creating new spans while maintaining all other operation like distributed tracing, etc. 
Note to reviewers:
I've changed the concept of `ready()` to its own reverse `limited()` somehow it felt more natural this way.
It still means a ton of Ifs in the code needed to be added. And I added them for all integrations + tests.
~Trying to explore some concepts how to best implement optional traces. This skeleton PR is my best idea so far :D (it's probably not objectively best so open to all and every feedback) 
/cc: @SammyK @labbati~
~I've considered changing existing api to return null spans or adding higher level abstractions. And this felt the cleanest.~

Implementation of `limited` tracer state in which most spans should not be created 

---

CHANGELOG.md
bridge/dd_wrap_autoloader.php
bridge/functions.php
composer.json
docker-compose.yml
phpunit.xml
src/DDTrace/Bootstrap.php
src/DDTrace/Integrations/Integration.php
src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php
src/DDTrace/Integrations/Lumen/V5/LumenIntegrationLoader.php
src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
tests/Frameworks/Custom/Version_Autoloaded/run
tests/Frameworks/Laravel/Version_4_2/phpunit.xml
tests/Frameworks/Laravel/Version_5_7/phpunit.xml
tests/Frameworks/Symfony/Version_3_4/app/AppKernel.php
tests/Frameworks/Symfony/Version_3_4/phpunit.xml.dist
tests/Integrations/CLI/CLITestCase.php
tests/Integrations/CLI/Custom/Autoloaded/CommonScenariosTest.php
tests/Integrations/CLI/EnvSerializer.php
tests/Integrations/CLI/IniSerializer.php
tests/Integrations/CLI/Laravel/V5_8/CommonScenariosTest.php
tests/WebServer.php

This PR adds support for tracing custom PHP CLI scripts and Laravel Artisan. This feature is disabled by default. To enable, set the env var `DD_TRACE_CLI_ENABLED=true`.
~~This PR adds support for the CLI SAPI by removing the `PHP_SAPI` and `getenv('APP_ENV')` checks.~~

Add support for the CLI SAPI

---

CHANGELOG.md
bridge/dd_wrap_autoloader.php

In PHP 5 there was a warning that would be raised when doing date/time manipulation if the default timezone wasn't set. The PHP tracer can cause this warning on systems that don't have the default timezone set from an INI setting [when the logger date stamps a log entry](https://github.com/DataDog/dd-trace-php/blob/638b1f1cb8dc4c82da196572df183ef65e6ca2a6/src/DDTrace/Log/ErrorLogLogger.php#L68).
```
Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. …
```

Fix timezone warning in PHP 5

---

.circleci/config.yml
CHANGELOG.md
src/DDTrace/Transport/Http.php

Fail fast if there are problems connecting to the agent.

Add timeouts to Curl Http client

---

CHANGELOG.md
src/DDTrace/Configuration.php
src/DDTrace/Tag.php
src/DDTrace/Tracer.php
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Unit/TracerTest.php

a Very simple PR :) adds hostname to a root span when enabled (only at very last moment to avoid people being able to easily overwrite this hostname).

Append hostname to root span

---

CHANGELOG.md
bridge/dd_optional_deps_autoloader.php
bridge/dd_require_all.php
bridge/dd_wrap_autoloader.php
composer.json
docker-compose.yml
phpunit.xml
src/DDTrace/Integrations/CakePHP/CakePHPIntegration.php
src/DDTrace/Integrations/CakePHP/V2/CakePHPIntegrationLoader.php
src/DDTrace/Integrations/IntegrationsLoader.php
tests/Common/WebFrameworkTestCase.php
tests/Frameworks/CakePHP/Version_2_8/app/Config/core.php
tests/Frameworks/CakePHP/Version_2_8/app/Controller/ErrorController.php
tests/Frameworks/CakePHP/Version_2_8/app/Controller/SimpleController.php
tests/Frameworks/CakePHP/Version_2_8/app/Controller/SimpleViewController.php
tests/Frameworks/CakePHP/Version_2_8/app/View/SimpleView/index.ctp
tests/Integrations/CLI/CakePHP/V2_8/CommonScenariosTest.php
tests/Integrations/CakePHP/V2_8/CommonScenariosTest.php
tests/request_replayer/index.php

This PR adds tracing support for CakePHP v2 and also includes support for Cake Console.

CakePHP v2 integration

---

package.xml

The *package.xml* syntax is not valid so this fixes that. :)

Fix invalid package.xml syntax

---

tests/ext/namespaces.phpt

From UPGRADING file
> 
>   . "fn" is now a reserved keyword. In particular it can no longer be used as a
>     function or class name. It can still be used as a method or class constant
>     name.
>

fix test for upcomint 7.4

---

CHANGELOG.md
package.xml
src/DDTrace/Tracer.php
src/ext/version.h

- Support for Slim Framework v3 #446
- IPC based configurable Circuit breaker `DD_TRACE_AGENT_ATTEMPT_RETRY_TIME_MSEC` and `DD_TRACE_AGENT_MAX_CONSECUTIVE_FAILURES` used when communicating with the agent #440
- Normalized URL's as resource names; a CSV string of URL-to-resource-name mapping rules with `*` and `$*` wildcards can be set from `DD_TRACE_RESOURCE_URI_MAPPING`. This feature is disabled by default to reduce cardinality in resource names; to enable this feature set `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED=true` #442

Release 0.25.0

---

CHANGELOG.md
src/DDTrace/Http/Urls.php
tests/Unit/Http/UrlsTest.php

Per #455, the URL normalization rules introduced in #442 are overly aggressive due to word boundaries that are too wide using `\b`. This PR narrows the word boundaries to `/` and `$`.
The specific edge case mentioned in #455 (`/v1.0/users/1414`) has been added to the test suite.

Narrow the URL normalization rules boundaries

---

CHANGELOG.md
src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php

The [API for `Symfony\Component\EventDispatcher\EventDispatcher::dispatch()` has changed](https://github.com/symfony/event-dispatcher/blob/861c10069b0a073618c7c2d60eacbccafa72f697/EventDispatcher.php#L51). This PR supports both the old and the new API.

Fix API change with Symfony 4.x EventDispatcher

---

CHANGELOG.md
src/ext/coms.c
src/ext/coms.h
tests/ext/dd_trace_coms_test_parallel_writer_consistency.phpt

Code responsible for stack allocation was not correctly freeing old stacks. On top of that - those were thrown away even if unused and brand new. These changes make it so that current stack which is empty will not thrown away.

Fix Memory leak when garbage collecting empty span stacks

---

CHANGELOG.md
package.xml
src/ext/dispatch_setup.c
tests/ext/very_nested_functions.phpt

Overriding `zend_execute_ex` causes tail recursive calls to fail due to different codepaths taken by the opcode parsers based on `zend_execute_ex == execute_ex` check. This makes each subsequent call to tailrecursive function actually be put on stack which causes os error to be raised due to stack overflow.

Only override execute on compilation step

---

CHANGELOG.md
src/ext/backtrace.c

In cases of stack overflow exception the backtrace handler can be run more than one time. This PR fixes that case and informs user when max stacktrace size (to be printed) have been reached indicating a possible stackoverflow type error.

Fix backtrace handler being run more than once, and inform about max stacktrace size reached

---

CHANGELOG.md
Makefile
RELEASING.md
bridge/dd_wrap_autoloader.php
src/DDTrace/Tracer.php
src/DDTrace/Transport/Http.php
src/DDTrace/version.php
src/ext/ddtrace.c
tests/AutoInstrumentation/AutoInstrumentationTest.php
tests/AutoInstrumentation/scenarios/autoloader_die_on_not_found/index.php
tests/AutoInstrumentation/scenarios/autoloader_includes_even_non_existing/index.php
tests/AutoInstrumentation/scenarios/composer_without_ddtrace_dependency/index.php
tests/AutoInstrumentation/scenarios/symfony_33_private_loader/index.php
tests/Integration/Transport/HttpTest.php

This PR does version checks in the request init hook to ensure that the version of the extension matches the version in userland code. If the versions don't match, then the tracer does not run. This prevents the extension and PHP code from getting out of sync (which can happen after upgrading the tracer and before restarting the SAPI.)
The extension version is exposed via a new userland constant `DD_TRACE_VERSION`.
One thing to keep in mind. Until we remove `Tracer::VERSION`, we need to update the version number in three places for version bumps:
1. **src/ext/version.h**
2. **src/DDTrace/Tracer.php** (`Tracer::VERSION`; deprecated in this PR)
3. **src/DDTrace/version.php** (new; accessed via `Tracer::version()`)

Request init hook version sync

---

CHANGELOG.md
src/DDTrace/Http/Urls.php
src/DDTrace/Integrations/Curl/CurlIntegration.php
src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php

The Agent [expects tags](https://github.com/DataDog/datadog-agent/blob/5da007b59095381240223f59b29916207c553c39/pkg/trace/api/normalizer.go#L296-L317) to begin with a nonnumeric unicode character. With the `DD_TRACE_HTTP_CLIENT_SPLIT_BY_DOMAIN=true` feature added in #459, service names (sent to the Agent via a tag) can begin with a number (IP addresses & hostnames that begin with a number).
For example, making a request to `2guysaroundtheworld.com` with `DD_TRACE_HTTP_CLIENT_SPLIT_BY_DOMAIN=true` results in an incorrect service name in the UI:
~~This PR ensures that any hostname that begins with a number will be prefixed with a valid tag character, `:`. So the previous example becomes:~~ After some discussion, all hostnames are now automatically prefixed with `host-`.
Service names that …

Prefix invalid hostnames as service names

---

.circleci/config.yml
Makefile
src/ext/backtrace.c
src/ext/circuit_breaker.c
src/ext/circuit_breaker.h
src/ext/compat_zend_string.c
src/ext/compatibility.h
src/ext/coms.c
src/ext/coms_curl.c
src/ext/coms_debug.c
src/ext/coms_debug.h
src/ext/configuration.c
src/ext/configuration_php_iface.c
src/ext/configuration_php_iface.h
src/ext/configuration_render.h
src/ext/ddtrace.c
src/ext/dispatch.c
src/ext/dispatch.h
src/ext/dispatch_compat_php5.c
src/ext/dispatch_compat_php7.c
src/ext/dispatch_setup.c
src/ext/env_config.c
src/ext/logging.c
src/ext/memory_limit.c
src/ext/memory_limit.h
src/ext/random.c
src/ext/random.h
src/ext/request_hooks.c
src/ext/serializer.c
src/ext/vendor_stdatomic.h

Some of our tests started to exhaust all available memory when installing code through composer.
This PR fixes that
Additionally clang-format stopped working due to being removed from Debian repos. - newer version needed to reformat the files putting module header at the top, which caused some compilation configurations to break

Increase resource_class for web integration jobs and fix clang-format-6.0 being removed from image

---

src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

The Debian packages require the version field to begin with a number, otherwise there is an error like:
> 'Version' field value 'nightly': version number does not start with digit
Improves on PR #497.

Change nightly version to 1.0.0-nightly

---

CHANGELOG.md
src/ext/ddtrace.h
src/ext/dispatch_setup.c

This PR removes the `zend_execute_ex` override which allows the VM to behave under its normal conditions and allows the opcode `ZEND_DO_UCALL` to be emitted. As a result, this PR registers the opcode handler for `ZEND_DO_UCALL` as well.

Remove zend_execute_ex override and trace ZEND_DO_UCALL

---

CHANGELOG.md
src/ext/coms.c
src/ext/coms_curl.c
src/ext/configuration.c
src/ext/configuration.h
src/ext/ddtrace.c
tests/ext/segfault_backtrace_disabled.phpt
tests/ext/segfault_backtrace_enabled.phpt

Continuing the work started in PR #521, this cleans up the leaks in communications and configuration. With this merged, we'll be able to run ddtrace with ASAN and get meaningful results. 
TODO: add a  PHP 7.4+debug+asan build to our CI.

Fix memory leaks from coms and configuration

---

src/ext/coms_curl.c
src/ext/ddtrace.c

Addresses potential issue of freeing memory used by the Writer before the writer is completely shutdown:
related #523

Avoid freeing configuration before writer is completely shutdown

---

src/ext/dispatch.c
src/ext/dispatch.h
src/ext/dispatch_compat.h
src/ext/dispatch_compat_php5.c
src/ext/dispatch_compat_php7.c

In order to wrap up #491, we needed to refactor the entry into the opcode handler `ddtrace_wrap_fcall()`. The check for "should we trace this?" has been bubbled up to `ddtrace_wrap_fcall()` instead of being spread around to several function calls. There were also a few functions that we inlined which allowed us to remove extra code.
This will allow us (we think) to forward the original call at the C level and append the tracing closure cleanly for #491.
Thanks @morrisonlevi for pair programming this one with me. :)

Refactor opcode handler entry

---

package.xml
src/ext/compatibility.h
src/ext/ddtrace.c
src/ext/dispatch.c
src/ext/dispatch_compat.h
tests/ext/desctructor_called_when_this_gets_out_of_scope.phpt

After passing This to a closure, we were not releasing it in correct time when it was requested by the compiled opcodes. 
This PR releases This and closure object when first is requested, and when not needed anymore.
This fixes any code that expects the destructor to be called as soon as possible to free up resources (db connections etc).
https://github.com/DataDog/dd-trace-php/issues/510
https://github.com/DataDog/dd-trace-php/issues/451

Release This as soon as wrapping closure is finished and scope is left

---

package.xml
tests/ext/destructor_called_when_this_gets_out_of_scope.phpt

In PHP 7.4 and forward "fn" is a keyword.
Also fixes misspelling in the name of the file.
I'm unsure whether to target 0.30.1 or master for this change.

Avoid reserved word "fn"

---

src/ext/circuit_breaker.c
src/ext/compatibility.h
src/ext/configuration.c
src/ext/configuration.h
src/ext/ddtrace.c
src/ext/dispatch.h
src/ext/dispatch_compat_php7.c
src/ext/env_config.h
src/ext/logging.h
src/ext/random.h
src/ext/request_hooks.h
src/ext/span.h

PHP7 already had compat macros, so the previous COMPAT_CTX_ macros
were pointless. They did mask some ZTS issues, which is why they
are removed.

Fix ZTS builds, remove COMPAT_CTX_*

---

src/ext/dispatch_compat.h
src/ext/dispatch_compat_php5.c
src/ext/dispatch_compat_php7.c
src/ext/span.c
src/ext/trace.c

This pushes the responsibility of copying the VM stack args onto
the fci object to the caller of ddtrace_execute_tracing_closure,
instead of ddtrace_execute_tracing_closure doing it.
This also cleans up some lifetime messiness of objects that the
ddtrace_execute_tracing_closure uses. This doesn't fix any bugs
when called from existing contexts, but are necessary if we want
to call this function from zend_execute hooks.

Refactor ddtrace_execute_tracing_closure

---

package.xml
src/ext/dispatch_compat.h
src/ext/dispatch_compat_php5.c
src/ext/dispatch_compat_php7.c
src/ext/serializer.c
src/ext/span.c
src/ext/span.h
src/ext/trace.c
tests/ext/sandbox/exception_handling.phpt
tests/ext/sandbox/exception_handling_php5.phpt

This will attach exceptions to open spans that were traced through the new `dd_trace_function`/`dd_trace_method` API.

Attach exceptions to spans

---

package.xml
src/ext/dispatch_compat.h
src/ext/dispatch_compat_php5.c
src/ext/dispatch_compat_php7.c
src/ext/trace.c
tests/ext/sandbox/exceptions_are_passed_to_the_tracing_closure.phpt
tests/ext/sandbox/exceptions_are_passed_to_the_tracing_closure_php5.phpt
tests/ext/sandbox/exceptions_in_original_call_rethrown_in_tracing_closure.phpt
tests/ext/sandbox/exceptions_in_original_call_rethrown_in_tracing_closure_php5.phpt
tests/ext/sandbox/exceptions_in_tracing_closure_and_original_call.phpt

This PR adds a fourth parameter to sandboxed tracing closures that contains the exception thrown from the original call. If no exception was thrown, the argument passed in will be `null`.
```php
dd_trace_function('myFunc', function (SpanData $span, array $args, $retval, $ex) {
if ($ex instanceof FooException) {
echo "FooException thrown!\n";
}
});
```

[Sandbox] Pass original call exception to tracing closure

---

src/ext/dispatch_compat_php7.c

This tiny PR fixes a compiler warning about a possibly uninitialized zval.

Fix compiler warning about uninitialized zval

---

src/ext/dispatch_compat_php7.c

After merging #560, the master build is still failing. This PR should fix the compiler warning for real this time. :)

Fix compiler warning about uninitialized zval (redux)

---

package.xml
src/ext/dispatch.c
src/ext/dispatch_setup.c
tests/ext/case_insensitive_class_hook.phpt

In PHP, class and method names are case insensitive. We already handled method names correctly. This PR adds support for case insensitive class names too.

Correctly treat class names as case insensitive

---

src/dd-doctor.php

This PR adds more diagnostic information to **dd-doctor.php**. The main improvements include:
0. Add warning when running from CLI SAPI and encourage user to run from target SAPI.
0. Support `DD_TRACE_AGENT_PORT` when testing Agent connectivity.
0. Cross-check all the extension version numbers (internal and userland).
0. Check that `request_init_hook` has run.
0. Check that the integrations load when expected.
0. Add a splash of color for `OK` and `FAIL` statuses. :)

Improve dd-doctor.php with more info

---

package.xml
src/ext/dispatch_compat_php5.c
src/ext/dispatch_compat_php7.c
tests/ext/new_static.phpt
tests/ext/sandbox/errors_are_flagged_from_userland.phpt
tests/ext/sandbox/new_static.phpt

This PR fixes an edge case the breaks usage of `new static()` for traced methods in both the sandbox and original API's.

Fix static keyword handling

---

bridge/dd_require_all.php
src/DDTrace/Integrations/IntegrationsLoader.php
src/DDTrace/Integrations/Memcached/MemcachedSandboxedIntegration.php
tests/Common/TracerTestTrait.php
tests/Integrations/Memcached/MemcachedSandboxedTest.php
tests/Integrations/Memcached/MemcachedTest.php

This PR migrates the memcached integration to the new awesome sandboxed api.

Migrate memcached integration to sandboxed API

---

package.xml
src/ext/request_hooks.c
src/ext/sandbox.h

This PR ensures that the `ddtrace.request_init_hook` is still bound by the `open_basedir` INI directive. It also sandboxes the request init hook so that errors or exceptions within the request init hook do not affect the main script execution.
- ~~[ ] Tests added for this feature/bug.~~ The master build tests are expected to fail for this PR; this will be addressed ASAP

Ensure the request init hook is bound by the open_basedir INI directive

---

.circleci/valgrind/valgrind_7_3_musl_suppressions.lib
package.xml
src/dd-doctor.php
src/ext/dispatch_compat_php5.c
src/ext/request_hooks.c
src/ext/sandbox.h
tests/ext/includes/sanity_check.php
tests/ext/request-init-hook/raises_fatal_error.php
tests/ext/request-init-hook/request_init_hook_check_blacklisted_modules.phpt
tests/ext/request-init-hook/request_init_hook_confined_to_open_basedir.phpt
tests/ext/request-init-hook/request_init_hook_file_not_found.phpt
tests/ext/request-init-hook/request_init_hook_ignores_exceptions.phpt
tests/ext/request-init-hook/request_init_hook_ignores_fatal_errors.phpt
tests/ext/request-init-hook/run_file_before_request_handling.phpt
tests/ext/request-init-hook/throws_exception.php
tests/ext/simple_sanity_check.phpt

* This PR pulls #579 into master.
* It also adds more tests to the request init hook and specifically tests that the request init hook is properly sandboxed such that errors raised and exceptions thrown in the hook do not crash the app.
* It also includes a tweak to **dd-doctor.php** to better accommodate environments jailed with `open_basedir` and more debug info.
* It also includes a small fix for a compiler warning that was making the master build fail.

Request init hook edge cases tests

---

src/DDTrace/Integrations/Predis/PredisIntegration.php
tests/Integrations/Predis/PredisTest.php

Currently, the Predis integration makes our application crash when enabling APM (see issue #315). Because the interface that Predis provides doesn't allow getting the connection details for a cluster, in this PR I've removed the host and port tags for clusters. This also makes the retrieving of host and port a bit cleaner.

Fix Predis integration for clusters

---

.circleci/valgrind/valgrind_musl_suppressions.lib
Makefile
src/ext/dispatch_compat_php5.c
src/ext/trace.c
tests/ext/from_php_7_3_test_user_streams_consumed_bug.phpt
tests/ext/sandbox/exceptions_are_passed_to_the_tracing_closure_php5.phpt
tests/ext/sandbox/exceptions_in_original_call_rethrown_in_tracing_closure_php5.phpt

This PR fixes a memory issue with copying the function arguments when being passed to the tracing closure. It also cleans up some other testing issues, such as having memory leaks fail the build so we detect these issues sooner, and skipping a PHP 7.3 test that was still running on PHP 5.
These issues are isolated to the sandboxing API, which hasn't been released yet.

Fix copying function args for forwarding and clean up tests

---

tests/Frameworks/Laravel/Version_5_7/app/Http/Controllers/EloquentTestController.php

The testing infrastructure uses the builtin PHP web SAPI. If this SAPI does not generate output, it will sometimes leak memory and sometimes even segfault.
All tests should generate output. For now, I've added output to the Eloquent tests, which are the tests which helped us find this issue.

Generate output on test controllers

---

.phpcs.xml
bridge/dd_optional_deps_autoloader.php
bridge/dd_wrap_autoloader.php
src/DDTrace/Bootstrap.php
src/DDTrace/Encoders/SpanEncoder.php
src/DDTrace/Integrations/Curl/CurlIntegration.php
src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
src/DDTrace/Integrations/Symfony/SymfonyIntegration.php
src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
src/DDTrace/Propagators/CurlHeadersMap.php
src/DDTrace/Span.php
src/DDTrace/StartSpanOptionsFactory.php
src/DDTrace/Util/ObjectKVStore.php
tests/Common/IntegrationTestCase.php
tests/Frameworks/TestScenarios.php
tests/Frameworks/Util/Request/GetSpec.php
tests/Frameworks/Util/Request/RequestSpec.php
tests/Integration/Transport/HttpTest.php
tests/Integrations/Laravel/V4/EloquentTest.php
tests/Integrations/Laravel/V5_7/EloquentTest.php
tests/Integrations/Laravel/V5_7/PipelineTracingTest.php
tests/Integrations/Laravel/V5_8/EloquentTest.php
tests/Integrations/Memcached/MemcachedTest.php
tests/Integrations/Mysqli/MysqliTest.php
tests/Unit/BaseTestCase.php
tests/Unit/CleanEnvTrait.php
tests/Unit/Util/TryCatchFinallyTest.php
tests/bootstrap_utils.php

Yesterday PHP CodeSniffer v3.5.0 was released, and they added a bunch of lints to enforce the PSR-12 coding style. This fixes these issues.
There is one issue I've been unable to fix thus far, and `composer fix-lint` can't fix it either. I think it may be a bug: squizlabs/PHP_CodeSniffer#2616. For now, I have disabled this lint in this file.

Fix PHP CodeSniffer v3.5.0 lints

---

package/post-install.sh

This fixes a post-install issue with determining the PHP version. Supersedes #587 and fixes #586. Thanks Dan Sapala!

Make PHP API check more specific

---

src/ext/serializer.c
tests/ext/sandbox/exception_handling.phpt
tests/ext/sandbox/exception_handling_php5.phpt

Function arguments can have sensitive information. Since we do not
have a comprehensive way to know which function arguments are sensitive
we will just hide all of them.

Replace function arguments with ellipsis in stack traces

---

tests/Frameworks/Laravel/Version_4_2/app/controllers/EloquentTestController.php
tests/Frameworks/Laravel/Version_5_8/app/Http/Controllers/EloquentTestController.php

The testing infrastructure uses the builtin PHP web SAPI. If this
SAPI does not generate output, it will sometimes leak memory and
sometimes even segfault.
This is a continuation of the work started in PR #591.

Generate output on Eloquent test controllers (v4.2, v5.8)

---

.circleci/config.yml
composer.json
dockerfiles/frameworks/nginx_file_server/.gitignore
dockerfiles/frameworks/src/Dockerfile
dockerfiles/frameworks/src/wordpress/4.8.10.patch
dockerfiles/frameworks/src/wordpress/run.sh
dockerfiles/frameworks/src/wordpress/wp-tests-config.php
dockerfiles/frameworks/wordpress.yml

This PR adds WordPress 4.8.10 core tests (running on PHP 5.6) to the framework tests in preparation for the WordPress integration.
- ~~[ ] Changelog has been added to the appropriate release draft. For community contributors the reviewer is in charge of this task.~~

WordPress 4.8 core tests

---

.gitignore
bridge/dd_require_all.php
bridge/functions.php
composer.json
phpunit.xml
src/DDTrace/Integrations/CodeIgniter/V2/CodeIgniterSandboxedIntegration.php
src/DDTrace/Integrations/IntegrationsLoader.php
tests/Frameworks/CodeIgniter/Version_2_2/application/config/config.php
tests/Frameworks/CodeIgniter/Version_2_2/application/config/routes.php
tests/Frameworks/CodeIgniter/Version_2_2/application/controllers/error_.php
tests/Frameworks/CodeIgniter/Version_2_2/application/controllers/simple.php
tests/Frameworks/CodeIgniter/Version_2_2/application/controllers/simple_view.php
tests/Frameworks/CodeIgniter/Version_2_2/application/views/simple_view.php
tests/Frameworks/CodeIgniter/Version_2_2/ddshim.php
tests/Frameworks/CodeIgniter/Version_2_2/system/core/Benchmark.php
tests/Integrations/CodeIgniter/V2_2/CommonScenariosTest.php
tests/Unit/Integrations/IntegrationsLoaderTest.php

This adds an integration for CodeIgniter v2 , tested using v2.2.6. Support includes tracing views, `$this->db->query(...)`, caching, and controllers, including ones using `_remap`.
Note: on PHP 5 due to CodeIgniter's `call_user_func_array` usage the controller will not be traced.

Add CodeIgniter v2 integration

---

bridge/functions.php

When working with a real agent we have an issue with dd_trace_method
being used to set up the global tracer and company. Using the old
dd_trace API avoids this issue since it doesn't attempt to make any
spans.
At present, I'm not sure how to test it through CI. Will sleep on it.

Fix CodeIgniter v2 integration init hook

---

src/DDTrace/Integrations/Mysqli/MysqliIntegration.php

The `mysqli_connect()` span gets closed twice which can cause the span ID's to get out of sync between userland and internal spans. This PR fixes that. :)

Prevent mysqli_connect span from closing twice

---

bridge/dd_require_all.php
composer.json
src/DDTrace/Integrations/IntegrationsLoader.php
src/DDTrace/Integrations/Yii/V2/YiiIntegrationLoader.php
src/DDTrace/Integrations/Yii/YiiSandboxedIntegration.php
tests/Frameworks/Yii/Version_2_0_26/config/db.php
tests/Frameworks/Yii/Version_2_0_26/config/test_db.php
tests/Frameworks/Yii/Version_2_0_26/config/web.php
tests/Frameworks/Yii/Version_2_0_26/controllers/HomesController.php
tests/Frameworks/Yii/Version_2_0_26/controllers/SimpleController.php
tests/Frameworks/Yii/Version_2_0_26/views/simple/index.php
tests/Frameworks/Yii/Version_2_0_26/web/index.php
tests/Integrations/Yii/V2_0_26/CommonScenariosTest.php
tests/Integrations/Yii/V2_0_26/ParameterizedRouteTest.php

Adds support for Module and Controller runAction, View::renderFile, and adds some metadata to the root span.
Tests are for PHP 5.4, 5.6, and 7.

Add Yii 2 integration

---

.circleci/config.yml
docker-compose.yml

Images used for testing (specifically `5.4`,`5.6`,`7.0`,`7.1`,`7.2`,`7.3`) were moved to new repo `dd-trace-ci` and some utilities were added to the images.
This PR updates image versions in the `docker-compose.yml` file so development images are up to date with the latests tools.
In order to run a dev environment for a specificic version, e.g. `7.2`:
```
docker-composer run --rm 7.2
```
- ~[ ] Changelog has been added to the appropriate release draft. For community contributors the reviewer is in charge of this task.~

Move dev images to new dd-trace-ci repo

---

docker-compose.yml

Move back dev images to a public repo hosted on Docker Hub.

Move dev images again to docker hub

---

tests/Integrations/Yii/V2_0_26/ParameterizedRouteTest.php

The duplicate trait usage is unnecessary and causes an E_STRICT warning on PHP 5.6.

[Yii 2] Remove duplicate trait usage in test

---

.circleci/config.yml
composer.json
package.xml
phpunit.xml
src/DDTrace/Propagators/TextMap.php
src/DDTrace/SpanContext.php
src/DDTrace/Tracer.php
src/ext/ddtrace.c
src/ext/ddtrace.h
src/ext/random.c
src/ext/random.h
src/ext/span.c
tests/Common/SpanAssertion.php
tests/Common/SpanChecker.php
tests/Common/WebFrameworkTestCase.php
tests/DistributedTracing/DistributedTraceTest.php
tests/DistributedTracing/SamplingPriorityTest.php
tests/DistributedTracing/SandboxAndLegacyTest.php
tests/DistributedTracing/SyntheticsTest.php
tests/Frameworks/Custom/Version_Not_Autoloaded/sandbox.php
tests/Frameworks/Util/Request/GetSpec.php
tests/Frameworks/Util/Request/RequestSpec.php
tests/Integrations/Curl/CurlIntegrationTest.php
tests/ext/dd_trace_push_span_id_from_userland.phpt
tests/ext/sandbox/dd_trace_set_trace_id.phpt

Distributed traces serialize over the wire using HTTP headers `x-datadog-trace-id` and `x-datadog-parent-id`.
Due to the way the tracer supports both internal and userland spans, neither of these propagated ID's were being synced between the sandbox and legacy API's properly and would thus break distributed traces. This issue wasn't caught by the tests since there wasn't a full integration test for distributed traces.
This PR:
- Adds integration tests for distributed traces including Synthetics requests
- Properly handles `x-datadog-trace-id` and `x-datadog-parent-id` for internal and userland spans
- Improves validation and handling of span ID's
- Fixes a small edge-case where the sampling priority would erroneously be set to the default value when the `x-datadog-sampling-priority` …

Fix distributed trace ID handling

---

src/DDTrace/Integrations/CodeIgniter/V2/CodeIgniterSandboxedIntegration.php
src/DDTrace/Integrations/IntegrationsLoader.php
tests/AutoInstrumentation/AutoInstrumentationTest.php
tests/AutoInstrumentation/scenarios/composer_with_ddtrace_dependency/composer.json
tests/AutoInstrumentation/scenarios/composer_with_local_code_dependency/composer.json
tests/AutoInstrumentation/scenarios/composer_with_local_code_dependency/index.php

This PR fixes a bug in the namespace definition of the CodeIgniter integrations.
An application is impacted by this bug is all the following conditions apply:
- the application uses composer.
- ddtrace manual tracing is used (if your application only uses automatic instrumentation is not impacted).
- the application explicitly declare a dependency in composer instead of using classes provided by our extension.
What happens is that the when declaring a dependency our library in `composer.json` composer register an autoloader that place itself before our `OptionalDepsAutoloader` and `RequiredDepsAutoloader`, as it uses the `$prepend = true` flag when invoking `spl_autoload_register`.
As a result we have the following chain of autoloaders, that are attempted in this order:
1. …

Fix CodeIgniter namespace definition

---

.phpcs.xml
bridge/dd_require_all.php
src/DDTrace/Integrations/Integration.php
src/DDTrace/Integrations/IntegrationsLoader.php
src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
src/DDTrace/Integrations/Memcached/MemcachedSandboxedIntegration.php
src/DDTrace/Integrations/Mysqli/MysqliCommon.php
src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
src/DDTrace/Integrations/Mysqli/MysqliSandboxedIntegration.php
src/DDTrace/Integrations/SandboxedIntegration.php
tests/Common/IntegrationTestCase.php
tests/Common/SpanAssertion.php
tests/Common/SpanChecker.php
tests/Frameworks/WordPress/Version_4_8/wp-config.php
tests/Frameworks/WordPress/Version_4_8/wp-load.php
tests/Integrations/Mysqli/MysqliSandboxedTest.php
tests/Integrations/Mysqli/MysqliTest.php
tests/Integrations/WordPress/V4_8/CommonScenariosTest.php

Move Mysqli integration to sandboxed api. Along the way a few issues (mostly with testing) came out that forced me to add more changes to this PR than I would have wanted. I am sorry for the CR that has to look at quite a few things. Specifically:
- Wordpress tests had to be migrated to the new assertFlamegraph api. A minor bug in our integration was found and a card was created to keep track of it.
- SpanChecker had to be added the possibility to support multi-spans at the same level of a grph with the same name and resource. This has been done in a very quick and dirty way. We might want to provide a more sophisticated approach in the future, but this works for now in our use case.

Move Mysqli integration to sandboxed api

---

config.m4
src/ext/ddtrace.c
src/ext/ddtrace.h

This makes two changes aimed to make code review easier:
- Introduce DDTRACE_FE macros that mirror the PHP_FE/ZEND_FE macros _except_ that they do not have a trailing comma. This puts the comma in the usage site so that clang-format will do the Right Thing, instead of doing a very-long, unreviewable mess.
- I also sorted the list.
- Introduce a sorted, multi-line sources list variable in config.m4. Now when we add/remove files it should be easy to see.

Make code review of certain items easier

---

tests/Integrations/Symfony/V2_3/RouteNameTest.php
tests/Integrations/Symfony/V2_8/RouteNameTest.php
tests/Integrations/Symfony/V3_0/CommonScenariosTest.php
tests/Integrations/Symfony/V3_0/TraceSearchConfigTest.php
tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
tests/Integrations/Symfony/V3_3/TraceSearchConfigTest.php
tests/Integrations/Symfony/V3_4/AutofinishedTracesSymfony34Test.php
tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
tests/Integrations/Symfony/V3_4/TemplateEnginesTest.php
tests/Integrations/Symfony/V3_4/TraceSearchConfigTest.php
tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
tests/Integrations/Symfony/V4_0/TraceSearchConfigTest.php
tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
tests/Integrations/Symfony/V4_2/TraceSearchConfigTest.php

Move the entire Symfony test suite to flame graph assertion ahead of migrating Symfony to Sandboxed api.

Move entire Symfony test suite to flame graph assertions

---

bridge/dd_require_all.php
src/DDTrace/Integrations/IntegrationsLoader.php
src/DDTrace/Integrations/ZendFramework/ZendFrameworkSandboxedIntegration.php
tests/Integrations/ZendFramework/V1/CommonScenariosSanboxedTest.php
tests/Integrations/ZendFramework/V1/CommonScenariosTest.php
tests/Integrations/ZendFramework/V1/TraceSearchConfigSandboxedTest.php
tests/Integrations/ZendFramework/V1/TraceSearchConfigTest.php

This PR implements a sandboxed integration for the Zend Framework and enables it by default.

Migrate Zend framework integration to sandboxed api

---

tests/Frameworks/Symfony/Version_4_0/config/bundles.php

Recently we have had some CI failures due to DoctrineCacheBundle, and we are not alone; see:
https://github.com/doctrine/DoctrineCacheBundle/issues/156#issuecomment-555900329
This should unblock our CI builds due to this failure.

Remove DoctrineCacheBundle

---

docker-compose.yml
playground/index.php
playground/start-server.sh

A super simple playground that can be used to test basic changes to the tracer and send spans to the our real backend.
- ~[ ] Changelog has been added to the appropriate release draft. For community contributors the reviewer is in charge of this task.~

Add basic playground to live test changes to the code base

---

.circleci/config.yml
composer.json
tests/Integrations/Symfony/V4_0/CommonScenariosTest.php

A few things were happening that prevented CI to run correctly:
- `symfony/process:5.0.0` was released which had a more strict api
- 2 dev images (mysql and request replayer) were still on github registry and this caused issues when executing tests in CI on PRs from external contributors, who do not have privileges to download images from our github registry.
- Symfony 4.4 and Symfony 5.0 were released on Nov 21. The way we pinned Symfony tests for `4.0` was `^4.0` which means 4.3 (before Nov 21) and 4.4 (after Nov 21). So basically this means that 1) we assumed we were testing Symfony 4.0 while we were testing Symfony 4.3, 2) we do not work with symfony 4.4 (not app is not crashing, only some metadata is missing) and 3) just pinning version 4.0 does not resolve the issue as a bunch of …

Fix CI failing tests

---

src/ext/ddtrace.c
src/ext/ddtrace.h
src/ext/dispatch.c
src/ext/dispatch.h
src/ext/dispatch_setup.c
src/ext/engine_hooks.c
src/ext/engine_hooks.h

Ticket: https://datadoghq.atlassian.net/browse/APMPHP-42
This PR moves the opcode hooks to the new **engine_hooks.c** file and removes the previous handlers out of the extension globals and into true globals since they do not need to be thread safe in this context. It also includes a fix for forwarding the `ZEND_DO_ICALL` and `ZEND_DO_UCALL` handlers to the proper previous opcode handlers on PHP 7.

Refactor opcode hooks

---

.circleci/config.yml
config.m4
dockerfiles/frameworks/src/Dockerfile
m4/polyfill.m4
package.xml

With the recent addition of `ax_execinfo` for detecting support for `<execinfo.h>` support, this caused our builds to fail on CentOS 6. The version of autoconf on CentOS 6 is 2.63, and the `ax_execinfo` macro uses `m4_ifnblank` which was added in 2.64.
This adds a polyfill for `m4_inblank` so that it will work with autoconf < 2.64, such as CentOS 6.

Add polyfill.m4 to support autoconf < 2.64

---

src/DDTrace/Integrations/Memcached/MemcachedSandboxedIntegration.php
tests/Integrations/Memcached/MemcachedTest.php

This PR fixes #622 and #656.
The Memcached integration was calling `Memcached::getServerByKey()` after the original traced call in order to append the server info to the span metadata. That method mutates the result code returned from `Memcached::getResultCode()` which was causing unexpected behavior when there was an error returned from the original call.
The Memcached integration now uses `Memcached::getServerList()` in order to append the server metadata which does not mutate the result code.

[Memcached] Prevent mutation of the result code

---

.circleci/config.yml

Version 0.12.0 has been released and brings some new issues we need to fix. Until we get around to that, let's pin this at 0.11.x.
Links:
- [Failed master build](https://app.circleci.com/jobs/github/DataDog/dd-trace-php/92497)
- [JIRA ticket to fix 0.12 issues](https://datadoghq.atlassian.net/browse/APMPHP-80?atlOrigin=eyJpIjoiNmQ5Y2FhZTEwMzQwNDRhZWEzYWI0YjU2NjJhYjlhN2YiLCJwIjoiaiJ9).

Pin phpstan to 0.11.x

---

.circleci/valgrind/valgrind_7_3_musl_suppressions.lib
.circleci/valgrind/valgrind_musl_suppressions.lib
package.xml
src/ext/dispatch.h
src/ext/php7/dispatch.c
src/ext/php7/engine_hooks.c
src/ext/span.c
src/ext/span.h
tests/Integrations/WordPress/V4_8/CommonScenariosTest.php
tests/ext/sandbox/close-on-exit-retval.phpt
tests/ext/sandbox/close-on-exit.phpt

When a script calls `exit` the spans opened through the sandbox API will now get closed. This PR targets PHP 7 only.

Close open sandboxed spans on exit on PHP 7

---

tests/Integrations/Curl/CurlIntegrationTest.php

This updates PR #405 to the latest master. However, I wasn't sure what the Ubuntu tests were for -- issue 405 did not seem specific to Ubuntu -- so this only updates the test case.

Add test for HTTP headers being overridden

---

src/DDTrace/Integrations/IntegrationsLoader.php
src/DDTrace/Integrations/Symfony/SymfonySandboxedIntegration.php
tests/Integrations/Elasticsearch/V1/ElasticSearchIntegrationTest.php
tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
tests/Integrations/Symfony/V4_0/TraceSearchConfigTest.php
tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
tests/Integrations/Symfony/V4_2/TraceSearchConfigTest.php

Enable the sandboxed integration for Symfony now that sandboxed spans will close on exit.
Includes a minor fix for if the HttpKernel `$response` arg is null.

Enable Sandboxed Symfony Integration

---

src/DDTrace/Transport/Http.php
tests/Integration/Transport/HttpTest.php

While debugging curl timeouts, it is helpful to know exactly what the timeout settings were. This adds this info to the log.
It also copies curl's stderr stream into the error log if debug mode is enabled. This happens for all curl errors, not just timeouts.

Add extra info to curl errors

---

src/DDTrace/Configuration.php
tests/DistributedTracing/SyntheticsTest.php
tests/Unit/ConfigurationTest.php

We move to a naming more consistent with other tracers. We still support the deprecated name `DD_SAMPLING_RATE` at least until 0.40.0.

Rename env DD_SAMPLING_RATE to DD_TRACE_SAMPLE_RATE

---

src/DDTrace/Transport/Http.php
tests/Integration/Transport/HttpTest.php

Add the Empty Expect header to prevent Curl from auto adding 100-Continue workflow. 
This is a fix for https://github.com/DataDog/dd-trace-php/issues/651

Add Empty Expect Header to Avoid Curl 100-Continue

---

src/DDTrace/Integrations/Curl/CurlIntegration.php
tests/Common/SpanAssertion.php
tests/Common/SpanChecker.php
tests/Common/TracerTestTrait.php
tests/Integrations/Curl/CurlIntegrationTest.php

We're already calling curl_getinfo to get the URL and status code. Rather than throwing away the rest of the array, add it as tags to the span

Curl Integration: Add all available information from curl_getinfo as span tags

---

package.xml
src/ext/engine_hooks.c
src/ext/engine_hooks.h
src/ext/php5/engine_hooks.c
src/ext/php7/engine_hooks.c
tests/ext/sandbox/exception_is_defined.phpt
tests/ext/sandbox/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
tests/ext/sandbox/get_last_error.phpt

This fixes two issues, both part of #693:
1. On PHP 7 the exception argument to the tracing closure was previously set to undef, when it should have been null. This causes an undefined variable access warning if it's accessed when there isn't an exception. The sandbox catches it, but due to another bug it can leak out.
2. Don't leak the error out of the sandbox. It does this by backing up the previous error and restoring it.

Backup and restore last error

---

.circleci/config.yml
package/post-install.sh
tests/PostInstallHook/README.md
tests/PostInstallHook/bootstrap.php
tests/PostInstallHook/classes.php
tests/PostInstallHook/docker-compose.yml
tests/PostInstallHook/run-tests.sh
tests/PostInstallHook/test-installed.php
tests/PostInstallHook/test-not-installed.php

When installing from a package, the post-install script will install ddtrace for the default PHP version located at `$ which php`. This PR enables a user to target a specific PHP binary using `DD_TRACE_PHP_BIN` on hosts that have multiple versions of PHP installed.
For example, if I wanted to target `php-fpm7`, I could set the path to the binary using `DD_TRACE_PHP_BIN`.
```bash
$ export DD_TRACE_PHP_BIN=$(which php-fpm7)
$ #... install the extension ...
```

Target a specific PHP version during install

---

src/dd-doctor.php

When we ask customers to enable dd-doctor.php, then we find in the agent
logs the following error which is misleading:
```
2019-12-23 10:00:16 PST | TRACE | WARN | (pkg/trace/api/api.go:358 in handleTraces) | Error getting trace count: "HTTP header \"X-Datadog-Trace-Count\" not found". Functionality may be limited.
```
The reason for that is that dd-doctor.php sends an empty array of traces to
the agent to check connectivity. This request this not provide the header above
(it is created manually).
This PR adds the above header to all requests with a value of `X-Datadog-Trace-Count: 0`.
- ~[ ] Tests added for this feature/bug.~ Manual testing was successfully done.

avoid `X-Datadog-Trace-Count` error in agent during dd-doctor.php requests

---

package.xml
src/ext/php5/engine_hooks.c
src/ext/php7/engine_hooks.c
tests/ext/sandbox/exception_error_log.phpt

This adds more information to the error log when an exception is thrown in a tracing closure. This should speed up debugging in such cases.

Add more information to tracing closure exceptions

---

config.m4
package.xml
src/dogstatsd/README.md
src/dogstatsd/client.c
src/dogstatsd/dogstatsd_client/client.h
src/dogstatsd/test/client.cc
src/ext/ddtrace.c
src/ext/ddtrace.h
src/ext/dogstatsd_client.c
src/ext/dogstatsd_client.h
src/ext/signals.c
tests/ext/segfault_backtrace_enabled.phpt

This moves the client init to rinit and shutdown to rshutdown. This is in preparation for using the client in more places than only the sigsegv health metric, such as a heartbeat metric or tracking tracing closure exceptions.
It also does some minor cleanup, such as always emitting "Segmentation fault" (it was accidentally only emitting that message if health metrics are enabled) and allowing the caller of the dogstatsd client to control error messages.

Move dogstatsd client init to rinit

---

src/dogstatsd/CMakeLists.txt
src/dogstatsd/client.c
src/dogstatsd/dogstatsd_client/client.h
src/dogstatsd/test/client.cc

This adds support for gauges, histograms, and the ability to send metrics in a generic way. This also completely revamps the tests and fixes some C++ incompatibilities that I accidentally introduced recently.
At this point, the new features aren't used in the tracer anywhere yet because I'm still trying to figure out the best way to do that. I anticipate usage like:
```c
const char *metric = "datadog.tracer.heartbeat";
dogstatsd_metric_t type = DOGSTATSD_METRIC_COUNT;
dogstatsd_client_metric_send(&client, metric, "1", type, 0.01, NULL);
```

Add gauge, histogram, and generic metric helpers

---

package.xml
src/ext/php5/engine_hooks.c
src/ext/php7/engine_hooks.c
src/ext/span.c
tests/ext/sandbox/spans_out_of_sync.phpt

This PR fixes an edge case where spans can get out of sync if the open spans are cleared after the original call but before the tracing closure is run.

Handle out-of-sync spans

---

package.xml
src/DDTrace/Bootstrap.php
src/ext/php5/engine_hooks.c
src/ext/php7/engine_hooks.c
tests/ext/sandbox/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
tests/ext/sandbox/fatal_errors_ignored_in_shutdown.phpt

This PR ensures that the tracer flushing is sandboxed and also attempts to push the flushing to the end of all of the user shutdown handlers.
There's also a bonus update that exposes errors raised in tracing closures when `DD_TRACE_DEBUG=1`.

Sandbox tracer flushing

---

package.xml
tests/ext/sandbox/memory_limit_graceful_bailout.phpt

There is an edge case where the span stack can be left in a "dirty" state when a `zend_bailout()` occurs while serializing the spans. Now that #689 is merged, the stack is cleaned up properly in RSHUTDOWN. This PR just adds a test to hit that specific edge case.

Add test to hit memory limit in a shutdown hook

---

composer.json
src/DDTrace/OpenTracer/Tracer.php
tests/OpenTracerUnit/TracerTest.php

This now supports tags and other choices. It does not support references and child_of.
It also runs more pre-existing test cases for OpenTracing Tracer that were not being run on CI. I marked the pre-existing test cases that are currently failing ones as incomplete. We'll look at those later; I wanted to get the fix for the specific issue from #476 shippable.

Enhance OpenTracing StartSpanOptions support

---

docker-compose.yml
src/dogstatsd/client.c
src/dogstatsd/dogstatsd_client/client.h
src/dogstatsd/test/client.cc
src/ext/configuration.c
src/ext/configuration.h
src/ext/configuration_php_iface.c
src/ext/configuration_render.h
src/ext/dogstatsd_client.c
src/ext/env_config.c
src/ext/env_config.h

This adds a gauge metric to each request called `datadog.tracer.heartbeat` with a default sample rate of 0.1%. The sample rate can be controlled via the `DD_TRACE_HEALTH_METRICS_HEARTBEAT_SAMPLE_RATE` environment variable.

Add heartbeat health metric

---

src/DDTrace/Tracer.php
tests/Integration/TracerTest.php

Global tags were not set on internal spans generated by the sandboxed API. This PR adds such tags when the final traces is generated for serialization.

Set global tags in internal spans

---

package.xml
src/ext/ddtrace.c
tests/ext/sandbox/sandbox_api_not_available_on_unsupported_versions.phpt

Since the sandbox API is not supported on PHP 5.4, this PR removes the functions `dd_trace_function()` and `dd_trace_method()` on PHP 5.4 (and technically PHP 5.5 since that is not supported at all).

PHP 5.4: Remove sandbox API

---

src/ext/coms.c
src/ext/coms.h
src/ext/coms_curl.c
src/ext/coms_curl.h
src/ext/coms_debug.c
src/ext/coms_debug.h

Update code style to C99 and fix small potential bug in `ddtrace_coms_buffer_data` with a return-type mismatch. This potential bug is unlikely to have any effect in practice, and would be isolated to 
disabled-by-default BETA background sender.
Code style changes include:
- Add void parameters to functions that take no args
- Convert BOOL_T->bool, TRUE->true, FALSE->false. Note that C99's bool will do a conversion from integral types; the BOOL_T will not and be vulnerable to truncation issues (which is basically what the small potential bug was).
- Remove `inline` from static functions in source files
- Remove `static`  from inline functions in header files
- Rename a few macros to be consistent with the rest of the repo
- Refactor `ddtrace_coms_buffer_data` and …

Update coms code style to C99

---

.circleci/config.yml
LICENSE
LICENSE.Apache
LICENSE.BSD3
NOTICE

This PR adds the option to ingest the tracer as BSD3 or Apache 2. See https://github.com/DataDog/dd-trace-php/issues/692 for discussion.

Add dual license

---

dockerfiles/ci/xfail_tests/7.4.list
package.xml

A cherry pick from #731 as a follow-up to #727.
This PR also adds some PHP 7.4 tests to the xfail list since the `datadog/dd-trace-ci:php-7.4-debug-buster` container was updated to the latest patch version of PHP 7.4.

Add new license files to package.xml

---

config.m4
package.xml
src/DDTrace/Tracer.php
src/DDTrace/Transport/Http.php
src/ext/arrays.c
src/ext/arrays.h
src/ext/comms_php.c
src/ext/comms_php.h
src/ext/coms.c
src/ext/coms.h
src/ext/coms_curl.c
src/ext/coms_curl.h
src/ext/coms_debug.c
src/ext/ddtrace.c
tests/bootstrap.php
tests/ext/dd_trace_coms_curl_out.phpt
tests/ext/dd_trace_coms_test_parallel_writer_consistency.phpt
tests/ext/dd_trace_coms_test_span_concatenation.phpt
tests/ext/dd_trace_coms_writer_shutdown_and_flush_on_exit.phpt
tests/ext/dd_trace_send_traces_via_thread.phpt

This updates the background sender to re-use headers that have already been gathered by PHP, and also uses the PHP encoder instead of serializing msgpack on its own. As a side effect, the whole trace is buffered at once. This means in the future we can significantly simplify the background sender code.

Update background sender

---

.circleci/config.yml
composer.json

Composer was running out of memory when updating Symfony 2.8 and was getting killed by CircleCi. Seeing if running with a larger node will clear it up.
Also fixes a mis-spelling in the name "increase-memory-limit."

Increase available memory for PHP 5.6 Web Integration tests

---

src/DDTrace/Bootstrap.php
tests/Integration/BootstrapTest.php
tests/Integration/BootstrapTest_files/index.php

Release 0.37.0 introduced two changes that, together, prevent traces to be sent when the span limit is reached.
Specifically:
- #689 prevents a callback registered through `dd_trace_(method|function)` to be called if we are in limited mode, AKA if the number of spans exceed the value DD_TRACE_SPANS_LIMIT which defaults to 1000.
- #707 sandboxed the execution of the final flush of the tracer using, as a hook, a callback registered through `dd_trace_method()`.
As a consequence, when the limit of `DD_TRACE_SPANS_LIMIT` was reached (default is 1000) no more callbacks are invoked anymore, including the final one that would trigger sending traces to the agent.
This PR forces the execution of the callback used to flush through the parameter `'instrument_when_limited' => 1`.

Traces are flushed when in limited mode

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

This reverts commit 55ef4a00bb2ca95ee316de77b48bf5a373bea2b1, reversing changes made to a074ef1bd22fd864f14c6823ad33f5990df79d4c.
The release PR was accidentally pulled into master instead of ddtrace-0.39.1.

Revert "Merge pull request #747 from DataDog/release-0.39.1"

---

src/dd-doctor.php

This PR adds a line to dd-doctor showing if background sender is enabled and how to enable it.
- ~[ ] Tests added for this feature/bug.~ It was manually tested

Background sender debug info in dd-doctor

---

phpunit.xml
src/DDTrace/Transport/Http.php
tests/Frameworks/Custom/Version_Autoloaded/src/CircuitBreakerController.php
tests/Frameworks/Custom/Version_Autoloaded/src/routes.php
tests/Integrations/Custom/Autoloaded/CircuitBreakerTest.php

The background sender can fall back to the PHP Transport\HTTP sender if certain conditions are met,  so the open circuit-breaker code was left in place for these situations. This PR fixes a bug where even if the background sender is used the open circuit breaker would prevent traces being sent, instead of only applying if the PHP fallback is used.

Circuit breaker should not prevent background sender

---

Makefile
config.m4

This `-lexecinfo` check is needed for Alpine containers where execinfo is a separate library from the libc. Relates to #381.
Also fixes some mixed tabs and spaces.

Fix execinfo on builds from source in Alpine containers

---

package.xml
src/ext/php7/engine_hooks.c
tests/ext/sandbox/exit_and_drop_span.phpt

It is possible to cause a segmentation fault if a span is dropped from an instrumented call that uses `exit`. This PR ensures that this case is handled gracefully.
No customers have reported running into this issue.

Gracefully handle a dropped span on exit

---

src/DDTrace/Encoders/SpanEncoder.php
src/ext/configuration.h
src/ext/engine_hooks.c
tests/Integrations/Custom/Autoloaded/CompileTimeDisabledTest.php
tests/Integrations/Custom/Autoloaded/CompileTimeEnabledTest.php

Our `compile_file` hook will delay compiling files a little bit by measuring how long it takes. If those files are prone to SIGBUS then this hook will exacerbate those issues by keeping them open slightly longer.
This flag defaults to on as most customers do not have this issue, but those who do have it can turn it off by setting `DD_TRACE_MEASURE_COMPILE_TIME=false` in their environment.

Put compile_file hook behind a feature flag, default on

---

config.m4

Require curl at configuration time. For some time curl has been required, but the configuration would continue even if it couldn't find it.
This PR also uses PHP_ADD_LIBRARY instead of using *FLAGS directly.

Require curl at configuration time

---

.phpcs.xml
CONTRIBUTING.md
composer.json

Our contributing guidelines were left a little bit behind, with a few not yet up-to-date steps.
This PR applies the following changes:
- add testing scripts for php 7.3 and 7.4
- update instructions on how to setup a dev env for a specific version instead of bringing up all containers
It fixes #756 

Bring CONTRIBUTING.md up to date with current dev process

---

src/DDTrace/Transport/Http.php
src/ext/coms.c
src/ext/configuration.h

Separate background sender timeout env vars from userland. This allows them to be controlled independently, which is important because they both be in use at the same time. The background sender has higher default values than the PHP components.
Also create `DD_TRACE_BGS_ENABLED` to replace `DD_TRACE_BETA_SEND_TRACES_VIA_THREAD`
for when the feature goes into GA.

Separate background sender timeout env vars from userland

---

src/ext/configuration.c
src/ext/configuration.h
src/ext/configuration_render.h
src/ext/dogstatsd_client.c
src/ext/signals.c

This PR changes the `configuration.h` family of files to use more modern C standard features. 
- Convert static inline functions to inline only
- Convert BOOL_T to bool
- Add (void) to 0-arg functions
There should not be any functional changes in this PR.

Modernize configuration

---

phpunit.xml
src/ext/coms.c
src/ext/ddtrace.c
src/ext/logging.c
src/ext/logging.h
tests/Integrations/Custom/Autoloaded/BackgroundSenderLogTest.php

This changes the background sender to log to a file instead of stdout.
Also enables some missing tests on CI.

Log background sender messages to error_log

---

src/ext/php5/engine_hooks.c
src/ext/span.c
src/ext/span.h
tests/ext/sandbox/close-on-exit-retval.phpt
tests/ext/sandbox/close-on-exit.phpt
tests/ext/sandbox/exit_and_drop_span.phpt

This PR adds support for closing sandbox spans when `exit` is used on PHP 5. This feature was already available in PHP 7 via #679.

Close open sandboxed spans on exit (PHP 5)

---

config.m4

As reported in #778, `pecl install datadog_trace` is not working. This PR fixes up the config.m4 file to support installation of the extension through this method.
Note for anyone reading this who installs via pecl: this only installs the extension. You still need to install the PHP sources (can be done with composer, but you need to keep extension and composer version in sync), and if you want automated tracing you still need to add ini settings such as `extension=ddtrace` and `ddtrace.request_init_hook=/path/to/vendor/datadog/dd-trace/bridge/dd_wrap_autoloader.php`.

Fix pecl installs

---

src/ext/ddtrace.c
src/ext/logging.c
src/ext/logging.h

Delay saving the `error_log` until RINIT. As a consequence, nothing can be logged until the first request is served. I don't think we can log anything at the moment without any requests, so this doesn't matter.
Reported in #782.

Fix background sender logging for ZTS

---

.circleci/config.yml
package.xml
src/ext/ddtrace.c
src/ext/dispatch.h
src/ext/php7/engine_hooks.c
tests/ext/dd_trace_api_error.phpt
tests/ext/sandbox-prehook/access_modifier_method_access_hook.phpt
tests/ext/sandbox-prehook/access_modifier_property_access_hook.phpt
tests/ext/sandbox-prehook/args_copy_before_mutation.phpt
tests/ext/sandbox-prehook/close_on_exit.phpt
tests/ext/sandbox-prehook/closure_arg_exception.phpt
tests/ext/sandbox-prehook/closure_arg_retval.phpt
tests/ext/sandbox-prehook/dd_trace_api_error.phpt
tests/ext/sandbox-prehook/dd_trace_function_internal.phpt
tests/ext/sandbox-prehook/dd_trace_function_userland.phpt
tests/ext/sandbox-prehook/dd_trace_method.phpt
tests/ext/sandbox-prehook/dd_trace_method_binds_called_object.phpt
tests/ext/sandbox-prehook/dd_trace_method_works_with_dd_trace.phpt
tests/ext/sandbox-prehook/drop_spans.phpt
tests/ext/sandbox-prehook/exception_error_log.phpt
tests/ext/sandbox-prehook/exception_handling.phpt
tests/ext/sandbox-prehook/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
tests/ext/sandbox-prehook/exit_and_drop_span.phpt
tests/ext/sandbox-prehook/keep_spans_in_limited_tracing_userland_functions.phpt
tests/ext/sandbox-prehook/new_static.phpt
tests/ext/sandbox-prehook/php5_unsupported.phpt
tests/ext/sandbox-prehook/trace_static_method.phpt
tests/ext/sandbox-prehook/variable_length_parameter_list.phpt
tests/ext/sandbox/dd_trace_api_error.phpt

This PR allows tracing closures to be run _before_ the original call by using the `prehook` option.
```php
dd_trace_function('foo', [
'prehook' => function (\DDTrace\SpanData $span, array $args) {
// ...
}
]);
```
This feature is only supported on PHP 7.

Prehook: run tracing closures before the original call (PHP 7)

---

package.xml
src/ext/php7/engine_hooks.c
tests/ext/sandbox/retval_is_null_with_exception.phpt

This PR ensures that if a return value is of type `IS_UNDEF`, it will be passed to the tracing closure as null.
Fixes #788.

Pass return value as null to tracing closure when value IS_UNDEF

---

src/ext/env_config.c
src/ext/env_config.h
src/ext/logging.c

With C11 on Alpine under libc6-compat, the strdup function will segfault on some inputs such as `php://stderr`. This makes no sense, but it is reality; see #797.
Use `ddtrace_strdup` instead. The fact this function exists kind of makes me think we've hit this case before. I've better documented it to hopefully help us find it, but I wonder if there's a tool we can use to forbid the use of certain functions?
Aside from this, we should probably work towards packaging Alpine with musl directly instead of using libc6-compat.

Avoid strdup

---

src/ext/configuration.h
tests/ext/read_c_configuration.phpt

The reliability environment shows that our work on the background sender has improved response times for the end-user. We've also had a few customers use it in beta, so we're confident now to enable it by default.

Enable background sender (BGS) by default

---

playground/start-server.sh
src/DDTrace/Transport/Http.php
tests/Integration/Transport/HttpTest.php

We were calculating and setting the content-length header when not using the background sender.
This was probably the source of errors `unexpected EOF` in the trace agents logs.
While we were not able to deterministically assert this, here are a few facts:
- Literature seems to relegate that error to Content-Length > actualy payload size
- I was able to recreate from curl
- I was able to recreate after hours-long random spans/trace generation using msgpack
- In long runs, I was never able to recreate this error using json
- If Content-Length is not provided, it is automatically added by the underlying curl lib
- I assume curl is better at calculating the payload compared to us using PHP's strlen on a binary var
- That explixit Content-Length header was there from forever (one of the first …

Let curl calculate Content-Length header value when sending requests to the agent

---

src/DDTrace/Transport/Http.php
src/ext/compatibility.h
src/ext/coms.c
src/ext/configuration.h
tests/Common/TracerTestTrait.php
tests/Common/WebFrameworkTestCase.php
tests/Integrations/Custom/Autoloaded/BackgroundSenderLogTest.php
tests/Integrations/Custom/Autoloaded/CircuitBreakerTest.php
tests/Integrations/Custom/Autoloaded/TraceSearchConfigTest.php
tests/ext/read_c_configuration.phpt

Building on PR #796, this enables the background sender (BGS) across the entire testsuite. Since the BGS works only with msgpack, we change the default encoding too.

Enable background sender in tests

---

bridge/dd_require_all.php
src/DDTrace/Integrations/Guzzle/GuzzleSandboxedIntegration.php
src/DDTrace/Integrations/IntegrationsLoader.php
tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V5/GuzzleSandboxedIntegrationTest.php
tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V6/GuzzleSandboxedIntegrationTest.php

This adds sandboxing to the Guzzle integration using a posthook.
Note that the Guzzle 6 distributed tracing did not work, but curl adds the distributed headers anyway, so in practice everything is fine. I am still verifying if Guzzle 5 has the same issue.
I mention this because the current iteration does not attempt to send these in Guzzle anymore because we can't use a pre- and post- hook simultaneously -- not yet, anyway. Since we have to use a post-hook to get the HTTP response status and curl already adds the distributed tracing headers, this may be okay even on Guzzle 5.

Sandbox the Guzzle integration

---

src/DDTrace/Configuration.php
src/DDTrace/Span.php
src/DDTrace/Tracer.php
tests/AutoInstrumentation/AutoInstrumentationTest.php
tests/Common/SpanChecker.php
tests/Common/TracerTestTrait.php
tests/Common/WebFrameworkTestCase.php
tests/Integration/TracerTest.php
tests/Integration/TracerTest_files/index.php
tests/Integrations/CLI/EnvSerializer.php
tests/Integrations/Custom/Autoloaded/BackgroundSenderLogTest.php
tests/Integrations/Custom/Autoloaded/CircuitBreakerTest.php
tests/Unit/ConfigurationTest.php
tests/WebServer.php

This PR enable the feature request URI by default. In addition to that a few changes were necessary to test real web request with different env variables.
- [*] (only for Members) Changelog has been added to the appropriate release draft. Create one if necessary.
- [*] Tests added for this feature/bug.

Uri to resource name ON by default

---

src/DDTrace/Configuration.php
src/DDTrace/Tracer.php
tests/Integration/TracerTest.php
tests/Integration/TracerTest_files/index.php
tests/Unit/ConfigurationTest.php

This PR adds the possibility to implement service mapping via env variables:
Examples:
- Simple service renaming:
```DD_SERVICE_MAPPING=pdo:payments-db,mysqli:orders-db```
- Together with split by domain:
```
DD_TRACE_HTTP_CLIENT_SPLIT_BY_DOMAIN=true
DD_SERVICE_MAPPING=host-api.example.com:example-api,host-api.internal.com:internal-api
```

Implement service mapping

---

src/DDTrace/Integrations/Guzzle/GuzzleSandboxedIntegration.php

This is a tiny bugfix to #809; I forgot to return `Integration::LOADED` which causes entries like this to show up in the debug log:
> [2020-04-10T20:29:07+00:00] [ddtrace] [error] - Invalid value returning by integration loader for guzzle:

Return that the sandboxed Guzzle integration loaded

---

.circleci/config.yml

This reverts commit c473a42324389bf559e7748d9c06910ca5362373.
Yesterday, this was done because nobody was around to force-push some bugfixes which definitely did not cause those tests to fail, and were blocking other work. However, they were not supposed to block a merge anyway, so I'm opening this PR to get that worked out.

Revert "Stop running PHP 5.4 integration tests"

---

Makefile
config.m4
package.xml
src/ext/auto_flush.h
src/ext/configuration.h
src/ext/php5/auto_flush.c
src/ext/php7/auto_flush.c
src/ext/span.c
tests/ext/sandbox/auto_flush.phpt
tests/ext/sandbox/fake_tracer.inc

This change add a feature to auto-flush spans when the internal open span count reaches zero. The feature is enabled by setting `DD_TRACE_AUTO_FLUSH_ENABLED=1`. This change allows flushing multiple traces within the same request.

Auto flushing (PHP 7)

---

package.xml
src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchSandboxedIntegration.php
src/DDTrace/Integrations/Yii/V2/YiiIntegrationLoader.php
src/ext/ddtrace.c
src/ext/dispatch.c
src/ext/dispatch.h
src/ext/dispatch_setup.c
src/ext/engine_hooks.c
src/ext/php5/dispatch.c
src/ext/php5/engine_hooks.c
src/ext/php7/dispatch.c
src/ext/php7/engine_hooks.c
src/ext/span.c
src/ext/span.h
tests/ext/sandbox-prehook/variadic_args_internal.phpt
tests/ext/sandbox/exception_does_not_close_span_that_catches.phpt
tests/ext/sandbox/exception_from_user_error_handler_internal.phpt
tests/ext/sandbox/exception_handled_for_correct_catch_block.phpt
tests/ext/sandbox/exception_handled_in_correct_catch_frame.phpt
tests/ext/sandbox/exception_handled_in_multicatch.phpt
tests/ext/sandbox/exception_handled_with_finally.phpt
tests/ext/sandbox/exceptions_are_passed_to_the_tracing_closure.phpt
tests/ext/sandbox/generator.phpt
tests/ext/sandbox/generator_not_supported.phpt
tests/ext/sandbox/generator_with_exception.phpt
tests/ext/sandbox/generator_with_return.phpt
tests/ext/sandbox/generator_yield_from.phpt
tests/ext/sandbox/return_by_ref.phpt
tests/ext/sandbox/variadic_args_internal.phpt
tests/ext/sandbox/vm_var_types_return.phpt

This PR addresses part two of a two-part refactor of the opcode handlers. The the first part was merged in #754. This PR changes the way the tracer hooks into the engine for instrumented calls for PHP 7. PHP 5 will be addressed in a separate PR.
Before this PR, instrumented calls would be forwarded from within the custom handlers for `ZEND_DO_FCALL` and friends. This required the handlers to return `ZEND_USER_OPCODE_LEAVE` to the VM which would prevent any downstream neighboring extensions from reliably hooking the function call opcodes.
This PR will start the span and run any prehook tracking closures in the function-call handlers and immediately return `ZEND_USER_OPCODE_DISPATCH` to the VM to resume normal execution. The span is stopped by hooking return opcodes. Exceptions are tracked …

Always return unaltered VM dispatch (PHP 7)

---

package.xml
src/DDTrace/Bootstrap.php
src/ext/ddtrace.c
src/ext/php7/auto_flush.c
src/ext/span.c
tests/ext/sandbox/auto_flush_disables_tracing.phpt
tests/ext/sandbox/auto_flush_userland_root_span.phpt
tests/ext/sandbox/fake_tracer.inc

This followup PR to #819 enables auto flushing when the root span is created in userland. Before this, only internal root spans would trigger auto flushing.
This also includes a fix to disable instrumentation during auto flushing to prevent infinite recursion.

Auto flush with userland root span

---

src/ext/dispatch.c
src/ext/dispatch.h
src/ext/php5/engine_hooks.c
src/ext/php7/engine_hooks.c
tooling/bin/cputime.d

The cputime.d dtrace script showed ddtrace_find_dispatch as a function of interest for performance.  This commit does not change performance very much; basically there is a addref/delref that is avoided. However, I think the code is better and the cputime.d script will probably be useful later.

Cleanup finding dispatch and add cputime.d dtrace script

---

config.m4
package.xml
src/ext/clocks.c
src/ext/clocks.h
src/ext/ddtrace.c
src/ext/engine_hooks.c
src/ext/span.c
src/ext/span.h

This adds three clock functions at ~both the C and PHP levels~ the C level:
- ddtrace_monotonic_nsec
- ddtrace_monotonic_usec
- ddtrace_realtime_nsec
The first two are monontonic clock ticks in nanoseconds and
microseconds respectively. The latter is a system clock time
in nanoseconds.
It consolidates the existing clock functions found in span.c and
engine_hooks.c.
It also adds three typedefs, one for each clock type+unit:
- ddtrace_monotonic_nsec_t
- ddtrace_monotonic_usec_t
- ddtrace_realtime_nsec_t
This helps convey the semantics of the result, such as in
ddtrace_span_t where they were previously just uint64_t.
This does not change the `DDTrace\Time::now()` call. It
appears that it is doing microseconds, but then multiplies
it by the wrong multipliers, and the encoder appends extra …

Consolidate internal monotonic and realtime clocks

---

src/ext/serializer.c
tests/ext/sandbox-prehook/dd_trace_method.phpt
tests/ext/sandbox-prehook/dd_trace_method_works_with_dd_trace.phpt
tests/ext/sandbox/dd_trace_function_complex.phpt
tests/ext/sandbox/dd_trace_function_internal.phpt
tests/ext/sandbox/dd_trace_function_userland.phpt
tests/ext/sandbox/dd_trace_method.phpt
tests/ext/sandbox/dd_trace_method_works_with_dd_trace.phpt
tests/ext/sandbox/errors_are_flagged_from_userland.phpt

The Agent only supports string values in the `meta` array. This PR ensures that when a pid is added to a root internal span, it is added as a string instead of a long.

Convert pid from long to string for internal spans

---

src/ext/ddtrace.c
src/ext/handlers_curl.h
src/ext/php5/handlers_curl.c
src/ext/php7/handlers_curl.c

This provides two main changes:
- Removes the curl rinit hook that found the `le_curl` resource id. Instead we install a handler for `curl_init` that fetches this same value. This removes upfront cost but slightly increases it at usage site.
- Cleans up how the handlers are installed. Previously this was duplicated for every handler; now it is consolidated into a single array and function.
Targeting ddtrace v0.43.0, which will need to cherry-pick this change if merged.

Refactor curl handlers

---

src/ext/ddtrace.c
src/ext/handlers_curl.h
src/ext/php5/handlers_curl.c
src/ext/php7/handlers_curl.c

This picks up some curl refactoring for the 0.43.0, which moves some of the cost for the curl integration out of rinit into `curl_init`.

Cherry-pick #831 into 0.43.0

---

dockerfiles/ci/xfail_tests/7.4.list
package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Version bump to `0.43.0`. Also contains a cherry-pick from #835 because the Buster container was updated for the PHP 7.4 language tests.

Bump version to 0.43.0

---

.circleci/config.yml
dockerfiles/ci/xfail_tests/7.3.list
dockerfiles/ci/xfail_tests/7.4.list

The Buster containers were updated to the latest patch versions of PHP. There were a few new tests that have object ID's in the output that were added to the xfail list.
The PHP source directory also moved from `/usr/src/php` to `/usr/local/src/php`.

Fix CI build after latest Buster container updates

---

src/ext/arrays.c
src/ext/arrays.h
src/ext/dispatch.c
src/ext/dispatch.h
src/ext/dispatch_setup.c
src/ext/php5/dispatch.c
src/ext/php7/engine_hooks.c
src/ext/serializer.c

`ddtrace_hash_find_ptr` is `zend_hash_str_find_ptr` for both PHP 5 and 7.
`ddtrace_hash_find_ptr_lc` lowercases its string parameter, using the stack if the string is small enough (probably is), and then calls ddtrace_hash_find_ptr. This improved performance in a local
test using dtrace by about 4% (will be less pronounced in real apps).
Also adds some ZEND_STRL's in serializer. I thought I found a bug due to being off by one, but turned out to not be a bug; left a comment to save someone some time in the future.

Add ddtrace_hash_find_ptr_lc and which stack-allocates small strings

---

.circleci/config.yml
.gitignore
src/ext/ddtrace.c
tests/Common/WebFrameworkTestCase.php
tests/Metrics/SigSegV/SigSegVTest.php
tests/Nginx/NginxServer.php
tests/Nginx/nginx-default.conf
tests/WebServer.php

This PR whitelists the `cgi-fcgi` SAPI.
For build branches, the web integration tests will be run via nginx and FastCGI for PHP 7.2, 7.3 and 7.4. These tests only run on build branches since they take longer to run than the standard web integration tests (which use the built-in web server from the CLI SAPI). On non-build branches, the web integration tests will continue to run as before for all supported PHP versions.

Whitelist the cgi-fcgi SAPI

---

src/ext/ddtrace.c
src/ext/env_config.c
src/ext/env_config.h

The functionality these ddtrace_config_* functions replaced used
PHP's getenv(), which will by default use sapi_getenv first, and
getenv second.
I avoided the use of existing env related functions because they
will duplicate the string to get it out of the Zend Memory Manager,
but these functions are perf sensitive, so I didn't want to copy
any more than is necessary.
This also means ddtrace_getenv() cannot be used from the background
writer thread.

Add ddtrace_getenv and use it ddtrace_config_* PHP functions

---

src/DDTrace/Integrations/Curl/CurlIntegration.php
src/ext/php7/handlers_curl.c
tests/Common/IntegrationTestCase.php

Both legacy and sandboxed integrations were caching the result of
Configuration::get() -- I'm not sure which recent change makes this
impossible, but nonetheless that's how it currently is.
Also fix sandboxed curl integration's `copy_curl_handle` and distributed
tracing checks.
This PR is unnecessary if we merge in #833 soon, as the configuration
and curl fixes are also contained in that branch.

Fix curl integrations

---

src/ext/ddtrace.c

The most recent merge into master has a failing test where it [tries to compile on CentOS 7 and fails](https://app.circleci.com/jobs/github/DataDog/dd-trace-php/148045). This fixes the issue.

Fix build error on CentOS 7

---

src/DDTrace/Configuration.php
src/DDTrace/Integrations/Curl/CurlIntegration.php
src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
src/DDTrace/StartSpanOptionsFactory.php
src/ext/configuration.c
src/ext/configuration.h
src/ext/ddtrace.c
src/ext/ddtrace_string.h
src/ext/php7/handlers_curl.c
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Integrations/Elasticsearch/V1/ElasticSearchIntegrationTest.php
tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
tests/Unit/ConfigurationTest.php
tests/Unit/StartSpanOptionsFactoryTest.php

Create `ddtrace_config_distributed_tracing_enabled()` for both PHP and the C extension.
- Migrate uses of `DDTrace\Configuration->isDistributedTracingEnabled()` to `ddtrace_config_distributed_tracing_enabled()` for both PHP and C extension.
- Migrate `DDTrace\Configuration->isDistributedTracingEnabled()` itself to use `ddtrace_config_distributed_tracing_enabled()` for backwards compatibility.
Also cleanup some recently added configuration related code in ddtrace.c by moving it into configuration.{c,h}.
This work has been split off from #833 and improved.

Add ddtrace_config_distributed_tracing_enabled

---

src/DDTrace/Integrations/Curl/CurlIntegration.php
src/DDTrace/Integrations/Curl/CurlSandboxedIntegration.php
tests/Integrations/CLI/Custom/Autoloaded/NoRootSpanTest.php
tests/Integrations/Curl/CurlIntegrationTest.php

Use the normalized URL rather than the sanitized URL as the resource name for curl requests. This allows for URLs like users/123 and users/456 to be grouped togerher providing more useful summary statistics in datadog.
See: https://github.com/DataDog/dd-trace-php/issues/864

Use normalized URL as the resource name for curl

---

package.xml
src/ext/php5/handlers_curl.c
src/ext/php7/engine_hooks.c
tests/ext/sandbox/variadic_no_args.phpt

Variadic arguments were being passed to a tracing closure incorrectly when the function signature was empty. This fixes issue #857. 
This also includes a tiny build fix for PHP 5 on Mac.

Fix variadic args with empty function signature

---

.circleci/config.yml
phpstan.neon
src/DDTrace/Configuration/AbstractConfiguration.php
src/DDTrace/NoopScopeManager.php
src/DDTrace/NoopTracer.php

While fixing phpstan errors for another branch I remembered we don't use the latest phpstan version because there were issues with the new version. It's stable now and there are only a handful of failures, which are genuine.
Note that I ignore one issue. Throwing an exception would make the issue go away and is arguably what should have been done when it was stubbed, but that could cause issues for clients. So we'll just ignore it.

Bump phpstan to 0.12 and fix issues

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

If you are using dd_trace, dd_trace_function, or dd_trace_method then you need to call these functions before the first invocation of the target e.g. dd_trace('foo', ...) should be done before foo is called for the first time.
- Compile to one single file #840, #874
- Simplify configuration #833, #870
- Refactor module blacklist #852
- Cache that a function is not traced #854, #863
- Simplify spl_autoload_register instrumentation #867
- Use normalized URL as the resource name for curl #869 (thanks, @akdh!)
- Sandbox header and http_response_code #875
- Fix variadic args with empty function signature #872
- Bump phpstan to 0.12 and fix issues #841

Bump version to 0.45.0

---

bridge/_files.php
src/DDTrace/Integrations/IntegrationsLoader.php
src/DDTrace/Integrations/Slim/SlimSandboxedIntegration.php
tests/Integrations/Slim/V3_12/CommonScenariosSandboxedTest.php

This PR moves the Slim integration to the sandbox api. One span (the one for controller) added to the stack as we need to instrument the controller in order to extract relevant metadata and non-instrumentation api is not implemented yet, so as a consequence we would see orphaned spans.
Cavits: `error.msg` is missing in php 5.6 as we are not able to trace `*->__invoke`.

Move Slim to Sandboxed API

---

src/DDTrace/Integrations/Curl/CurlSandboxedIntegration.php
src/DDTrace/Integrations/Guzzle/GuzzleSandboxedIntegration.php
tests/Common/SpanChecker.php
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Integrations/Curl/curl_in_web_request.php
tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V5/guzzle_in_web_request.php
tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V6/guzzle_in_web_request.php

Problem:
- `curl` and `guzzle` should not inherit the top level service name. Their service name should instead always be `curl` and `guzzle` respectively.
- If they inherit top level app name as a service, then service mapping is impossible.
What was happening:
- For `curl` and `guzzle` we were computing the service name as `$service = \ddtrace_config_app_name(self::NAME);` when we were 'loading' the integration.
- If a user DID NOT set `DD_SERVICE_NAME` then what we would end up with was `curl'/'guzzle`.
- If a user DID set `DD_SERVICE_NAME` then the default `self::NAME` was not used and the service name was set to the top level service name, making service mapping impossible.
Why we did not detect it in tests?
- We only tested `curl` and `guzzle` in integration (not in a web request …

Prevent curl and guzzle from inheriting top level app name

---

src/DDTrace/Integrations/PDO/PDOIntegration.php
src/DDTrace/Integrations/PDO/PDOSandboxedIntegration.php
tests/Integrations/PDO/PDOSandboxedTest.php
tests/Integrations/PDO/PDOTest.php

Problem: we found out the having UC PDO name as sa service generates confusion with service mapping
as users were trying to do pdo:something. The reason is that service name appears as 'pdo' LC
in UI
Possible issues: manually testing this showed no drawbacks can be thought of:
- traces already appear as 'pdo' in UI
- the LC version is used in service map
- search and monitors work with LC

Change PDO service name to lowercase

---

package.xml
src/ext/php7/auto_flush.c
tests/ext/sandbox/auto_flush.phpt
tests/ext/sandbox/auto_flush_attach_exception.phpt
tests/ext/sandbox/auto_flush_disables_tracing.phpt
tests/ext/sandbox/auto_flush_sandbox_exception.phpt
tests/ext/sandbox/auto_flush_userland_root_span.phpt
tests/ext/sandbox/fake_global_tracer.inc
tests/ext/sandbox/fake_tracer.inc
tests/ext/sandbox/fake_tracer_exception.inc

This PR fixes #879. When `DD_TRACE_AUTO_FLUSH_ENABLED=1`, the tracer will flush automatically when the open span stack reaches `0`. If there is an exception that has not been caught by the time it bubbles past the root span, the exception will get cleared when the tracer auto flushes. This occurs before PHP has finished handling the exception and causes a crash.
This PR prevents the original exception from being cleared during auto flushing. And although the auto flushing was sandboxed for PHP errors, it was not sandboxed for exceptions. This PR ensures that if an exception is thrown from the userland tracer during an auto flush, it will also be sandboxed.

Fix uncaught exceptions with auto flushing enabled

---

bridge/functions.php
tests/AutoInstrumentation/AutoInstrumentationTest.php
tests/AutoInstrumentation/scenarios/composer_with_local_code_dependency/composer.json

**What happened**
We recently moved from a psr4 compliant class map for our tracer to a hybrid psr4/files approach to
boost performance.
One of the changes involved was to move from psr4 `DDTrace\Configuration` class to a number of functions
in `bridge/configuration.php` hard-loaded during the required dependencies.
When a user depends in composer on datadog/dd-trace the following chain of classloaders is executed:
```
1. Composer
2. DDTrace Required
3. DDTrace Optional
```
Before configuration was accessed through `Configuration::*`. When we instantiated the `Tracer` the config class was loaded
by composer and the worst thing that could happene was a non updated version.
Now configuration is loaded from `\dd_config_*` (non-psr4) in the Tracer (Tracer is loaded from composer) but no-one, …

Be compatible with psr4 composer autoloading now that we have non-psr4 config functions

---

src/dd-doctor.php

*Problems this PR fix*
- We said `Opcache enabled` while the fact that the function exists only tells if opcache is installed, while the following props will tell if opcache is enabled.
- We did not `return;` if the function did not exist, causing an error
- If opcache was enabled, we did say `Opcache enabled [NO]` + `Opcache enabled [YES]`

fix opcache check in dd-doctor

---

bridge/_files.php
composer.json
src/DDTrace/Integrations/CakePHP/CakePHPIntegration.php
src/DDTrace/Integrations/CakePHP/CakePHPSandboxedIntegration.php
src/DDTrace/Integrations/CakePHP/V2/CakePHPIntegrationLoader.php
src/DDTrace/Integrations/IntegrationsLoader.php
tests/Integrations/CLI/CLITestCase.php
tests/Integrations/CLI/CakePHP/V2_8/CommonScenariosSandboxedTest.php
tests/Integrations/CLI/CakePHP/V2_8/CommonScenariosTest.php
tests/Integrations/CakePHP/V2_8/CommonScenariosSandboxedTest.php
tests/Integrations/CakePHP/V2_8/CommonScenariosTest.php

This PR sandboxes the CakePHP integration. It also fixes an issue in the legacy integration that did not set the proper HTTP response code on the root span.

Sandbox the CakePHP integration

---

docs/open_tracing.md
src/DDTrace/Bootstrap.php

This PR removes the legacy API from the OpenTracing implementation. This introduces a breaking change in the way OpenTracing is initialized with ddtrace. Before this change, an OpenTracing-compatible tracer (`\DDTrace\OpenTracer\Tracer`) would be automatically returned from `\OpenTracing\GlobalTracer::get()`. After this change, the OpenTracing-compatible tracer must be set manually.
```php
$otTracer = \OpenTracing\GlobalTracer::get();
$otTracer = new \DDTrace\OpenTracer\Tracer(\DDTrace\GlobalTracer::get());
\OpenTracing\GlobalTracer::set($otTracer);
```
The [OpenTracing documentation](https://docs.datadoghq.com/tracing/opentracing/php/) will be updated as part of this PR.
**Edit:** [Preview link](https://docs-staging.datadoghq.com/sammyk/php/open-tracing/tracing/opentracing/php/) of the …

Remove legacy hook for OpenTracing

---

config.m4
package.xml
src/ext/php5/auto_flush.c
src/ext/php5/blacklist.c
src/ext/php5/engine_hooks.c
src/ext/php5_4/auto_flush.c
src/ext/php5_4/blacklist.c
src/ext/php5_4/dispatch.c
src/ext/php5_4/engine_hooks.c
src/ext/php5_4/handlers_curl.c

This PR:
- Splits some of the sources for PHP 5.4 off into a php5_4 folder (fun note, you can't name that folder `php5.4` or the build will fail).
- Removes some version-specific in `php5/engine_hooks.c` that is now unused since PHP 5.4 doesn't use that file anymore. However, I did not do the equivalent task for `php5_4/engine_hooks.c` because every time I did this I broke the build.
- Uses `zend_execute_internal` for PHP 5.6. This fixes an issue in `labbati/noop-api` when `PDO::ATTR_STATEMENT_CLASS` is used.
This is targeting `labbati/noop-api` instead of master.

Use zend_execute_internal on PHP 5.6

---

src/ext/blacklist.h
src/ext/ddtrace.c
src/ext/ddtrace.h
src/ext/php5/blacklist.c
src/ext/php7/blacklist.c

This upgrades the module blacklist functionality to noop the legacy API when a potentially conflicting module is detected. The `dd_trace()` function can be re-enabled by setting the INI setting `ddtrace.ignore_legacy_blacklist=1`.

Noop the legacy API when a potentially conflicting module detected

---

src/ext/configuration.h
src/ext/ddtrace.c
src/ext/ddtrace.h
src/ext/php5_4/blacklist.c

This is a follow up PR to #900.
Since there are a number of changes that need to be done before we move to INI settings, this PR moves the `ddtrace.ignore_legacy_blacklist` INI setting (not released yet) to the `DD_TRACE_IGNORE_LEGACY_BLACKLIST` environment variable.

Move setting that ignores legacy blacklist to env var

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Bump the release version to 0.46.0.

Bump version to 0.46.0

---

composer.json
tests/OpenTracerUnit/GlobalTracerTest.php

Due to the fact that we have to whitelist tests, we were running in CI only `tests/OpenTracer/Unit/TracerTest.php` instead of the entire suite `tests/OpenTracer/Unit/`.
Moreover, as a consequence of this, we had not realized that the tests the verifies automatic registration in OT was failing, as we no longer automatically register the OT tracer as of #899.

Enable OpenTracing test suite in CI

---

src/ext/configuration.c
src/ext/configuration.h
src/ext/ddtrace.c
src/ext/env_config.c
src/ext/env_config.h
tests/Integrations/CLI/CakePHP/V2_8/CommonScenariosTest.php
tests/Integrations/CLI/Custom/Autoloaded/CommonScenariosTest.php
tests/Integrations/CakePHP/V2_8/CommonScenariosTest.php
tests/Integrations/CodeIgniter/V2_2/CommonScenariosTest.php
tests/Integrations/Curl/CurlIntegrationTest.php
tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
tests/Integrations/Lumen/V5_2/CommonScenariosTest.php
tests/Integrations/Lumen/V5_6/CommonScenariosSandboxedTest.php
tests/Integrations/Lumen/V5_6/CommonScenariosTest.php
tests/Integrations/Lumen/V5_8/CommonScenariosTest.php
tests/Integrations/Slim/V3_12/CommonScenariosTest.php
tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
tests/Integrations/WordPress/V4_8/CommonScenariosTest.php
tests/Integrations/Yii/V2_0_26/CommonScenariosTest.php
tests/Integrations/Yii/V2_0_26/ParameterizedRouteTest.php
tests/Unit/ConfigurationTest.php

**Deprecation notice**"  Setting service name via `DD_SERVICE_NAME` is now deprecated and will be removed in a future release. Use `DD_SERVICE` instead for consistency with other Datadog tracers and services.
This PR adds support for both `DD_SERVICE` (primary) and `DD_SERVICE_NAME` (secondary) as env variable names to configure the service name.
This was done as part of an effort to increase consistency among different tracers and Datadog products.

Add support for service name configuration via DD_SERVICE

---

tests/Frameworks/Symfony/Version_4_0/composer.json
tests/Frameworks/Symfony/Version_4_2/composer.json

`doctrine/migrations 3.0.0` was [released yesterday](https://github.com/doctrine/migrations/releases/tag/3.0.0) which is not compatible with migrations command in Symfony 4.2 and 4.4.
This PR pin `doctrine/migrations` to 2.* for those test suite.

Fix doctrine/migrations dependency in Symfony 4.2 and 4.4 test

---

bridge/configuration.php
src/api/Configuration.php
tests/Integration/TracerTest.php
tests/Integrations/Laravel/V4/CommonScenariosSandboxedTest.php
tests/Integrations/Laravel/V4/CommonScenariosTest.php
tests/Unit/ConfigurationTest.php
tests/Unit/TracerTest.php

This PR adds support for `DD_TAGS` to configure global tags to be set on every span. This new environment variable replaces `DD_TRACE_GLOBAL_TAGS` for consistency with other tracers and Datadog products. **NOTE**: the legacy `DD_TRACE_GLOBAL_TAGS` is still supported as a fallback mechanism for backward compatibility but it will removed in a future version.
`DD_TAGS` preserves the same associative array format, e.g. `DD_TAGS=key1:value1,key2:value2`

Add support for DD_TAGS, fallback to DD_TRACE_GLOBAL_TAGS

---

config.m4
package.xml
src/ext/php5/serializer.c
src/ext/php5_4/serializer.c
src/ext/php7/serializer.c
tests/ext/sandbox/memory_limit_graceful_bailout.phpt

Since the serializer is very PHP version specific, this PR just separates the file into the PHP version directories without making any functional changes.
This also includes a fix for the failing test reported in #912.
- ~[ ] Changelog has been added to the appropriate release draft. For community contributors the reviewer is in charge of this task.~

Separate serializer.c into PHP version directories

---

config.m4

This PR addresses the issue raised in #912 where ddtrace builds on 32-bit platforms when only 64-bit is supported. This adds a check to the config.m4 to fail on 32-bit platforms.

Only build on 64-bit platforms

---

src/ext/engine_hooks.c
src/ext/engine_hooks.h
src/ext/php5/engine_hooks.c
src/ext/php7/engine_hooks.c
src/ext/php7/handlers_curl.c

Most of the time the sandboxing code is the same, so let's de-duplicate it. We're going to start using it more too, for example:
- Non-instrumentation API
- Loading integrations on-demand
Note that the PHP 7 curl handlers were only partly sandboxed as they don't expect exceptions from curl calls; they now backup the exception info anyway.

Extract ddtrace_sandbox_begin/ddtrace_sandbox_end helpers

---

composer.json

For performance reasons, we compile all our files into a single file that is then served from the `bridge` folder. The problem with this is that in 3 classes of files in our code base relies on `include __DIR__ . '...';`. During compilation `__DIR__` is replaced with the actual absolute path of the machine when compilation happens, e.g. `/home/circleci/datadog/...`. This is clearly not compatible with our deployments that are installed in either `/opt/...` or any custom folder the user likes.
Only users on PHP 5.4, because
1. Legacy integrations because of the include of `try_catch_finally.php` include. Hence only users on PHP 5.4 are impacted as the new sandboxed integrations are not using this mechanism.
2. `Tracer::version()` method: this impact no one in production, it only breaks one …

Make compilation to single file compatible with `include __DIR__ . '...'` in files

---

src/DDTrace/Integrations/IntegrationsLoader.php

This integration was already written; it just wasn't enabled. Sammy guesses that it's because we didn't support close-on-exit on PHP 5 at the time. We support it on PHP 5.6 now, so this should be good to go as long as the tests pass in CI.

Enable sandboxed integration for Symfony on PHP 5

---

bridge/dd_init.php
bridge/php5.php
tests/Integration/ResponseStatusCodeTest_files/index.php
tests/Integration/TracerTest_files/index.php
tests/Integrations/Curl/CurlIntegrationTest.php

In Sandbox cURL (PHP 5) #911 we added another function to `dd_init.php` and even though this function is needed only on PHP 5 it still increased memory usage on PHP 7. This PR adds a `php5.php` file that PHP 5 specific functions can go into without affecting PHP 7 much.
This PR also adds output to 2 more of our tests which were segfaulting because there wasn't any output. This is a known issue with the PHP CLI web server that isn't fixable; we have to keep mitigating it until we move off of this SAPI entirely.

Add a separate PHP 5 only file

---

src/DDTrace/Integrations/IntegrationsLoader.php
src/DDTrace/Integrations/Lumen/LumenSandboxedIntegration.php
tests/Integrations/Lumen/V5_2/CommonScenariosSandboxedTest.php
tests/Integrations/Lumen/V5_2/CommonScenariosTest.php
tests/Integrations/Lumen/V5_2/TraceSearchConfigTest.php
tests/Integrations/Lumen/V5_6/CommonScenariosSandboxedTest.php
tests/Integrations/Lumen/V5_6/TraceSearchConfigTest.php
tests/Integrations/Lumen/V5_8/TraceSearchConfigTest.php

This adds some un-necessary spans that can be removed once the non-tracing API is completed, but it is worth it to get off of `dd_trace`.

Sandbox Lumen on PHP 5

---

.circleci/config.yml
config.m4
package.xml
src/ext/coms.c
src/ext/coms.h
src/ext/configuration.h
src/ext/ddtrace.c
src/ext/env_config.c
src/ext/php5/startup_logging.c
src/ext/php7/startup_logging.c
src/ext/startup_logging.h
tests/ext/startup_logging.inc
tests/ext/startup_logging.phpt
tests/ext/startup_logging_config.phpt
tests/ext/startup_logging_diagnostics.phpt
tests/ext/startup_logging_disabled.phpt
tests/ext/startup_logging_json.phpt
tests/ext/startup_logging_json_config.phpt
tests/ext/startup_logging_skipif.inc

This PR adds startup logs that contain a JSON-encoded string of configuration and diagnostic information. The JSON can be provided to the support team to help identify configuration issues. The log message is only generated on process startup and can be disabled by setting `DD_TRACE_STARTUP_LOGS=0`.
```
[2020-07-01T17:42:50Z] DATADOG TRACER CONFIGURATION - {"agent_error":"Couldn't connect to server","ddtrace.request_init_hook_reachable":false,"date":"2020-07-01T17:42:50Z","os_name":"Linux 49b1cb4bdd12 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64","os_version":"4.19.76-linuxkit","version":"1.0.0-nightly","lang":"php","lang_version":"7.4.5","env":null,"enabled":true,"service":null,"enabled_cli":false,"agent_url":"https://localhost:8126","debug":false,"analytics_enabled":false, …
```

Add startup logging

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h

Release 0.47.0.
**Deprecation notice**:
- Setting service name via `DD_SERVICE_NAME` is now deprecated and will be removed in a future release. Use `DD_SERVICE` instead for consistency with other Datadog tracers and services.
- Setting global tags via `DD_TRACE_GLOBAL_TAGS` is now deprecated and will be removed in a future release. Use `DD_TAGS` instead (with the same format) for consistency with other Datadog tracers and services.
- `DD_TRACE_RESOURCE_URI_MAPPING` is deprecated now that it has been split into `DD_TRACE_RESOURCE_URI_MAPPING_INCOMING` and `DD_TRACE_RESOURCE_URI_MAPPING_OUTGOING`.
- The functions `dd_trace` and `dd_trace_forward_call` are deprecated and will be made a no-op in the next release. See #924 for how to migrate.
- Apply new uri to resource normalization rules …

Release 0.47.0

---

package.xml
tests/ext/sandbox/non-zero_duration.phpt

A while back we had a clock issue where spans generated by `dd_trace_function`/`dd_trace_method` would have durations of 0. This adds a test so that if a similar issue happens again we might notice it.

Add a test for non-zero durations

---

tests/ext/startup_logging.inc
tests/ext/startup_logging_diagnostics.phpt

honors standard env. variable.
especially TEST_PHP_ARGS which may provides directive to load needed extension (json)
For ex, for RPM, we use `TEST_PHP_ARGS="-n -d extension=curl.so -d extension=json.so -d extension=posix.so -d extension=$PWD/modules/ddtrace.so"
And TEST_PHP_EXECUTABLE can be /usr/bin/zts-php (if this case, as /usr/bin/zts-php-cgi doesn't exists, tests are skipped).

improve CGI usage in test suite

---

examples/apache-mod_php/docker-compose.yml
examples/apache-mod_php/public/index.php
examples/nginx-php-fpm/docker-compose.yml
examples/nginx-php-fpm/public/index.php
src/dd-doctor.php

Before in `dd-doctor.php` we used to:
- check that initially integration `web` was not loaded
- trigger the `spl_autoload_register` mechanism
- check that integration `web` is now loaded
Because we are not using the `spl_autoload_register` mechanism and we load, instead, a separate noop public api and a separate internal api, this check no longer applies and it would always fail.
This PR remove the pre-check and only verify integrations are actually (always) loaded.
Along the way, I fixed `Content-Type: text/plain` in example applications (used to manually check this change) that weren't properly rendered text messages.
- [*] (only for Members) Changelog has been added to the appropriate release draft. Create one if necessary.
~- [ ] Tests added for this feature/bug.~ Manually tested

Removed obsolete pre-integrations loading check from dd-doctor.php

---

phpunit.xml
src/ext/coms.c
src/ext/coms.h
src/ext/php5/startup_logging.c
src/ext/php7/startup_logging.c
tests/Integrations/Custom/Autoloaded/AgentUrlEnvVarInvalidTest.php
tests/Integrations/Custom/Autoloaded/AgentUrlEnvVarTest.php

This is a followup PR to the awesome work @nurcahyo did in #926. This PR adds tests for `DD_TRACE_AGENT_URL` and also consolidates the Agent URL generation logic to be shared with the startup logging diagnostic checks.

Consistent env vars: DD_TRACE_AGENT_URL

---

.circleci/config.yml
.gitignore
tests/Common/SpanChecker.php
tests/Common/TracerTestTrait.php
tests/Common/WebFrameworkTestCase.php
tests/Integrations/Custom/Autoloaded/AgentUrlEnvVarInvalidTest.php
tests/Integrations/Custom/Autoloaded/AgentUrlEnvVarTest.php
tests/Integrations/Custom/Autoloaded/BackgroundSenderLogTest.php
tests/Integrations/Custom/Autoloaded/CircuitBreakerTest.php
tests/Integrations/Custom/Autoloaded/CommonScenariosTest.php
tests/Integrations/Custom/Autoloaded/CompileTimeDisabledTest.php
tests/Integrations/Custom/Autoloaded/CompileTimeEnabledTest.php
tests/Integrations/Custom/Autoloaded/TraceSearchConfigTest.php
tests/Nginx/NginxServer.php
tests/Nginx/nginx-default.conf
tests/Sapi/CliServer/CliServer.php
tests/Sapi/PhpCgi/PhpCgi.php
tests/Sapi/PhpFpm/PhpFpm.php
tests/Sapi/PhpFpm/www.conf
tests/Sapi/Sapi.php
tests/WebServer.php

This PR adds a PHP-FPM test runner to the web server tests in CircleCI. As of right now it only runs the custom web framework tests on PHP 7.4 since the test runner is quite slow. We will add more and make speed improvements going forward.
This also includes a refactoring of the existing web SAPI test runners. And also adds a new `phpunit_error.log` to the CircleCI artifacts for more visibility on failed web tests.

Add PHP-FPM test runner to web tests

---

src/private/functions.php
tests/Unit/private/UriTest.php
tests/overhead/docker-compose.yml

The old uri to resource mapper used to both normalize a uri AND remove the query string param.
The new one only currently normalizes the uri.
This creates problems in generic web tracing as the uri is used as part of the resource name.
This PR adds removal of query string from resource uri.
With fix

Remove query string when new resource mapper is used

---

bridge/configuration.php
src/DDTrace/Integrations/DefaultIntegrationConfiguration.php
src/api/Configuration.php
src/ext/configuration.c
src/ext/configuration.h
src/ext/ddtrace.c
src/ext/ddtrace.h
src/ext/env_config.c
src/ext/env_config.h
src/ext/integrations/elasticsearch.h
src/ext/integrations/integrations.c
src/ext/integrations/integrations.h
src/ext/php5/startup_logging.c
src/ext/php7/startup_logging.c
tests/Unit/ConfigurationTest.php
tests/Unit/Integrations/DefaultIntegrationConfigurationTest.php
tests/Unit/Integrations/IntegrationsLoaderTest.php
tests/ext/startup_logging_diagnostics.phpt

This PR normalizes usage of integration-specific environment variable names to be consistent with other tracers.
| Old Name  | New Name |
| ------------- | ------------- |
| `DD_<INTEGRATION>_ANALYTICS_ENABLED` | `DD_TRACE_<INTEGRATION>_ANALYTICS_ENABLED`  |
| `DD_<INTEGRATION>_ANALYTICS_SAMPLE_RATE `  | `DD_TRACE_<INTEGRATION>_ANALYTICS_SAMPLE_RATE `  |
| `DD_INTEGRATIONS_DISABLED` | `DD_TRACE_<INTEGRATION>_ENABLED` |
For example, to disable the `pdo` and `laravel` integrations before this PR:
```
DD_INTEGRATIONS_DISABLED=pdo,laravel
```
Starting from 0.47.1:
```
DD_TRACE_PDO_ENABLED=false
DD_TRACE_LARAVEL_ENABLED=false
```
The old names will continue to work but are deprecated and may be removed in a future release.

Consistent env vars: Support for DD_TRACE_<INTEGRATION>_<SUFFIX> env vars

---

dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/debian_jessie/Dockerfile

PHP packages on sury.org went EOL on June 30, 2020 and our `package verification` checks have failed ever since. This PR updates the Jessie package verification to use the PHP available in the default repo (PHP 5.6).
- ~[ ] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.~

Update Jessie package verification

---

.circleci/config.yml
composer.json
docker-compose.yml
dockerfiles/frameworks/phpredis4.yml
dockerfiles/services/Makefile
dockerfiles/services/redis/Dockerfile
src/DDTrace/Integrations/PHPRedis/PHPRedisSandboxedIntegration.php
src/ext/php7/handlers_phpredis.c
tests/Integrations/PHPRedis/PHPRedis3SandboxedTest.php
tests/Integrations/PHPRedis/PHPRedis4SandboxedTest.php

This PR adds support for PHPRedis 4 on PHP 7

Add support for PHPRedis 4 extension on php 7

---

src/DDTrace/Integrations/IntegrationsLoader.php
tests/Unit/Integrations/IntegrationsLoaderTest.php

This is a tiny followup PR to #891 to prevent the ElasticSearch integration from falling back to non-sandboxed version on PHP 7. The deferred integration loading feature hasn't been released yet.

Fix ElasticSearch integration fallback to legacy

---

src/ext/configuration.c
src/ext/php5/startup_logging.c
src/ext/php7/startup_logging.c
tests/Unit/ConfigurationTest.php

There was an off-by-one error that prevented `DD_TRACE_ELASTICSEARCH_ANALYTICS_SAMPLE_RATE` and `DD_TRACE_ZENDFRAMEWORK_ANALYTICS_SAMPLE_RATE` (added in `0.47.1`) from being read properly.
This PR fixes the issue and also adds tests for each integration's specific configuration. The tests also ensure that the integration has been added at the C level in response to [this CR comment](https://github.com/DataDog/dd-trace-php/pull/948#discussion_r465336826).

Fix off-by-one error with longest config name for integrations

---

.circleci/config.yml
package.xml
tooling/bin/pecl-build

This PR improves and automates several aspects of PECL builds:
- Adds the `_generated.php` file as part of the PECL build
- Adds a PECL build (`pecl/datadog_trace-<version>.tgz`) as part of `package extension` in CI **(do not build PECL packages with `pear package` directly)**
- Runs the phpt tests from the PECL build on all supported PHP versions via `pecl run-tests`
- `package.xml` is automatically updated for `<version>` and `<date>` when the package is built
I've updated the release notes with this information.

Package _generated.php with PECL

---

src/ext/php7/handlers_curl.c

I took a peek to see how much code could be re-used if we tried to implement `curl_multi_exec` support. I think the hardest bits can all be reused, which is good news. I did notice a few things that could be cleaned up while looking, so that's what this PR is (no multi curl support yet, just cleanup).
The dd_tracer_inject_helper now uses the stackful goto cleanup strategy, which I think is at least better than what it was doing before. Next step: remove goto?

Cleanup PHP 7 curl handlers

---

src/DDTrace/Integrations/IntegrationsLoader.php
src/ext/integrations/integrations.c
tests/Unit/Integrations/IntegrationsLoaderTest.php

This loads the Predis integration once `Predis\Client::__construct` is called. This way if a request doesn't use the predis integration then it isn't loaded (less cost).
It also does some minor cleanup on the deferred loading of phpredis integration impl too.

Defer loading of Predis integration

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/version.h
tooling/bin/pecl-build

See `package.xml` for what is in the release, or [0.48.0 release notes](https://github.com/DataDog/dd-trace-php/releases/tag/0.48.0) once the release is finished.

Release 0.48.0

---

tooling/bin/pecl-build

This was cherry-picked from the 0.48.0 release PR #997. It fixes the build for real releases.
Although the existing tests are adequate, should we persist the artifact in the CI job?

Fix pecl-build for real releases

---

.circleci/config.yml
Makefile
src/ext/configuration.h
tests/ext/read_c_configuration.phpt

This PR enables the background sender by default on PHP 5.4.
This also includes a fix to CI where the phpt tests would not properly report the exit code of `run-tests.php` when running it via `make` on PHP 5.4. Running `run-tests.php` directly fixes this bug as well as a number of other issues we've run into in the past with running the test runner through `make`.
- ~[ ] Tests added for this feature/bug.~ (Added "PHP 54 web tests with nginx + FastCGI" tests)

Enable the BGS by default on PHP 5.4

---

.circleci/valgrind/valgrind_musl_suppressions.lib
Makefile
package.xml
src/ext/coms.c
tests/ext/request_timeout_01.phpt

If the background thread is delivered these signals then it probably results in a crash. PHP 7.0 is the only version I could trigger an issue on; PHP 5 and PHP 7.1+ don't seem to trigger it.
Notably, PHP uses SIGPROF on Linux to trigger the timeout (this is a gross abuse of this signal, imo, but that's out of our control). If the background thread intercepts this signal it will badly crash.

Block Zend signals from background sender thread

---

src/DDTrace/Integrations/Symfony/SymfonySandboxedIntegration.php
tests/Frameworks/TestScenarios.php
tests/Frameworks/Util/CommonScenariosDataProviderTrait.php
tests/Integrations/Symfony/V3_0/CommonScenariosTest.php
tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
tests/Integrations/Symfony/V4_4/CommonScenariosSandboxedTest.php

This PR just wraps up the fantastic contribution from @franek in #995 by adding tests of 404 endpoints to the Symfony integration.

Add 404 tests to Symfony integration

---

.circleci/valgrind/valgrind_musl_suppressions.lib
Makefile
package.xml
src/DDTrace/Integrations/Symfony/SymfonySandboxedIntegration.php
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/coms.c
src/ext/php5/engine_hooks.c
src/ext/php5_4/engine_hooks.c
src/ext/version.h
tests/Frameworks/TestScenarios.php
tests/Frameworks/Util/CommonScenariosDataProviderTrait.php
tests/Integrations/Symfony/V3_0/CommonScenariosTest.php
tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
tests/Integrations/Symfony/V4_4/CommonScenariosSandboxedTest.php
tests/ext/request_timeout_01.phpt
tests/ext/sandbox/spans_out_of_sync_01.phpt
tests/ext/sandbox/spans_out_of_sync_02.phpt
tests/ext/sandbox/spans_out_of_sync_03_php5.phpt
tests/ext/sandbox/spans_out_of_sync_03_php7.phpt
tests/ext/sandbox/spans_out_of_sync_04_php5.phpt
tests/ext/sandbox/spans_out_of_sync_04_php7.phpt
tests/ext/sandbox/spans_out_of_sync_05.phpt
tests/ext/sandbox/spans_out_of_sync_06.phpt

- Symfony HttpException with status less than 500 should not be considered an error #995, #1002 (thanks, @franek!)
- Block Zend signals from background sender thread #1000
- Fix out-of-sync issue if span stack is closed while a closure is running #1001

Release 0.48.1

---

src/DDTrace/Bootstrap.php

Enable sandboxed writing of traces when reached spans limit on php 5.4 now that 5.4 is sandboxed

Sandbox flush in limited mode on PHP 5.4

---

src/ext/ddtrace.c

These were added, but then never called :facepalm:
Honestly, we were unlucky that tests did not catch this. This means
that most of the time the function used the same address in subsequent
requests.
I also don't know how to add a test for this, as I don't know how to
force the address to change.
I believe issue #1012 is caused by this, but have not confirmed it yet.

Call ddtrace_engine_hooks_{rinit,rshutdown}

---

.github/ISSUE_TEMPLATE/bug_report.md
src/dd-doctor.php

Deprecates `dd-doctor.php` in favor of using `phpinfo()` for troubleshooting. Also updates the GitHub issue template to refer to a `phpinfo()` page.

Deprecate dd-doctor.php

---

.circleci/php-5.5_web.txt
composer.json
tests/Frameworks/Slim/Version_3_12/composer.json
tests/Integrations/Slim/V3_12/CommonScenariosTest.php

This is a follow-up PR to Support PHP 5.5 #1008 that adds Slim 3 to the test suites for PHP 5.5.

Add Slim 3 to PHP 5.5's test suite

---

package.xml
src/ext/php7/engine_api.c
src/ext/php7/engine_hooks.c
tests/ext/sandbox/deferred_load_missing_load_fn.phpt

A user encountered this in #1021. In the case the loading function couldn't be found the `zval retval` would be un-initialized and then sigsegv would occur when trying to `zval_ptr_dtor` it. I initialized the local variable, but also changed `ddtrace_call_function` to initialize the retval like `zend_call_function` would, which contributed to the bug occurring.

Fix sigsegv in deferred loading

---

package.xml
src/ext/php7/engine_api.c
src/ext/php7/engine_api.h
src/ext/php7/handlers_curl.c
tests/ext/sandbox/distributed_tracing_curl_missing_fn.phpt

As a follow-up to the feedback given in #1022 , this adds defensive initializations of local zvals in `php7/handlers_curl.c` and a test for a missing curl helper function on PHP 5. No issues were found.

Harden curl integration

---

package.xml
src/DDTrace/Tracer.php
src/DDTrace/version.php
src/ext/php7/engine_api.c
src/ext/php7/engine_hooks.c
src/ext/version.h
tests/ext/sandbox/deferred_load_missing_load_fn.phpt

Fixes a segmentation fault in deferred loading; affects users calling these methods when ddtrace's request init hook is not run:
- `Redis::__construct`
- `Predis\Client::__construct`
- `Elasticsearch\Client::__construct`

Release 0.48.3

---

.circleci/config.yml
dockerfiles/ci/xfail_tests/5.5.list

This adds more tests for supporting PHP 5.5.

Add more tests for PHP 5.5

---

src/DDTrace/Integrations/Curl/CurlIntegration.php
tests/Integrations/Curl/CurlIntegrationTest.php

As part of release 0.43.0 we sandboxed curl on php 7. We missed enabling
trace analytics.
This PR restore trace analytics on curl.

Add back support for trace analytics to curl integration

---

dockerfiles/ci/xfail_tests/5.5.list

There are multiple serialization bugs fixed in PHP 5.6 and 7.0 that
affect this test. I thought I already committed this one, but it
failed recently so I guess not.

Skip bug 64146 on PHP 5.5

---

.phpcs.xml
src/ext/ddtrace.c
tests/Common/CLITestCase.php
tests/Common/EnvSerializer.php
tests/Common/IniSerializer.php
tests/Integration/LongRunning/LongRunningScriptTest.php
tests/Integration/LongRunning/long_running_script_manual.php
tests/Integrations/CLI/CakePHP/V2_8/CommonScenariosTest.php
tests/Integrations/CLI/Custom/Autoloaded/CommonScenariosTest.php
tests/Integrations/CLI/Custom/Autoloaded/NoRootSpanTest.php
tests/Integrations/CLI/Custom/NotAutoloaded/NotAutoloadedTestCase.php
tests/Integrations/CLI/Laravel/V5_8/CommonScenariosTest.php
tests/Sapi/CliServer/CliServer.php
tests/Sapi/PhpCgi/PhpCgi.php

By default the background sender enqueue traces and sends them every 5 seconds (or when necessary if they are piling up). Spans are grouped together (and traces counted) based on a group id that was reset in the RINIT. Problem is: for long running scripts RINIT is run only once and we were sending all traces correctly, but header `X-Datadog-Trace-Count: 1` caused only the first trace (every 5 seconds) to be decoded.
This PR add state reset after traces are sent to the background sender and the script is ready to handle a new trace.

Properly group traces sent in batch during long running scripts

---

.circleci/config.yml

This PR enable running `build_package` workflow always, to make sure that if something is merged into master, it has no failing tests. In addition to that, this PR fixes naming of a test suite that changes in the transition from composer-based test execution to make-based execution.
As a separate effort, we must reduce CI times, as part of a different effort.

Always run build_package workflow

---

dockerfiles/ci/buster/docker-compose.yml
src/ext/ddtrace.c
src/ext/engine_hooks.c
src/ext/php5_4/engine_hooks.c

This updates the PHP 8 container to 8.0.0 RC 1 and fixes two `ZEND_API` changes. This PR does not include a shippable build of ddtrace on RC 1. That will come in a future PR.
This PR also fixes a build error on PHP 5.4 ZTS and cleans up a small section of `UNUSED` macro usage.
- ~[ ] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.~ Does not include a shippable build.

Build on PHP 8.0.0 RC 1 (without a shippable build)

---

package.xml
src/ext/engine_hooks.c
src/ext/engine_hooks.h
src/ext/php5/engine_hooks.c
src/ext/php5_4/engine_hooks.c
src/ext/php7/engine_hooks.c
tests/ext/sandbox/fatal_errors_are_tracked_005.phpt

Previously fatal errors were attached only to the top-most open internal span. In this case, "internal" means traced by `DDTrace\trace_method` or `DDTrace\trace_function`; it doesn't apply to spans made through Open Tracing or the `DDTrace\Tracer` API which notably includes the root span when `DD_TRACE_GENERATE_ROOT_SPAN` is on (it defaults to on).
Also avoid installing `ddtrace_error_cb` on PHP 5.4 as this feature it isn't supported yet.

Attach fatal errors to all open internal spans

---

tests/Unit/Sampling/ConfigurableSamplerTest.php

This PR adds a test to assert that both `0` and `1` work as values for `DD_TRACE_SAMPLE_RATE`.

Assert both 0 and 1 work as values for DD_TRACE_SAMPLE_RATE

---

Makefile

Some release of symfony/flex's recipes or dependencies (I believe around monolog but I was not able to track it down to the rela cause) is causing the `cache:clear` post install to fail with an error `"excluded_http_codes" cannot be used as your version of Monolog bridge does not support it.`. Attempts based on issues in various symfony recipes did not work.
Only trick that worked is running composer update once with `--no-script` (so cache clear is not run) and once without it, so all the post-update scripts required by symfony is executed.

Fix Symfony 4.0 composer update issue in CI

---

dockerfiles/ci/xfail_tests/5.5.list
dockerfiles/ci/xfail_tests/7.3.list
dockerfiles/ci/xfail_tests/7.4.list

Locally I updated PHP 7.2, 7.3, and 7.4 buster containers to the latest versions. All of these tests fail because a specific object ID is tested.
The PHP 5.5 test is one that happens in a 1 second request time limit. If it triggers in a memory routine then it is corrupted and sigsegvs in the next memory operation. This is why newer PHP versions (I think PHP 7.1+?) use a different mechanism for timeout handling.

Update PHP language xfail lists

---

.circleci/config.yml
Makefile
docker-compose.yml
dockerfiles/ci/centos/6/docker-compose.yml
dockerfiles/ci/centos/6/php-5.5/Dockerfile
dockerfiles/ci/centos/6/php-5.5/modules/php/.version
dockerfiles/ci/centos/6/php-5.5/modules/php/5.5
dockerfiles/ci/centos/6/php-5.5/modules/php/5.5-debug
dockerfiles/ci/centos/6/php-5.5/modules/php/5.5-debug-zts
dockerfiles/ci/centos/6/php-5.5/switch-php
dockerfiles/ci/centos/6/php-8.0/Dockerfile
dockerfiles/ci/centos/6/php-8.0/configure.sh
dockerfiles/ci/centos/6/php-8.0/download-src.sh
dockerfiles/ci/centos/6/php-8.0/switch-php
tests/Frameworks/Symfony/Version_4_0/composer.lock

This PR adds experimental support for PHP 8.0.0 RC 1. **This is provided for testing only and not intended for use on production.**
This does not include refactoring onto the new [observer API](https://github.com/php/php-src/blob/master/Zend/zend_observer.h). That refactoring will happen over a series of PR's targeted at the upcoming PHP 8 release candidates.
This PR also includes two updates to the PHP 5.5 container that builds for release:
- Ship ZTS mode without `--enable-debug`.
- Replace PHP version switching from `environment-modules` to a script that symlinks to the target PHP binaries.
It also fixes installation/update issues with Symfony 4.0 by committing the `composer.lock` and using `composer install` instead of update.

Experimental PHP 8.0.0 RC 1 support

---

package.xml
src/ext/php5/engine_hooks.c
tests/ext/sandbox/generator_php5.phpt

Generators cannot be reliably instrumented on PHP 5 so this PR ensures that generators are never traced.
This PR also includes a tiny PECL build fix for files that were deleted in #1006.

Disable instrumenting generators on PHP 5

---

package.xml
src/DDTrace/Tracer.php
src/ext/version.h

Version bump for `0.49.0` release.

Bump version to 0.49.0

---

dockerfiles/ci/centos/6/docker-compose.yml

PHP 8.0.0 RC 2 was [released today](https://www.php.net/archive/2020.php#2020-10-16-1). \o/

Experimental support for PHP 8.0.0 RC 2

---

README.md

With 0.49 we officially support PHP 5.5, filling in the hole from 5.4 -> 5.6. May as well advertise it.

Update badge for minimum requirement of PHP 5.4

---

dockerfiles/ci/xfail_tests/5.4.list

This string tests is unreliable on PHP 5.4. For PHP 5.5 this test was relaxed:
php/php-src@09b92a3a542455651016afe1bc9854e52b4673c3
This has failed in CI from time to time, so let's xfail it.

XFAIL unreliable string shuffle test on PHP 5.4

---

Makefile
src/DDTrace/Integrations/Symfony/SymfonyIntegration.php
tests/Integrations/Symfony/V2_3/RouteNameTest.php
tests/Integrations/Symfony/V2_8/RouteNameTest.php
tests/Integrations/Symfony/V3_0/CommonScenariosTest.php
tests/Integrations/Symfony/V3_0/TraceSearchConfigTest.php
tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
tests/Integrations/Symfony/V3_3/TraceSearchConfigTest.php
tests/Integrations/Symfony/V3_4/AutofinishedTracesSymfony34Test.php
tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
tests/Integrations/Symfony/V3_4/TemplateEnginesTest.php
tests/Integrations/Symfony/V3_4/TraceSearchConfigTest.php
tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
tests/Integrations/Symfony/V4_0/TraceSearchConfigTest.php
tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
tests/Integrations/Symfony/V4_2/TraceSearchConfigTest.php
tests/Integrations/Symfony/V4_4/CommonScenariosTest.php
tests/Integrations/Symfony/V4_4/TraceSearchConfigTest.php

This adds the following enhancements:
- Trace the Symfony controller as `symfony.controller`, attaching the method name as the resource. Note that this doesn't work with controllers that are closures, only other forms of callables. Also, some versions of Symfony call this with `call_user_func` or `call_user_func_array`, and sometimes it's fully qualified and sometimes it's not. I point this out because on PHP 7 it matters; if it's unqualified then it won't be traced.
- Trace the main HttpKernel\Kernel's methods `boot` and `handle`.
- Move `Symfony\Component\HttpKernel\HttpKernel::__construct` to the non-tracing prehook API.
- Trace public methods of Doctrine Repository classes. This will probably be split off of this PR in its final form, but it was really satisfying to see it in the demo …

Trace Symfony controller and more

---

Makefile
tests/Frameworks/Symfony/Version_5_0/src/Controller/CommonScenariosController.php
tests/Frameworks/Symfony/Version_5_0/templates/twig_template.html.twig
tests/Frameworks/Symfony/Version_5_1/src/Controller/CommonScenariosController.php
tests/Frameworks/Symfony/Version_5_1/templates/twig_template.html.twig
tests/Integrations/Symfony/V5_0/CommonScenariosTest.php
tests/Integrations/Symfony/V5_0/TraceSearchConfigTest.php
tests/Integrations/Symfony/V5_1/CommonScenariosTest.php
tests/Integrations/Symfony/V5_1/TraceSearchConfigTest.php

Adds integration tests for Symfony 5.0 and 5.1. ~Blocked on [Tests: add Symfony 5 sources](/Datadog/dd-trace-php/pull/1060)~.

Tests: add Symfony 5 tests

---

tests/overhead/dockerfiles/Dockerfile_73_fpm_head
tests/overhead/dockerfiles/Dockerfile_73_fpm_master

Starting from #1039 we need two steps to have a fully functional local working environment:
- install extension
- generate the `_generated.php` file
They cannot be done in the same composer command as the library we use to do that is not compatible with PHP 8.
This PR add the file generation to the master and head images in the `test/overhead` sample app.

invoke make generate in overhead measurement sample app

---

.circleci/config.yml
.editorconfig
ext/DatadogArena/CMakeLists.txt
ext/DatadogArena/arena.c
ext/DatadogArena/datadog/arena.h
ext/DatadogArena/test/CMakeLists.txt
ext/DatadogArena/test/arena.cc
ext/DatadogArena/test/main.cc

This adds an arena allocator `datadog_arena` similar to PHP's `zend_arena`. Critically it is not tied to _any_ PHPisms at all so it can be used across all PHP versions. This allocator doesn't support deallocating individual objects; it frees all its memory at once. There is also a checkpoint/restore API so you can save the current allocator position and then rewind to the same spot (caller is responsible for making sure conflicting checkpoint/restores nor frees happen between checkpoint/restore).
In particular arena allocators are good for serializing variable-length data which is then transferred and freed. This pattern comes up in both the tracer and the profiler.
Tests are written using the Catch2 library and uses the CMake build system. The arena simple enough that it can be …

Add DatadogArena and tests

---

.circleci/config.yml
dockerfiles/ci/alpine/docker-compose.yml
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/centos/6/docker-compose.yml
dockerfiles/ci/xfail_tests/8.0.list
dockerfiles/compile_extension/docker-compose.yml
tests/Integrations/PDO/PDOTest.php
tests/xdebug/3.0.0beta1/request_init_hook.phpt

Update PHP 8 containers to RC 3 which was [released on Oct 29](https://news-web.php.net/php.internals/112142).
This PR also fixes two recent changes that caused test failures for Xdebug (php/php-src#6324) and PDO (php/php-src#6355).

Update PHP 8 containers to RC 3

---

Makefile
src/DDTrace/Integrations/WordPress/WordPressIntegration.php

Due to some possible performance regressions discovered with WordPress 5 on PHP 5.6, this PR will only load the WP 5 integration on PHP 7+. Once the possible performance regressions have been validated/addressed, we can add the WP 5 integration back to PHP 5.

Only load WordPress 5 integration on PHP 7+

---

bridge/configuration.php
src/DDTrace/Integrations/PHPRedis/PHPRedisIntegration.php
src/private/functions.php
tests/Common/SpanChecker.php
tests/Integrations/PHPRedis/PHPRedis3Test.php
tests/Integrations/PHPRedis/PHPRedis4Test.php
tests/Integrations/PHPRedis/PHPRedis5Test.php
tests/Unit/ConfigurationTest.php
tests/Unit/private/UtilTest.php

This PR:
- introduces a new setting named `DD_TRACE_REDIS_CLIENT_SPLIT_BY_HOST`. Default value is `false`. It can be set to `true`;
- if the value of the above setting is `true`, then the service name for phpredis client spans is changed to `redis-<host>`. Example: `host=127.0.01 --> service=redis-127.0.0.1`, `host=some.host --> service=redis-some.host`;
- while this PR only applies to phpredis, we do not make a distinction between phpredis and predis while defining the service name, both will be prefixed by `redis-`.

Support service split by host in PHPRedis integration

---

Makefile
src/DDTrace/Integrations/WordPress/WordPressIntegration.php

This reverts commit fd237bd17f2810db56fd6a7e43ce85a7da0d072e which was introduced in #1081. The suspected performance regressions were false-positives so we can enable WP 5 on PHP 5 again.

Load WordPress 5 integration on PHP 5

---

ext/php5/circuit_breaker.h
ext/php5/ddtrace.h
ext/php5/integrations/integrations.c
ext/php5/integrations/integrations.h
ext/php5/php5/dispatch.c
ext/php5/php5/engine_hooks.c
ext/php5/php5_4/auto_flush.c
ext/php5/php5_4/dispatch.c
ext/php5/php5_4/engine_hooks.c
ext/php5/signals.c
ext/php5/startup_logging.c
ext/php7/circuit_breaker.h
ext/php7/ddtrace.h
ext/php7/integrations/integrations.c
ext/php7/integrations/integrations.h
ext/php7/php7/dispatch.c
ext/php7/php7/engine_hooks.c
ext/php7/signals.c
ext/php7/startup_logging.c

This is a follow up PR to #1085 based on @morrisonlevi's suggestion to make the includes paths relative to the `ext/` directory vs relative to the current file path.

Make include paths relative to ext/

---

.circleci/config.yml

This PR:
- disable caching of `vendor` folders, as speed p is provided by caching composer's cache folder and vendor files would be different for version to version in any case
- updates the caching key version so we start from a clean cache on master, as some errors came up on master after we updated to composer 2

Fix composer self-update on master properly handling cached directories

---

dockerfiles/ci/alpine/Dockerfile
dockerfiles/ci/alpine/docker-compose.yml
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/centos/6/docker-compose.yml
dockerfiles/ci/centos/6/php-8.0/Dockerfile
dockerfiles/ci/xfail_tests/8.0.list

It looks like we might get a PHP 8.0.0 RC5 release [next week](https://github.com/php/php-src/pull/6377#issuecomment-725574878). (Thanks again @carusogabriel!) Ahead of the release, this PR updates the Alpine, Buster, and CentOS 6 containers with a custom build that includes php/php-src#6377, php/php-src#6421, and a [Dmitry JIT fix](https://github.com/php/php-src/commit/11c4821ba968d2a39310851ab89d673c553b72f3) to the observer API.
This will unblock #1089 to allow continued development of the observer API refactor.

[PHP 8] Custom pre-RC5 build

---

Makefile

As part of every execution, before we copied ALL files (sources, tests, .m4) and run a complete build even if only one single test file changed, not a source file. With this PR we separate the concept of source files and test files.
When a test file changes, the file is only automatically copied to `tmp/build_extension/tests/ext/**` and a build is NOT done.
When a source file changes, the file is copied to `tmp/build_extension/**` and a build IS done automatically.
Now developers can run `make test_c TESTS=tests/ext/some_thing.phpt` and the quickest possible process will be executed, only building if necessary.
Note that the `EXTRA_CFLAG` variable is provided to provide extra CFLAGS, e.g. `EXTRA_CFLAGS=-g`.
Limitations:
- When a `.h` file changes, it is automatically copied to the build …

Make execution of ext tests locally faster and easier

---

src/DDTrace/Integrations/Predis/PredisIntegration.php
tests/Integrations/Predis/PredisTest.php

This PR brings the same functionality as implemented for PHPredis #1084 to Predis integration.

Support service split by host in Predis integration

---

dockerfiles/ci/alpine/docker-compose.yml
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/centos/6/docker-compose.yml

This PR is a follow up to #1093 that adds php/php-src#6422 to the PHP 8 containers. That PR fixes a number of issues with passing the correct return value to the end handlers.
These changes will be landing in [RC5 next week](https://github.com/php/php-src/pull/6377#issuecomment-726107473).

[PHP 8] Second custom pre-RC5 build

---

.circleci/config.yml
dockerfiles/ci/alpine/docker-compose.yml
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/centos/6/docker-compose.yml
dockerfiles/compile_extension/docker-compose.yml
dockerfiles/compile_extension/install-php
ext/php8/ddtrace.c
ext/php8/dispatch.c
ext/php8/dispatch.h
ext/php8/engine_hooks.c
ext/php8/engine_hooks.h
ext/php8/php8/dispatch.c
ext/php8/php8/engine_hooks.c
package.xml
tests/ext/sandbox-regression/closure_accessing_outside_variables_php8.phpt
tests/ext/sandbox-regression/closure_set_inside_object_methods_php8.phpt
tests/ext/sandbox-regression/reset_configured_overrides.phpt
tests/ext/sandbox-regression/reset_configured_overrides_php8.phpt
tests/ext/sandbox-regression/used_dispatch_should_not_free.phpt
tests/ext/sandbox-regression/used_dispatch_should_not_free_php8.phpt
tests/ext/sandbox/generator.phpt
tests/ext/sandbox/generator_php8.phpt
tests/ext/sandbox/generator_with_exception_php8.phpt
tests/ext/sandbox/generator_with_return_php8.phpt
tests/ext/sandbox/generator_yield_from_php8.phpt
tests/ext/sandbox/hook_method/posthook_04.phpt
tests/ext/sandbox/hook_method/prehook_04_php8.phpt

This PR refactors the engine hooks to use the new [observer API](https://github.com/php/php-src/blob/PHP-8.0/Zend/zend_observer.h) in PHP 8. \o/
Notable differences from PHP 7:
- The dispatch is now immutable and cannot be overwritten. Deferred loading still works as expected.
- `dd_trace_reset()` is now noop. This is due to the "ask once and cache" nature of the dispatch lookup that is dictated by the observer API design.
- Generators are fully supported on PHP 8 now. However, `yield from` is not observed properly. This is a limitation of the observer API that will be fixed in an upcoming patch release of PHP 8.0.
- Instrumenting a sub class of a parent class that is already instrumented is not possible. We might want to revisit this topic later, but at the moment this would add extra …

PHP 8: Observer API

---

ext/php8/integrations/integrations.c
src/DDTrace/Integrations/IntegrationsLoader.php
tests/Unit/Integrations/IntegrationsLoaderTest.php

To prevent accidentally loading an integration that does not have support for PHP 8, this PR removes them from the integration loaders. We will keep an eye out for PHP 8 support for each of these integrations and add them back to the loader once they become available.

Remove integrations that do not yet support PHP 8

---

.circleci/config.yml
ext/DatadogMemHash/CMakeLists.txt
ext/DatadogMemHash/README.md
ext/DatadogMemHash/include/datadog/memhash.h
ext/DatadogMemHash/include/datadog/memhash.hh
ext/DatadogMemHash/memhash.cc
ext/DatadogMemHash/test/CMakeLists.txt
ext/DatadogMemHash/test/cantor.cc
ext/DatadogMemHash/test/main.cc
package.xml

This PR adds two functions for hashing:
1. `datadog::memhash`, which hashes linear bytes. Currently it uses the lower 64 bits of MurmurHash3's 128-bit hash. MurmurHash3 is in the public domain and the author has disclaimed any copyrights to it.
2. `datadog::cantor_hash`, which hashes two unsigned, 64-bit numbers using the [cantor pairing function](https://en.wikipedia.org/wiki/Pairing_function#Cantor_pairing_function). The hash of `(1, 2)` and `(2, 1)` are different. For small integers it forms a perfect hash; if the product of the two integers overflows then there can be collisions.

Add functions for hashing

---

.circleci/config.yml
dockerfiles/ci/alpine/docker-compose.yml
dockerfiles/ci/alpine/php-8.0/Dockerfile
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/buster/php-8.0/Dockerfile
dockerfiles/ci/centos/6/docker-compose.yml
dockerfiles/compile_extension/docker-compose.yml
tests/xdebug/3.0.0/request_init_hook.phpt

PHP 8 is [GA](https://www.php.net/releases/8.0/en.php). 🎉

Update containers to PHP 8.0.0

---

ext/php5/ddtrace.c
ext/php5/ddtrace.h
ext/php5/engine_hooks.c
ext/php5/engine_hooks.h
ext/php5/serializer.c
ext/php5/span.h
tests/Integrations/CodeIgniter/V2_2/CommonScenariosTest.php
tests/Integrations/Custom/Autoloaded/FatalErrorTest.php
tests/Integrations/WordPress/V4_8/CommonScenariosTest.php
tests/Integrations/WordPress/V5_5/CommonScenariosTest.php

This is a followup PR to #1040 that attaches fatal errors to root spans created in userland for PHP 5.6 and 5.5.
As mentioned in #1034, PHP 5.4 is still not supported.

Attach fatal errors to userland root span on PHP 5

---

bridge/_files.php
bridge/dd_register_optional_deps_autoloader.php

Notably, PECL builds were failing when DD_TRACE_DEBUG=false (default)
was set because they would end up using NullLogger, but it couldn't
be found because it isn't shipped in the package.xml.
Maybe we should ship the optional files in src/api too, but at the
very least NullLogger isn't optional and should be included in
_files.php so it gets shipped in _generated.php.
Relates to #1090.

NullLogger is essential, not optional

---

.clang-format
src/arena.c
src/native/dictionary.c
src/native/pprof.c
src/native/proto/.clang-format
src/native/string_table.c

This adjusts the `.clang-format` file and runs it across the project. A few notes on options:
- `AlignOperands: DontAlign` is there mostly because it formats ternary statements quite poorly without it.
- `AllowShortBlocksOnASingleLine: true` is supposed to permit things like `if (cond) { return; }` on a single line, but it doesn't seem to work most of the time.
Let me know if you see anything related to code style you don't like and I can try to adjust the options more.

[Profiler] Run .clang-format on everything; adjust style

---

.circleci/config.yml

Image `circleci/php:7.2-cli-node-browsers` that we use in CI to run `clang-format` checks are on buster now, apparently from a while. Possibly, some cache recently expired in CircleCI and with the updates we are no longer able to install `clang-format` using the old repositories.
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
This PR updates the llvm.org repositories urls for [buster/clang-format-12](https://apt.llvm.org/) based on the recommended urls from docs.
- ~[ ] …

fix clang-format installation after circleci image update to buster

---

ext/php8/ddtrace.c

Without **curl** extension, extension load fails with "undefined symbol: curl_multi_ce" (PHP 8 only , build with --enable-rtld-now) so will segfault on standard build when curl extension is build shared and not loaded.
PHP 5 and 7 are not affected as this symbol is not used

add missing dependency on curl extension for PHP 8

---

dockerfiles/ci/xfail_tests/5.6.list
ext/php8/ddtrace.c

Just a quick cleanup PR to fix linting on PHP 8 and xfail a flaky test on PHP 5.6 (already on the xfail list for PHP 7+).

Fix linting + xfail a flaky test

---

src/native/pprof.c
test/CMakeLists.txt
test/pprof.cc

This adds the basic testing setup in CMake for running tests for the `native` folder. It also converts a parameter to take `const char*` instead of `char *` to silence a few warnings.

[Profiler] Add testing setup for pprof/native

---

.clang-format

Several of the shared libraries pack optional parameters into bitfields.  I don't anticipate these to change too often, but when they do it's nice to be able to eyeball the diffs, which is a little harder to do when the indentations are all over the place.
This is a stylistic change for the build system.  Just an idea.

Add consecutive bitfield alignment to clang-format

---

.phpcs.xml
bridge/configuration.php
src/DDTrace/Bootstrap.php
src/private/functions.php
tests/Frameworks/Custom/Version_Not_Autoloaded/Headers/index.php
tests/Integrations/Custom/NotAutoloaded/HttpHeadersConfiguredTest.php
tests/Integrations/Custom/NotAutoloaded/HttpHeadersNotConfiguredTest.php
tests/Unit/ConfigurationTest.php

This PR adds the possibility to define a list of http headers names that are set on the root span.
Headers values are separated by request and response headers and the configuration variable is unique.

Add configured http headers to root span

---

ext/php7/arrays.c
ext/php7/auto_flush.h
ext/php7/comms_php.c
ext/php7/compat_string.c
ext/php7/compat_string.h
ext/php7/compatibility.h
ext/php7/configuration.c
ext/php7/ddtrace.c
ext/php7/ddtrace_string.c
ext/php7/ddtrace_string.h
ext/php7/dispatch.c
ext/php7/engine_api.c
ext/php7/engine_hooks.c
ext/php7/engine_hooks.h
ext/php7/logging.h
ext/php7/php7/engine_hooks.c
ext/php7/random.c
ext/php7/request_hooks.c
ext/php7/serializer.c
ext/php7/span.c
ext/php7/span.h
ext/php7/startup_logging.h

Get rid of all non php7 code in `ext/php7`

remove non php7 code from ext/php7 folder

---

ext/php5/arrays.c
ext/php5/comms_php.c
ext/php5/compat_string.c
ext/php5/compat_string.h
ext/php5/compatibility.h
ext/php5/configuration.c
ext/php5/ddtrace.c
ext/php5/ddtrace_string.h
ext/php5/dispatch.c
ext/php5/dispatch.h
ext/php5/handlers_internal.c
ext/php5/integrations/integrations.c
ext/php5/logging.h
ext/php5/php5/engine_hooks.c
ext/php5/random.c
ext/php5/request_hooks.c
ext/php5/serializer.c
ext/php5/span.c
ext/php5/startup_logging.h

Get rid of all non php5 code in `ext/php5`

Remove non php5 code from ext/php5 folder

---

tests/randomized/docker/run.sh

A degree of flakiness in randomized testing was observed regardless of the tracer installed or not.
A typical error that is a false positive is [this one](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/5231/workflows/c839b1ba-0e9e-4f07-ab5e-9d304e121c01) where a EOF error is generated by vegeta supposedly when the server close the connection due to high traffic.
Searching online it seems that this is generated when the Go's http client receive a response with `Keep-Alive` and then the server closes the connection, for other reasons.
In order to increase stability we set to false the `-keepalive` flag in vegeta and observe flakiness in the next few pushes.

do not keep alive connections while executing randomized testing

---

ext/php8/arrays.c
ext/php8/auto_flush.h
ext/php8/comms_php.c
ext/php8/compat_string.c
ext/php8/compat_string.h
ext/php8/compatibility.h
ext/php8/configuration.c
ext/php8/ddtrace.c
ext/php8/ddtrace_string.c
ext/php8/ddtrace_string.h
ext/php8/dispatch.c
ext/php8/dispatch.h
ext/php8/engine_api.c
ext/php8/excluded_modules.c
ext/php8/logging.h
ext/php8/random.c
ext/php8/request_hooks.c
ext/php8/serializer.c
ext/php8/span.c
ext/php8/startup_logging.h

Get rid of all non php8 code in `ext/php8`

Remove non php8 code from ext/php8 folder

---

.circleci/config.yml
Makefile
components/CMakeLists.txt
components/catch2_main.cc
components/sapi/CMakeLists.txt
components/sapi/sapi.c
components/sapi/sapi.h
components/sapi/tests/CMakeLists.txt
components/sapi/tests/sapi.cc
components/string_view/CMakeLists.txt
components/string_view/string_view.c
components/string_view/string_view.h
components/string_view/tests/CMakeLists.txt
components/string_view/tests/string_view.cc
config.m4
dockerfiles/ci/xfail_tests/5.4.list
ext/php5/ddtrace.c
ext/php7/ddtrace.c
ext/php8/ddtrace.c
package.xml

Adds top-level directory components. Components have a single
public header and their own tests.
This bumps the minimum version of CMake required to 3.14. The
specific feature needed is:
> The install(TARGETS) command learned how to install to an
> appropriate default directory for a given target type, based on
> variables from the GNUInstallDirs module and built-in defaults,
> in lieu of a DESTINATION argument.
This is so each component doesn't have to copy/paste the same config
and keep it in sync.
This also drops the older Catch2 version; it was not being done
for any specific reason.
Put bad test on PHP 5.4 into xfail; already xfail this on PHP 5.5.
php/php-src@471540d

[Tracer] Add component system, string_view and sapi components

---

tests/randomized/app/src/RandomizedTests/Snippets.php

This follow up PR to #1171 adds a few more scenarios to the randomized tests for the `curl_multi_*()` API.
- ~[ ] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.~

More curl-multi scenarios in randomized tests

---

Makefile
src/DDTrace/Integrations/IntegrationsLoader.php
tests/Frameworks/Symfony/Version_4_4/composer.json
tests/Frameworks/Symfony/Version_5_0/composer.lock
tests/Unit/Integrations/IntegrationsLoaderTest.php

This enables Symfony on PHP 8.0. It runs the Symfony 4.4 LTS and 5.1 integration tests.
Note that Symfony 5.0 is EOL and does not work with PHP 8.0.
This also adds a lock file that was meant to be included in #1062.
Relates to #1148.

Enable Symfony on PHP 8.0

---

tests/Frameworks/README.md
tests/Frameworks/Symfony/Version_5_2/.env
tests/Frameworks/Symfony/Version_5_2/.gitignore
tests/Frameworks/Symfony/Version_5_2/bin/console
tests/Frameworks/Symfony/Version_5_2/composer.json
tests/Frameworks/Symfony/Version_5_2/config/bundles.php
tests/Frameworks/Symfony/Version_5_2/config/packages/cache.yaml
tests/Frameworks/Symfony/Version_5_2/config/packages/framework.yaml
tests/Frameworks/Symfony/Version_5_2/config/packages/prod/routing.yaml
tests/Frameworks/Symfony/Version_5_2/config/packages/routing.yaml
tests/Frameworks/Symfony/Version_5_2/config/packages/test/framework.yaml
tests/Frameworks/Symfony/Version_5_2/config/packages/test/twig.yaml
tests/Frameworks/Symfony/Version_5_2/config/packages/twig.yaml
tests/Frameworks/Symfony/Version_5_2/config/preload.php
tests/Frameworks/Symfony/Version_5_2/config/routes.yaml
tests/Frameworks/Symfony/Version_5_2/config/routes/annotations.yaml
tests/Frameworks/Symfony/Version_5_2/config/routes/dev/framework.yaml
tests/Frameworks/Symfony/Version_5_2/config/services.yaml
tests/Frameworks/Symfony/Version_5_2/public/index.php
tests/Frameworks/Symfony/Version_5_2/src/Kernel.php
tests/Frameworks/Symfony/Version_5_2/templates/base.html.twig

This uses symfony/skeleton instead of symfony/web-skeleton to have
fewer unused dependencies, which have caused dependency issues
in the past when trying to run tests on a wide range of PHP versions.
Add doctrine/annotations for routing. Symfony 5.2 now supports PHP 8
attributes for routing, but since we need this to work on PHP 7.2-7.4
we use annotations.
Add symfony/twig-bundle for testing Twig integration.

Add sources for Symfony 5.2 framework

---

Makefile
tests/Frameworks/Symfony/Version_5_2/src/Controller/CommonScenariosController.php
tests/Frameworks/Symfony/Version_5_2/templates/twig_template.html.twig
tests/Integrations/Symfony/V5_2/CommonScenariosTest.php
tests/Integrations/Symfony/V5_2/TraceSearchConfigTest.php
tooling/bin/install-xdebug.sh

This tests the Symfony 5.2 release. Note that some of the common scenarios results are slightly different because this doesn't install the web debug toolbar, so there is one less template render command.
This runs on PHP 7.2 - 7.4 and 8.0.
~Blocked on #1177 so it will be easier to review.~ Unblocked.
Relates to #1148.

Test Symfony 5.2

---

ext/php8/engine_api.h
ext/php8/serializer.c
tests/Integrations/PDO/PDOTest.php

This is now based on the PHP 8.0 version of
Exception::getTraceAsString.
Also patch up PDO exception tests. In 8.0.1 PHP fixed a bug:
php/php-src@ccb7f1c7d8518dc4548273a5acd578c57d47cc0c
In our tests it manifests as:
> SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
This isn't what we are testing, so let's fix it so when we upgrade
our container it doesn't start failing.

Refactor the PHP 8 exception serialization

---

src/DDTrace/Integrations/Slim/SlimIntegration.php
tests/Integrations/Slim/V4/CommonScenariosTest.php

Adds support for some of Slim 4's middleware implementations; it doesn't support all forms because our tracer doesn't support tracing closures and anonymous classes (at least, not statically).
This PR previously had support for Slim 4's error handler. Support for the Slim 4 error handler has been disabled and will be re-enabled in another PR.

 Support PsrHttpServerMiddleware for Slim 4

---

include/dd_send.h
include/http.h
src/dd_send.c
src/http.c
src/pprof.c
src/string_table.c

Various v3 intake format stuff.
dd_send should now support the v3 intake format.  We don't provide a v2 compatibility mode--just outright disable it.  It would be easy enough to add support again, but I see no reason to support a legacy interface.
Also the HTTP layer now:
* uses Connection: close and do tail-closing for HTTP reqs
* properly handles SIGPIPE (by not allowing it to be thrown!)

[ddprof] Support v3 intake format; HTTP bugfixes

---

dockerfiles/frameworks/Makefile
dockerfiles/frameworks/README.md
dockerfiles/frameworks/contrib/Dockerfile
dockerfiles/frameworks/contrib/entrypoint.sh
dockerfiles/frameworks/contrib/flow/20-redis.ini
dockerfiles/frameworks/contrib/flow/30.tz.ini
dockerfiles/frameworks/contrib/flow/Settings.yaml
dockerfiles/frameworks/contrib/flow/patch.patch
dockerfiles/frameworks/contrib/flow/run.sh
dockerfiles/frameworks/contrib/laravel/patch.patch
dockerfiles/frameworks/contrib/phpredis/3.1.6/patch.patch
dockerfiles/frameworks/contrib/phpredis/3.1.6/run.sh
dockerfiles/frameworks/contrib/phpredis/4.3.0/patch.patch
dockerfiles/frameworks/contrib/phpredis/4.3.0/run.sh
dockerfiles/frameworks/contrib/phpredis/5.3.1/patch.patch
dockerfiles/frameworks/contrib/phpredis/5.3.1/run.sh
dockerfiles/frameworks/contrib/switch_php.sh
dockerfiles/frameworks/contrib/symfony/run.sh
dockerfiles/frameworks/contrib/symfony/v4.3.4.patch
dockerfiles/frameworks/contrib/wordpress/4.8.10.patch
dockerfiles/frameworks/contrib/wordpress/run.sh
dockerfiles/frameworks/contrib/wordpress/wp-tests-config.php
dockerfiles/frameworks/flow.yml
dockerfiles/frameworks/laravel.yml
dockerfiles/frameworks/phpredis3.yml
dockerfiles/frameworks/phpredis4.yml
dockerfiles/frameworks/phpredis5.yml
dockerfiles/frameworks/symfony.yml
dockerfiles/frameworks/wordpress.yml

Note to the reviewer:
- this commit https://github.com/DataDog/dd-trace-php/pull/1183/commits/dc729ac39a174455a5546201fa0713a6aeba8192 brings the code over as it is from https://github.com/DataDog/dd-trace-ci/pull/32
- this commit https://github.com/DataDog/dd-trace-php/pull/1183/commits/f0106a7e336c1b3fa71d33e242575ff883fd3518 contains the actual changes

Import framework tests suite from dd-trace-ci to dd-trace-php

---

.gitattributes

When installing `datadog/dd-trace` via composer, the large `dockerfiles/` directory is pulled down as well.
This directory is over 40 MB uncompressed, and makes up the majority of the package contents.
Similar to #61, this change excludes that directory from the resulting archive to slim down installs.
If some of the contents of `dockerfiles/` are needed in the release, most of the benefit of this PR could be achieved by excluding just `dockerfiles/testing-environment/`.
Comparison of the resulting archives:

Exclude dockerfiles directory from the composer package

---

tests/Common/AgentReplayerTrait.php
tests/Common/TracerTestTrait.php
tests/Integration/LongRunning/LongRunningScriptTest.php
tests/Integration/Transport/HttpTest.php
tests/ext/includes/request_replayer.inc

While we are still able to handle only one request in the response from the request replayer, the response is not in the format `[{req_1}, {req_2}]` instead of `{req}`, so that we can assert that only one request was done.
This was required in the context of `pcntl` testing.
Note: this expects https://github.com/DataDog/dd-trace-ci/pull/33 to be merged, as well. Image is already live.

Accept multiple requests dumped from request-replayer

---

dockerfiles/ci/xfail_tests/5.4.list
dockerfiles/ci/xfail_tests/5.5.list
dockerfiles/ci/xfail_tests/README.md

Disabled on versions: `5.4`, `5.5`.
Links to sample broken executions: [5.4](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/5511/workflows/3d3921f6-bcfc-4975-9a8f-3b8db6005462/jobs/375326), [5.5](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/5511/workflows/3d3921f6-bcfc-4975-9a8f-3b8db6005462/jobs/375320).
_Investigation_
This test started to fail after we [enabled the pcntl extension](https://github.com/DataDog/dd-trace-ci/pull/34/files) in our buster containers.
It was [skipped before](https://github.com/php/php-src/blob/bcd100d812b525c982cf75d6c6dabe839f61634a/ext/openssl/tests/bug54992.phpt#L6) because function `pcntl_fork` was not available.
Building again the container without `pcntl` enabled AND not even building the tracer, the test still fails. …

Disable php language tests `ext/openssl/tests/bug54992.phpt`

---

.circleci/config.yml
src/DDTrace/Integrations/Laravel/LaravelIntegration.php
tests/Frameworks/Laravel/Version_8_x/app/Http/Controllers/RouteCachingController.php
tests/Frameworks/Laravel/Version_8_x/routes/web.php
tests/Integrations/Laravel/V5_7/CommonScenariosTest.php
tests/Integrations/Laravel/V5_8/CommonScenariosTest.php
tests/Integrations/Laravel/V8_x/CommonScenariosTest.php
tests/Integrations/Laravel/V8_x/RouteCachingTest.php

Starting from [7.x](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Routing/AbstractRouteCollection.php#L227), unnamed routes in Laravel are given a randomly generated name. This PR normalized the randomly generated name to `unnamed_route` as we do for uncached routes.
Note: Symfony, on which Laravel is heavily based, does not seem to have a similar mechanism, based on their [official docs](https://symfony.com/doc/current/routing.html) and on the output of `ph bin/console list` command.

handle laravel 7+ generated:: prefix for unnamed routes

---

.circleci/config.yml
dockerfiles/ci/buster/Dockerfile
dockerfiles/ci/buster/php-5.4/Dockerfile
dockerfiles/ci/buster/php-5.4/welcome
dockerfiles/ci/buster/php-5.5/Dockerfile
dockerfiles/ci/buster/php-5.5/welcome
dockerfiles/ci/buster/php-5.6/Dockerfile
dockerfiles/ci/buster/php-5.6/welcome
dockerfiles/ci/buster/php-7.0/Dockerfile
dockerfiles/ci/buster/php-7.0/welcome
dockerfiles/ci/buster/php-7.1/Dockerfile
dockerfiles/ci/buster/php-7.1/welcome
dockerfiles/ci/buster/php-7.2/Dockerfile
dockerfiles/ci/buster/php-7.2/welcome
dockerfiles/ci/buster/php-7.3/Dockerfile
dockerfiles/ci/buster/php-7.3/welcome
dockerfiles/ci/buster/php-7.4/Dockerfile
dockerfiles/ci/buster/php-7.4/welcome
dockerfiles/ci/buster/php-8.0/Dockerfile
dockerfiles/ci/buster/php-8.0/Dockerfile_shared_ext
dockerfiles/ci/buster/php-8.0/welcome

Since we dismissed the idea of having multiple versions of PHP in our development containers due  to images size, we remove all the version prefixes from the installation dirs.
This will reduce code duplication in CI, since now you can have one `swith_php_version: <variant>` that serves well across multiple versions in a matrix configuration.
Moreover, we re-enable `memcached` extension that was installed but not enabled on 7.4-.
Note to the reviewer: tests are failing because I did not push the new images. We have probably to wait until 0.57.0 before we can push the images and consequently merge this PR, but I'd love to receive an early feedback since to rebuild images takes ages.
- ~[] Tests added for this feature/bug.~

Remove PHP version prefix from buster development containers

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

Version bump 0.57.0
Note for the reviewer: errors on php7.5 (pcntl) and the components failures are expected and fixed on master. They do not impact the quality of the release.

Release 0.57.0

---

components/container_id/tests/container_id_parser.cc

This specific line from a Kubernetes cgroup file was reported as not being parsed correctly on the Python tracer (DataDog/dd-trace-py#2314).

Add a Kubernetes example to container tagging tests

---

zend_abstract_interface/zai_sapi/php5/zai_sapi.c
zend_abstract_interface/zai_sapi/php7/zai_sapi.c
zend_abstract_interface/zai_sapi/php8/zai_sapi.c
zend_abstract_interface/zai_sapi/tests/CMakeLists.txt
zend_abstract_interface/zai_sapi/tests/stubs/basic.php
zend_abstract_interface/zai_sapi/tests/zai_sapi.cc
zend_abstract_interface/zai_sapi/zai_sapi.h

- Add some version agnostic APIs for performing common tasks in the Zend Engine for use in C-level tests (PHP 5, PHP 7, and PHP 8).
- Add some basic hello-world SAPI test functionality as [requested](https://github.com/DataDog/dd-trace-php/pull/1204#pullrequestreview-637065530) in #1204.

[ZAI SAPI] Add test helpers

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

Release 0.58.0
**Note to the reviewer**
- Randomized test failure is not related to a code flaw, is an operation issue.
- Failures on 8 are known and are only a CI issue, not a code issue. will be fixed once  https://github.com/DataDog/dd-trace-php/pull/1210 gets merged.

Release 0.58.0

---

.circleci/config.yml
.phpcs.xml
config.m4
package.xml
zend_abstract_interface/zai_sapi/CMakeLists.txt
zend_abstract_interface/zai_sapi/php5/zai_sapi.c
zend_abstract_interface/zai_sapi/php7/zai_sapi.c
zend_abstract_interface/zai_sapi/php8/zai_sapi.c
zend_abstract_interface/zai_sapi/tests/CMakeLists.txt
zend_abstract_interface/zai_sapi/tests/stubs/trigger_error_E_CORE_ERROR.php
zend_abstract_interface/zai_sapi/tests/stubs/trigger_error_E_ERROR.php
zend_abstract_interface/zai_sapi/tests/stubs/trigger_error_E_NOTICE.php
zend_abstract_interface/zai_sapi/tests/stubs/trigger_error_E_WARNING.php
zend_abstract_interface/zai_sapi/tests/stubs/trigger_error_invalid.php
zend_abstract_interface/zai_sapi/tests/zai_sapi_functions.cc
zend_abstract_interface/zai_sapi/zai_sapi.h
zend_abstract_interface/zai_sapi/zai_sapi_functions.c
zend_abstract_interface/zai_sapi/zai_sapi_functions.h

This copies `DDTrace\Testing\trigger_error()` into the ZAI SAPI as `Zai\trigger_error()`. This will be necessary to test an upcoming PR that adds ZAI sandboxing.

[ZAI SAPI] Zai\trigger_error() SAPI function

---

components/container_id/container_id.c
components/container_id/container_id.h
components/container_id/tests/container_id_from_file.cc
components/sapi/sapi.c
components/sapi/tests/sapi.cc

Remove unused macros.
Remove unused include.
Fix mis-spellings.
Use nullptr over NULL in C++ files.
Use C++ ranged-based for loops instead of calculating the size of
the array by hand (in C++ files only, ofc). Rename cases to servers
so that the singular form is a valid variable name (cannot have a
variable named 'case', since it's part of the langauge).
With these changes, the components/ directory is free from warnings
from clang-tidy, at least with the options enabled by default in
CLion.

Tidy the components/

---

docker-compose.yml

While developing https://github.com/DataDog/dd-trace-php/pull/1210 we had renamed the buster images to `_tmp` in order to avoid breaking master.
Now that the PR is on master, we can go back to _tmp-less as usual.

remove _tmp suffix from development buster images

---

bridge/configuration.php
src/DDTrace/Sampling/ConfigurableSampler.php
tests/Unit/ConfigurationTest.php
tests/Unit/Sampling/ConfigurableSamplerTest.php

`_dd.rule_psr` has always to be set. Previously we were only setting it for sampling rules. It is necessary to have the correct values in the ingestion control pages.

Fix ingestion control reporting

---

dockerfiles/ci/buster/Dockerfile

This adds `make [Tab]` autocomplete functionality to our dev images. Actually builds and push of images will progressively come next.

Autocomplete Makefile target names in buster dev images

---

.circleci/config.yml
Makefile
ext/php8/handlers_curl.c
tests/ext/from_php_7_3_bug61728.phpt
tests/ext/pcntl/pcntl_fork_long_running_autoflush.phpt
tests/ext/pcntl/pcntl_fork_long_running_manual.phpt
tests/ext/pcntl/pcntl_fork_short_running_multiple.phpt
tests/ext/pcntl/pcntl_fork_short_running_nested.phpt
tests/ext/pcntl/pcntl_fork_short_running_single.phpt
tests/ext/segfault_backtrace_disabled.phpt
tests/ext/segfault_backtrace_enabled.phpt

This is a followup PR to #1181 which addressed #1157 when the tracer was installed from source. However, the prebuilt packages are built on a machine that has ext/curl enabled as part of the PHP build. This results in the `undefined symbol: curl_multi_ce` error when the PHP tracer is installed from a prebuilt package and ext/curl is loaded as a shared library.
This PR removes the dependency on the `ext/curl/php_curl.h` header entirely and always resolves the curl symbols at runtime.
To test this (on Debian), the phpt tests are run in CI after installing the tracer from a `.deb` package and then tested again after compiling from source. It is tested on a minimum build of PHP (`--disable-all`) to ensure maximum missing symbols from extensions.
Thank you to @metaxy for the followup report!

Always resolve curl class entry symbols at runtime (PHP 8)

---

.editorconfig
CONTRIBUTING.md
UPGRADE-0.10.md
architecture.md
components/README.md
tests/PostInstallHook/README.md

This is an incomplete documentation of components, ext/php$n, and
the background sender. This information should be valuable to
newcomers.
I opted to write this as markdown in this repository instead of
a Google Document so that it is close to the thing it documents
and is open to everyone, not just Datadog employees.
This also changes the `.editorconfig` to care less about
formatting in Markdown files, though it now enforces that
trailing whitespace is removed.

Begin documenting architecture

---

.circleci/config.yml
config.m4
package.xml
zend_abstract_interface/CMakeLists.txt
zend_abstract_interface/sandbox/CMakeLists.txt
zend_abstract_interface/sandbox/php5/sandbox.c
zend_abstract_interface/sandbox/php7/sandbox.c
zend_abstract_interface/sandbox/php8/sandbox.c
zend_abstract_interface/sandbox/sandbox.h
zend_abstract_interface/sandbox/tests/CMakeLists.txt
zend_abstract_interface/sandbox/tests/sandbox.cc
zend_abstract_interface/sandbox/tests/stubs/throw_exception.php
zend_abstract_interface/sandbox/tests/stubs/trigger_error_E_ERROR.php
zend_abstract_interface/sandbox/tests/stubs/trigger_error_E_NOTICE.php
zend_abstract_interface/sandbox/tests/stubs/trigger_error_E_WARNING.php
zend_abstract_interface/zai_sapi/php5/zai_sapi.c
zend_abstract_interface/zai_sapi/php7/zai_sapi.c
zend_abstract_interface/zai_sapi/php8/zai_sapi.c
zend_abstract_interface/zai_sapi/tests/zai_sapi.cc
zend_abstract_interface/zai_sapi/tests/zai_sapi_functions.cc
zend_abstract_interface/zai_sapi/zai_sapi.h
zend_abstract_interface/zai_sapi/zai_sapi_functions.c

ZAI Sandbox prevents PHP code execution from throwing exceptions or raising errors if executed inside the sandbox. It ensures that if there is an existing error or unhandled exception when the sandbox is opened, the error and exception state will be unchanged after closing the sandbox.
This PR includes a number of other enhancements to the ZAI SAPI test runner including:
- Fake PHP frame injection (scoped to the `Zai\noop()` internal function)
- Last error introspection
- Exception throwing
- Unhandled exception introspection

ZAI Sandbox

---

config.m4
package.xml
zend_abstract_interface/CMakeLists.txt
zend_abstract_interface/methods/CMakeLists.txt
zend_abstract_interface/methods/methods.h
zend_abstract_interface/methods/php5/methods.c
zend_abstract_interface/methods/tests/CMakeLists.txt
zend_abstract_interface/methods/tests/php5/methods.cc
zend_abstract_interface/methods/tests/stubs/AbstractTest.php
zend_abstract_interface/methods/tests/stubs/ExceptionTest.php
zend_abstract_interface/methods/tests/stubs/Test.php

The Zend Abstract Interface (ZAI) is an API for calling into PHP from C. The seams are decoupled from the main PHP tracer and tested using the ZAI SAPI.
This PR includes the first ZAI seam on PHP 5 for safely calling methods (sandboxed):
- `zai_class_lookup()`
- `zai_call_method_without_args()`
- `zai_call_static_method_without_args()`
This seam will be used to finish the implementation of autoflushing in #1189.

Zend Abstract Interface: Method call seam (PHP 5)

---

.circleci/config.yml

Due to:
- https://blog.packagist.com/composer-command-injection-vulnerability/
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-29472
Note, we wait for composer images to be released on docker hub before rebuilding the development images.
We do not use composer in other images used to build the final artifact.

Self update composer in the image we use to prepare the code in CI

---

.circleci/config.yml
zend_abstract_interface/methods/tests/php5/methods.cc
zend_abstract_interface/sandbox/tests/sandbox.cc
zend_abstract_interface/zai_sapi/php5/zai_sapi.c
zend_abstract_interface/zai_sapi/php7/zai_sapi.c
zend_abstract_interface/zai_sapi/php8/zai_sapi.c
zend_abstract_interface/zai_sapi/zai_sapi.h

This PR adds a way to detect Zend Memory Manager leak messages in the ZAI tests by grepping the test log in CI for:
```
=== Total n memory leaks detected ===
```
There were a few ZMM leaks that were isolated to the tests (the leaks were not in the tracer or any production code paths) and those are fixed in d8b4c3e.
Ideally the leak detection would be implemented as part of the ZAI SAPI test runner, but every way I tired to implement it, I hit a blocker.
- ZMM bypasses the SAPI error logger and [writes the leak message directly to stderr](https://github.com/php/php-src/blob/PHP-8.0.4/main/main.c#L1588) which I haven't been able to capture from ZAI SAPI during RSHUTDOWN.
- There is no way to inject a [custom hook](https://github.com/php/php-src/blob/PHP-8.0.4/main/main.c#L2034) to capture …

Detect ZAI ZMM leaks

---

tests/Integrations/PCNTL/PCNTLTest.php

This PR fixes some flaky PCNTL tests by giving them some more execution time wiggle room in CI. (See flaky failure examples [here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/5757/workflows/c7dfa82d-c101-4236-8156-06e7c8a22091/jobs/427720), [here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/5762/workflows/14ebc8db-3b0f-4605-95f6-19f04d66da3f/jobs/429103), and [here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/5770/workflows/74b29683-2160-41f0-837f-22034e19915e/jobs/431385).)

Fix flaky PCNTL tests

---

dockerfiles/ci/README.md
dockerfiles/ci/xfail_tests/7.1.list
dockerfiles/ci/xfail_tests/7.2.list
dockerfiles/ci/xfail_tests/7.4.list
dockerfiles/ci/xfail_tests/8.0.list
dockerfiles/ci/xfail_tests/README.md

- Update the Docker `ci` docs per @morrisonlevi's [request](https://github.com/DataDog/dd-trace-php/pull/1201#pullrequestreview-634834368) from #1201. 
- ~~Update the references to the Buster containers in the main `docker-compose.yml` file.~~ Addressed in #1223.
- Skip a test in PHP 7.0+ that has [a long history of being flaky in CI](https://github.com/php/php-src/commits/master/ext/standard/tests/streams/proc_open_bug69900.phpt). (This was already being skipped on PHP 7.0 and 7.3.)
- Reorganize the `xfail_tests/README.md`.

Update Docker ci docs

---

config.m4
ext/php5/signals.c
ext/php7/signals.c
ext/php8/signals.c
php_ddtrace.h

Putting dd-trace-php directly under php-src/ext should now work.
~Tests added for this feature/bug.~

Change config.m4 to allow in-tree build

---

ext/php5/coms.c
ext/php7/coms.c
ext/php8/coms.c
tests/Common/TracerTestTrait.php
tests/ext/background-sender/agent_headers.phpt

Starting from `0.57.0` we were sending the language version using the header `Datadog-Meta-Version` instead of the correct name `Datadog-Meta-Lang-Version`. This results in wrong reports about language usage and in missing filters in urser's metrics panel, with missing possibility to filter.

Fix meta header name for language version in BGS agent request

---

tests/randomized/app/composer-5.4.json
tests/randomized/app/composer-5.5.json
tests/randomized/app/composer-5.6.json
tests/randomized/app/composer-7.0.json
tests/randomized/app/composer-7.1.json
tests/randomized/app/composer-7.2.json
tests/randomized/app/composer-7.3.json
tests/randomized/app/composer-7.4.json
tests/randomized/app/composer-8.0.json

After 0.57.0 our composer package is way smaller thanks to #1192. We want to use a post-0.57.0 version to make the update operation quicker.
Moreover we pin the exact version in composer to improve reproducibility of regressions, since the composer file is copied and pasted.

speed up randomized testing using a post #1192  version

---

config.m4
package.xml
zend_abstract_interface/CMakeLists.txt
zend_abstract_interface/functions/CMakeLists.txt
zend_abstract_interface/functions/functions.h
zend_abstract_interface/functions/php8/functions.c
zend_abstract_interface/functions/tests/CMakeLists.txt
zend_abstract_interface/functions/tests/php8/functions.cc
zend_abstract_interface/functions/tests/stubs/basic.php
zend_abstract_interface/methods/php5/methods.c
zend_abstract_interface/sandbox/php8/sandbox.c
zend_abstract_interface/sandbox/sandbox.h
zend_abstract_interface/zai_assert/CMakeLists.txt
zend_abstract_interface/zai_assert/zai_assert.h

This PR adds a Zend Abstract Interface (ZAI) seam for safely calling (sandboxed) PHP functions from C in PHP 8:
- `bool zai_call_function_literal(const char *name, zval *retval, ...);`
- `bool zai_call_function(const char *name, size_t name_len, zval *retval, ...);`
- `bool zai_call_function_ex(const char *name, size_t name_len, zval *retval, int argc, ...);`
This seam will initially be used to call the [userland deferred-loading function](https://github.com/DataDog/dd-trace-php/blob/5b8ea36/ext/php8/php8/engine_hooks.c#L127-L160) in PHP 8.
This PR also includes a new macro for asserting lowercase strings (`zai_assert/zai_assert.h`):
```c
zai_assert_is_lower(str, "String must be lowercase.");
```
As with `assert()`, `zai_assert_is_lower()` will only abort on debug builds of PHP.

ZAI function-call seam (PHP 8)

---

ext/php8/ddtrace.c
ext/php8/engine_hooks.h
ext/php8/php8/engine_hooks.c

This uses the ZAI function-call seam added in #1234 to call the userland deferred loader function `DDTrace\Integrations\load_deferred_integration`.

Deferred loading with ZAI function-call seam (PHP 8)

---

config.m4
package.xml
zend_abstract_interface/CMakeLists.txt
zend_abstract_interface/properties/CMakeLists.txt
zend_abstract_interface/properties/php7-8/properties.c
zend_abstract_interface/properties/php7-8/properties.h
zend_abstract_interface/properties/properties.h
zend_abstract_interface/properties/tests/CMakeLists.txt
zend_abstract_interface/properties/tests/php7-8/properties.cc
zend_abstract_interface/properties/tests/stubs/classes.php

A simple function allowing direct access into userland (and internal classes without very special property storage) properties, bypassing __get() and similar.

Create property ZAI seam for PHP 8

---

config.m4
ext/php8/engine_hooks.c
ext/php8/engine_hooks.h
ext/php8/php8/engine_hooks.c
ext/php8/request_hooks.c
ext/php8/serializer.c
package.xml
zend_abstract_interface/CMakeLists.txt
zend_abstract_interface/exceptions/CMakeLists.txt
zend_abstract_interface/exceptions/exceptions.h
zend_abstract_interface/exceptions/exceptions_common.h
zend_abstract_interface/exceptions/php8/exceptions.c
zend_abstract_interface/exceptions/php8/exceptions.h
zend_abstract_interface/exceptions/tests/CMakeLists.txt
zend_abstract_interface/exceptions/tests/php8/exceptions.cc
zend_abstract_interface/exceptions/tests/stubs/functions.php

Using the properties seam within an exceptions seam, and use that in the php 8 source.

Create exceptions ZAI seam for PHP 8 

---

.circleci/config.yml
dockerfiles/frameworks/contrib/Dockerfile
dockerfiles/frameworks/contrib/mongodb-driver/README.md
dockerfiles/frameworks/contrib/mongodb-driver/run.sh
dockerfiles/frameworks/mongodb-driver.yml

Run the latest mongodb-drive testsuite in CI (https://github.com/mongodb/mongo-php-driver).

Run mongodb-driver testsuite in CI with and without the tracer

---

ext/php8/ddtrace.c
ext/php8/ddtrace.h
ext/php8/php8/engine_hooks.c
ext/php8/serializer.c
ext/php8/span.c
ext/php8/span.h
package.xml
tests/ext/active_span.phpt
tests/ext/sandbox/span_clone.phpt
tests/ext/sandbox/span_resource_serialization.phpt

Also already exposes DDTrace\active_span() and getStartTime() / getDuration(). (Which are crucial for the #1251 internal spans, where this PR was split off.)
The refactor itself is needed to access time info from the fci from the object.
Note that there are currently no proper tests for the two methods, but in PR #1251 there are some; properly (i.e. in a meaningful way) testing this needs start_span() functions.

Refactor internal span objects to be allocated together with their internal data

---

config.m4
package.xml
zend_abstract_interface/CMakeLists.txt
zend_abstract_interface/env/env.h
zend_abstract_interface/headers/CMakeLists.txt
zend_abstract_interface/headers/headers.h
zend_abstract_interface/headers/php7-8/headers.c
zend_abstract_interface/headers/tests/CMakeLists.txt
zend_abstract_interface/headers/tests/php7-8/headers.cc
zend_abstract_interface/zai_assert/zai_assert.h
zend_abstract_interface/zai_sapi/php5/zai_sapi.c
zend_abstract_interface/zai_sapi/php7/zai_sapi.c
zend_abstract_interface/zai_sapi/php8/zai_sapi.c
zend_abstract_interface/zai_sapi/zai_sapi.h
zend_abstract_interface/zai_string/CMakeLists.txt
zend_abstract_interface/zai_string/string.h

Required for internal spans, to read x-datadog-parent-id and x-datadog-origin-id headers to set parent id & trace id on root spans.
Note: ZAI_HEADER_NOT_READY case is not tested yet, I'm waiting for @SammyK changes to ZAI in #1250 to test this.

Add ZAI component for reading headers

---

ext/php5/serializer.c
ext/php7/serializer.c
ext/php8/serializer.c
tests/ext/sandbox-prehook/dd_trace_method.phpt
tests/ext/sandbox/dd_trace_function_complex.phpt
tests/ext/sandbox/dd_trace_method.phpt

Internal serializer is currently preserving the metrics array as-is. I'm now only preserving string keys and converting them to double as mandated by the agent. This is especially important when cutting out userland from serializing.

Enforce metrics to be floats in internal serializer

---

ext/php5/serializer.c
ext/php7/serializer.c
ext/php8/serializer.c
tests/ext/dd_trace_serialize_msgpack.phpt

Trying to serialize empty meta arrays lead to invalid message pack data.

Fix msgpack serialization of empty arrays

---

CONTRIBUTING.md
Makefile
docker-compose.yml
dockerfiles/ci/buster/Dockerfile
tests/Sapi/CliServer/CliServer.php
tests/Sapi/PhpCgi/PhpCgi.php
tests/Sapi/PhpFpm/PhpFpm.php
zend_abstract_interface/CMakeLists.txt

See list of commits, in particular it will now be possible to add `export DD_TRACE_DOCKER_DEBUG=1` to your environment (I recommend saving it to `~/.profile`) on the host. This will always imply `dev` and `debug` during make. These can be disabled when needed by `use_generated` and `prod`, respectively.

Allow for global debug mode, add zai testing to Makefile and more minor testing improvements

---

Makefile

Trivial fix for bogus behavior introduced in 6e1dccff9d69b3e913be764ad661e3a965bd662e:
```
make: Nothing to be done for 'prod'.
make: invalid option -- 'g'
make: invalid option -- 'g'
make: invalid option -- '0'
```

Fix debug/prod Makefile options

---

ext/php8/engine_hooks.h
ext/php8/request_hooks.c
zend_abstract_interface/sandbox/sandbox.h

Only fix the build, some tests are  failing
and as 8.1 API is not yet final...

fix some API change in 8.1.0alpha3

---

dockerfiles/ci/alpine/docker-compose.yml
dockerfiles/ci/alpine/php-8.0/configure.sh
dockerfiles/ci/buster/Dockerfile
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/buster/php-7.4/configure.sh
dockerfiles/ci/buster/php-8.0/configure.sh
dockerfiles/ci/buster/php-8.0/configure_shared_ext.sh
dockerfiles/ci/buster/php-master/install-php-master
dockerfiles/ci/centos/6/CentOS-Base.repo
dockerfiles/ci/centos/6/CentOS-SCLo-scl-rh.repo
dockerfiles/ci/centos/6/CentOS-SCLo-scl.repo
dockerfiles/ci/centos/6/Dockerfile
dockerfiles/ci/centos/6/Dockerfile_php5
dockerfiles/ci/centos/6/Dockerfile_php7
dockerfiles/ci/centos/6/Dockerfile_php8
dockerfiles/ci/centos/6/docker-compose.yml
dockerfiles/ci/centos/6/php-7.4/configure.sh
dockerfiles/ci/centos/6/php-8.0/configure.sh
dockerfiles/ci/xfail_tests/7.4.list
dockerfiles/ci/xfail_tests/8.0.list
dockerfiles/ci/xfail_tests/README.md
dockerfiles/compile_extension/docker-compose.yml
dockerfiles/compile_extension/install-php

This allows us to try sideeffect-ful syscalls in our testsuite.
Also fix CentOS 6 for now by hardcoding repository files from their vault (repository archive).

Add ext/ffi to PHP builds

---

config.m4
ext/php5/coms.c
ext/php5/configuration.h
ext/php7/coms.c
ext/php7/configuration.h
ext/php8/coms.c
ext/php8/configuration.h
package.xml
tests/ext/background-sender/background_sender_survives_setuid.phpt

Setuid() calls reset the effective capabilities of a thread to zero. This will prevent us from doing some operations. (including the setgroups() syscall where we encountered the crash.)
_No tests added as I have no idea how to meaningfully test this, especially in a non-privileged docker container ..._

Set SECBIT_NO_SETUID_FIXUP to prevent crashes after setuid() calls

---

ext/php8/compatibility.h
ext/php8/ddtrace.c
ext/php8/ddtrace.h
ext/php8/engine_hooks.h
ext/php8/handlers_exception.c
ext/php8/php8/engine_hooks.c
ext/php8/serializer.c
ext/php8/serializer.h
ext/php8/span.h
package.xml
tests/ext/sandbox/deferred_load_missing_load_fn.phpt
tests/ext/span_with_removed_exception.phpt

Implements feature request #1231: exceptions are now tracked in the properties instead of internally, in particular so that the exception can be changed or removed within post-tracing hook callbacks.

Register SpanData->exception property and store exception info there instead of internally

---

.circleci/config.yml
Makefile
dockerfiles/ci/buster/php-8.0/Dockerfile_shared_ext
ext/php5/handlers_curl.c
ext/php7/handlers_curl.c
ext/php8/handlers_curl.c
package.xml
tests/ext/integrations/curl/distributed_tracing_curl_existing_headers_003.phpt

This PR fixes a bug that would not apply the original curl headers to a request when `curl_setopt_array()` returns false. Although not strictly necessary, the `datadog/dd-trace-ci:php-8.0-shared-ext` container has been updated with two additional curl versions to test with the curl-related phpt tests in CI. The original bug was discovered due to a curl version upgrade, but the included test will trigger the same behavior on all curl versions.
This PR also fixes the `PHP 80 curl integration tests a shared lib` tests in CI; they [were failing and returning a successful exit code](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/6033/workflows/c9add20d-11af-422c-bc14-fb89c2e11415/jobs/501437).

Apply original curl headers when curl_setopt_array() fails

---

.circleci/config.yml
Makefile
dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/docker-compose.yml
dockerfiles/verify_packages/tar_gz/install.sh
dockerfiles/verify_packages/verify_tar_gz_root.sh

Our `.tar.gz` archive had files in it owned by user `3434:3434`, which is the `circleci` user from the docker images we use from our CI provider, including for `.` and `..` paths.
As a consequence, when installed, it changed ownership of the root directory to user `3434`.

Fix owner of files included in the distributed .tar.gz archive

---

Makefile
dockerfiles/ci/centos/6/Dockerfile

linux/securebits.h was not present in the CentOS container, leading to 026d4d304c32489a846fb56291fe036dd3894953 being inactive in our release artifacts.

Add linux/securebits.h to CentOS docker container, to have it present in linux build artifacts

---

config.m4
ext/php5/coms.c
ext/php7/coms.c
ext/php8/coms.c
package.xml
tests/ext/background-sender/background_sender_restores_capabilities.phpt

Turns out, while re-testing, the order of operations can be different and setuid() called before our MINIT. In this case the background sender will have to reset capabilities...
To test this, we just start the process with capabilities not present in effective set.

Handle an additional case of capabilities being dropped within our background sender

---

.circleci/config.yml
Makefile
ext/php8/handlers_exception.c

Non-registered function arginfo are not inspectable in userland, except by other extensions like xdebug. But it was pointing to the wrong value. And hence crashing with xdebug inspecting it...
This also means that the issue is not directly testable except with an extension intercepting internal fcalls.
Fixes #1290.

Fix arginfo of error&exception handler

---

.circleci/config.yml
dockerfiles/ci/xfail_tests/5.6.list
dockerfiles/ci/xfail_tests/7.0.list
dockerfiles/ci/xfail_tests/7.1.list
dockerfiles/ci/xfail_tests/7.2.list
dockerfiles/ci/xfail_tests/7.3.list
dockerfiles/ci/xfail_tests/7.4.list
dockerfiles/ci/xfail_tests/8.0.list
dockerfiles/ci/xfail_tests/README.md

PHP 8.1 switches to using ephemeral ports. Prior to this, these
tests are flaky and will fail because a port is already in use:
php/php-src@08eb917fd5d5f62eb2c3403ac41e576325a0b519

Disable flaky ext/ftp tests on PHP < 8.1

---

.circleci/config.yml
composer.json

Recently static analysis started to fail because composer would install binaries, specifically phpstan binary, to
~/.config/composer/vendor/bin instead of ~/.composer/vendor/bin
In addition to fix this path, we also now use the most modern cimg/php images as recommended by circleci:
https://circleci.com/developer/images/image/cimg/php
~- [ ] (only for Members) Changelog has been added to the release document.~

Fix static analysis execution on CI

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

**WARNING**: With this release the file `_generated.php` is not used anymore and files `_generated_api.php` and `_generated_internal.php` are generated instead. This only impacts users having a very custom installation procedure that requires custom builds and manual copy of files.
- Bring ZAI config, internal spans, and improved exception handling to PHP 7 #1293
- Disable flaky ext/ftp tests on PHP < 8.1 #1296
- Compatibility with PHP 7.4+ preloading #1298 (thank you @olsavmic for the investigation and reproduction case)
- Check for php8 binary in package/post-install.sh script #1301 (thank you for the contribution @daiwai)
- Support userland spans with custom root spans created internally #1303
- Fix memory leak of already defined global tags #1304

Release 0.64.0

---

.gitignore
tooling/metrics/Makefile
tooling/metrics/README.md
tooling/metrics/sirun.template.yml
tooling/metrics/synthetic.php

Allow measuring memory's max resident size while running the a synthetic script under 3 scenarios: no-tracer, a specific version used as a reference (via a url provided as a `REFERENCE_URL`), the target version that has to be measured (via a url provided as a `TARGET_URL`).

allow comparing two versions through DataDog/sirun

---

src/DDTrace/Tracer.php
tests/Common/SpanAssertion.php
tests/Common/SpanChecker.php
tests/Common/TracerTestTrait.php

Fix for #1311. We are now implicitly checking timing sanity for every ever tested span.

Fix span start times of userland spans

---

.circleci/config.yml
Makefile
ext/php7/ddtrace.c
ext/php7/handlers_curl.c
ext/php7/span.c
ext/php8/ddtrace.c
ext/php8/handlers_curl.c
ext/php8/span.c
tests/Common/AgentReplayerTrait.php
tests/Integration/DisabledTest.php

Fix CLI processes emitting empty root spans when CLI tracing is not enabled

---

src/DDTrace/Integrations/Lumen/LumenIntegration.php
tests/Integrations/Lumen/V5_2/CommonScenariosTest.php
tests/Integrations/Lumen/V5_2/TraceSearchConfigTest.php
tests/Integrations/Lumen/V5_6/CommonScenariosTest.php
tests/Integrations/Lumen/V5_6/DeprecatedResourceNameTest.php
tests/Integrations/Lumen/V5_6/TraceSearchConfigTest.php
tests/Integrations/Lumen/V5_8/TraceSearchConfigTest.php

With this PR, we honor the value of `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED` when setting resource names.
This means that with the default value of `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED` (`true`), automatically users will have resources as `GET /actual/uri/path` instead of `GET action_name` or `GET App\Controller@action_method`.
This PR requires a **WARNING** to be added to the release notes, since resource names (thus possibly monitors) might have to be adjusted.
Users can go back to their default behavior setting `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED=false`.

Honor DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED in Lumen resource naming

---

ext/version.h
package.xml
src/DDTrace/Tracer.php

**WARNING**: Resource names for “Lumen” applications will change by default to `GET /actual/uri/path` from the previous format `GET action_name` or `GET App\Controller@action_method`. You might need to adjust your monitors and filters for the change. In order to go back to the previous behavior, instead, you can temporarily set `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED=false`
- Add functions ZAI support for PHP 5 and 7 #1300
- Add properties and exceptions ZAI implementations for PHP 5 #1306
- Remove src/dd-doctor.php #1316
- Honor DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED in Lumen resource naming #1318
-  Fix CLI processes emitting empty root spans when CLI tracing is not enabled #1320

Release 0.65.0

---

src/DDTrace/Integrations/Laravel/LaravelIntegration.php
tests/Integrations/Laravel/V5_7/CommonScenariosTest.php
tests/Integrations/Laravel/V5_8/CommonScenariosTest.php
tests/Integrations/Laravel/V8_x/CommonScenariosTest.php

The Laravel integration now attaches error information to the root span
in more cases, such as an exception during routing. It also switches
from tracing hooks which drop spans to non-tracing hooks.
Thanks, Luca, for finding which methods should be hooked.

Enhance exception reporting on Laravel 5+

---

ext/php7/auto_flush.c
ext/php8/auto_flush.c
tests/Integrations/Custom/Autoloaded/NonExecutingEndpointsTracingTest.php
tests/Nginx/nginx-default.conf
tests/Sapi/PhpFpm/www.conf

This should prevent any unnamed-php-service coming from "meta" requests like fpm-status page and requests in general which lead to traces without proper information as no PHP code is executed.

Prevent flushing traces of requests without actual PHP code

---

config.m4

This is test code. It's not supposed to be compiled in, and contains references to functions whose existence is dependent on compile time flags.
Fixes running e.g. under amazon linux preinstalled PHP.

Remove all lines containing zai_sapi from config.m4

---

ext/php7/comms_php.c
ext/php7/configuration.h
ext/php7/ddtrace.c
ext/php7/ddtrace.h
ext/php7/handlers_curl.c
ext/php7/handlers_exception.c
ext/php7/handlers_pcntl.c
ext/php7/php7/engine_hooks.c
ext/php7/serializer.c
ext/php8/comms_php.c
ext/php8/configuration.h
ext/php8/ddtrace.c
ext/php8/ddtrace.h
ext/php8/handlers_curl.c
ext/php8/handlers_exception.c
ext/php8/handlers_pcntl.c
ext/php8/php8/engine_hooks.c
ext/php8/serializer.c
package.xml
tests/Integrations/Custom/NotAutoloaded/HttpHeadersConfiguredTest.php
tests/Nginx/nginx-default.conf
tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_disable.phpt
tests/ext/pcntl/pcntl_fork_long_running_autoflush.phpt
tests/ext/request-init-hook/auto_prepend_file_original_disabled-legacy.phpt
tests/ext/startup_logging_config.phpt
tests/ext/startup_logging_json_config.phpt

This implementation now cleanly streamlines the handling of tracer disabling.

Fix unnamed service spans caused by improper handling of DD_TRACE_ENABLED

---

.gitlab-ci.yml

This PR changes where the latest PHP build is defined. Instead of being defined in the reliability project, it is defined in this project (via a simple `curl` execution). This change gives two benefits:
1. If the artifact URL expires, it doesn't break the reliability build
2. If/when `dd-trace-php` is built inside of gitlab, no changes are needed in the reliability project.

Pass artifacts to reliability env from dd-trace-php project

---

dockerfiles/ci/xfail_tests/7.2.list
dockerfiles/ci/xfail_tests/7.3.list
dockerfiles/ci/xfail_tests/7.4.list
dockerfiles/ci/xfail_tests/8.0.list
dockerfiles/ci/xfail_tests/8.1.list
dockerfiles/ci/xfail_tests/README.md

Xfail php-src tests accessing a shutdown http2 server

---

.phpcs.xml
ext/php5/arrays.c
ext/php5/compat_string.c
ext/php5/compat_string.h
ext/php5/ddtrace.c
ext/php5/dispatch.c
ext/php5/php5/dispatch.c
ext/php5/php5_4/dispatch.c
ext/php5/serializer.c
ext/php7/compat_string.c
ext/php7/compat_string.h
ext/php7/ddtrace.c
ext/php7/serializer.c
ext/php8/compat_string.c
ext/php8/compat_string.h
ext/php8/ddtrace.c
ext/php8/serializer.c
src/DDTrace/Integrations/Integration.php
src/DDTrace/Integrations/Mongo/MongoIntegration.php
src/DDTrace/Integrations/PDO/PDOIntegration.php
src/api/Http/Urls.php
tests/ext/sandbox/safe_to_string_metadata.phpt
tests/ext/sandbox/safe_to_string_properties.phpt
tests/internal-api-stress-test.php

Fixed these crashes and leaks:
- PHP_FUNCTION(dd_trace) assumed some zvals to be strings when printing the error message without checking
- span_id stack leaked if the tracer was disabled
- msgpack array writing function write_hash_table had problems with string+integer keys mixed
- use-after-free in PHP 5 if meta or metrics properties on SpanData were assigned non-array values
- hooking or tracing a function, with a name of an empty string on PHP 5 got an assertion failure
- Object of class %s could not be converted to string style exceptions could occur in our serialization code, removing object casting logic completely
I'm mostly unsure about the last point, I'm emulating it in our integration tracing hooks for now...

Add small framework to stress test our internal API with bogus inputs

---

src/DDTrace/Integrations/Laravel/LaravelIntegration.php
tests/Integrations/Laravel/V8_x/RouteCachingTest.php

When route caching is enabled in Laravel 7.x+ [routes are given a name](https://github.com/laravel/framework/blob/cada3d21c7f127ba01bb949b2fa045b7faaedbca/src/Illuminate/Routing/AbstractRouteCollection.php#L227) in any case that is randomly generated and follows two patterns:
- `generated:<random string>`: this was already handled by our instrumentation
- `some.domain.com.generated::<random string>`: when `Route::domain('some.domain.com')->group(...)` is used to register a route. We did not handle this case.
This PR adds support for this secondo case and refactors the route normalization code to make it more testable from the outside.

Fix Laravel unnamed route with caching and domain specification

---

dockerfiles/ci/buster/Dockerfile
dockerfiles/ci/buster/php-7.0/Dockerfile

Add libuv to Debian containers.
Also pin PHP 7.0's mongodb version as support for it has been
dropped.
Also add strace as per Bob's request.

Add libuv to Debian containers

---

ext/php5/ddtrace.c
ext/php5/ddtrace.h
ext/php5/span.c
ext/php7/ddtrace.c
ext/php7/ddtrace.h
ext/php7/span.c
ext/php7/span.h
ext/php8/ddtrace.c
ext/php8/ddtrace.h
ext/php8/span.c
ext/php8/span.h
package.xml
tests/ext/span_with_parent_property_access.phpt

Implement access to SpanData::$parent.
- This does not yet use ZEND_ACC_READONLY to keep the source simple (php9 will use ZEND_ACC_READONLY)
- This does not prohibit indirect modification, that would be costly to all other reads and doesn't seem worth it

SpanData::$parent property

---

ext/php5/serializer.c
ext/php7/serializer.c
ext/php8/serializer.c
package.xml
tests/Composer/ComposerInteroperabilityTest.php
tests/DistributedTracing/SyntheticsTest.php
tests/Integration/ResponseStatusCodeTest.php
tests/Integrations/Custom/Autoloaded/CircuitBreakerTest.php
tests/Integrations/Custom/Autoloaded/CommonScenariosTest.php
tests/Integrations/Custom/Autoloaded/FatalErrorTest.php
tests/Integrations/Custom/Autoloaded/TraceSearchConfigTest.php
tests/Integrations/Custom/NotAutoloaded/HttpHeadersConfiguredTest.php
tests/Integrations/Custom/NotAutoloaded/HttpHeadersNotConfiguredTest.php
tests/Integrations/Nette/V2_4/NetteTest.php
tests/Integrations/Nette/V3_0/NetteTest.php
tests/Integrations/Slim/V3_12/CommonScenariosTest.php
tests/Integrations/Symfony/V2_3/RouteNameTest.php
tests/Integrations/Symfony/V2_8/RouteNameTest.php
tests/ext/root_span_url_as_resource_names.phpt
tests/ext/root_span_url_as_resource_names_no_host.phpt

The internal root span defines (when `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED` is on) `http.url` as `$_SERVER['REQUEST_URI']`. This is incorrect according to the [RFC](https://github.com/DataDog/architecture/blob/master/rfcs/apm/integrations/trace-http-client-tagging/rfc.md) and other implementations. This PR build `http.url` as http(s)://<http_host or server_name><request uri>.

Fix http.url of internal root span

---

.circleci/config.yml
dockerfiles/ci/buster/Dockerfile

Also build with CATCH_BUILD_STATIC_LIBRARY=on, which will speed up
the component builds a bit because catch2_main (which is slow to build)
will be replaced by this one, which is built into the images.

Bump cmake and catch2 versions on Debian images

---

src/DDTrace/Integrations/PDO/PDOIntegration.php

This was found to be faulty for various flavours of PDO.
Essentially some keys (discovered from manual entries) are not supported in DSN key value pairs, in addition a driver is allowed to treat keys case insensitively, so that Host=localhost, and host=localhost and HOST=localhost may be treated the same, so we should also ignore key case.

PDOIntegration::parseDSN fails to parse some DSN

---

docker-compose.yml
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/buster/php-7.4/Dockerfile_shared_ext
dockerfiles/ci/buster/php-7.4/configure_shared_ext.sh

We already have a minimum build of PHP (`--disable-all`) for PHP 8.0 (`datadog/dd-trace-ci:php-8.0-shared-ext`) to run tests when extensions are loaded as shared libraries. This PR adds a PHP 7.4 minimum build (`datadog/dd-trace-ci:php-7.4-shared-ext`) with the json extension loaded as a shared library. This will help us to test the changes in #1366 & #1378 which impacts how the tracer interacts with the json extension.

PHP 7.4: Shared-extension Buster container

---

.circleci/config.yml
.clang-format
components/CMakeLists.txt
components/README.md
components/catch2_main.cc
components/container_id/CMakeLists.txt
components/container_id/tests/CMakeLists.txt
components/container_id/tests/container_id_from_file.cc
components/container_id/tests/container_id_parser.cc
components/sapi/CMakeLists.txt
components/sapi/sapi.c
components/sapi/sapi.h
components/sapi/tests/CMakeLists.txt
components/sapi/tests/sapi.cc
components/string_view/CMakeLists.txt
components/string_view/string_view.c
components/string_view/string_view.h
components/string_view/tests/CMakeLists.txt
components/string_view/tests/string_view.cc
config.m4
ext/php5/ddshared.c
ext/php5/ddshared.h
ext/php5/ddtrace.c
ext/php7/ddshared.c
ext/php7/ddshared.h
ext/php7/ddtrace.c
ext/php8/ddshared.c
ext/php8/ddshared.h
ext/php8/ddtrace.c

Change BUILD_COMPONENTS_TESTING to DATADOG_PHP_TESTING.
Require `components/` prefix on includes e.g.
#include <components/string_view/string_view.h>
This will prevent conflicts in the future like uuid/uuid.h and libuuid.
Set `BreakStringLiterals: false` for clang-format; wrapping string
literals makes for worse grep'ing. Re-format some tests which had
long string literals.
Remove custom catch2_main target for the standard target
Catch2::Catch2WithMain, with a polyfill for older/differently
configured versions.

Adjust components

---

src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
src/api/Http/Urls.php
tests/Unit/Http/UrlsTest.php

Previously, host names without a schema were not correctly parsed while setting resource names, tags and service name when split by domain was enabled.

Fix parsing of urls without schema into host name

---

components/CMakeLists.txt
components/log/CMakeLists.txt
components/log/log.c
components/log/log.h
components/log/tests/CMakeLists.txt
components/log/tests/log.cc

The log component can write to a file or to stdout/stderr. It is not
threadsafe, and borrows the mutex and file descriptor used. It could
theoretically be used to write to other file descriptors without much
work, but since logging as written is a blocking operation this would
be risky.
It supports these log levels:
- off
- error
- warn
- info
- debug
The profiler uses the component to build a thread-safe-ish abstraction
for a global profiler logger. The profiler uses the log levels to mean
roughly the following:
- off: nothing will be logged
- error: an error that will likely stop the profiler, such as failing
to spawn a worker thread.
- warn: an error that will likely not stop the profiler, such as
an HTTP 5xx error on upload. The profile will be dropped, but the
profiler will continue …

Add log component

---

components/CMakeLists.txt
components/arena/CMakeLists.txt
components/arena/arena.c
components/arena/arena.h
components/arena/tests/CMakeLists.txt
components/arena/tests/arena.cc

This arena is used to do bump pointer style allocations inside of a
previously allocated block, such as stack memory, static storage, or
heap memory.
Individual allocations made by the arena are not tracked and are not
freed. The use-case is allocating a bunch of data which has the same
lifetime, and then everything can be freed at once by resetting the
arena. This means that care must be taken to either not store types
which have custom destructors, or that they should be tracked and dtor'd
outside of the arena before resetting it.

Add arena component

---

components/CMakeLists.txt
components/stack-sample/CMakeLists.txt
components/stack-sample/stack-sample.c
components/stack-sample/stack-sample.h
components/stack-sample/tests/CMakeLists.txt
components/stack-sample/tests/stack-sample.cc

Represents a stack trace with function/method name, file, and
line-number information, up to a bounded depth. Frames are not required
to have all members; for instance, there may be a frame that has no
function but exists in file X on line Y, and there may be a frame that
has function Z but no file nor line information.
This isn't collecting data from the Zend Engine; this just represents
the relevant information gathered.

Add stack sample component

---

.gitlab-ci.yml

The previous release was using the CircleCI artifacts, which expire. This bumps the release version used and switches to GitHub, which will be much more reliable.

Update outdated release artifacts

---

dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/buster/php-7.4/configure_shared_ext.sh
dockerfiles/ci/buster/php-8.0/configure_shared_ext.sh

Adding the embed SAPI exposes `libphp` so that we can run ZAI SAPI in the shared-ext containers.

Add embed SAPI to shared-ext containers

---

components/CMakeLists.txt
components/time/CMakeLists.txt
components/time/time.c
components/time/time.h

The time component accounts for differences in cpu-time calls in
different platforms. In the past it was also used for monotonic and
system time, which is why it is called "time" instead of "cpu-time".
There are no tests for this component -- I could not think of any tests
that would be meaningful.

Add time component

---

components/time/CMakeLists.txt
components/time/tests/CMakeLists.txt
components/time/tests/time.cc

This simply checks for a non-zero code. It's not particularly
helpful, but it is something.

Add simple test for time component

---

src/DDTrace/OpenTracer/Tracer.php
src/DDTrace/OpenTracer1/Tracer.php
tests/OpenTracer1Unit/TracerTest.php
tests/OpenTracerUnit/TracerTest.php

Fixes https://github.com/DataDog/dd-trace-php/issues/1384

Fix constructor of OpenTracing wrapper when no Datadog tracer is provided

---

Makefile
config.m4
ddtrace.sym
dockerfiles/compile_extension/build-dd-trace-php
ext/php5/ddtrace.c
ext/php7/ddtrace.c
ext/php7/ddtrace_export.h
ext/php7/span.c
ext/php7/span.h
ext/php8/ddtrace.c
ext/php8/ddtrace_export.h
ext/php8/span.c
ext/php8/span.h
package.xml

There are only two symbols which need to be exported:
1. `get_module`, needed by all PHP modules.
2. `ddtrace_root_span_add_tag`, needed by the appsec product.
Symbols which should be exported should be marked DDTRACE_PUBLIC, which
comes from the new `ddtrace_export.h` header. The symbols should also
be added to the `ddtrace.sym` file, one per line.
Using `-fvisibility=hidden` will hide our own symbols, reduce object
size, and to a mild degree improve performance. However, it won't hide
symbols from static libraries, which is why libtool's `-export-symbols`
is also used.
Note that for the hybrid extension hack that the symbol needs to be
public on Alpine, so it was switched to use `get_module` which is
always available on correctly built modules.
Note: this is a new PR because GH …

Export only specific symbols

---

.circleci/config.yml
dd-library-php-setup.php
docker-compose.yml
dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/installer/test_alpine_no_ext_json.sh
dockerfiles/verify_packages/installer/test_install_no_ext_curl_no_curl_cli.sh
dockerfiles/verify_packages/installer/test_install_no_ext_curl_yes_curl_cli.sh
dockerfiles/verify_packages/verify_no_ext_json.sh
package/post-install.sh

The latest version (on `master`, not released yet) cannot be loaded if the json extension is not enabled and it fails with a warning:
```
[Tue Dec  7 06:05:46 2021] PHP Warning:  Cannot load module 'ddtrace' because required module 'json' is not loaded ...
```
This is the case for default installation of PHP, which does not include `json`, unless a user also add `php7-json`, for example.
This PR adds checks (and tests) to both legacy and new installers to make sure that if the extension is not installed we fail with a proper and explanatory message.

Have both legacy and new installer to fail when json PHP extension is not enabled

---

.gitattributes
phpcs.xml

VSCode phpcs extension does not recognize `.phpcs.xml` as a file name.

Rename .phpcs.xml to phpcs.xml as the first one is not recognized by VSCode

---

dockerfiles/ci/xfail_tests/7.0.list
dockerfiles/ci/xfail_tests/7.1.list
dockerfiles/ci/xfail_tests/7.2.list
dockerfiles/ci/xfail_tests/7.3.list
dockerfiles/ci/xfail_tests/7.4.list
dockerfiles/ci/xfail_tests/8.0.list
dockerfiles/ci/xfail_tests/8.1.list
dockerfiles/ci/xfail_tests/README.md

Skip a failing lang test due to an expired cert. (Recently fixed in php/php-src#7763)

Skip failing lang test

---

.gitattributes
dd-library-php-setup.php
dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/installer/test_install_add_missing_ini_settings.sh
dockerfiles/verify_packages/installer/utils.sh

As we add properties and new modules (e.g. profiling) we need to add entries for the new properties to the Ini file so they are available for the user to tweak.

Split INI setting in installer so they can be added separately when missing

---

.gitlab-ci.yml
Makefile
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Bring priority sampling to internal #1366
- SpanData::$parent property #1369
- Add queue and channel components #1388
- Add log component #1390
- Add arena component #1391
- Add stack sample component #1392
- Add uuid component #1393
- Add time component #1394, #1408
- Add profiler installation #1422
- Zai/json #1378, #1397
- Add Code Coverage #1389
- (PHP 8) Migrate ObjectKVStore to WeakMap internally #1362
- Adjust components #1387
- Export only specific symbols #1407
- Sanitize user information from urls #1396
- Split INI setting in installer so they can be added separately when missing #1415
- Use the new targz bundle format with the new PHP installer #1421
- Have both legacy and new installer to fail when json PHP extension is not enabled #1410
- Fix Laravel unnamed route with …

Bump version 0.68.0

---

src/DDTrace/Integrations/Predis/PredisIntegration.php
tests/Integrations/Predis/PredisTest.php

The Predis integration is marked as type `cache` but in order for the Agent to properly obfuscate `redis.raw_command`, the integration type needs to be `redis`.

Change Predis integration type to "redis"

---

zend_abstract_interface/methods/CMakeLists.txt
zend_abstract_interface/methods/methods.h
zend_abstract_interface/methods/php5/methods.c
zend_abstract_interface/methods/tests/CMakeLists.txt
zend_abstract_interface/methods/tests/methods.cc
zend_abstract_interface/methods/tests/stubs/Test.php
zend_abstract_interface/zai_sapi/php5/zai_sapi.c

Before adding ZAI methods for PHP 7 and 8 we needed to update the API on PHP 5 to support calling methods with arguments. The retval handling has also been updated to work more similar to the ZAI functions API. This also will also make it easier to share the same tests on PHP 7 & 8.

ZAI methods on PHP 5: Args and retval

---

.circleci/config.yml
docker-compose.yml
dockerfiles/ci/buster/docker-compose.yml
dockerfiles/ci/buster/php-5.4/Dockerfile_shared_ext
dockerfiles/ci/buster/php-5.4/configure_shared_ext.sh
ext/php5/configuration.c
ext/php5/configuration.h
ext/php5/ddtrace.c
ext/php7/configuration.c
ext/php7/configuration.h
ext/php7/ddtrace.c
ext/php8/configuration.c
ext/php8/configuration.h
ext/php8/ddtrace.c
zend_abstract_interface/CMakeLists.txt
zend_abstract_interface/config/config.c
zend_abstract_interface/config/config.h
zend_abstract_interface/config/config_decode.c
zend_abstract_interface/config/tests/config.cc
zend_abstract_interface/config/tests/config_decode.cc
zend_abstract_interface/config/tests/config_ini.cc
zend_abstract_interface/json/json.c
zend_abstract_interface/json/json.h
zend_abstract_interface/json/tests/json.cc
zend_abstract_interface/zai_sapi/php5/zai_sapi.c
zend_abstract_interface/zai_sapi/php7/zai_sapi.c
zend_abstract_interface/zai_sapi/php8/zai_sapi.c
zend_abstract_interface/zai_sapi/zai_sapi_ini.c
zend_abstract_interface/zai_sapi/zai_sapi_ini.h

This is a followup PR to address the [concerns raised](https://github.com/DataDog/dd-trace-php/pull/1366#discussion_r760421429) in #1366 with regard to resolving symbol addresses from ext/json. This technique implements weak symbols similar to how we resolved the same issue for ext/curl in #1181 & #1209 and gracefully handles the case where the symbol addresses could not resolve.
I also added a new shared-extension container for PHP 5.4 (`datadog/dd-trace-ci:php-5.4-shared-ext`) to test the edge cases.

Fix json symbol address resolving logic

---

ext/php5/ddtrace.c
ext/php7/ddtrace.c
ext/php8/ddtrace.c

When ddtrace is disabled by configuration, we need not run or display diagnostics

Disable diagnostics when the tracer is disabled

---

ext/php5/php5/engine_hooks.c
ext/php5/php5_4/engine_hooks.c
ext/php7/php7/engine_hooks.c
ext/php8/php8/engine_hooks.c

Fixes #1428 
dd-trace-php has a requirement that the runtime is properly initialized before tracing is attempted - *all* loaded extensions must have executed their RINIT stage hooks before the tracer can instrument anything safely.
This change enforces that requirement.

Disable tracing when PHP is executed during RINIT

---

.circleci/config.yml
tests/ext/integrations/curl/curl_helper.inc
tests/ext/integrations/curl/distributed_tracing_curl.phpt
tests/ext/integrations/curl/distributed_tracing_curl_copy_handle.phpt
tests/ext/integrations/curl/distributed_tracing_curl_existing_headers_001.phpt
tests/ext/integrations/curl/distributed_tracing_curl_existing_headers_002.phpt
tests/ext/integrations/curl/distributed_tracing_curl_existing_headers_003.phpt
tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_001.phpt
tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_002.phpt
tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_copy_handle.phpt
tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_copy_handle_bug_71523.phpt
tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_disable.phpt
tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_existing_headers_001.phpt
tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_existing_headers_002.phpt
tests/ext/integrations/curl/distributed_tracing_curl_sampling_priority.phpt

This PR fixes the [flaky curl tests in CI](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/7110/workflows/402191ef-8b1c-41aa-9c85-7447903af20b/jobs/831899/artifacts). It also adds error info to the curl tests so that we can more easily debug issues like this in the future.
For this specific issue, the tests would fail intermittently with the following curl error:
```
Could not resolve host: httpbin_integration
```
Resolving the `httpbin_integration` hostname's IP address for `HTTPBIN_HOSTNAME` fixed the issue.

Fix flaky curl tests

---

dockerfiles/ci/alpine/php-8.0/configure.sh
dockerfiles/ci/centos/6/php-5.4/configure.sh
dockerfiles/ci/centos/6/php-5.5/configure.sh
dockerfiles/ci/centos/6/php-5.6/configure.sh
dockerfiles/ci/centos/6/php-7.0/configure.sh
dockerfiles/ci/centos/6/php-7.1/configure.sh
dockerfiles/ci/centos/6/php-7.2/configure.sh
dockerfiles/ci/centos/6/php-7.3/configure.sh
dockerfiles/ci/centos/6/php-7.4/configure.sh
dockerfiles/ci/centos/6/php-8.0/configure.sh

As a followup to https://github.com/DataDog/dd-trace-ci/pull/34, this PR removes the `embed` sapi.

Remove embed sapi

---

tests/ext/segfault_backtrace_enabled.phpt

This is an internal fix for our failing CI.
It's okay to mark this as XFAIL: we know why it sometimes will not produce useful output.
Since the end result is always a fault, and the only difference is the resulting output (and dump), it's not terrible to expect this to fail in CI.
It doesn't excuse use of unsafe code, and we have a plan to resolve that.

Fix CI failures caused by unsafe signal handler

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Do not diagnostics when ddtrace is disabled #1434
- Fix json symbol address resolving logic #1432
- Disable tracing when PHP is executed during RINIT #1429
- Change Predis integration type to "redis" #1427

Release 0.68.1

---

ext/php5/ddshared.c
ext/php5/startup_logging.c
ext/php7/ddtrace.c
ext/php7/ddtrace.h
ext/php7/priority_sampling/priority_sampling.c
ext/php7/serializer.c
ext/php7/span.c
ext/php7/startup_logging.c
ext/php8/ddtrace.c
ext/php8/ddtrace.h
ext/php8/priority_sampling/priority_sampling.c
ext/php8/serializer.c
ext/php8/span.c
ext/php8/startup_logging.c

Fixing #1439 by eliminating a class of errors regarding missing derefs/type checks on meta and metrics.

Replace direct access of meta/metrics zvals by safe array access in most places

---

ext/php7/ddtrace.h
ext/php8/ddtrace.h

Prevent rc > 1 write access on meta and metrics by always separating these.

Always separate meta and metrics arrays on access

---

.circleci/config.yml
Makefile

A quick follow up to #1411 that fixes `ZaiSapi_ROOT` references in the Makefile. Also removes a redundant PATH modification in CI config.

Fix ZaiSapi_ROOT path in Makefile

---

tooling/bin/generate-final-artifact.sh

Clean up generate-final-artifact.sh:
- Shortens some long lines.
- Adds verbose output to some of the commands.
- Adds some whitespace.

Clean up generate-final-artifact.sh

---

Makefile
tooling/bin/generate-final-artifact.sh

This is a stacked PR based on #1442.
This bumps the profiling product to v0.3.0-rc.6, which fixes some bugs
around over- and under-linking.

Bump profiling to v0.3.0-rc.6

---

dockerfiles/ci/alpine/php-8.0/configure.sh
dockerfiles/ci/centos/6/php-5.4/configure.sh
dockerfiles/ci/centos/6/php-5.5/configure.sh
dockerfiles/ci/centos/6/php-5.6/configure.sh
dockerfiles/ci/centos/6/php-7.0/configure.sh
dockerfiles/ci/centos/6/php-7.1/configure.sh
dockerfiles/ci/centos/6/php-7.2/configure.sh
dockerfiles/ci/centos/6/php-7.3/configure.sh
dockerfiles/ci/centos/6/php-7.4/configure.sh
dockerfiles/ci/centos/6/php-8.0/configure.sh

This reverts commit c2bbaad6469c0db1264eecf9434082350bb5543c. I believe #1195 was merged in error.
```bash
$ ll /opt/php/8.0/lib/
total 43512
-rwxr-xr-x  1 root root 44551144 Oct  2 00:21 libphp.so
drwxr-xr-x 15 root root     4096 Oct  2 00:22 php
```
The containers still have `libphp` (which is good) so they do not appear to have been rebuilt based on this change.

Revert "remove embed sapi (#1195)"

---

bridge/dd_init.php

In particular datadog.trace.cli_enabled was not accounted for, leading to tracing being aborted, if the request_init_hook was active.

Get rid of ini-ignoring and redundant checking of ddtrace being enabled

---

src/DDTrace/Util/ObjectKVStore.php
tests/Unit/Util/ObjectKVStoreTest.php

Some frameworks can use autoloaders that are not lenient, meaning that when they are asked to load a class, they either load it or generate a fatal (e.g. because the file is not found), rather than just returning `false` - example [`Varien_Autoload`](https://github.com/engineyard/magento-ce-1.9/blob/170c1a51387428fb56f3ada2504d52a2b130360a/lib/Varien/Autoload.php#L81-L93).
Since we use `class_exists('WeakMap')` in our `ObjectKVStore` ([usage 1](https://github.com/DataDog/dd-trace-php/blob/29b1106cbaaf6d7a8cca259600d493ad349bdae9/src/DDTrace/Util/ObjectKVStore.php#L126) and [usage 2](https://github.com/DataDog/dd-trace-php/blob/29b1106cbaaf6d7a8cca259600d493ad349bdae9/src/DDTrace/Util/ObjectKVStore.php#L158)) and `class_exists()` triggers the autoloading mechanism by default, then the …

Fix ObjectKVStore compatibility with throwing autoloaders

---

ext/php5/serializer.c
ext/php7/serializer.c
ext/php8/serializer.c
tests/ext/root_span_url_as_resource_names.phpt

Strips everything including and after the ? from an url.

Strip query string from http.url

---

src/DDTrace/Integrations/CakePHP/CakePHPIntegration.php
src/DDTrace/Integrations/CodeIgniter/V2/CodeIgniterIntegration.php
src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
src/DDTrace/Integrations/Laravel/LaravelIntegration.php
src/DDTrace/Integrations/Lumen/LumenIntegration.php
src/DDTrace/Integrations/Nette/NetteIntegration.php
src/DDTrace/Integrations/Slim/SlimIntegration.php
src/DDTrace/Integrations/Symfony/SymfonyIntegration.php
src/DDTrace/Integrations/WordPress/V4/WordPressIntegrationLoader.php
src/DDTrace/Integrations/Yii/YiiIntegration.php
src/DDTrace/Integrations/ZendFramework/V1/Ddtrace.php
src/DDTrace/Integrations/ZendFramework/V1/TraceRequest.php
src/DDTrace/Integrations/ZendFramework/ZendFrameworkIntegration.php
tests/Common/WebFrameworkTestCase.php
tests/Frameworks/TestScenarios.php
tests/Integrations/Yii/V2_0/ParameterizedRouteTest.php

As an additional step away from our hybrid approach (legacy ve internal api), this PR:
- removes usage of `DDTrace\GlobalTracer` from `src/DDTrace/Integrations`;
- removes usage of `DDTrace\Contracts\Span` from `src/DDTrace/Integrations` with the exception of `DDTrace\Integrations\Integration` as it might cause backward compatibility issues if users have inherited from this class - even if it has always been considered internal;

Use internal root spans in Integrations in place of using the legacy API

---

Makefile
zai_sapi/CMakeLists.txt
zend_abstract_interface/CMakeLists.txt

CI and makefile builds were configured differently causing local asan builds to fail.
This change uses the toolchain file for both makefile and CI builds for ZAI SAPI and ZAI.
It drops the option from both ZAI and ZAI SAPI in favour of the working, more precise toolchain file that was already present.
Also fix dist_clean (another cause of build failures)

Make consistent (working) ASAN builds

---

zai_sapi/php5/zai_sapi.c
zai_sapi/php7/zai_sapi.c
zai_sapi/php8/zai_sapi.c
zai_sapi/testing/catch2.hpp
zai_sapi/tests/CMakeLists.txt
zai_sapi/tests/zai_sapi_testing.cc

As discussed, we should have a way to differentiate between test case and test code bailout handling.

ZAI Test Harness Bailout Handling

---

ext/php5/span.c
ext/php7/span.c
ext/php8/span.c
tests/ext/disabling_root_span_generation_at_runtime.phpt

Will segfault (or at least leak) when datadog.trace.generate_root_span is switched from true to false if only a root span is present.

Clear the root span when dropped

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Query string is now not included in `http.url` in Nette integration and in generic web frameworks tracing.
- Implement x-datadog-tag propagation and _dd.p.upstream_services #1405
- Get rid of ini-ignoring and redundant checking of ddtrace being enabled #1448
- Strip query string from http.url in generic web tracing #1454
- Use internal root spans in Integrations in place of using the legacy API #1383
- Hard-code version in installer, remove --url option, rename it #1463
- Remove generator support on PHP 7 #1464
- Ensure a proper sampling decision is also evaluated when distributed tracing is used #1450
- Fix ObjectKVStore compatibility with throwing autoloaders #1451
- Properly report error for artisan command in Laravel 7+ #1456 (thank you @ls-paul-julien-vauthier)
- Migrate ZAI tests …

Release 0.69.0

---

.circleci/config.yml
Makefile
ext/php7/ddtrace.c
ext/php7/serializer.c
ext/php8/ddtrace.c
ext/php8/serializer.c
tests/internal-api-stress-test.php

This testsuite also would have caught #1439.
Additionally fixing:
- extension shutdown being called after module unload - seems to not have real impact in practice, but breaks with ASAN enabled.
- Fixing a crash when the previous exception is not an exception object.

Run randomized internal API stress testing in CI

---

ext/php5/priority_sampling/priority_sampling.c

PHP5 was not handling null services property like 7/8, causing possible faults, found under stress testing just merged.

fix dd_update_upstream_services on php5

---

zend_abstract_interface/symbols/call.c
zend_abstract_interface/symbols/lookup.c
zend_abstract_interface/symbols/symbols.h
zend_abstract_interface/symbols/tests/CMakeLists.txt
zend_abstract_interface/symbols/tests/call/closure.cc
zend_abstract_interface/symbols/tests/lookup/local/static.cc
zend_abstract_interface/symbols/tests/stubs/call/closure/Stub.php
zend_abstract_interface/symbols/tests/stubs/lookup/local/static/Stub.php

When I tried to move usage of ZAI Symbols into the extension, it uncovered many build errors because the ext built has stricter Wflags.
In addition, the randomized testing framework uncovered a flaw in the logic of the call interface.
Doesn't need to go into release doc, follow up to #1452, depends on #1473

fix symbols build and call issues

---

dockerfiles/ci/buster/php-7.0/0001-Fixed-incorrect-behavior-of-internal-memory-debugger.patch
dockerfiles/ci/buster/php-7.0/Dockerfile
dockerfiles/ci/buster/php-7.1/0001-Fixed-incorrect-behavior-of-internal-memory-debugger.patch
dockerfiles/ci/buster/php-7.1/Dockerfile
dockerfiles/ci/buster/php-7.2/0001-Fixed-incorrect-behavior-of-internal-memory-debugger.patch
dockerfiles/ci/buster/php-7.2/Dockerfile

Patch zend_alloc.c to not crash in CI for PHP 7.0 to 7.2

---

Makefile

Since we added install_tea as a dependency of zai builds, tea is built over and over again during development, slowing things down considerably.
We want tea to be rebuilt for test runs, but for everything else, we don't need to rebuild.
I've added guards to tea rules so that they run once, and clean when they have too.

Tea: build once during development

---

tea/config.m4

This allows tea to be built in-tree as a normal sapi without dependence on embed.
Supports shared/static builds, installs headers in same way as cmake based build ...
We should maybe ship a cmake, or additional autoconf tooling ...
We should probably include a simple CI job to make sure we don't break this ability in some strange way ... but later ...
to test `cp -r dd-trace-php/tea /path/to/php-src/sapi && ./buildconf --force && ./configure --enable-tea`

Support in-tree builds of Tea

---

ext/php5/php5_4/engine_hooks.c
ext/php5/span.c
ext/php7/span.c
ext/php8/span.c
tests/ext/dropped_spans_have_negative_duration.phpt

This ensures that the DDTrace\Span::isFinished() check with which we guard closing spans in the manual tracing API returns true when a span is dropped.

Ensure dropped spans are distinguishable from unfinished spans

---

ext/php5/coms.c
ext/php7/coms.c
ext/php8/coms.c

The background sender is configured with a shutdown timeout, which defines the maximum amount of time the shutdown routine will wait for the writer thread before the routine ignores the request to join.
This is not safe, threads must be joined for predictable behaviour.
In the case where the timeout is reached, the shutdown routine needs to cancel the writer thread and then join with it at the last opportunity.
Failing to fulfil the contract of the function at the last opportunity leads to surprising behaviour, like the background sender trying to read from memory that was freed at mshutdown stage.

BGS shutdown/flush

---

.circleci/config.yml
Makefile
datadog-setup.php
dockerfiles/verify_packages/Makefile
dockerfiles/verify_packages/alpine/install.sh
dockerfiles/verify_packages/centos/install.sh
dockerfiles/verify_packages/debian/install.sh
dockerfiles/verify_packages/docker-compose.yml
dockerfiles/verify_packages/verify_rpm_centos6.sh
tooling/bin/generate-final-artifact.sh

Based on the latest agreements, this PR:
1. adds `appsec` to the release bundle (actually installing `appsec` will come with a separate PR #1470)
2. renames bundles adding the version number.
- ~[] Tests added for this feature/bug.~

Add appsec library to the release bundle

---

components/stack-sample/stack-sample.c
components/stack-sample/stack-sample.h

Adjust max stack depth so record_msg can fit in 8KiB (it was slightly
going over). The `record_msg` is part of the profiler that hasn't been
merged yet, so only the parts that have been merged have been sync'd.
This is part of a sync with the current dd-prof-php components.

Adjust stack sample max stack depth

---

datadog-setup.php

Fix #1488. It is not perfect, but it is better. It catches things like these:
php datadog-setup.php --version 0.69.0 --enable-profiling
php datadog-setup.php 0.69.0 --enable-profiling
But if the error happens after the first argument, then it won't catch it e.g.
php datadog-setup.php --enable-profiling 0.69.0 --php-bin php-fpm
Will go into interactive mode because `getopt` stopped parsing at `0.69.0`.

Improve error detection for datadog-setup.php

---

ext/php5/ddtrace.c
ext/php5/tracer_tag_propagation/tracer_tag_propagation.c
ext/php5/tracer_tag_propagation/tracer_tag_propagation.h
ext/php7/ddtrace.c
ext/php7/tracer_tag_propagation/tracer_tag_propagation.c
ext/php7/tracer_tag_propagation/tracer_tag_propagation.h
ext/php8/ddtrace.c
ext/php8/tracer_tag_propagation/tracer_tag_propagation.c
ext/php8/tracer_tag_propagation/tracer_tag_propagation.h
src/DDTrace/Propagators/TextMap.php
src/DDTrace/SpanContext.php
src/DDTrace/Tracer.php
tests/OpenTracer1Unit/TracerTest.php
tests/OpenTracerUnit/TracerTest.php
tests/Unit/TracerTest.php
tests/ext/dd_trace_current_context.phpt
tests/ext/dd_trace_current_context_noenv.phpt
tests/ext/distributed_tracing/distributed_trace_no_overwrite_with_active_span.phpt
tests/ext/distributed_tracing/distributed_trace_overwrite.phpt

We broke the manual distributed tracing handling when moving the distributed tracing to internal.
Fixes #1292.

Restore support for manual distributed tracing

---

Makefile

Update the URL of the AppSec package to point to the latest release v0.2.1

Update AppSec Release URL to v0.2.1

---

.circleci/config.yml
components/sapi/sapi.c
components/sapi/sapi.h
components/sapi/tests/sapi.cc
ext/php5/ddtrace.c
ext/php7/ddtrace.c
ext/php8/ddtrace.c
tea/CMakeLists.txt

The extension maintains a list of recognized SAPIs. If an unknown SAPI
is detected, then tracing is disabled. This PR adds the Tea SAPI to
this list so tracing can happen in the Tea SAPI.

Clean up Tea SAPI and allow ddtrace to run there

---

ext/php5/coms.c
ext/php5/coms.h
ext/php7/comms_php.c
ext/php7/coms.c
ext/php7/coms.h
ext/php8/coms.c
ext/php8/coms.h

Before this PR, we initialized a curl session at the first iteration (with loop time of 5 seconds) and then we used it until the process got killed. This means, potentially, that the same curl session could be alive for days.
This resulted in some cycles to be lost because the trace agent closed the connection (RST flag verified through tcpdump) at random intervals.
This PR changes this behavior in two ways:
1. it instantiates a new session at each writer iteration (5 seconds by default) and clears it after the transmission of the payloads that can be sent is completed.
2. increases the total usable number of buffers by 20% (from 10 to 12). This in order to account for possible delays due to slower connection operations during each cycle.
Note that this is only a first optimization, as a …

Use a new curl session for each writer iteration and clear it after

---

.circleci/config.yml
ext/php7/ddtrace.c
ext/php7/engine_hooks.h
ext/php7/handlers_internal.c
ext/php7/handlers_internal.h
ext/php7/php7/engine_hooks.c
ext/php8/ddtrace.c
ext/php8/engine_hooks.h
ext/php8/handlers_internal.c
ext/php8/handlers_internal.h
ext/php8/php8/engine_hooks.c
tests/tea/CMakeLists.txt
tests/tea/profiling/CMakeLists.txt
tests/tea/profiling/interrupt.cc
tests/tea/profiling/profiling.cc
tests/tea/profiling/profiling.h
tests/tea/profiling/sleep.php

If the observer_end is called before the profiler processes an
interrupt, then the profiler mis-attributes time taken to the tracing
function, instead of the real leaf function. This change pairs with one
in the profiler that exposes `datadog_profiling_interrupt_function`.
Here's the profiling function which ends up being called by
`datadog_profiling_interrupt_function`:
[datadog_php_stack_collector_interrupt_function](https://github.com/DataDog/dd-prof-php/blob/ed9b20cd4bf15e7dad0438cd9341d6c96d576123/profiling/plugins/stack_collector_plugin/stack_collector_plugin.c#L306). It is safe to call this
function even when the profiler is disabled.
I wrote a simple "sleep" app + integration to demonstrate the bug:
```php
<?php
if (function_exists('DDTrace\trace_function')) { …
```

Trigger profiling interrupt function before internal observer_end

---

tea/CMakeLists.txt

I originally recommended only installing the Catch2 test header when `BUILD_TEA_TESTING=ON` but since Tea SAPI is built and installed separately as a static object, it doesn't always need to have the tests enabled. This PR makes the `tea/testing/catch2.hpp` header available all the time; even when `BUILD_TEA_TESTING=OFF`.
```
$ tree /opt/tea/include/tea
/opt/tea/include/tea
├── common.h
├── error.h
├── exceptions.h
├── extension.h
├── frame.h
├── sapi.h
└── testing
└── catch2.hpp
```

Always include the Tea SAPI Catch2 test header

---

components/container_id/container_id.h
ext/php5/ddtrace.c
ext/php7/ddtrace.c
ext/php8/ddtrace.c

get_module is only declared when building as a shared object
And fix build on mac: without stddef.h and sys/types.h container component lacks off_t and size_t
We need to ensure ext/standard RINIT is executed before ours (can only happen with in-tree builds).

Explicitly depend on ext/standard and fix in-tree builds

---

package/post-install.sh

Fixes post install script.
The functions verify_installation and verify_required_ext were using matching that was not precise enough.
We are looking for an exact match; We don't want to match "could not load ddtrace because of something" or any other similar output when checking a required ext with -m, we want precisely the extension name on a newline.
It would have been better to use reflection to make this check, but fpm doesn't support executing code on the command line.
I found an unused var that used php -r, so dropped that too.

Fix #1510 post-install not detecting required extension

---

src/Integrations/Integrations/Curl/CurlIntegration.php
tests/Integrations/Curl/CurlIntegrationTest.php

Keep a distinction between the native span duration and the measured curl duration.
This also prevents type confusion in the APM itself.

Do not mess with the span duration in curl integration

---

ext/php5/handlers_curl.c
ext/php5/handlers_internal.c

Fixes a memory leak.
- ~[ ] Tests added for this feature/bug.~ - Tets part of to be committed randomized suite

(PHP 5) Remove empty multi_curl handles hashtables and track curl handle freeing

---

components/uuid/tests/uuid.cc
components/uuid/uuid.c
components/uuid/uuid.h

Add `datadog_php_uuid_is_nil` function to UUID component.
This is used by a work-in-progress implementation of Code Hotspots.

Add is_nil function to UUID component

---

config.m4
ext/php8/compatibility.h
ext/php8/handlers_curl.c
ext/php8/serializer.c
zend_abstract_interface/config/config_decode.c

Fixes a couple immediate segfaults / assertion failures when running ddtrace against php-src master.

Fix compatibility with PHP 8.2 (master)

---

ext/php5/configuration.h
ext/php7/configuration.h
ext/php8/configuration.h
src/Integrations/Integrations/PDO/PDOIntegration.php
tests/Integrations/PDO/PDOTest.php
tests/randomized/config/envs.php

This feature implements split by instance for PDO spans, allowing to differentiate between different host/servers based on service name.

Implement split by instance in PDO

---

ext/php5/coms.c
ext/php7/coms.c
ext/php8/coms.c
tests/randomized/analyze-results.php

With the new ES integration we consume a little more memory. Adjusting the limit.
Additionally adding CURLOPT_NOSIGNAL to prevent spurious issues upon reconnects in background sender.

Fix randomized testsuite memory limits and background sender curl handling

---

zend_abstract_interface/symbols/call.c
zend_abstract_interface/symbols/tests/CMakeLists.txt
zend_abstract_interface/symbols/tests/call/generator.cc
zend_abstract_interface/symbols/tests/stubs/call/generator/Stub.php

Also add a stack buffer on calls on PHP 8 (so that observer calls on bailout don't immediately run into a segfault by polluting the stack.

Simplify calls (zai symbols), add support for generators

---

Makefile

Update profiling to v0.5.0 from v0.5.0-rc.2. The new version has been
running on the relenv for a few hours and given that there weren't any
changes between v0.5.0-rc.2 and v0.5.0 except the version bump, I am
confident in making this change.

Update profiling to v0.5.0 from v0.5.0-rc.2

---

Makefile

This adds the Version field to the phpinfo diagnostics. The profile in
the phpinfo diagnostics now has a sample so the profile isn't empty.

Update profiling to v0.5.1

---

tests/randomized/Makefile
tests/randomized/analyze-results.php
tests/randomized/docker/prepare.sh

This PR addresses some flakiness in CI for randomized tests. Specifically the issues were:
1. we found a recurring `curl error 7` that results in 500 under very heavy traffic, that we are not able to reproduce locally. After extensive investigation by several members of the team, we were not able to understand the real root cause and we have to assume is something due to the high traffic + CircleCI environment;
2. PHP-FPM 5.6  at times fails in CI during module shutdown for reasons that we believe are not associated to dd-trace-php
```
#0  0x00007ff9836a2387 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ff9836a3a78 in __GI_abort () at abort.c:90
#2  0x00007ff9836e4ed7 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ff9837f73f0 "*** …
```

Move from checking status code reported by vegeta to check error logs

---

.gitlab-ci.yml
Makefile
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Do not disable tracing when ionCube loader is detected #1520
- Added ES integration support for newer PHP and ES versions #1516
- Add support for wordpress on PHP 8 and use a different hook #1522
- Add Code Hotspots #1517
- Implement split by instance in PDO #1498
- Trigger profiling interrupt function before internal observer_end #1499
- Fix compatibility with PHP 8.2 (master) #1521
- Clean up Tea SAPI and allow ddtrace to run there #1502
- Use a new curl session for each writer iteration and clear it after #1504
- Increase bgs backlog by 20% #1506
- Always include the Tea SAPI Catch2 test header #1507
- Add is_nil function to UUID component #1515
- Fix randomized testsuite memory limits and background sender curl handling #1525
- Run cmake-format on TEA's CMakeLists.txt #1527
- …

Release 0.71.0

---

.circleci/config.yml

CircleCI is deprecating ubuntu 14.04 and 16.04 images, that we were using to verify centos 6 installs (14.04)
https://circleci.com/blog/ubuntu-14-16-image-deprecation
Moreover, this PR also updates ubuntu 20.04 images to the latest with the log4j vulnerability patched.
While we do not use Java, it is still preferrable to have a patched image.
https://circleci.com/docs/2.0/configuration-reference/#available-machine-images

Use latest ubuntu images in CI

---

ext/php8/php8/engine_hooks.c

PHP 8.1.4+ the op_array_extension handles start from zero instead of 1.
Fixes #1549.

Use -1 as uninitialized op_array_extension marker

---

.gitlab-ci.yml
Makefile
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Use -1 as uninitialized op_array_extension marker #1550
- Use latest ubuntu images in CI #1543
- Use 8.1.4 in development buster images #1553
- Add randomized tests for PHP 8.1 and make buster containers arm64 ready #1551
- Remove regressions from randomized tests #1547

Release 0.71.1

---

ext/php5/span.c
ext/php7/span.c
ext/php8/span.c

Fixes #1544. The dummy span hack of hooks strikes again.
To expand on that: in our current implementation of hook_function we install a dummy span. This dummy span must never be exposed to userland. This fixes this span being exposed via the parent property.
Once we merge our new hooks implementation no such span will exist anymore and this hack of skipping that span can be removed.
- Intentionally skipped it this time, it's a hack and obsolete once the new hooks land.

Fix #1544: Handle hook dummy span hack when assigning parent

---

.circleci/config.yml

Add [System tests](https://github.com/DataDog/system-tests) in CI ([doc](https://github.com/DataDog/system-tests/tree/main/docs)).
System tests is a functional test suite that performs end-to-end testing on our customer products. It spawns a tracer, an agent, some proxies to spy traffic between all components, run a typical scenario and checks that everything happen as expected.
* Having a unique tests suite for all tracers
* good to catch integration bugs and everything that happen in real life.
* fast (5 mn for build step, 2:30 minutes for test step), and adding new test case is almost free.
* free from flakiness, so you can rely on failure on test step. If you have any doubt, please reach us on slack channel `libraries-system-tests`.
* easy to run locally
* provide a detailled …

Add system tests in CI

---

tooling/gdbinit-8.0
tooling/gdbinit-8.1

Add gdbinit files for php 8.0 and 8.1

---

tests/Frameworks/Symfony/Version_4_0/composer.lock
tests/Frameworks/Symfony/Version_5_0/composer.lock

The newer flex version check against the existence of the manifest key instead of failing outright when it is missing.
This fixes our test_web_symfony runners.

Update flex to v1.18.5 in composer.lock files for Symfony 4.0 and 5.0

---

.circleci/config.yml

On release branches the file name does not include `nightly` in it.

Run system tests on release branches

---

.gitlab-ci.yml
Makefile
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Add support for memcached on PHP 8 #1558
- Fix #1544: Handle hook dummy span hack when assigning parent #1557
- Add gdbinit files for php 8.0 and 8.1 #1556
- Add system tests in CI #1552
- Use latest 8.0.17 in buster images #1559
- Update flex to v1.18.5 in composer.lock files for Symfony 4.0 and 5.0 #1560
- Add a single test to xfail after upgrade of docker image to 8.0.18 #1561
- Update link to download 0.71.1 in the reliability environment #1555

Release 0.72.0

---

ext/php5/ddtrace.c
ext/php5/span.c
ext/php7/ddtrace.c
ext/php7/span.c
ext/php8/ddtrace.c
ext/php8/span.c
src/DDTrace/Span.php
src/DDTrace/Tracer.php
tests/Integration/TracerTest.php
tests/Integrations/PCNTL/scripts/long-running-manual-flush.php
tests/ext/close_spans_until.phpt
tests/ext/start_span_without_closing.phpt
tests/ext/start_span_without_closing_autofinish.phpt

- Respect the autofinish setting on `DDTrace\flush()`.
- Actually, I discovered that the original flush() implementation pre-internal spans did just that. So I restored that behaviour.
- Add `DDTrace\close_spans_until()`, a facility to close spans up to a current span, or up to the last internal (i.e. trace/hook) span.
- `Span->finish` makes use of this new function, to ensure generally balanced spans.
- Warnings are emitted with `DD_TRACE_DEBUG=1` active, if spans are found to be unbalanced.
- `GlobalTracer->reset()` now does a hard-reset of the tracer.

Respect autofinish on flush(), add warnings in debug mode when having unbalanced spans

---

src/DDTrace/Tracer.php
tests/Integration/TracerTest.php

Fixing (unreleased) bug introduced in #1564. (Thanks @olsavmic for the hint!)
Also fix the test to actually test something. (Now it fails, without the fix.)

Fix typo in ini name in GlobalTracer->reset()

---

Makefile

This adds support for PHP 8.1 and DD_TAGS. It also fixes a crash that
can occur on startup if no certificates are found.
cross-product APIs changed.

Update profiling to v0.6.0

---

Makefile

Update AppSec to v0.3.1 - this introduces a fix to an incompatibility between DDTrace and DDAppSec on php 7.3 due to module reordering on DDTrace.

Update AppSec to v0.3.1

---

zend_abstract_interface/symbols/call.c

The handling of MAP_PTR_INIT changes with PHP 8.2, and the old code had 8.2+ handling only.
On PHP 7.4 - 8.1 run_time_cache needs to be allocated 8 bytes bigger.
This might be a possible sources of crashes.
- It's an actual failure, but somehow asan does not see it, only valgrind...

Fix run_time_cache initialization for closure calls with foreign scope on PHP 7.4-8.1

---

datadog-setup.php
tooling/bin/generate-final-artifact.sh

As a follow-up to #1573 which adds support in profiling for PHP 8.1, we
also need to allow it in the installer.

datadog-setup: allow profiling for PHP 8.1

---

ext/php5/ddtrace.c
ext/php7/ddtrace.c
ext/php8/ddtrace.c
tests/Integration/TracerTest.php

On PHP 8 we cache our dispatches directly with the op_arrays. We thus must not free the dispatches before we are certain that we won't use them anymore. As an additional safeguard the tracer disables itself in RSHUTDOWN.
Given that on PHP 5 we also preserve dispatches across tracer disabling, we bring this behaviour in line for all versions and just keep the dispatches when disabling (or re-enabling) the tracer.
Fixes a crash reported in #1545.

Fix dispatch resetting

---

ext/php5/configuration.h
ext/php5/serializer.c
ext/php7/configuration.h
ext/php7/serializer.c
ext/php8/configuration.h
ext/php8/serializer.c
src/Integrations/Integrations/CakePHP/CakePHPIntegration.php
src/Integrations/Integrations/CodeIgniter/V2/CodeIgniterIntegration.php
src/Integrations/Integrations/Laravel/LaravelIntegration.php
src/Integrations/Integrations/Symfony/SymfonyIntegration.php
src/Integrations/Util/Normalizer.php
tests/Unit/Util/Normalizer/UriTest.php
tests/ext/root_span_url_as_resource_names.phpt
tests/ext/root_span_url_with_query_params_whitelist.phpt
zend_abstract_interface/uri_normalization/php5/uri_normalization.c
zend_abstract_interface/uri_normalization/php7-8/uri_normalization.c
zend_abstract_interface/uri_normalization/tests/uri_normalization.cc
zend_abstract_interface/uri_normalization/uri_normalization.h

This restores the possibility to fully send the request URL as http.url. (Which was previously disabled to prevent accidental PII leaks.)
Additionally query parameters in resources are now supported.
This is configurable via `datadog.trace.http_url_query_param_whitelist` (for http.url) and `datadog.trace.resource_uri_query_param_whitelist` (for resources).
Fixes #1270, #1033, #1117.
On top of that, I'm ensuring integrations pass full normalized URLs to http.url tag, including sanitized query string, fixing #1577.

Add configurations for retaining select query string parameters in resources and http.url

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Rename ini settings from `datadog.appsec.rules_path` to `datadog.appsec.rules` [#74](https://github.com/DataDog/dd-appsec-php/pull/74)
- Interpret `datadog.appsec.waf_timeout` as microseconds rather than milliseconds [#74](https://github.com/DataDog/dd-appsec-php/pull/74)
- Add obfuscator strings when initialising WAF from client settings [#83](https://github.com/DataDog/dd-appsec-php/pull/83)
- Fix relative module order with ddtrace on PHP 7.3 issue [#88](https://github.com/DataDog/dd-appsec-php/issues/88) -  [#86](https://github.com/DataDog/dd-appsec-php/pull/86)
- Add WAF metrics and errors to traces [#79](https://github.com/DataDog/dd-appsec-php/pull/79)
- Actor IP resolution from request headers [#80](https://github.com/DataDog/dd-appsec-php/pull/80)
- Add support for WAF event …

Release 0.73.0

---

Makefile
tests/randomized/README.md

Update AppSec to v0.3.2 which contains a fix for the randomized test crashes.
Also updated the randomized tests README.

Update AppSec to v0.3.2

---

dockerfiles/ci/xfail_tests/5.4.list
dockerfiles/ci/xfail_tests/README.md

The test fails because `$b > $a` instead of the [expected](https://github.com/php/php-src/blob/PHP-5.4/ext/standard/tests/http/bug60570.phpt#L37) `$b == $a`, where `$b` is the previous output of `memory_get_usage()` and `$a` is the latest output of `memory_get_usage()`.
Actually what we are observing here is that the previous read is larger than the latest read, which means no leak at all. Specifically `$b = 257896` and `$a = 257880`.
My hypothesis is that incidentally a gc collection happens between the two latest iterations. This hypothesis seems confirmed by the fact that if we `gc_collect_cycles()` right before the [loop](https://github.com/php/php-src/blob/PHP-5.4/ext/standard/tests/http/bug60570.phpt#L25) now the test will pass - or `$b == $a` even when the tracer is installed.
- ~[ …

Disable flacky test on PHP 5.4

---

datadog-setup.php

Currently the installer checks if a setting was already available before adding it to the `.ini` file, however since the extension setting is not unique, on existing installations performed with a different installation method, `extension = ddappsec.so` is not added.
This fix just makes sure we verify that the correct extensions and zend extensions are loaded by checking not only the setting but also the value.

Fix installer setting check for extensions

---

ext/php7/ddtrace.c
ext/php8/ddtrace.c

Currently the tracer calls `dlload` on itself on `MINIT` to ensure the reference count is consistent with the number of times `dlclose` should, in theory, be called against it, due to it being both a module and a zend extension. However during `MSHUTDOWN` the tracer also sets the module handle to `NULL`, thus preventing one of the two calls to `dlclose` on its handle and leaking resources.
This change consolidates the current behaviour during `MINIT` by setting the module handle to `NULL` and removing any extra calls to `dlload`.

Fix inconsistent module load and unload sequence

---

Makefile

Symfony 4.2 did not resolve to a properly installable set of packages when using symfony/flex, which was fixed with https://github.com/symfony/flex/commit/e74319d17ed4edc5f27b9d24757e172930a7ebc4.
This incidentally made the composer run as a whole not fail. Now that this is working now, a zend-code compatibility layer seems to be missing.
Given that we anyway test 4.0 on 7.4 too, and 4.2 is tested on all other PHP 7 versions, I guess we're fine dropping it for 7.4.

Remove Symfony 4.2 from PHP 7.4 web tests

---

Makefile

This re-initialize statics variables on startup/minit. This should help
prevent crashes on Apache reloads, but I couldn't get it to crash
before these changes, so I'm not sure what I am doing wrong in my
tests, or if it's completely fixed.

Bump profiling to v0.6.1

---

tests/randomized/lib/templates/Makefile.scenario.template
tests/randomized/lib/templates/docker-compose.template.yml

The name ends up in logs e.g.
```
php-test-randomized-277800912-centos7-7.0_1  |   - Installing elasticsearch/elasticsearch (v6.7.2): Extracting archive
php-test-randomized-277800912-centos7-7.0_1  |   - Installing symfony/polyfill-php72 (v1.19.0): Extracting archive
php-test-randomized-277800912-centos7-7.0_1  |   - Installing paragonie/random_compat (v9.99.100): Extracting archive
```
Previously it would have looked more like this for every scenario, making it hard to know what scenario went wrong:
```
php-test_1       |   - Installing elasticsearch/elasticsearch (v6.7.2): Extracting archive
php-test_1       |   - Installing symfony/polyfill-php72 (v1.19.0): Extracting archive
php-test_1       |   - Installing paragonie/random_compat (v9.99.100): Extracting archive
```
Motivated by …

Add the scenario name to the randomized test docker name

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Add configurations for retaining select query string parameters in resources and http.url #1566
- Respect autofinish on flush(), add warnings in debug mode when having unbalanced spans #1564, #1569
- Loose restrictions around distributed tracing context setting #1571
- Fix dispatch resetting #1570
- Fix run_time_cache initialization for closure calls with foreign scope on PHP 7.4-8.1 #1578
- Eliminate the separate span id stack, fix distributed tracing trace_id #1586
- Fix handling of INI and ENV changes post minit, pre runtime #1593
- Fix inconsistent module load and unload sequence #1585
- Fix installer setting check for extensions #1584
- Pin composer on PHP 7 docker containers to version 2.2 #1565
- Disable flaky test on PHP 5.4 #1583
- Remove Symfony 4.2 from PHP 7.4 web tests …

Release 0.74.0

---

.gitlab-ci.yml

Updates the url of the binary installed on the reliability environment to the latest version

Update dd-trace-php link for reliability environment

---

.circleci/config.yml
docker-compose.yml
dockerfiles/services/Makefile
dockerfiles/services/request-replayer/Dockerfile
dockerfiles/services/request-replayer/src/composer.json
dockerfiles/services/request-replayer/src/index.php
dockerfiles/services/request-replayer/src/test_send_msgpack.php

Note: the `index.php` file has been modified compared to what's in our internal repo based on the file found in `/var/www/index.php` of image `datadog/dd-trace-ci:php-request-replayer-1.0`. The commit that applied those changes was lost.

Move request-replayer from our internal deprecated repository to dd-trace-php

---

tests/randomized/Makefile
tests/randomized/generate-scenarios.php

For arm we will only support a limited number of versions.

Support restricting PHP versions while running randomized tests

---

ext/php7/php7/engine_hooks.c
ext/php8/php8/engine_hooks.c

I noticed the `DL_ERROR()` message wasn't showing up when I was
re-implementing the profiler in Rust.

Fix dlerror logging format

---

ext/php7/serializer.c
ext/php8/serializer.c
tests/ext/root_span_http_useragent.phpt

This PR introduces a change to include the `http.useragent` tag to the root span on PHP 7 and 8.

Add http.useragent to root span

---

docker-compose.yml
ext/php5/coms.c
ext/php5/configuration.h
ext/php5/ddtrace.h
ext/php5/dogstatsd_client.c
ext/php7/coms.c
ext/php7/configuration.h
ext/php7/ddtrace.h
ext/php7/dogstatsd_client.c
ext/php8/coms.c
ext/php8/configuration.h
ext/php8/ddtrace.h
ext/php8/dogstatsd_client.c
src/dogstatsd/client.c
src/dogstatsd/dogstatsd_client/client.h
tests/ext/background-sender/agent_headers_unix_domain_socket.phpt
tests/ext/background-sender/default_unix_domain_socket_agent.phpt
tests/ext/includes/request_replayer.inc

Including:
- default unix socket for dogstatsd
- default unix socket for background sender
Manually tested dogstatsd by creating a dummy socket `socat UNIX-LISTEN:/var/run/datadog/dsd.socket -` - not sure how to test that automatically, or against the real stats receiver.

Add support for unix domain sockets

---

.circleci/config.yml
ext/php5/ddtrace.h
ext/php7/ddtrace.h
ext/php8/ddtrace.h
tea/include/exceptions.h
tea/include/sapi.h
tea/src/sapi.c
zend_abstract_interface/symbols/call.c
zend_abstract_interface/symbols/lookup.c
zend_abstract_interface/symbols/symbols.h
zend_abstract_interface/zai_string/string.h

Transition to non-legacy circleci images. I'm not sure this is all of them, but it's at least a good chunk. A job will have a notice like this if it's a deprecated image:
This also means a newer clang-format is used, so had to fixup a few of those changes.

Transition to non-legacy circleci images

---

ext/php5/configuration.h
ext/php5/priority_sampling/priority_sampling.c
ext/php7/configuration.h
ext/php7/priority_sampling/priority_sampling.c
ext/php8/configuration.h
ext/php8/priority_sampling/priority_sampling.c
tests/ext/distributed_tracing/distributed_trace_bogus_ids.phpt
tests/ext/root_span_add_tag.phpt
tests/ext/root_span_url_as_resource_names.phpt
tests/ext/root_span_url_as_resource_names_no_host.phpt
tests/ext/sandbox-prehook/dd_trace_method.phpt
tests/ext/sandbox/dd_trace_function_alias.phpt
tests/ext/sandbox/dd_trace_function_complex.phpt
tests/ext/sandbox/dd_trace_function_internal.phpt
tests/ext/sandbox/dd_trace_method.phpt
tests/ext/sandbox/dd_trace_method_alias.phpt
tests/ext/sandbox/default_span_properties.phpt
tests/ext/sandbox/default_span_properties_method.phpt
tests/ext/sandbox/errors_are_flagged_from_userland.phpt
tests/ext/sandbox/span_clone.phpt
tests/ext/span_with_removed_exception.phpt
tests/ext/start_span_with_all_properties.phpt
tests/ext/start_span_without_closing.phpt

We decided to simplify the name.
Also omitting _dd.dm.service_hash if unused. (This caused me to have to change all the tests again...)

Rename DD_TRACE_X_DATADOG_TAGS_PROPAGATE_SERVICE to DD_TRACE_PROPAGATE_SERVICE

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Add a new decision maker mechanism #1598
-  Rename DD_TRACE_X_DATADOG_TAGS_PROPAGATE_SERVICE to DD_TRACE_PROPAGATE_SERVICE #1612
- Add support for unix domain sockets #1601
- Add RedisCluster split by host #1602 (Thanks to @radykal-com)
- Add http.useragent to root span #1607
- Fix #1582: *_id keys in meta and metrics are wrongly encoded #1599
- Fix dlerror logging format #1605
- Fix DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED accidentally guarding http.method and http.url as well #1608
- Fix downstream job trigger for deployments to rel-env #1597
- Update dd-trace-php link for reliability environment #1595
- Move request-replayer from our internal deprecated repository to dd-trace-php #1600
- Support restricting PHP versions while running randomized tests #1604

Release 0.75.0

---

.circleci/config.yml

This disables the clang format check for C source files while leaving the remaining tasks for the lint job unchanged.
Our very basic usage of clang format leads to frustration when opening PR's of any complexity. We could invest time in learning and configuring the software, however it would seem like a waste of time.
Bob and I both agree that our current usage is a hinderance rather than a help; We both agree that it's reasonable for us to just point out particularly jarring formatting during code review.

Disable clang format check in CI

---

tests/randomized/Makefile
tests/randomized/docker/Dockerfile
tests/randomized/docker/apache.php.conf
tests/randomized/docker/envs/5.4.env
tests/randomized/docker/envs/5.5.env
tests/randomized/docker/envs/5.6.env
tests/randomized/docker/envs/7.0.env
tests/randomized/docker/envs/7.1.env
tests/randomized/docker/envs/7.2.env
tests/randomized/docker/envs/7.3.env
tests/randomized/docker/envs/7.4.env
tests/randomized/docker/envs/8.0.env
tests/randomized/docker/envs/8.1.env
tests/randomized/docker/php-fpm.conf
tests/randomized/generate-scenarios.php
tests/randomized/lib/templates/apache.template.conf
tests/randomized/lib/templates/docker-compose.template.yml
tests/randomized/lib/templates/php-fpm.template.conf

Since Remi's repo does not  provide arm64 binaries, we have moved to manually build our version of PHP which required quite a few changes  at our makefile to support different versions.

Manually build PHP for randomized tests images

---

.circleci/config.yml

This is a pre-requisite to removing PHP 5 altogether from the codebase.

Remove PHP 5 from CI and fetch it instead from the latest PHP-5 branch build

---

ext/php7/configuration.h
ext/php8/configuration.h
tests/ext/root_span_url_with_query_params_obfuscation.phpt
zend_abstract_interface/uri_normalization/php7-8/uri_normalization.c

The query string obfuscation currently doesn't work on encoded URLs, so this change simply decodes the URL (specifically the query string portion) before obfuscation.

Update regex to account for URL encoding

---

ext/php7/configuration.h
ext/php7/serializer.c
ext/php8/configuration.h
ext/php8/serializer.c

Rename `DD_OBFUSCATION_QUERY_STRING_REGEXP` variable to `DD_TRACE_OBFUSCATION_QUERY_STRING_REGEXP`

Rename query string obfuscation variable

---

Makefile

- Do not upload empty profiles. See DataDog/dd-prof-php@e03ff23e5216f863061285e13170d011d0c04bc8 for details.
- Fix a small memory leak with env var handling.
- Add SAPI as profile tag.
- Add support for `DD_PROFILING_EXPERIMENTAL_CPU_TIME_ENABLED` env var. It previously supported this functionality under a different, undocumented name.

Update profiling to v0.7.0

---

ext/php7/ddtrace.c
ext/php7/tracer_tag_propagation/tracer_tag_propagation.c
ext/php8/ddtrace.c
ext/php8/tracer_tag_propagation/tracer_tag_propagation.c
tests/ext/distributed_tracing/distributed_trace_inherit.phpt
tests/ext/distributed_tracing/distributed_trace_overwrite.phpt
tests/ext/integrations/curl/distributed_tracing_curl.phpt
tests/ext/integrations/curl/distributed_tracing_curl_propagate_custom_tags.phpt
tests/ext/integrations/curl/distributed_tracing_curl_propagate_tags.phpt

We only want tags starting with _dd.p. prefix to avoid arbitrary tag injection...

Filter x-datadog-tags for _dd.p. prefix and add DDTrace\add_distributed_tag

---

.circleci/config.yml
dockerfiles/frameworks/contrib/Dockerfile
dockerfiles/frameworks/wordpress_php5.yml

The wordpress container now runs PHP 7. Creating an extra _php5 variant for the PHP 5 testsuite.

Run Wordpress testsuite actually against PHP 5

---

tests/Frameworks/Symfony/Version_4_0/composer.json
tests/Frameworks/Symfony/Version_4_2/composer.json
tests/Frameworks/Symfony/Version_4_4/composer.json
tests/Frameworks/Symfony/Version_5_0/composer.json
tests/Frameworks/Symfony/Version_5_1/composer.json
tests/Frameworks/Symfony/Version_5_2/composer.json
tests/composer.json
tests/ext/extract_server_values.phpt

Whitelisting composer plugins has been required from this first of July, hence tests on runners using a recent composer are failing.

Add g1a/composer-test-scenarios and symfony/flex to composer allow-plugin list

---

src/Integrations/Integrations/Integration.php
src/Integrations/Integrations/IntegrationsLoader.php

Showing there only always loaded integrations might be confusing when debugging which integrations are supposed to be loaded.
Fixes #1592.

Add integration loaded output for deferred integrations on DD_TRACE_DEBUG=1

---

ext/php7/compatibility.h
ext/php8/compatibility.h

This generally cuts fresh span memory overhead by 40%:
strpprintf under the hood uses a smart_str. Smart strings always use at least 224 bytes of memory.
By default for each string we allocate a span_fci (256 bytes), empty metrics and meta arrays (each 64 bytes) - and two strings: the span id and the resource name. Which are ~20 + 50-100 bytes, but we alloc 448 bytes.
This improvement will be (see https://github.com/php/php-src/pull/8902) on php-src master, but we do it for versions older than PHP 8.2 as well.

Reduce memory footprint of strpprintf

---

.circleci/config.yml

Debian stretch repos are no longer available, testing bullseye instead (in addition to the already tested buster).

Test debian bullseye instead of stretch in CI

---

composer.json
tests/Frameworks/Symfony/Version_4_0/composer.json
tests/Frameworks/Symfony/Version_4_2/composer.json
tests/Frameworks/Symfony/Version_4_4/composer.json
tests/Frameworks/Symfony/Version_5_0/composer.json
tests/Frameworks/Symfony/Version_5_1/composer.json
tests/Frameworks/Symfony/Version_5_2/composer.json
tests/composer.json

Backport from master: cherry picked from commits 5c93191a30046eeb72f7dfd58174a47ec30fb56b, 70b131cd839d079767f19479449aebabbc1993fe
Fixing CI.

(PHP 5) Add g1a/composer-test-scenarios and symfony/flex to composer allow-plugin list

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

- Add B3 headers injection and extraction #1629
- Collect http.client_ip #1621
- Filter x-datadog-tags for _dd.p. prefix and add DDTrace\add_distributed_tag #1618
- ​​Rename query string obfuscation variable #1630
- Collect query string by default and obfuscate #1615
- Update regex to account for URL encoding #1622
- Update library versions used in tests + support plesk paths #1632
- Remove service name propagation #1635, #1636
- Add integration loaded output for deferred integrations on DD_TRACE_DEBUG=1 #1639
- ​Reduce memory footprint of strpprintf #1640
- New implementation for hooks #1617
- (PHP 5) Remove service name propagation and filter x-datadog-tags for _dd.p. prefix #1636
- Fix crash with numerical value in $_SERVER array #1634
- Fix missing query string on http.url from …

Release 0.76.0

---

.gitlab-ci.yml
ext/version.h
package.xml
src/DDTrace/Tracer.php

Bump PHP minimum version in PECL #1652
PHP 7.3+ Fix compatibility with opcache #1656
%d resource ids in language tests #1657

Release 0.76.1

---

ext/php7/handlers_curl.c
tests/ext/integrations/curl/curl_release_on_shutdown.phpt

The internal object could be destroyed before the curl handles were all properly destroyed. Ensure the curl wrapper multi-array is not destroyed early.
Fixes a bug reported in #1633.

(PHP 7) Fix curl wrapper use after free

---

zend_abstract_interface/interceptor/php7/interceptor.c

The Alpine images recently updated the compiler and now this warning triggers there:
> tmp/build_extension/zend_abstract_interface/interceptor/php7/interceptor.c:30:24: error: taking address of packed member of 'struct <anonymous>' may result in an unaligned pointer value [-Werror=address-of-packed-member]
This fixes the issue by making it aligned to the same alignment as `zend_string`. 
This only occurred on PHP 7.0 for those who are curious.

Fix -Werror=address-of-packed-member

---

tests/ext/integrations/curl/curl_release_on_shutdown.phpt

This test fails on [PHP 8.1 min tests run](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/8601/workflows/cf8ca03f-0f22-4ecf-b137-77238cc17495/jobs/1314491). Not sure if this container _should_ have curl or not, but it's odd to have just one test in the curl suite avoid the skipif.

Skip curl test if curl is not loaded
